### ISSUE TITLE
Support setting date and time for tasks and creating of repeating tasks with Google Tasks API (Bugzilla Bug 1538326)

### ISSUE THREAD

**Issue by kewisch** [kewisch/gdata-provider#10]
# [Bugzilla Bug 1538326](https://bugzilla.mozilla.org/show_bug.cgi?id=1538326)
Date: 2019-03-22T20:51:58+01:00
From: dabama1@upv.es
Assigned To:   nobody

Last updated: 2019-09-11T13:21:18+02:00

**Comment by hscells** [comment]
How easy would this be to implement?

**Comment by kewisch** [comment]
Probably not too difficult. Whatever the repeat info looks like in the API needs to be converted into something like the ics RRULEs, using interfaces Lightning provides. 

Interested in contributing?

**Comment by MrObvious** [comment]
Hi. I would like to get this considered as this is a major feature lacking.

**Comment by kewisch** [comment]
So, it looks like Google does not expose the repeating property in their API: https://developers.google.com/tasks/v1/reference/tasks#resource

Due and completed dates are already implemented. Therefore there is nothing we can do about this at the current time. Please feel free to ping if the API does support repeating properties.

**Comment by kewisch** [comment]
Closing this one until the feature is supported on the Google side. There are a few other issues open that would be interesting to look at if you are still up for contributing!
