### ISSUE TITLE
New calendar dialog empty due to changed cookie settings in Thunderbird

### ISSUE THREAD

**Issue by GWdd** [kewisch/gdata-provider#100]
### Describe the problem and steps to reproduce it:

Using TB 78.2 / P4GC 78.0.1

Attempting to create a new calendar:
Create New Calendar
On Network
Google Calendar
enter valid gmail address
Please select the calendars ...
 -- screen never stops spinning nor provides any selection option:

<img width="676" alt="Capture" src="https://user-images.githubusercontent.com/32851040/91609572-e0f5d580-e934-11ea-9303-9faf0211a6b2.PNG">

Tried several iterations of new calendar - reinstalled P4GC - deleted all calendars - 

Removed P4GC add-on - restarted TB78.2 - installed fresh copy of P4GC 78.01
 -- same result

Verified my Google account is allowing P4GC access.

So I am out of ideas...

(Please include as many details as possible.)

### What happened?

Can't create a new calendar that is connected to Google

### What did you expect to happen?

Connect to a Google calendar.

### Anything else we should know?

The creation process allows me to click NEXT even though there is no selection.  It says a calendar has been created, however there is no new calendar.

I have also tried setting up an iCal calendar linking to my secret Google calendar - it works to get my calendar info - and P4GC asks if I want to write to it, I select YES, but writing still fails.

<img width="452" alt="Capture2" src="https://user-images.githubusercontent.com/32851040/91644334-4c54ab80-e9f8-11ea-9f17-6cb894373ee9.PNG">

I select "Tim" and click okay; then when I try to create an event, I get this:

<img width="375" alt="Capture3" src="https://user-images.githubusercontent.com/32851040/91644377-a0f82680-e9f8-11ea-96d3-4cb35a3d2f36.PNG">

**UPDATE:**
I updated to 78.2.1 (64-bit) today; and tried P4GC again; this time it updated by iCAL, seemed to do a dismissal of all old events. But left my calendar 100% blank - it erased everything. Fearing the worst, went to my phone and my calendar was still there.

So I created a new calendar in Thunderbird, selecting Network/Google, and found that my correct email was showing (it hadn't been with 78.0.1).  Going through the motion of creating this new calendar, now my Google calendar is showing again, and appears to properly sync new items. 

However - after adding a new event - the "busy" spinner comes up and doesn't go away until I switch screens (select the mail tab and then calendar tab). Annoying, but the present combination does work, so 90% happy again.

**Comment by CheariX** [comment]
On a fresh profile running 78.2.1, I could set up all calenders.
After a restart, all calendars are gone.

Trying to add them again results in exactly your error description.

If I uninstall P4GC, I can see all previously marked calendars again (as inactive).
If i then reinstall P4GC, all calendars are gone again.

**Comment by hiroshi-ohno** [comment]
Workaround of @CheariX works for me, too! I fully disabled cookie a while ago, since I did not receive any email that requires HTML access with cookies. I did not imagine that interferes with the calendar feature!

**Comment by kewisch** [comment]
Ah yes, cookie issues. This is sufficiently common. I do have code that adds cookie exceptions, but it doesn't seem to be working. I think we might have an issue on file for this.
