### ISSUE TITLE
Unable to add guest to events on TB 78.2.1 (Windows 10)

### ISSUE THREAD

**Issue by Mic75** [kewisch/gdata-provider#101]
### Describe the problem and steps to reproduce it:

Adding guest to event does not seem to work with TB 78.2.1 (I am on Windows 10)

### What happened?

When creating an event with guest and saving it, it seems that the guests are not notified nor are they saved into the event, as reopening the event shows an empty guests list.

### What did you expect to happen?

- Guest should be notified by mail
- Guest should be persisted into the guest list

### Anything else we should know?

A link to [a capture describing the issue](https://e.pcloud.link/publink/show?code=XZa71Z7Ti3SzROsb5I1TzuxaLsR54XiEfk).

**Comment by JanaJarecki** [comment]
I confirm the bug - am having the same issue (Windows 10, TB 81.0.b2)

**Comment by NT-Christ** [comment]
Confirmed here also

**Comment by HosiPantaloni** [comment]
konfirming the bug (Win10, TB78.2.2 64-bit)

**Comment by kewisch** [comment]
Confirming as well, I have a few more recent bugs that describe this issue. Please stay tuned for the Provider 91.0.2
