### ISSUE TITLE
When creating an event via Thunderbird, the attendees are not saved

### ISSUE THREAD

**Issue by jessc-real** [kewisch/gdata-provider#103]
### Describe the problem and steps to reproduce it:
1. Create an invite from Thunderbird.
2. Invite attendees
3. Save and Close

### What happened?
1. The attendees did not show up in the invite.
### What did you expect to happen?
1. To be able to see the attendees

### Anything else we should know?
1. Works in previous version (68.12.0)

![image](https://user-images.githubusercontent.com/59487633/93431648-c8f7ed00-f907-11ea-8e83-6e6c81549fa7.png)

**Comment by kewisch** [comment]
Interesting. I was about to say this would be an easy fix, but I can't quite explain why this error occurs. `cal` is defined at the top of that file. Confirming either way.

**Comment by jessc-real** [comment]
![google provider](https://user-images.githubusercontent.com/59487633/95342984-bae42d80-0903-11eb-99ff-e02ecf7c26be.gif)

**Comment by ostroskyjeremiah** [comment]
I'm having this same exact issue, as we use Thunderbird/Google Calendar for scheduling.  I create events and add attendees, the events seem to schedule fine, but the attendees are not invited and the event shows up as normal, just no attendees.

**Comment by tobiberlin** [comment]
Just want to state that I have the same issue, currently on Thunderbird 78.4.0 and Google Provider 78.0.1

**Comment by mwithi** [comment]
> Just want to state that I have the same issue, currently on Thunderbird 78.4.0 and Google Provider 78.0.1

+1

And also for events created online, attendees are not showed in Google Provider and the tab is even missing:

![Google Calendar](https://user-images.githubusercontent.com/2938553/98096963-a22c5080-1e8c-11eb-80f6-197332039746.png)

![Google Provider](https://user-images.githubusercontent.com/2938553/98096901-904aad80-1e8c-11eb-90f3-ed4e88971fa7.png)

**Comment by marzn** [comment]
May this issue is related to #121 and #129

**Comment by tobiberlin** [comment]
@marzn - for me it looks like as if the linkes issue decribe the same problem, yes

**Comment by UrbanLily** [comment]
We are having the same issue, cannot invite attendees to a new or existing event on TB 78.4.2 and Provider 78.0.1. Earlier TB versions (68.12.1) can invite attendees with new versions and their calendar shows the outstanding invitation in the shared calendar. The invited person with TB 78.4.2 does not receive a notification of the invite and the Invitations window does not update any invitations on the new version. On 68.12.1 the invitations window is up-to-date with only outstanding invitations showing.

**Comment by andrewgdotcom** [comment]
I have found also that when I am notified of an upcoming meeting (alarm 15 minutes before), it resyncs the meeting with google and *removes all other attendees*, meaning that it disappears from everyone else's calendar. This is a CRITICAL bug as it leads to data loss.

**Comment by andrewgdotcom** [comment]
Update: I tried a workaround by marking all my google calendars as read-only in Thunderbird (I now have to create/edit all my events in the browser of course). This has caused a new warning to pop up, saying that snoozing is not possible on read-only calendars. This implies that the problem was being caused by me snoozing or dismissing my notifications, since apparently this causes a modification to the event itself.

This further implies that the same mechanism may be causing another of my calendaring issues: when snoozing or dismissing an alarm, the dialog window hangs and must be force closed. After marking my calendar as read-only this no longer occurs. It is unclear whether this is a Thunderbird issue or an extension one though.

**Comment by roccopietrini** [comment]
I can confirm what @andrewgdotcom says, dismissing the notification remove all attendees. This is a really critical bug and should be addressed with high priority please..

**Comment by tomaslledo** [comment]
Hi,

As unode pointed out, on thread #138 we have posted the same issue discussed here.

**Comment by Tripp339** [comment]
I'm having the same issue.  TB 78.5.0 (64-bit), GProvider ver 78.0.1.  Cannot add attendees to events and have them saved and written to Google.

**Comment by sgdavis1** [comment]
Same issue, also with TB 78.5.0 (64-bit)

**Comment by Tripp339** [comment]
Is there any progress on a resolution?

**Comment by Genji-tech** [comment]
I have the same problem (Attendees are not invited and are removed from the event) but different console errors:

On creating a new event:
`aElement is null 2 calendar-ui-utils.js:180
    removeChildren chrome://calendar/content/calendar-ui-utils.js:180
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:147
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    commonUpdateReminder chrome://calendar/content/calendar-dialog-utils.js:514
    updateReminder chrome://lightning/content/lightning-item-iframe.js:1604
    updateCalendar chrome://lightning/content/lightning-item-iframe.js:2762
    updateCalendar self-hosted:844
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:36
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    loadDialog chrome://lightning/content/lightning-item-iframe.js:824
    onLoad chrome://lightning/content/lightning-item-iframe.js:445
    onload chrome://lightning/content/lightning-item-iframe.xhtml:1
`

`
Uncaught TypeError: aElement is null
    removeChildren chrome://calendar/content/calendar-ui-utils.js:180
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:147
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    commonUpdateReminder chrome://calendar/content/calendar-dialog-utils.js:514
    updateReminder chrome://lightning/content/lightning-item-iframe.js:1604
    updateCalendar chrome://lightning/content/lightning-item-iframe.js:2762
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:36
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    loadDialog chrome://lightning/content/lightning-item-iframe.js:824
    onLoad chrome://lightning/content/lightning-item-iframe.js:445
    onload chrome://lightning/content/lightning-item-iframe.xhtml:1
`
and then when I add an attendee in the "Invite Attendees' dialog:
`
Lightning: [calGoogleCalendar] Failed freebusy request: [Exception... "A request Error Occurred. Status Code: 400 Bad Request Body: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "badRequest",
    "message": "Bad Request"
   }
  ],
  "code": 400,
  "message": "Bad Request"
 }
}
"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://gdata-provider/legacy/modules/gdataRequest.jsm :: fail :: line 232"  data: no] 2 gdataSession.jsm:562
`

`
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIAutoCompleteInput.popup] LoginManagerChild.jsm:174
    observe resource://gre/modules/LoginManagerChild.jsm:174
    handleKeyDown chrome://global/content/elements/autocomplete-input.js:518
    AutocompleteInput chrome://global/content/elements/autocomplete-input.js:38
    editAttendees chrome://lightning/content/lightning-item-iframe.js:2078
    receiveMessage chrome://lightning/content/lightning-item-iframe.js:228
`

`
Lightning: [calGoogleCalendar] Failed freebusy request: [Exception... "A request Error Occurred. Status Code: 400 Bad Request Body: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "badRequest",
    "message": "Bad Request"
   }
  ],
  "code": 400,
  "message": "Bad Request"
 }
}
"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://gdata-provider/legacy/modules/gdataRequest.jsm :: fail :: line 232"  data: no]
`
and then when I actually Save & Close:
`
Uncaught 
Exception
​
columnNumber: 0
​
data: null
​
filename: "chrome://lightning/content/lightning-item-iframe.js"
​
lineNumber: 487
​
location: XPCWrappedNative_NoHelper { QueryInterface: QueryInterface(), filename: Getter, name: Getter, … }
​
message: "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIObserverService.removeObserver]"
​
name: "NS_ERROR_ILLEGAL_VALUE"
​
result: 2147942487
​
stack: "onEventDialogUnload@chrome://lightning/content/lightning-item-iframe.js:487:16\nonunload@chrome://lightning/content/lightning-item-iframe.xhtml:1:1\n"
​
<prototype>: ExceptionPrototype
​​
columnNumber: 
​​
data: 
​​
filename: 
​​
lineNumber: 
​​
location: 
​​
message: 
​​
name: 
​​
result: 
​​
stack: 
​​
toString: function toString()
​​
Symbol(Symbol.toStringTag): "Exception"
​​
<get columnNumber()>: function columnNumber()
​​
<get data()>: function data()
​​
<get filename()>: function filename()
​​
<get lineNumber()>: function lineNumber()
​​
<get location()>: function location()
​​
<get message()>: function message()
​​
<get name()>: function name()
​​
<get result()>: function result()
​​
<get stack()>: function stack()
​​
<set stack()>: function stack()
​​
<prototype>: Object { … }
lightning-item-iframe.js:487
    onEventDialogUnload chrome://lightning/content/lightning-item-iframe.js:487
    onunload chrome://lightning/content/lightning-item-iframe.xhtml:1
`

**Comment by tomaslledo** [comment]
Do we have any news regarding this issue with Google calendars? Any improvement with newer Thunderbird versions?

**Comment by Tripp339** [comment]
Doesn't seem so.  Has Philipp discontinued support?

**Comment by roccopietrini** [comment]
I don't know acutally, but I switched to tbsync .. it works as expected and saves me in my daily job :)

**Comment by humbertleonardo** [comment]
Poderia descrever melhor essa transição para o tbSync ? Não consegui configurar aqui

**Comment by humbertleonardo** [comment]
TbSync has ended support for Google, is there any other alternative?

> I don't know acutally, but I switched to tbsync .. it works as expected and saves me in my daily job :)

**Comment by kewisch** [comment]
I've been able to identify the cause here, will be releasing a fix for Provider 91.0.2
