### ISSUE TITLE
Unable to write to events

### ISSUE THREAD

**Issue by dgagnon** [kewisch/gdata-provider#104]
### Describe the problem and steps to reproduce it:

Unable to accept invitations or dismiss reminders.

### What happened?

nothing

### What did you expect to happen?

accepted invitation or dismissed event.

### Anything else we should know?

brand new install with latest thunderbird and extension, no custom config.

no error show up, nothing happens.

**Comment by kewisch** [comment]
Can you enable debugging (see wiki) and check the error console when you dismiss?
