### ISSUE TITLE
A calendar is listed and active but not shown

### ISSUE THREAD

**Issue by ilNebbioso** [kewisch/gdata-provider#105]
I have more calendars from the same GoogleCalendar account. When I add the calendar, as expected I can choose which ones I want to see.

When I added a calendar, all calendars are correctly shown in Thunderbird Lightning as expected, also it needs half a minute (a lot more than before last updates) to show its appointments.

Once rebooted TB, I see all the calendars listed and active on the left-pane, but for ONE (always the same!) of them I cannot see any appointment.

If I try to add a new appointment to this calendar from TB, the "Save and exit" button doesn't do anything. 
If I try to add a new appointment to another calendar on the same Google Account it works as expected (I can add/odify/delete it).

Workaround found: none. I have to use Google Calendar website.

Error console (I hope this may help and it is what you expect from me)

TypeError: item.startDate is null 2 CalStorageCalendar.jsm:1842:7
TypeError: impl is null 3 network-response-listener.js:104:7
TypeError: impl is null network-response-listener.js:104:7
TypeError: impl is null network-response-listener.js:104:7
TypeError: impl is null 8 network-response-listener.js:104:7
TypeError: impl is null network-response-listener.js:104:7
TypeError: impl is null network-response-listener.js:104:7
TypeError: impl is null network-response-listener.js:104:7
TypeError: impl is null network-response-listener.js:104:7
TypeError: impl is null network-response-listener.js:104:7
TypeError: impl is null network-response-listener.js:104:7
TypeError: impl is null network-response-listener.js:104:7
TypeError: impl is null network-response-listener.js:104:7
TypeError: impl is null network-response-listener.js:104:7
TypeError: impl is null network-response-listener.js:104:7
TypeError: impl is null network-response-listener.js:104:7
TypeError: item.startDate is null CalStorageCalendar.jsm:1842:7

**Comment by kewisch** [comment]
Can you enable the debugging prefs noted in the project readme and check the error console again? This should show more information, look out for anything that might be related to start dates.

**Comment by michaelber** [comment]
Hi,

I have the same issue since a recent update. Whenever i restart Thunderbird, all Google calendars are hidden. A workaround is to hide + unhide them. Then they are visible again for the current session.

![hide+unhide](https://user-images.githubusercontent.com/7449343/95895363-d8dde200-0d8a-11eb-9980-08990e501cc3.png)

I'm not sure if the error messages in the console log are related to this issue:
![console](https://user-images.githubusercontent.com/7449343/95895360-d7acb500-0d8a-11eb-8aaf-925f23409cf9.PNG)

Thanks,
Michael

**Comment by ilNebbioso** [comment]
@michaelber can you please tell me which version are you using (both TB + Google Calendar provider)?
I'm using TB 78.3.1 + GCp 78.0.1 and your workaround doesn't work.

@kewisch this is my console error. I hope this helps.

`[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
Successfully loaded OpenPGP library rnp.dll from C:\Program Files (x86)\Mozilla Thunderbird\rnp.dll RNPLib.jsm:46:13
public keys: 0, secret keys: 0 RNPLib.jsm:194:15
0 protected and 0 unprotected keys BondOpenPGP.jsm:99:13
Error while loading 'jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Thunderbird/omni.ja!/chrome/messenger/search-extensions/twitter/manifest.json' (NS_ERROR_FILE_NOT_FOUND) Extension.jsm:570
TypeError: item.startDate is null
CalStorageCalendar.jsm:1842:7
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
TypeError: item.startDate is null
2 CalStorageCalendar.jsm:1842:7
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
Successfully loaded OTR library libotr-5.dll from C:\Program Files (x86)\Mozilla Thunderbird\libotr-5.dll OTRLib.jsm:43:13
TypeError: item.startDate is null
10 CalStorageCalendar.jsm:1842:7`

**Comment by michaelber** [comment]
I'm using TB 78.3.2 and GDp 78.0.1 on Windows 10

**Comment by ilNebbioso** [comment]
@michaelber I:
- removed the calendar, 
- then removed+reinstalled GDp 78.0.1, 
- added again the calendar

but I wasn't able to reproduce your workaround.

PS I'm on Windows 10 too (20H2, full updated)

**Comment by fishears** [comment]
> Hi,
> 
> I have the same issue since a recent update. Whenever i restart Thunderbird, all Google calendars are hidden. A workaround is to hide + unhide them. Then they are visible again for the current session.
> 
> ![hide+unhide](https://user-images.githubusercontent.com/7449343/95895363-d8dde200-0d8a-11eb-9980-08990e501cc3.png)
> 
> I'm not sure if the error messages in the console log are related to this issue:
> ![console](https://user-images.githubusercontent.com/7449343/95895360-d7acb500-0d8a-11eb-8aaf-925f23409cf9.PNG)
> 
> Thanks,
> Michael

I have exactly the same issue as you describe here with the same workaround possible. Thunderbird 78.3.2 GCp 78.0.1 Arch Linux.

**Comment by DanielS1381** [comment]
I had exactly the same issue (Thunderbird 78.4.0 and GCp 78.0.1, Windows 10). After starting Thunderbird all Google calendars (from the same Google account) were hidden. Hiding and unhiding the calendars worked only for the current session.

Reinstalling GCp without removing subscriptions was the solution. Thx.

**Comment by LordChaos73** [comment]
Just started TB 78.0.4; this issue is present (TB 78.0.4, GCp 78.0.1 & Linux Mint 20) and re-installing GCp without removing the subscriptions didn't help.

**Comment by fishears** [comment]
> Just started TB 78.0.4; this issue is present (TB 78.0.4, GCp 78.0.1 & Linux Mint 20) and re-installing GCp without removing the subscriptions didn't help.

Did you restart Thunderbird before re-installing GCp?

**Comment by LordChaos73** [comment]
> Did you restart Thunderbird before re-installing GCp?

Yes, I did that while I was still running 78.0.3. Could it be we have to do this every time after installing a new version?

**Comment by kewisch** [comment]
I've seen the L10nRegistry issue in quite a few issues now, it looks like there are a few duplicates. Please re-test this in Thunderbird 91, if that doesn't do it let's see if we can find another issue to tack it on to.
