### ISSUE TITLE
Freeze when opening new task dialog

### ISSUE THREAD

**Issue by dodona2408** [kewisch/gdata-provider#106]
If you try to create a new task using the specified function (right click → New Task), the program freezes and can only be ended using the Task Manager.
<img width="171" alt="NeueAufgabe" src="https://user-images.githubusercontent.com/16988880/94020426-30ec7e80-fdb3-11ea-848b-b6c706774de1.png">

**Comment by kewisch** [comment]
This will be difficult to debug. Can you try unsubscribing from all Google Calendars and then re-subscribing?

**Comment by frankrebenstock** [comment]
Same problem here. What sort of information is needed? I followed your hint to 1. unsubscribe from my 2 Google calendars (1 calendar, 1 task list), restarting (TB 78.3.1 x64 - doing auto-update to TB 78.3.2 x64), then 2. re-subscribed - but the issue of freezing still unsolved.

**Comment by mat4444** [comment]
> This will be difficult to debug. Can you try unsubscribing from all Google Calendars and then re-subscribing?

Hi Kewisch, 
I found out that 'DefaultReminder' is not defined and seems to be the root cause of this problem.
Please have a look at my bug report here : #110 
Thanks !

**Comment by kewisch** [comment]
Thanks for digging! This should make it somewhat easier to fix.

**Comment by mat4444** [comment]
Hi,
is there any update on this problem ? Let me know if I can help you in any way.
Thanks

**Comment by mat4444** [comment]
Hello @kewisch !
Is this plug-in still actively supported ? There are has been no update for quite a while.
Thanks for your feedback!

**Comment by kewisch** [comment]
The `defaultReminder` issues should be fixed in Thunderbird 91.
