### ISSUE TITLE
Calendar migration dialog shows on each restart

### ISSUE THREAD

**Issue by NicoHaase** [kewisch/gdata-provider#107]
### Describe the problem and steps to reproduce it:

I have one calendar in my list where writing is not allowed. On starting Thunderbird, a message box appears telling me about this calendar, and that write access should get enabled (I've found that message under the key `gdata.migration.description` in the locales). But as I know that this won't happen, I unchecked the box in the lower left which is labeled "Always check", and I unchecked the only calendar in question. Afterwards, I've clicked "Upgrade".

### What happened?

Unfortunately, this window appears on **each** startup, and the checkbox "Always check" is checked.

### What did you expect to happen?

This window should no longer be shown - as far as I understand the checkbox "Always check" ;)

**Comment by kewisch** [comment]
I've noticed this as well and have an idea. Can you try not checking any calendars, uncheck always check, and then use the "migrate" button instead of cancel?

This should work around while I fix.

**Comment by NicoHaase** [comment]
Thanks for that hint, but on restarting Thunderbird, the same dialog appears :(

**Comment by rakyi** [comment]
I have the same problem. Tried checking and unchecking different stuff a clicking different buttons, but I still get the same dialog on each restart.

**Comment by kewisch** [comment]
Fixed in faf2124e6e4e4f058e8d163efa7ce635df9d0f7a
