### ISSUE TITLE
Can't accept meeting invite

### ISSUE THREAD

**Issue by LancashireLad** [kewisch/gdata-provider#108]
### Describe the problem and steps to reproduce it:
Invitations appear in my calendar (dotted).  If I right click to accept and send response now, nothing happens.  The event remains dotted.  (Previous versions, the event shows confirmd after acceptance (not dotted)

(Please include as many details as possible.)

### What happened?
Right click - attendance - accepted - send response now.  Nothing happens

### What did you expect to happen?
In the past a response was sent and the event showed as confirmed (not greyed out)

### Anything else we should know?
Stopped working with TB 78

**Comment by Rolf185** [comment]
Hopefully I can add some details (TB 78.3.1 / Provider for Google Kalender 78.0.1).
I'm missing all options "calendar.google". Even after a reinstall of the Provider the "calendar.google" options are not visible in TB and are not in the prevs.js file. I can define a new boolean option "calendar.google.enableEmailInvitations" = true in the TB options editor and the google calendar settings dialog comes up with a filed to store an email address but it's gone after a TB restart.
Hope this may help.
Rolf

**Comment by kewisch** [comment]
You should be able to set the debug prefs calendar.debug.log. The Provider prefs are migrated to new storage. 

If you want to edit them you need to go to Tools, Developer Tools, Debug Add-ons, Inspect, Storage, and then select the extension storage. I don't know if there are any prefs that would affect your issue though.

Can you check the error console with the debug.log prefs enabled?

**Comment by Rolf185** [comment]
Hi kewisch,
this is the relevant log line:
[gdata-provider] Migrating legacy prefs 
Object { "settings.sendEventNotifications": true, "settings.enableEmailInvitations": true }
Looking into the code I found this in gdataCalendar.jsm:

**Comment by Rolf185** [comment]
Sorry, wrong key pressed.
Looking into the code I found this in gdataCalendar.jsm:
!Services.prefs.getBoolPref("calendar.google.enableEmailInvitations", false)
Setting calendar.google.enableEmailInvitations to true in the options editor works (but only for the running session as it's not stored permanent): The provider options dialog for my goolgle calendar shows a selection box to specify a mail account for invitations.
Maybe a naming problem?
Rolf

**Comment by brodny** [comment]
Same problem for me - TB 78.3.2 / Provider for Google Kalender 78.0.1). calendar.google.enableEmailInvitations is still present after TB restart (which seems to be different than Rolf185's case) but is definitely gone after Windows restart. Win10 Home 2004 x64 if that's relevant.

**Comment by sgdavis1** [comment]
Same problem with me, but I cannot even edit the values in "extension storage".

**Comment by twain28** [comment]
@kewisch , I think this is probably the same as issue #63 ...AFAIK, latest syntax for gcal support does not seem to tolerate the "calendar.google.enableEmailInvitations" setting anymore...so what happens is that thunderbird correctly reads events and sends them as well, but you cannot choose the email account to accept invites anymore (search me why)...and what you get is that you have "no writable calendars" available...

**Comment by OlivierJFJacques** [comment]
Same problem with my configuration after updating Thunderbird to 78.
In the about:config all calendar.google entries are gone (even after reinstalling the add-on "Provider for Google Calendar" and  re-creating the Google calendar).
Thank you for your time on fixing it and let me know if you need more details on the issue. I'll be happy to help.

**Comment by pmarini** [comment]
Same problem here after updating to Thunderbird 78

**Comment by Scheisskalender** [comment]
This is a big Problem!
Thunderbird 78.4.3 (32-bit)

I do not have the option "calendar.google.enableEmailInvitations" anymore and therefor can not choose the google calender to accept Invitations. Thank you Mozilla/Thunderbird for this update we are thinking about removing your software and switch to Outlook

**Comment by LancashireLad** [comment]
I got round the problem by installing the add on 'Open Google Calendar'  
.  It works fine.  I've removed Provider.

**Comment by Scheisskalender** [comment]
> 
> I got round the problem by installing the add on 'Open Google Calendar'  .  It works fine.  I've removed Provider.
> […](#)


Thank you for your suggestion but this has nothing to do with integrating a google Calendar into Thunderbird, your Addon does simply open a browser page in thunderbird thats it...

What people are trying here is to have an invitation accepted and added to an integrated GoogleCalendar but the it does not show up in the list:
![invitation](https://user-images.githubusercontent.com/74358190/98942447-46963e80-24ee-11eb-8a6a-d0e121ccbe2d.PNG)

**Comment by twain28** [comment]
@Scheisskalender : I don't think the new syntax is Thunderbird's fault... :P

In any case, whenever you update or add a new google calendar extension, it is highly recommended to check and delete all stored AUTH tokens from the "saved passwords" dialog...hope this solves your missing calendar issue...

**Comment by laxxity** [comment]
I'm having the same issue, I can't Accept or Decline any calendar invites.  Clicking the Accept/Decline buttons or "send a response now" makes the window disappear but the change never takes effect. Returning to the event details shows "you haven't responded to this invitation". Accepting it via google calendar on the web works and then correctly updates the status in Thunderbird.

**Comment by igorscs** [comment]
same problem here, cannot choose calendar when I accept an invite
press on "Accept" on google calendar events does nothing

**Comment by coofercat** [comment]
I've been looking at various other issues trying to find a solution (#13 looked promising, but it's related to interaction with another addon).

I have the same problem as described here, with Thunderbird 78.12.0, Provider for Google Calendar 78.0.1 on a Mac. I don't have any `calendar.google.*` config options in the Config Editor.

In my case, I have 3 calendars, all actually hosted on Google. My two work ones are connected via the Provider, and my personal one is (still) connected via CalDav. It seems that only the Caldav one can accept events - if I make it read-only, then I see `No writeable calendars are configured for invitations, please check the calendar properties` at the top of any invitations. If I make my CalDav calendar writable again, then it works, but obviously events from my work email go into my personal calendar - which I don't want.

If I had to guess, I'd say that the Provider calendars aren't showing up as writable, even though they are (you can create them in the calendar tab quit happily - and they sync up to google too. Although you CAN'T write-click an event and say "accept" - it just doesn't do anything). In my case, as only one calendar appears to be writable, no dialogue is shown asking which calendar to put the event into (and the auto-matching can't work either).

Summary
- I can't accept an invite into the correct calendar (all the Provider ones seem read-only, even though they're writeable)
- When receiving an invite, the calendar shows it (unaccepted, so slightly greyed out). I can't right-click and accept (it does nothing) - it's in the correct calendar though
- I can create calendar entries in the calendar screen, and they sync up to Google almost immediately. Likewise I can create/delete in Google and they sync to Thunderbird

**Comment by kewisch** [comment]
#191
