### ISSUE TITLE
Provider for Google Calendar is incompatible with Thunderbird 78.3.1.

### ISSUE THREAD

**Issue by genechuah** [kewisch/gdata-provider#109]
Provider for Google Calendar is incompatible with Thunderbird 78.3.1.

Add-on is disabled by default now. No Calendar data.

**Comment by genechuah** [comment]
![image](https://user-images.githubusercontent.com/19858965/94930581-a54eae00-0494-11eb-8e0f-42db004c08d3.png)

**Comment by Zwixx** [comment]
Version 78.0.1 is the latest Version:
![grafik](https://user-images.githubusercontent.com/4589892/94994409-b59b8180-0597-11eb-9601-cd5f05261d6c.png)

**Comment by genechuah** [comment]
There must be a way to avoid thing breaking when Thunderbird auto-updates to the latest version... Now I can't use the Calendar.

**Comment by kewisch** [comment]
Please update to the latest version of the Provider for Google Calendar, it should be offered automatically if you check for add-on updates in the Add-ons tab.

I'm not sure why this wouldn't be installed automatically, this seems to either be a Thunderbird issue or addons.thunderbird.net not advertising the latest version.
