### ISSUE TITLE
New task window will not close - TB 78.3.1

### ISSUE THREAD

**Issue by mat4444** [kewisch/gdata-provider#110]
### Describe the problem and steps to reproduce it:

After updating TB to 78.3.1, I am unable to create a new task (Google Task). The task window will show up, but I can't save it, or even just close it. The rest of TB is responsive, but I can't close the task window unless I kill TB with the task manager (Windows 10).

### What happened?

When clicking on "save and close" to save the task, nothing happens. The window does not disappear. It's also impossible to simply close the window (even if no info was entered). The rest of TB is responsive.

### What did you expect to happen?

The window should close and the task saved.

### Anything else we should know?

Using the error console, I found out that 'DefaultReminder' is not defined. It prevents the new task window from closing.
If I set the "Reminder" to any value but the default reminder, the window will close.
I didn't have this issue before the update of thunderbird, I could leave the reminder to default.

Error Console log : 
```
Uncaught TypeError: defaultReminders is undefined
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:161
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    saveDialog chrome://lightning/content/lightning-item-iframe.js:1700
    saveItem chrome://lightning/content/lightning-item-iframe.js:3161
    isItemChanged chrome://lightning/content/lightning-item-iframe.js:4118
    onCommandCancel chrome://lightning/content/lightning-item-iframe.js:520
    onCancel chrome://lightning/content/lightning-item-iframe.js:582
    receiveMessage chrome://lightning/content/lightning-item-iframe.js:243
gdata-lightning-item-iframe.jsm:161:7
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:161
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    saveDialog chrome://lightning/content/lightning-item-iframe.js:1700
    saveItem chrome://lightning/content/lightning-item-iframe.js:3161
    isItemChanged chrome://lightning/content/lightning-item-iframe.js:4118
    onCommandCancel chrome://lightning/content/lightning-item-iframe.js:520
    onCancel chrome://lightning/content/lightning-item-iframe.js:582
    receiveMessage chrome://lightning/content/lightning-item-iframe.js:243
```

**Comment by fthx** [comment]
I confirm this.

**Comment by Richardk2n** [comment]
Can confirm as well for 78.5.0

**Comment by ericzolf** [comment]
Same thing on 78.6.0 (64-bit) under Fedora 33 (AFAICJ it did also happen under Fedora 32), and with gdata-provider version 78.0.1
