### ISSUE TITLE
Support for the new Autodetect dialog

### ISSUE THREAD

**Issue by marvinandro** [kewisch/gdata-provider#111]
Vanilla Window 10
Install Thunderbird 82.0b2 (64-bit)
Install Provider for Google Calendar 78.0.1
File -> New -> Calendar -> On the Network

The option to select Google Calendar doesn't show up on the menu.

Hope support (even beta) is coming soon.

Thanks!

**Comment by srevinsaju** [comment]
Can reproduce on Linux , Thunderbird 82.0b2 (64-bit), provider 78.0.1

**Comment by Eagle3386** [comment]
Is there a workaround while @kewisch adopts TB's recent calendar-related changes?

**Comment by kewisch** [comment]
You can set up most calendars in prefs.js in the profile, or about:config. If you use prefs.js then do so while Thunderbird isn't running, if you use about:config make sure to restart Thunderbird. The guid needs to be unique per calendar. In the googleapi:// url, the first email is the session you are logging in with, the second is the email of the calendar to subscribe to.

```javascript
pref("calendar.registry.5ce63672-fbe5-46d6-b8ca-a8bf42b16b55.uri", "googleapi://example@gmail.com/?calendar=example%40gmail.com");
pref("calendar.registry.5ce63672-fbe5-46d6-b8ca-a8bf42b16b55.type", "gdata");
```

**Comment by srevinsaju** [comment]
It works. Thanks @kewisch :tada:

**Comment by CircleCode** [comment]
is this workaround also working for GSuite accounts?
It does not seem to work for me:
after restarting TB, the addon asked me to log in to my google account and asked permission to view and edit calendars,
but then nothing gets synchronized at all.
- is there a way to view any error that may have occured?
- is there a way to verify that the `?calendar=example%40gmail.com` I use is valid?

**Comment by kewisch** [comment]
Can you check the debugging tips in the main wiki? That should show how to enable debugging. The first part is arbitrary, the calendar parameter just needs to be urlencoded. %40 is equal to @

**Comment by CircleCode** [comment]
Sorry, I totally forgot the `--jsconsole` flag
So it appears there is indeed an error, see #112

**Comment by marvinandro** [comment]
> is this workaround also working for GSuite accounts?
> It does not seem to work for me:
> after restarting TB, the addon asked me to log in to my google account and asked permission to view and edit calendars,
> but then nothing gets synchronized at all.
> 
> * is there a way to view any error that may have occured?
> * is there a way to verify that the `?calendar=example%40gmail.com` I use is valid?

Same here. Customer GApps domain doesn't sync any of my calendars.

**Comment by Eagle3386** [comment]
@kewisch 
> The guid needs to be unique per calendar

Sorry to bother you, but just to be sure not to screw things up prior to your bugfix: randomly create one myself or how to get TB create it for me?

**Comment by twain28** [comment]
> You can set up most calendars in prefs.js in the profile, or about:config. If you use prefs.js then do so while Thunderbird isn't running, if you use about:config make sure to restart Thunderbird. The guid needs to be unique per calendar. In the googleapi:// url, the first email is the session you are logging in with, the second is the email of the calendar to subscribe to.
> 
> ```js
> pref("calendar.registry.5ce63672-fbe5-46d6-b8ca-a8bf42b16b55.uri", "googleapi://example@gmail.com/?calendar=example%40gmail.com");
> pref("calendar.registry.5ce63672-fbe5-46d6-b8ca-a8bf42b16b55.type", "gdata");
> ```

Just saw this, browsing around the issues...just out of curiosity, @kewisch ... would manually editing the prefs file perhaps also be somewhat linked to a possible solution of issue #63 , as well, or is it just something else ?

**Comment by Eagle3386** [comment]
Seems like this extension is obsolete due to Mozilla offering `.ics` support out of the box in the latest (beta) version?!

**Comment by Eagle3386** [comment]
@kewisch any chance I get my question right above this comment answered in the near future? 🤔

**Comment by Eagle3386** [comment]
@kewisch A simple "yes" or "no" would be sufficient..

**Comment by NHellFire** [comment]
@Eagle3386 ical has been supported for quite a few years now. This extension isn't obsolete as Google only supports read-only ical.

**Comment by Eagle3386** [comment]
@NHellFire Sorry for the late reply. Thanks for the clarification - I misinterpreted Google's "secret URL" for any calendar as being that one's writable URL & was about to switch back to this extension.

But thanks to your edit, I'm able to try CalDAV directly - hopefully it's supported feature set supports all of Thunderbird's capabilities..

Anyway, I have to thank you for this, too, so: thanks a lot, again! 😅👍🏻

**Comment by kewisch** [comment]
Fixed the original issue for Thunderbird 91. The `main` branch also has some additional integration for the new calendar wizard.
