### ISSUE TITLE
New calendar dialog empty in Thunderbird

### ISSUE THREAD

**Issue by clemenlg** [kewisch/gdata-provider#116]
### Describe the problem and steps to reproduce it:

In Thunderbird 68.10.0 (Ubuntu 20.04), when I add a new calendar account, after grant privileges to my google account for Lightning, appears a white screen with no calendars (I can't choose one).
![imagen](https://user-images.githubusercontent.com/8105025/96165748-533e6b80-0f1d-11eb-9175-a4f64c0c94d6.png)

### What happened?
Appears a white screen with no calendars to select
### What did you expect to happen?
Show a calendar list to select
### Anything else we should know?
Logs:
Lightning: [calGoogleSession] Authentication failure: undefined
[Exception... "null"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gdata-provider/modules/gdataSession.jsm :: login/authFailed< :: line 284"  data: no]
![imagen](https://user-images.githubusercontent.com/8105025/96165919-9698da00-0f1d-11eb-9773-148aea1d9de0.png)

It seems to be similar as issue #100, but cookies workaround don't work

**Comment by PhilAgar** [comment]
I have the same issue, the one computer with 78 worked for 2 weeks then lost google calendars. I updated to the latest Thunderbird today, I uninstalled and reinstalled the addon for 78.

If I disable the addon and reboot the calendar names reappear but nothing in the calendar. If I reinstall the addon, try to add my gmail account, all calendar names disappear and when try to add it back in, after I type in my gmail address  I get the above dialogue box with a spinning circle and  no calendars to choose from.

Could there be something we have to do in gmail to fix it? I seem to recall having to do something in gmail settings to dumb down gmail to accept older software... Sorry for the non-tech response, I know where the limits of my knowledge are, and it's after 5 on a Friday.
ps all my other computers running 68 are not affected.

**Comment by PhilAgar** [comment]
In Google Settings, "Security". "Less secure app access" was set to off. I set it to on. Re started Thunderbird, 

It did NOT fix the issue. Still no calendar access under Thunderbird 78.3.3
![2020-10-19_083316](https://user-images.githubusercontent.com/70652170/96451618-d8f43c80-11e5-11eb-9162-cebf32139d43.png)

**Comment by Perboire99** [comment]
@PhilAgar I'm having the same issue

**Comment by philagar16** [comment]
See #119 , I enabled Cookies in the Privacy Settings of TB and it now works

**Comment by avijaikumar** [comment]
I had the exact same issue. And enabling cookies in the options menu (privacy section) solved the problem.

**Comment by OnixGH** [comment]
Similar symptoms here, endless spinner after entering login (Thunderbird 78.4.0 / 64 bits, plugin version 78.0.1).

Cookies were already enabled, so that solution unfortunately doesn't work. This is happening on multiple Thunderbird installs on different PCs.

```
[Exception... "[object Object]"  nsresult: "0x804a0402 (<unknown>)"  location: 
"JS frame :: resource://gdata-provider/legacy/modules/gdataRequest.jsm :: fail :: line 232"  data: no] gdataRequest.jsm:232:14
    fail resource://gdata-provider/legacy/modules/gdataRequest.jsm:232
    onStreamComplete resource://gdata-provider/legacy/modules/gdataRequest.jsm:499
    openCalendarWizard resource:///modules/calendar/utils/calWindowUtils.jsm:25
    doCommand chrome://calendar/content/calendar-command-controller.js:379
    goDoCommand chrome://global/content/globalOverlay.js:101
    oncommand chrome://messenger/content/messenger.xhtml:1
```

According to the trace, this function call at `calWindowUtils.jsm:25`..
```
    window.openDialog(
      "chrome://calendar/content/calendarCreation.xhtml",
      "caEditServer",
      "modal,chrome,titlebar,resizable,centerscreen",
      aCallback
    );
```

..is ending up in a 404 in `gdataRequest.jsm:499`:
```
 case 404 /* The resource was not found on the server, which is
                         also a conflict */:
        //  404 NOT FOUND: Resource (such as a feed or entry) not found.
        // 410 Gone: Happens when deleting an event that has already
        //           been deleted.
        this.fail(calGoogleRequest.CONFLICT_DELETED, objData);
```

Anything else I can try?

**Comment by clemenlg** [comment]
> Similar symptoms here, endless spinner after entering login (Thunderbird 78.4.0 / 64 bits, plugin version 78.0.1).
> 
> Cookies were already enabled, so that solution unfortunately doesn't work. This is happening on multiple Thunderbird installs on different PCs.
> 
> ```
> [Exception... "[object Object]"  nsresult: "0x804a0402 (<unknown>)"  location: 
> "JS frame :: resource://gdata-provider/legacy/modules/gdataRequest.jsm :: fail :: line 232"  data: no] gdataRequest.jsm:232:14
>     fail resource://gdata-provider/legacy/modules/gdataRequest.jsm:232
>     onStreamComplete resource://gdata-provider/legacy/modules/gdataRequest.jsm:499
>     openCalendarWizard resource:///modules/calendar/utils/calWindowUtils.jsm:25
>     doCommand chrome://calendar/content/calendar-command-controller.js:379
>     goDoCommand chrome://global/content/globalOverlay.js:101
>     oncommand chrome://messenger/content/messenger.xhtml:1
> ```
> 
> According to the trace, this function call at `calWindowUtils.jsm:25`..
> 
> ```
>     window.openDialog(
>       "chrome://calendar/content/calendarCreation.xhtml",
>       "caEditServer",
>       "modal,chrome,titlebar,resizable,centerscreen",
>       aCallback
>     );
> ```
> 
> ..is ending up in a 404 in `gdataRequest.jsm:499`:
> 
> ```
>  case 404 /* The resource was not found on the server, which is
>                          also a conflict */:
>         //  404 NOT FOUND: Resource (such as a feed or entry) not found.
>         // 410 Gone: Happens when deleting an event that has already
>         //           been deleted.
>         this.fail(calGoogleRequest.CONFLICT_DELETED, objData);
> ```
> 
> Anything else I can try?
> 
> ![image](https://user-images.githubusercontent.com/10709325/101611044-4d3ea580-3a09-11eb-886c-26defe31b709.png)

Same issue, with cookies enabled, for me activating cookies not solve the issue:
![screen](https://user-images.githubusercontent.com/8105025/102012051-7c764f00-3d48-11eb-812f-94c712e8d5ca.jpg)

**Comment by kewisch** [comment]
Enabling cookies should do the job here. Thunderbird 91 also fixes a few issues around the new calendar wizard.
