### ISSUE TITLE
Google Calender without Google Mail requires always new signon and leads to security warnings

### ISSUE THREAD

**Issue by dieterxy** [kewisch/gdata-provider#117]
### Describe the problem and steps to reproduce it:
I have a primary mailbox different from gmail, but I use the Google calendar.
After every start of Thunderbird the Google Calender Provider needs to signin to Google.
Then I have to approve the access rights for the google calendar, what always leads to a Google account security warning.
Adding the gmail.com mailbox as secondary mailbox in Thunderbird does not help.

(Please include as many details as possible.)

### What did you expect to happen?
1. Approved access rights for the Calendar provider should be persistent.
2. No password dialog needeed after start of Thunderbird

**Comment by thstyl2000** [comment]
Same problem here. On Ubuntu 20.04.1, Official TB from repos (78.5.0) and Provider 78.0.1. Quite annoying since I am using sth like 10 calendars.....

**Comment by kewisch** [comment]
#161
