### ISSUE TITLE
Error in "Provider for Google Calendar" plugin. Not able to add google calendar to thunderbird 78.4.0

### ISSUE THREAD

**Issue by avijaikumar** [kewisch/gdata-provider#119]
### Describe the problem and steps to reproduce it:

I have installed the addon "Provider for google calendar" (latest version ) in Thunderbird 78.4.0. When I open my thunderbird calendar, create new calendar, select "On the network", choose google calendar and enter my gmail id & click next, I'm facing a blank window (with a spinning circle) and nothing happens. I even waited for 20 minutes once. Here's the screenshot:

![2020-10-26](https://user-images.githubusercontent.com/53212633/97164470-2ead8380-17a8-11eb-80ed-08d07b7afd68.png)

### What happened?

The google sign-in screen that should appear isn't popping-up.

### Anything else we should know?

I even uninstalled the addon, I uninstalled thunderbird, deleted my profile folder & cleaned up all traces of thunderbird from my system. Then I downloaded a fresh copy of thunderbird, installed it, installed the addon "provider for google calendar", setup my email accounts & my ics calendars, finally when i tried to add my google calendar like i'd mentioned above, I'm still facing the same issue!!

Any way i can get around this issue & add my google calendar to thunderbird?

Thunderbird, lightning & provider for google calendar are one of the most important piece of software i use regularly for everyday purposes. Pls solve this issue at the earliest possible. I running Windows 10 20H2. Fully updated.

**Comment by avijaikumar** [comment]
Note: Previously i was using thunderbird 68 & everything was working fine. Problem's there with only 78.x.x

**Comment by wvengen** [comment]
Seeing this too with Thunderbird 78.3.2 (64-bit) on Linux.

**Comment by OnixGH** [comment]
Similar symptoms here, Thunderbird 78.4.0 / 64 bits, plugin version 78.0.1:
```
[Exception... "[object Object]"  nsresult: "0x804a0402 (<unknown>)"  location: 
"JS frame :: resource://gdata-provider/legacy/modules/gdataRequest.jsm :: fail :: line 232"  data: no] gdataRequest.jsm:232:14
    fail resource://gdata-provider/legacy/modules/gdataRequest.jsm:232
    onStreamComplete resource://gdata-provider/legacy/modules/gdataRequest.jsm:499
    openCalendarWizard resource:///modules/calendar/utils/calWindowUtils.jsm:25
    doCommand chrome://calendar/content/calendar-command-controller.js:379
    goDoCommand chrome://global/content/globalOverlay.js:101
    oncommand chrome://messenger/content/messenger.xhtml:1
```

According to the trace, this function call at `calWindowUtils.jsm:25`..
```
    window.openDialog(
      "chrome://calendar/content/calendarCreation.xhtml",
      "caEditServer",
      "modal,chrome,titlebar,resizable,centerscreen",
      aCallback
    );
```

..is ending up in a 404 in `gdataRequest.jsm:499`:
```
 case 404 /* The resource was not found on the server, which is
                         also a conflict */:
        //  404 NOT FOUND: Resource (such as a feed or entry) not found.
        // 410 Gone: Happens when deleting an event that has already
        //           been deleted.
        this.fail(calGoogleRequest.CONFLICT_DELETED, objData);
```

Could it be something with the specific calendar? This is with a recently created calendar (same day), if I fill in a different email address the login popup does open.

**Comment by dd23** [comment]
I'm not sure if this solves the specific issue here, but I ran into a similar problem when I upgraded from TB68 to TB78.4.
I even tried setting up a fresh TB profile, but ran into the same issue that I could not add Google calendars, seeing only the empty screen that @avijaikumar shows in hist 1st post.

The solution to my problem was to **enable Cookies in the Privacy Settings of TB**. I had manually disabled them right after the TB installation, but apparently they are needed for Google Calendar to do its thing. 
Maybe this helps with the posted issue as well.

**Comment by avijaikumar** [comment]
> 
> 
> I'm not sure if this solves the specific issue here, but I ran into a similar problem when I upgraded from TB68 to TB78.4.
> I even tried setting up a fresh TB profile, but ran into the same issue that I could not add Google calendars, seeing only the empty screen that @avijaikumar shows in hist 1st post.
> 
> The solution to my problem was to **enable Cookies in the Privacy Settings of TB**. I had manually disabled them right after the TB installation, but apparently they are needed for Google Calendar to do its thing.
> Maybe this helps with the posted issue as well.

Awesome! The solution provided by dd23 worked perfectly. Something tells me it's better to leave the cookies on the TB 78.4.0 for lightning to work perfectly.

I'll continue to test out different combinations of the cookies setting & will post the results soon.

Thank you dd23!

**Comment by mohclips** [comment]
https://github.com/kewisch/gdata-provider/issues/119#issuecomment-718131039
this fixed my issue as well

**Comment by avijaikumar** [comment]
Kindly note that this issue is not related to issue #124 which appears after we successfully add google calendar to TB

**Comment by OnixGH** [comment]
Cookies were already enabled here, didn't solve the issue for me, moved to #116

**Comment by ph411** [comment]
I'm stumped! Can you pls uninstall tb, delete the profile folder completely. Then download a fresh copy of tb, install it & kindly ensure you do not modify any settings. Just leave all settings in default itself. Then try adding ur calendars. Might help.

(Note: I'm not associated with mozilla. I'm just a user.)

**Comment by danielmmmm** [comment]
> I'll continue to test out different combinations of the cookies setting & will post the results soon.
> 
> Thank you dd23!

@dd23 did you ever find out which sites to allow?

I unchecked "Accept cookies from sites" and added the following exceptions:
https://mail.google.com
https://calendar.google.com
https://accounts.google.com

Unfortunately, this didn't work out as expected. I had to enable all cookies for the calendar plug-in to work.
I feel uneasy allowing all cookies for privacy reasons :-(

**Comment by dd23** [comment]
Sorry, I also had no luck in figuring out which sites to allow while keeping cookies off.

Currently I have cookies enabled, but disabled 3rd-party cookies. The manually white-listed sites are the same as yours.

When I disable cookies, I get the following error on the error console.
```
Lightning: Can't create calendar for UID (gdata, googleapi://USERNAME@gmail.com/?calendar=USERNAME%40gmail.com): TypeError: right-hand side of 'in' should be an object, got undefined CalCalendarManager.jsm:280
```
When I enable cookies the error disappears.
