### ISSUE TITLE
The specified time range is empty

### ISSUE THREAD

**Issue by MLopez-Ibanez** [kewisch/gdata-provider#12]
I have issues with invitations in Google Calendar: https://bugzilla.mozilla.org/show_bug.cgi?id=1567255

Perhaps these errors are important?
```
console.log: Lightning: [calGoogleCalendar] Request GET https://www.googleapis.com/calendar/v3/users/me/calendarList/******%40group.calendar.google.com responded with HTTP 200
console.log: Lightning: [calGoogleRequest] Clock skew is 1 seconds
console.log: Lightning: [calGoogleCalendar] Request POST https://www.googleapis.com/calendar/v3/calendars/*****%40group.calendar.google.com/events responded with HTTP 400
console.log: Lightning: [calGoogleCalendar] A request Error Occurred. Status Code: 400 Bad Request Body: {
 "error": {
  "errors": [
   {
    "domain": "calendar",
    "reason": "timeRangeEmpty",
    "message": "The specified time range is empty.",
    "locationType": "parameter",
    "location": "timeMax"
   }
  ],
  "code": 400,
  "message": "The specified time range is empty."
 }
}

console.error: Lightning: 
  [calGoogleCalendar] Adding Item null failed:2147746065: A request Error Occurred. Status Code: 400 Bad Request Body: {
 "error": {
  "errors": [
   {
    "domain": "calendar",
    "reason": "timeRangeEmpty",
    "message": "The specified time range is empty.",
    "locationType": "parameter",
    "location": "timeMax"
   }
  ],
  "code": 400,
  "message": "The specified time range is empty."
 }
}

console.warn: Lightning: [calCachedCalendar] Unable to perform playback action add to the server, will try again next time (5f3f35ed-9eea-4ae3-b300-b5e6db0181d9,A request Error Occurred. Status Code: 400 Bad Request Body: {
 "error": {
  "errors": [
   {
    "domain": "calendar",
    "reason": "timeRangeEmpty",
    "message": "The specified time range is empty.",
    "locationType": "parameter",
    "location": "timeMax"
   }
  ],
  "code": 400,
  "message": "The specified time range is empty."
 }
}
)
```

**Comment by MLopez-Ibanez** [comment]
Yes, I had that setting enabled. The steps are simple:

1. Launch Thunderbird.
2. Enter master password
3. The error appears in the log
 
Attached a longer log with some private info removed:

[log.txt](https://github.com/kewisch/gdata-provider/files/3609059/log.txt)

**Comment by kewisch** [comment]
A few things from the log:

> `Request GET https://www.googleapis.com/calendar/v3/users/me/calendarList/****%40group.v.calendar.google.com responded with HTTP 404`

It looks like one of the calendars are missing, can you remove this one and try again?

If that doesn't fix it, could you maybe go into the developer tools and see what POST data is being sent for the request with the 400 response that triggers the timeRangeEmpty? I'm not getting this on my end.

**Comment by MLopez-Ibanez** [comment]
```
console.log: Lightning: [calGoogleCalendar] Request GET https://www.googleapis.com/calendar/v3/users/me/calendarList/%23contacts%40group.v.calendar.google.com responded with HTTP 404
console.log: Lightning: [calGoogleCalendar] Error syncing:
2152334338:[Exception... "[object Object]"  nsresult: "0x804a0402 (<unknown>)"  location: "JS frame :: resource://gdata-provider/modules/gdataRequest.jsm :: fail :: line 242"  data: no]
console.error: Lightning: 
  [calCachedCalendar] replay action failed: null, uri=googleapi://****@gmail.com/?calendar=%23contacts%40group.v.calendar.google.com, result=[object Object], operation=[xpconnect wrapped calIOperation]
console.log: Lightning: [calCachedCalendar] replayChangesOn finished.
console.log: Lightning: [calCachedCalendar] sync queue empty.
```

and later:

```
console.log: Lightning: [calGoogleCalendar] Request GET https://www.googleapis.com/calendar/v3/calendars/%23contacts%40group.v.calendar.google.com/events?maxResults=1000&showDeleted=true&syncToken=**** responded with HTTP 200
```
In developer tools, I don't see any POST for this calendar in particular, only a GET request. For another calendar triggering the timeRangeEmpty, I see:

console.log: Lightning: [calGoogleCalendar] Request POST https://www.googleapis.com/calendar/v3/calendars/866***%40group.calendar.google.com/events responded with HTTP 400
console.log: Lightning: [calGoogleCalendar] A request Error Occurred. Status Code: 400 Bad Request Body:

And the body is:

{"start":{"dateTime":"2019-03-29T10:00:00","timeZone":"Europe/London"},"end":{"dateTime":"2019-03-22T10:00:00","timeZone":"Europe/London"},"reminders":{"overrides":[],"useDefault":false},"recurrence":["RDATE;VALUE=DATE-TIME:20190329T110000Z"]}

**Comment by kewisch** [comment]
> And the body is:
> 
> ```
> {"start":{"dateTime":"2019-03-29T10:00:00","timeZone":"Europe/London"},"end":{"dateTime":"2019-03-22T10:00:00","timeZone":"Europe/London"},"reminders":{"overrides":[],"useDefault":false},"recurrence":["RDATE;VALUE=DATE-TIME:20190329T110000Z"]}
> ```

Hm I see, so the end is after the start time, I wonder how that happens. Could you show me the stack of where that request is made?

**Comment by MLopez-Ibanez** [comment]
> Hm I see, so the end is before the start time, I wonder how that happens. Could you show me the stack of where that request is made?

How do I get the stack?

**Comment by MLopez-Ibanez** [comment]
These are the entries around the errors:
``` "sequence": 1,
 "extendedProperties": {
  "private": {
   "X-MOZ-LASTACK": "2020-04-30T07:57:07Z",
   "X-MOZ-SNOOZE-TIME": "2020-04-30T08:57:07Z"
  }
 },
 "reminders": {
  "useDefault": false,
  "overrides": [
   {
    "method": "popup",
    "minutes": 21600
   }
  ]
 }
}

JavaScript strict warning: resource://gdata-provider/modules/gdataUtils.jsm, line 695: ReferenceError: reference to undefined property "originalStartTime"
JavaScript strict warning: resource://gdata-provider/modules/gdataLogging.jsm, line 103: ReferenceError: reference to undefined property "QueryInterface"
```

**Comment by kewisch** [comment]
It turns out I've fixed this in a more recent issue, should be fine in 91.0.2 and up once it is released.
