### ISSUE TITLE
Calendar events not shown

### ISSUE THREAD

**Issue by lucamosca1** [kewisch/gdata-provider#120]
Thunderbird 78.4.0 (32bit) installed on Windows 10 fully upgraded.

### Describe the problem and steps to reproduce it:
Calendar events (from default gmail calendar) are not shown when I open thunderbird. Both in main view (mail and calendar)

### What happened?
Opening the calendar view I see my gmail subscribed calendars in left column, but calendars are empy. 
Next to calendar there is the 'eye' icon to show/hide the events. Default is show the calendar but is empty.
If I clice twice, one to hide and the following to show, all events reappers.

### What did you expect to happen?
If I leave calendar set to show, I exepct that the calendar is always shown when I open the application

Not sure if it is something realted to calendar feature of thunderbird or this plugin

**Comment by mohclips** [comment]
i have a similar issue

**Comment by dmonnehay** [comment]
As indicated on #105 removing the extension (without unsubscribing to the calendars, just leave every check boxes uncheck) and reinstalling it fixed if for me (and a few others it seems)

**Comment by philagar16** [comment]
#119 fixed mine

**Comment by mohclips** [comment]
> i have a similar issue

fixed in https://github.com/kewisch/gdata-provider/issues/119#issuecomment-718131039

**Comment by avijaikumar** [comment]
> 
> 
> As indicated on #105 removing the extension (without unsubscribing to the calendars, just leave every check boxes uncheck) and reinstalling it fixed if for me (and a few others it seems)

Hi dmonnehay, this solution actually seems to work at first. But after a few days, the problem reappears. And the only solution is to repeat the same steps again & again.

This isn't an optimal. We have to find a more permanent solution.

**Comment by avijaikumar** [comment]
> 
> 
> > i have a similar issue
> 
> fixed in [#119 (comment)](https://github.com/kewisch/gdata-provider/issues/119#issuecomment-718131039)

#119 & #120 are very different issues. The first one happens when we try to add a google calendar. The second one happens after we add google calendar and start using it.

**Comment by jezhiggins** [comment]
Just as an extra data point, I'm seeing this behaviour with Thunderbird 78.3.2, 64 bit running on Ubuntu 20.10. I also have CalDav calendars and they are not affected - they always appear when I restart Thunderbird.

**Comment by jkytomak** [comment]
I also have this same issue on Mac OS Catalina 10.15.7:
Thunderbird 78.4.0 
Provider for Google Calendar 78.0.1

**Comment by jkytomak** [comment]
Looks like https://github.com/kewisch/gdata-provider/issues/113 is also same issue

**Comment by jkytomak** [comment]
Disabling and then reenabling provider in the add-ons tab fixed the problem for me.

**Comment by ph411** [comment]
You're right @jkytomak. It solves the problem. But only temporarily. The issue automatically re-appears after a day or two. Disabling & then re-enabling the addon is not a permanent solution. It's just a temporary fix.

**Comment by kewisch** [comment]
This was fixed in Thunderbird IIRC, please test with Thunderbird 91
