### ISSUE TITLE
Cannot invite attendees to existing event

### ISSUE THREAD

**Issue by monochromec** [kewisch/gdata-provider#121]
### Describe the problem and steps to reproduce it:

Schedule event in gcal
Invite attendees via their mail address
Changes never make it to the gcal entry

(Please include as many details as possible.)

### What happened?

Cf. error console log:
gist.github.com/monochromec/d9a5d257a1b4604af092e668bc284d15

### What did you expect to happen?

Email is sent to attendee and gcal entry is updated

### Anything else we should know?

Reproducible with 78.0.1 on TB 78.3.2 on Groovy and 78.4 on OSX 10.15.7

Please let me know if you need more info.

**Comment by kewisch** [comment]
#147
