### ISSUE TITLE
Incompatible with task due times

### ISSUE THREAD

**Issue by loquinator3000** [kewisch/gdata-provider#122]
### Describe the problem and steps to reproduce it:
Task due times don't sync to Thunderbird, and can't create due time inside Thunderbird at all
When making a task inside of the google task web interface, you can optionally set a due date or date+time. However, only the due date is shown correctly in Thunderbird, with the time showing as "all day" even if a due time is assigned. Furthermore, editing and saving this task inside Thunderbird will cause the task to lose its due time in the web interface. There isn't even an option to set a due time in the edit window at all, unlike tasks in all of my other accounts.

This is the case for both my G Suite and personal accounts.

There were no Provider for Google Calendar-related error messages. The only relevant information I found:
`Lightning: [calGoogleCalendar] Request GET https://www.googleapis.com/tasks/v1/lists/(redacted)/tasks responded with HTTP 200 gdataRequest.jsm:383`
`Lightning: [calGoogleCalendar] Parsing 1 received tasks gdataUtils.jsm:1039`
`Lightning: [calGoogleCalendar] Last sync date for My Tasks(tasks) is now: 2020/10/28 20:08:24 UTC isDate=0 nativeTime=1603915704000000`
`Lightning: [calCachedCalendar] replayChangesOn finished.`
`Lightning: [calCachedCalendar] sync queue empty. calCachedCalendar.js:329`

**Comment by kewisch** [comment]
Unfortunately this is an issue with Google's API. Please see https://issuetracker.google.com/issues/173281470 for details and star the issue to give it some attention. On the `main` branch of this repo I have code that will at least only change fields you've changed, so if you don't change the due date it will at least keep it.
