### ISSUE TITLE
Provider is disabled on Thunderbird 78.4.0

### ISSUE THREAD

**Issue by rdasilva** [kewisch/gdata-provider#123]
Thunderbird just auto-updated to 78.4.0 and disabled gdata-provider. Can we expect an update to fix compatibility soon?

**Comment by avijaikumar** [comment]
Not sure whether this'll help you. But I recommend that you try to uninstall the provider for google calendar addon & re-install the latest version to see whether is solves the problem. Might help.

**Comment by rdasilva** [comment]
The download page lists it as only compatible with 78.2.0 or lower (https://addons.thunderbird.net/en-US/thunderbird/addon/provider-for-google-calendar/). But I'll uninstall and force an install and see if it works. Thanks.

**Comment by avk411** [comment]
Not sure. Pls give it a try, I recently removed TB & all associated stuff including the profile folder from my system, downloaded a fresh copy of TB 78.4.0, installed it & configured the email, then opened the addons tab, searched for "provider".

The first result is "provider for google calendar". When i clicked "Add to Thunderbird", it just added without any issues. But getting it to work is a different story (your mileage may vary). If you encounter issues, pls check #119 & #124. The solution to #119 works fine. We're still waiting waiting for a good workaround or a nice bugfix for #124.

**Comment by LukeKitt** [comment]
On my System the autoupdate of the plugin didn't work. So I had an version from 2019.
After manually installing the newest Version everything worked again.

**Comment by imathrowback** [comment]
> On my System the autoupdate of the plugin didn't work. So I had an version from 2019.
> After manually installing the newest Version everything worked again.

Thanks! This was exactly my issue.

Auto-update didn't work properly.

The addon page showed 68.0 installed. The version (as of this writing) on the addons Thunderbird repository is 78.0.1

**Comment by kewisch** [comment]
This should be resolved for Thunderbird 91
