### ISSUE TITLE
recurring events go on forever......

### ISSUE THREAD

**Issue by ohmjohn** [kewisch/gdata-provider#125]
If I create a recurring 'once a week event' in Calendar (Thunderbird 78.4.0 MacOs) and limit it to '31-12-2020', it goes on for eternity. The recurrence doesn't halt after 31-12-2020. Never had this problem before, but it occurs since 78.2.0. I'm using the extension 'Provider for Google Calendar version 78.0.1'.
The problem does not exist if I create the recurring event directly in Google Calendar.

Update 13-11-20:
Several TB updates further (now on 78.4.3 MacOs) and the problem still exists. Isn't there anyone who has the same problem? Or is it a Lightning problem?

**Comment by whpress** [comment]
I notice behavior identical to that described.  Thunderbird 78.6.0 Windows, Provider 78.0.1.

**Comment by pmbrandao** [comment]
Happens to me also in TB 78.6.1
Changing the recurrence directly on Google Calendar fixes it in Thunderbird (although I have not changed the "until" date in TB again).

**Comment by kewisch** [comment]
Sounds like #183 ?
