### ISSUE TITLE
Compatibility with latest Thunderbird upate

### ISSUE THREAD

**Issue by leonbohmann** [kewisch/gdata-provider#126]
### Describe the problem and steps to reproduce it:

The Add-On is incompatible with the latest Thunderbird-Update (v78.x).

**Comment by LukeKitt** [comment]
Hi,

no the addon is compatible.
To me the same happend.
I saw in the update history that an old version from 2019 was present of the Addon. 
It seems like the autoupdate didn't work correctly.

Fixxed for me: 
Remove the old addon
Install manually from file
Old config was loaded automatically.

Hope that solves the problem for you.

**Comment by leonbohmann** [comment]
The solution posted by @LukeKitt worked for me.
Thanks!!
