### ISSUE TITLE
Sender line added in displayed emails after upgrade to TB 78

### ISSUE THREAD

**Issue by jouvin** [kewisch/gdata-provider#128]
After upgrading to TB78, all the displayed emails have a spurious Sender line added. After some troubleshooting, disabling the Google Agenda provider extension (the only one I have) fixed the issue. I don't think it is really related to this extension but more to something in TB. Details are in https://bugzilla.mozilla.org/show_bug.cgi?id=1670243. My comment mentioning GC provider extension is the last one at this time...

**Comment by kewisch** [comment]
Looks like this was fixed in Thunderbird, thanks for reporting!
