### ISSUE TITLE
Missing Location on some calendar events

### ISSUE THREAD

**Issue by TheOldChief** [kewisch/gdata-provider#130]
### Describe the problem and steps to reproduce it:
I have a long standin reminder for a bi-weekly event.  It occurs at various locations.  As soon as I learn of the location, I edit the event for that day so I will know where to be.  None of hte locations are displaying in the Thunderbird calendar, but they do on my other devices.
(Please include as many details as possible.)

**Comment by kewisch** [comment]
Can you try the following:

1) Enable debugging (see wiki)
2) Add a location on your other device
3) Clear browser console
4) Synchronize

Then you should be able to see the added/changed event in the console, would be interested to see both the original json and how it gets translated.

**Comment by TheOldChief** [comment]
Never mind - after several Thunderbird and Google Provider updates everything is working as expected - except ....

Seems stuck on 24 hour time format (no problem for me after a military career) rather than AM, PM time format (much better for friends and family) and I have no clue how to get back.
