### ISSUE TITLE
Does not work with Thunderbird 78 =fixed (?)

### ISSUE THREAD

**Issue by 3rdRockGuy** [kewisch/gdata-provider#131]
ref https://github.com/kewisch/gdata-provider/issues/77#issue-629621410
=closed
**but still a problem so still needs attention**
**because i repeatedly did *not* google popup asking for authentication**
after entering google account email adress, which just hanged for ages never completing.

Eventually I think I've solved this -pending more testing (=wait and see) by:
**disconnect google email saved passwords in TBird
+check google account no longer allows thirdparty access to TBird (email or calendar).**

Then (after reboot TBird) retry connect calendar.

So yes the basic procedure for connecting a google cal is simple, tvm = not the problem.
The problem seems to be TBird not fully dicsonnected  from Google Acc / Ggle Acc not fully disallowing 3rd Party access,
before trying to connect Tbird to Ggle Cal /trigger Ggle CAL 3rd party access to TBird.

**Comment by wendelb** [comment]
I was not that lucky with removing access to Google Calendar. I revoked access in Google Account Settings; removed all calendars from `prefs.js` and removed all passwords/tokens from password manager. Then reinstalled the addon.
Still not getting the login screen.

Here is a screen grab from the error log in case it helps:

![ErrorLog](https://user-images.githubusercontent.com/5375171/101286783-d4630200-37ec-11eb-8a3d-7493436c384c.png)

**Comment by kewisch** [comment]
This is fixed in Thunderbird 91
