### ISSUE TITLE
Read Only Calendars Generating Dialogs On Startup

### ISSUE THREAD

**Issue by y0himba** [kewisch/gdata-provider#132]
### Describe the problem and steps to reproduce it:
I am subscribed to 7 calendars that are read only. They aren't my calendars, so I don't have permission to change them. On startup of Thunderbird, I get 7 notifications that I must click Okay on before I can use the program. 

1: Subscribe to a read only calendar. 
2: Start Thunderbird.
3: You'll get a notification like the attached screenshot that you must dismiss to get your mail. 
![not_writeable](https://user-images.githubusercontent.com/11462603/98890399-e362c880-2469-11eb-8cc5-8ae97cc854ee.jpg)

(Please include as many details as possible.)

### What happened?
Multiple dialogs to be closed upon starting Thunderbird. 

### What did you expect to happen?
If a calendar is marked read only then sync shouldn't be attempted for that calendar. Writeable calendars should still sync. 

### Anything else we should know?
If there is a setting I am missing please let me know. No logs should be needed since it isn't really an error?

  Please also include screenshots and any relevant files.

![calendars](https://user-images.githubusercontent.com/11462603/98890394-e067d800-2469-11eb-9401-07da7af43d18.jpg)
![read_only](https://user-images.githubusercontent.com/11462603/98890326-b7dfde00-2469-11eb-8689-2d37f4d33a06.jpg)

**Comment by kewisch** [comment]
I don't know where this dialog comes from, are you sure it comes from the Provider?
