### ISSUE TITLE
Using provider with Seamonkey 2.54.3

### ISSUE THREAD

**Issue by mfidelman** [kewisch/gdata-provider#135]
### Describe the problem and steps to reproduce it:

New install of Seamonkey (2.54.3)
Downloaded Provider for Google Calendar
Tried to install

### What happened?
Error message:  "not compatible"

### What did you expect to happen?
For it to install & work.

### Anything else we should know?

Any notion of when a compatible update might be coming?

**Comment by kewisch** [comment]
Unfortunately I'm not supporting Seamonkey at the moment.
