### ISSUE TITLE
Calendars Hidden by default on Mac

### ISSUE THREAD

**Issue by pacolvin** [kewisch/gdata-provider#137]
### Describe the problem and steps to reproduce it:

Each time Thunderbird (78.4.3) is opened on a Mac, the calendars are hidden.  To see them, you must click the eyeball to unhide them.

### What happened?

Happens every time Thunderbird is opened.

### What did you expect to happen?

All calendars to be visible by default.

### Anything else we should know?

I have removed and reinstalled the add on and get the same result after adding all calendars.

**Comment by xentobias** [comment]
Same on Windows

**Comment by pire12** [comment]
Try to switch the add-on off then back on (see #133)

**Comment by kata32** [comment]
> Try to switch the add-on off then back on (see #133)

I don't know why, but this solve the issue!

**Comment by pacolvin** [comment]
That restores it but the problem will come back after the Thunderbird is closed and opened in a new session.

Thanks

Phil

**Comment by kata32** [comment]
> That restores it but the problem will come back after the Thunderbird is closed and opened in a new session. Thanks Phil

Not in my case, after pire12 advice if I close Thunderbird and reopen it calendars are correctly displayed

**Comment by monochromec** [comment]
Any progress on eliminating the root cause for this issue (as the above is a work-around)?

**Comment by kata32** [comment]
Not yet, and sometime issue return also with [pire12 advice](https://github.com/kewisch/gdata-provider/issues/137#issuecomment-736529139)

**Comment by kewisch** [comment]
I believe this was fixed in Thunderbird in the meanwhile. Please upgrade to Thunderbird 91 and try again.
