### ISSUE TITLE
"Reminder" does not appear

### ISSUE THREAD

**Issue by Catwheazle** [kewisch/gdata-provider#141]
The Google Calendar displays the "appointments" but not the "reminders"
Thunderbird 78.5.0 (32-Bit and 64-Bit)
Provider für Google Kalender 78.0.1

(Please include as many details as possible.)

### What happened?
nothing
### What did you expect to happen?
show "reminders too 
### Anything else we should know?
no

**Comment by fajabird** [comment]
"Reminder" are the type of events created for example when saying "hey google - remind me to by milk tomorrow" by google-assistant. They appear in my android calendar but lightning currently will not display them. IMHO they are neither tasks nor events but a new type of items. I also would love to see them on my desktop.

**Comment by Jacques-46** [comment]
At least, it should be useful to have a way to display this new type of calendar object which can be created on a smartphone.

**Comment by kewisch** [comment]
I don't see anything like this in the API, just tasks and events. Where do these appear in Google Calendar? Are you subscribed to both your main calendar and main tasks list in Thunderbird?

**Comment by Jacques-46** [comment]
Reminders appears recently both on Android and direct web access to calendar (url; calendar.google.com). Reminders can't be shared, there is only colour choice in the menu. Reminders appear as a separate calendar just like events, week-numbers and tasks calendars. In Thunderbird, I subscribed to all item which are available but reminder is not available in the list. 
As it is new feature, perhaps Google will include it in the API "soon" !

**Comment by Catwheazle** [comment]
Thx :-)

⁣BlueMail for Android herunterladen ​

**Comment by kewisch** [comment]
Ah I see what you mean. I don't see any special configuration for this calendar, if it doesn't show in the [calendarList](https://developers.google.com/calendar/api/v3/reference/calendarList/list) API then unfortunately there is nothing I can do about it right now. If Google enables this, it should "just work" unless they create a new API for it. Hope they add this soon!
