### ISSUE TITLE
Google holiday calendars do not work with TB 84.0b2 / Provider 78.0.1

### ISSUE THREAD

**Issue by HelmutL** [kewisch/gdata-provider#142]
### Describe the problem and steps to reproduce it:

Google holiday calendars do not show in TB any more. They have been created with former versions of TB. I do not remember which version nor when it got broken.

### What happened?
calendars cannot be shown
### Anything else we should know?
does not work with either of these definitions (calendars are shown on Android or web-browsers)
"googleapi://hlein@gmx.at/?calendar=de.austrian%23holiday%40group.v.calendar.google.com"
"googleapi://de.german#holiday@group.v.calendar.google.com/?calendar=de.german%23holiday%40group.v.calendar.google.com"

**Comment by HelmutL** [comment]
[console-export-2020-11-30_8-19-1.txt](https://github.com/kewisch/gdata-provider/files/5617392/console-export-2020-11-30_8-19-1.txt)

**Comment by r-a-y** [comment]
As a workaround, I'd use the holiday calendars available on thunderbird.net. They work with Lightning and use .ics:
https://www.thunderbird.net/en-US/calendar/holidays/

**Comment by HelmutL** [comment]
Thanks

**Comment by kewisch** [comment]
This should be resolved in Thunderbird 91 thanks to f5d4fc65cc09403b90c76aba52415432be567f9b
