### ISSUE TITLE
Thunderbird keeps verification via Google mobile app

### ISSUE THREAD

**Issue by Piotwie** [kewisch/gdata-provider#145]
I have 5 calendars on Google. Today I opened Thunderbird and it asked me to do verification via Google mobile app. I chose one of three codes and confirmed verification. After 5 verifications calendars was without a warning icon but when I tried to add event to calendar it asked me for another verification. I deleted google calendar extension from thunderbird, reset my computer, installed once again and the problem appear again. I can't add calendars. It shows information to confirm my google account on PC after choosng 1/3 code, it doesn't show me calendars to choose on thunderbird. 

Thunderbird 
52.4.0 (32 bity)
Google Calendar Proivder 4.4.2

Do you have any idea how to solve it ? Now I can't use my google calendar.. 

Here some infor from Error Console
TypeError: sourceDoc.getSelection is not a function[Więcej informacji]  mailWindow.js:74:19
[calGoogleSession] Authentication failure: {
  "error": "invalid_grant",
  "error_description": "Malformed auth code."
}  gdataSession.jsm:272:21
[Exception... "invalid_grant"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gdata-provider/modules/gdataSession.jsm :: calGoogleSession.prototype.login/authFailed< :: line 274"  data: no]  (nieznane)
[calGoogleSession] Authentication failure: {
  "error": "invalid_grant",
  "error_description": "Malformed auth code."
}  gdataSession.jsm:272:21
[Exception... "invalid_grant"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gdata-provider/modules/gdataSession.jsm :: calGoogleSession.prototype.login/authFailed< :: line 274"  data: no]

**Comment by liamdv4** [comment]
+1

Seeing the same "invalid_grant" error

**Comment by Piotwie** [comment]
Comments on Thunderbird Addons site:
https://addons.thunderbird.net/pl/thunderbird/addon/open-google-calendar/

I think we need to wait for an update.. 

_by Delusional Matt on Dec. 15, 2020 · permalink

Used to work great, however Google is making major security changes and this, and many many other apps, extensions and services, are causing Critical security alerts and account lock-outs. Author needs to contact Google to get them to approve extension again. Disabling extension for now.
Rated 5 out of 5 stars

by hjdschneider on Dec. 15, 2020 · permalink

seit gestern 14.12.2020 googledown war, verlangt das addon meine googlezugangsdaten in einem popup-fenster. die eingabe wird aber mit hinweis auf "Entweder unterstützt der verwendete Browser JavaScript nicht oder JavaScript ist deaktiviert." abgelehnt. Keine Seiten sind geblockt oder zugelassen, wie vorher auch. Was muss ich tun? Danke für ein Feedback, Gruß Achim_

**Comment by kewisch** [comment]
Hey folks, a few things to try:
* Remove all entries from the password manager related to the provider
* Make sure you have cookies enabled in Thunderbird

I'm going to go ahead and close this issue since it has been a while and a few things have changed. Please retest in Thunderbird 91.
