### ISSUE TITLE
Google Calendar ask to connect

### ISSUE THREAD

**Issue by Pixelkomando** [kewisch/gdata-provider#146]
Eveytime i open Thunderbird, Google Calendar ask to connect. A specific windows pops up and ask me to connect. It's ok, but it ask me everytime i open or everytime a want to modify / create an appointment.

`Lightning:[calGoogleCalendar] Failed to acquire a new OAuth token for xxx@gmail.com data: {
  "error": "invalid_grant",
  "error_description": "Malformed auth code."
}  gdataSession.jsm:247
Lightning:[calGoogleSession] Authentication failure: {
  "error": "invalid_grant",
  "error_description": "Malformed auth code."
}  gdataSession.jsm:272
Lightning:"[calGoogleCalendar] Error syncing:
2147500037:[Exception... "invalid_grant"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gdata-provider/modules/gdataSession.jsm :: login/authFailed< :: line 274"  data: no]"  calGoogleCalendar.js:797
Lightning:[calCachedCalendar] replay action failed: null, uri=googleapi://xxx@gmail.com/?calendar=xxx%40gmail.com, result=invalid_grant, operation=[xpconnect wrapped calIOperation]
`

**Comment by therealmantm** [comment]
I have the same problem.
December 14 from 12:00 to 13:00 UTC many services from Google did not work. After this event I get an endless authorization window when updating the calendar.

**Comment by Piotwie** [comment]
I posted the same problem.. 
https://github.com/kewisch/gdata-provider/issues/145

any ideas how to solve it ? Maybe Google changed verification process ?

**Comment by beeva-jacobofeijoo** [comment]
I have the same problem, **BUT**...

a) I have 2 profiles in Thunderbird
b) Personal profile has a name similar to fx6xvpop.myname for Thunderbird. It works perfect. It calls to an account as myname@gmail.com
c) Professional profile has a name similar to fx6xvpop.default-release. It crashes. It calls to an Gmail account **BUT** named as myname@myenterprise.com

It is the only difference I can see. I hope to help with this point of view.

**Comment by JacoboFeijoo** [comment]
I saw a new pattern. It asks me for conecting once per calendar (I have 4 calendars in my business profile, so it asks me for 4 connections). Each time I put user/pass (log in in Google), a new OAuth token is generated in plugin in options/privacy/passwords. I have a lot of tokens!

**Comment by kewisch** [comment]
The problem from the OP should be gone in Thunderbird 91
