### ISSUE TITLE
Add attendee window fails due to circular dependency

### ISSUE THREAD

**Issue by lduperval** [kewisch/gdata-provider#147]
### Describe the problem and steps to reproduce it:

using lightning 78.0.1
using Thunderbird 78.6
to reproduce the problem:

1. Create an invite for a Google calendar
2. Add an attendee
3. Click send and close
4. Reopen meeting
5. Notice that attendee list is empty
6. Look at the sent folder: invite was not sent

(Please include as many details as possible.)

### What happened?

the invite was not sent, and the event is saved in the Google calendar with no attendees.

### What did you expect to happen?

I expected the invite to be sent to the recipients and to be saved with the list of recipients in the Google calendar.

### Anything else we should know?

Lightning: [calGoogleCalendar] Failed freebusy request: [Exception... "A request Error Occurred. Status Code: 400 Bad Request Body: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "badRequest",
    "message": "Bad Request"
   }
  ],
  "code": 400,
  "message": "Bad Request"
 }
}
"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://gdata-provider/legacy/modules/gdataRequest.jsm :: fail :: line 232"  data: no]

**Comment by Tripp339** [comment]
Still not happening for me, either.  This issue has been ongoing now for a while.

**Comment by pgreer-splunk** [comment]
Anyone out there able to look into this? Really hoping can be resolved soon....

**Comment by gmayne** [comment]
I have the same issue (doesn't send invites) on Win10 and TB 78.6.1.

**Comment by rmc-va** [comment]
I have the same issue (doesn't send invites) on Win10 (64-Bit) and TB 78.6.1 (32-Bit) + Provider (78.0.1).  
If I disable Provider, then invitations can be sent and they stay in the new calendar entry.
:(

**Comment by punkfrogab** [comment]
I've had this problem since I upgraded to Big Sur in November, and it is still there. Exactly same behaviour as Iduperval describes. OSX 11.1, Tbird 78.7.0 (64-bit), Provider 78.0.1.

**Comment by rivens** [comment]
+1 On this. Same issue for me as described by the original poster. Windows 10 64-bit, TB 78.7.0 (32-bit), provider 78.0.1. When I create a calendar item & invite people, save it and then go immediately back into the event, the attendees are gone. (And they never received an invite)

**Comment by somzoli** [comment]
+1. Same issue for me. 
MacOS BigSur 11.1
Thunderbird 78.7.1 (64-bit)
Create new event, add attendee, Save and close, reopen, missing attendee

**Comment by humbertleonardo** [comment]
Did the Developer abandon the project?

**Comment by Tripp339** [comment]
It seems so.  Phillip is no where to be found for quite sometime now.  No replies, no fixes, no nothing.

**Comment by humbertleonardo** [comment]
We can mobilize and create a Fork to fix these bugs with the help of the guys, what do you think?

**Comment by Tripp339** [comment]
Anything anyone can do to fix this issue would help me tremendously.  This issue has gone on for a long time.

**Comment by realtofuine** [comment]
For me ,the fix was just using CalDav. Everything worked then. (I am using the latest version of Thunderbird)

**Comment by humbertleonardo** [comment]
Does CalDav allow reading and writing of events and participants?

**Comment by realtofuine** [comment]
Yes, it works perfectly for me.

**Comment by humbertleonardo** [comment]
How did you configure it? Could you teach us?

**Comment by realtofuine** [comment]
Yeah do the following (skip step 1)
https://www.ubuntubuzz.com/2017/07/how-to-setup-thunderbird-for-google-calendar-caldav-read-write-access.html

**Comment by humbertleonardo** [comment]
![image](https://user-images.githubusercontent.com/57204453/116413933-6c9a6b80-a80e-11eb-8bda-51beab2b6f54.png)

I managed to add via CalDav, but it does not enable the option to invite participants to my event

**Comment by realtofuine** [comment]
Yeah, it's a little bit buggy. Try to retype in your email address and then
press enter to add in a new person. Usually I have to do that

**Comment by humbertleonardo** [comment]
I was able to correct this bug using the following method, tested and approved by me

https://support.mozilla.org/en-US/kb/enable-email-invitations-caldav-servers-configured

**Comment by DerekBoothSEO** [comment]
I can't see the option!
Using 78.11.0 (64-bit)

What am I missing?

![image](https://user-images.githubusercontent.com/42970190/125442920-91ae2f1d-8e0c-445a-bcad-4fc13dced5e0.png)

**Comment by Tripp339** [comment]
The app no longer works and the developer is no where to be found.  That's what you are missing as is all the rest of us.  This app is no longer supported by the developer based on our experiences of late.

**Comment by kewisch** [comment]
Hey folks, sorry it has been such a long time. I'm fixing a number of issues related to attendees for 91.0.2, this one included.

**Comment by rmc-va** [comment]
Glad that you are ok and back along us again.
