### ISSUE TITLE
Provider for Google Calendar (gdata-provider) extension shows up in version 68.0 instead of 68.1 in Thunderbird 68.1 ESR

### ISSUE THREAD

**Issue by richardleger** [kewisch/gdata-provider#15]
As observed in https://bugzilla.mozilla.org/show_bug.cgi?id=1544320#c43

Steps to reproduce:
    - Install Thunderbird 68.1 ESR (British version) from https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/68.1.0/win32/en-GB/Thunderbird%20Setup%2068.1.0.exe
    - Go to TB Menu > Add-ons > Extensions
    - Search for Provider for Google Calendar
    - Add this add-on via the add button
    - Restart Thunderbird

Actual results:
    - Provider for Google Calendar extension shows up in version 68.0

Expected results:
    - Provider for Google Calendar extension should show up in version 68.1 as it seems available https://archive.mozilla.org/pub/thunderbird/releases/68.1.0/en-US/gdata-provider.en-US.xpi

**Comment by richardleger** [comment]
Phillipp,

When accessing the Provider for Google Calendar Add-On page via Thunderbird 68.1 ESR Extension tab redirecting to https://addons.thunderbird.net/en-GB/thunderbird/addon/provider-for-google-calendar/?src=search only 68.0 version of the add-on shows up... instead of version 68.1 as available here https://archive.mozilla.org/pub/thunderbird/releases/68.1.0/en-US/gdata-provider.en-US.xpi

Is that something you can easily fix?

I suppose TB 68.0 shall redirect to version 68.0 of the add-on while TB 68.1 shall redirect to version 68.1 of the add-on... otherwise that cause compatibility issue as observed in bug https://bugzilla.mozilla.org/show_bug.cgi?id=1544320#c39

Regards,

**Comment by kewisch** [comment]
I don't necessarily do a release for every Thunderbird release. You'll only see what was released on addons.mozilla.org, and that is what is authoritative.
