### ISSUE TITLE
Support conferenceData

### ISSUE THREAD

**Issue by igieon** [kewisch/gdata-provider#154]
### Describe the problem and steps to reproduce it:

When i open calendar via gdata-provider and then export to ics this ics contains for event:
DESCRIPTION:Default Mozilla Description

When i import same calendar via ics and export it same event in description has google meet url:
DESCRIPTION: .... https://meet.google.com/.....

### What did you expect to happen?
I expoct that meet.google.com url apear in description

**Comment by igieon** [comment]
Ok i debug it and i found that need to by updated gDataUtils.jsm around line 745. 
Is needed chagne line something like this 
```
item.setProperty("DESCRIPTION", (aEntry.description ||"") + " " + (aEntry.hangoutLink||""));
```

Or more precise extract data from conferenceData where is link, phone something similar how is it generated in clasic ics import.

**Comment by mpapis** [comment]
related #60

**Comment by MLopez-Ibanez** [comment]
> Ok i debug it and i found that need to by updated gDataUtils.jsm around line 745. Is needed chagne line something like this
> 
> ```
> item.setProperty("DESCRIPTION", (aEntry.description ||"") + " " + (aEntry.hangoutLink||""));
> ```
> 
> Or more precise extract data from conferenceData where is link, phone something similar how is it generated in clasic ics import.

Fork and send a pull request?
