### ISSUE TITLE
Not Responding

### ISSUE THREAD

**Issue by REWard01** [kewisch/gdata-provider#155]
### Describe the problem and steps to reproduce it:
On three different PCs all running Windows 10 Latest Release & All Updates.
Latest Thunderbird Version (78.6.1) and latest download of Provider for Google Calendar (78.0.1).
when the extension is installed (enabled or disabled) Thunderbird stops responding, have to force close, on all three systems.
have to load thunderbird in safe mode to remove extension, once extension is removed, thunderbird works fine.

(Please include as many details as possible.)

### What happened?
No Response with extension installed (enabled or disabled)
### What did you expect to happen?
Resonding!?!

**Comment by kewisch** [comment]
Please try to wait it out. If you have a large calendar, the first sync will be super slow. Any subsequent syncs will be very quick.
