### ISSUE TITLE
Liste invités dans un évènement

### ISSUE THREAD

**Issue by BobCol** [kewisch/gdata-provider#158]
Lorsque je créer des évènement avec des invités, des que thunderbird affiche le rappel programmé, la liste d'invités est supprimé et l'évènement et de ce fait supprimée des agenda des invités.
Par contre, si je créé un évènement sans qu'il n'y ai de rappel, la liste d'invité n'est pas supprimé, même après que l'évènement soit passé.

Thunderbird 78.7.0 (32bits),

**Comment by roccopietrini** [comment]
Duplicate of [https://github.com/kewisch/gdata-provider/issues/129](url)
