### ISSUE TITLE
Google Calenders sync problem with Thunderbird 78.7.0 (64-bit)

### ISSUE THREAD

**Issue by ghost** [kewisch/gdata-provider#159]
Google Calenders sync problem with Thunderbird 78.7.0 (64-bit). The  Provider for Google Calendar 78.0.1  Add-On needs updating.

**Comment by LIko2405** [comment]
I also have this problem. Upgraded to 78.7 and Calendar wouldn't sync tho it listed my Google calendars fine. I unsubscribed and re-subbed to Google and all seemed ok but after I closed TB and re-opened it showed none of my Google entries. Again, it listed them fine.

**Comment by Frank071** [comment]
It looks like simply undisplaying (eye with strikethrough) and displaying (normal eye) again the agenda shows the entries - no need to remove and resub the calendar.

**Comment by jsuvanto** [comment]
I have six synced calendars from Google calendar (one personal, several shared to some of which I have write access and some I don't) and they all behave the same way.

Error console does not indicate any problems reported by Lightning (some stuff redacted and collated):
```
Lightning: [calGoogleSessionManager] Creating session [gmail account]
Lightning: [calGoogleSessionManager] Reusing session [gmail account] x5
Lightning: [calCachedCalendar] Performing playback operation add on 0 items to [calendar name] x6
Lightning: [calCachedCalendar] Performing playback operation modify on 0 items to [calendar name] x4
Lightning: [calCachedCalendar] Performing playback operation delete on 0 items to [calendar name] x6
Lightning: [calCachedCalendar] Doing changelog based sync for calendar googleapi://[gmail account]/[...]
Lightning: [calGoogleSession] Adding item https://www.googleapis.com/calendar/v3/users/me/calendarList/[...] to queue x6
Lightning: [calGoogleSession] Adding item https://www.googleapis.com/calendar/v3/calendars/[...]/events to queue x6
Lightning: [calGoogleSession] Token expired 1612845764 seconds ago, resetting
Lightning: [calGoogleCalendar] Logging in session [gmail account]
Lightning: [calGoogleCalendar] No access token for [gmail account], refreshing token
Lightning: Start loading of locale dependent preference default values...
Lightning: Loading of locale sensitive preference default values completed.
Lightning: [calGoogleCalendar] Successfully acquired a new OAuth token for [gmail account]
Lightning: [calGoogleRequest] Clock skew is -1 seconds x12
Lightning: [calGoogleRequest] Requesting GET https://www.googleapis.com/calendar/v3/users/[...] x 12
Lightning: [calGoogleCalendar] Timezone for [calendar] is UTC x6
Lightning: [calGoogleCalendar] No events have been changed on [calendar] x6
Lightning: [calGoogleCalendar] New sync token for [calendar] is now: [token]
Lightning: [calCachedCalendar] replayChangesOn finished. x6
Lightning: [calCachedCalendar] sync queue empty. x6
```
I can provide full logs with sensitive information removed if necessary.

There are a few warnings:
```
OverrideError: An entry font-size-label of type message is already defined in this bundle
OverrideError: An entry window-close-key of type message is already defined in this bundle
OverrideError: An entry startup-label of type message is already defined in this bundle
OverrideError: An entry focus-search-shortcut of type message is already defined in this bundle
OverrideError: An entry close-button of type message is already defined in this bundle
[l10nregistry] Attempting to synchronously load file
            resource:///chrome/en-GB/locale/en-GB/calendar/messenger/openpgp/msgReadStatus.ftl while it's being loaded asynchronously. L10nRegistry.jsm:563:19

```

Also, there are six instances of this same error in L10nRegistry.jsm. It might be unrelated but there are six calendars I'm trying to sync. Not sure if this is a coincidence.
```
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
    loadSync resource://gre/modules/L10nRegistry.jsm:658
    fetchFile resource://gre/modules/L10nRegistry.jsm:573
    generateResourceSetSync resource://gre/modules/L10nRegistry.jsm:478
    map self-hosted:240
    generateResourceSetSync resource://gre/modules/L10nRegistry.jsm:473
    generateResourceSetsForLocaleSync resource://gre/modules/L10nRegistry.jsm:415
    next self-hosted:1099
    generateBundlesSync resource://gre/modules/L10nRegistry.jsm:177
    next self-hosted:1099
    touchNext resource://gre/modules/Localization.jsm:167
    regenerateBundles resource://gre/modules/Localization.jsm:552
    activate resource://gre/modules/Localization.jsm:243
    getRegionDisplayNames resource://gre/modules/mozIntl.jsm:837
    getLocaleDisplayNames resource://gre/modules/mozIntl.jsm:897
    map self-hosted:240
    getLocaleDisplayNames resource://gre/modules/mozIntl.jsm:867
    formatLocaleSetLabels chrome://messenger/content/preferences/general.js:942
    init chrome://messenger/content/preferences/general.js:243
    init chrome://messenger/content/preferences/preferences.js:76
    AsyncFunctionNext self-hosted:693
```

An error in ActorManagerChild.jsm:
```
TypeError: singletons is null 3 ActorManagerChild.jsm:297:32
    init resource://gre/modules/ActorManagerChild.jsm:297
    <anonymous> resource://gre/modules/ActorManagerChild.jsm:349
    <anonymous> chrome://global/content/browser-content.js:12
    get browsingContext chrome://global/content/elements/browser-custom-element.js:627
    setFindbarInActor chrome://global/content/elements/findbar.js:316
    set browser chrome://global/content/elements/findbar.js:326
    connectedCallback chrome://global/content/elements/findbar.js:163
```

And an error in conversation-browser.js:
```
NotSupportedError: CustomElementRegistry.define: 'conversation-browser' has already been defined as a custom element conversation-browser.js:853
    <anonymous> chrome://chat/content/conversation-browser.js:853
    <anonymous> chrome://messenger/content/customElements.js:34
    <anonymous> chrome://messenger/content/customElements.js:37
    observe resource://gre/modules/MailGlue.jsm:201
    initHTMLDocument resource:///modules/imThemes.jsm:741
    onStateChange chrome://chat/content/conversation-browser.js:62
```

Forcing a calendar to reappear by hiding and showing it via right-click menu (as suggested above) does not produce any extra log.

Tested on Thunderbird 78.7.0 (32-bit), 78.7.1 (32-bit) and 78.7.1 (64-bit) on Windows 10 Education N 20H2. All results are the same.

Strangely, after updating Thunderbird from one version to another the calendars were synced exactly once after starting the updated version. After restarting Thunderbird a second time they were again gone. Unfortunately I didn't look at the logs after the updates.

**Comment by karaluh** [comment]
The last TB version without the issue is 78.2.2

**Comment by elhennig** [comment]
For me I always need to unsubscribe a calendar and resubscribe to it to make the entries show correctly. I guess this affects appointment series with single modifications. I run TB 78.7.1 under Linux.

**Comment by lucamosca1** [comment]
Same on windows, available for retrieve info but someone should give me instructions. Not familiar with logs adndebug console.

**Comment by cyberneid** [comment]
Same here on windows 10 with TB 78.7.1

**Comment by Dolphyn5** [comment]
Additional information and workarounds are here: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1677336

CalDAV can be used to add a Google Calendar directly to Thunderbird, no need for add-on. 
https://support.mozilla.org/en-US/questions/1261974

**Comment by elhennig** [comment]
> CalDAV can be used to add a Google Calendar directly to Thunderbird, no need for add-on.
> https://support.mozilla.org/en-US/questions/1261974

How can I add other calendars from Google belonging to my account? Or does this only work with the main calendar?
The private ICS link is showing the very same behavior as the gdata provider and displays the entries of the series unchanged instead of the singular edits.

**Comment by Dolphyn5** [comment]
Yes, I think it works with all Google calendars (but probably not task list). The calender ID is shown in Google's settings for each calendar, under "Integrate Calendar," and the ID probably ends with @group.calendar.google.com or @gmail.com.
With CalDAV, I haven't been able to replicate any "singular edits" problem. (But maybe I misunderstand what you're saying.)
Using private ICS link, I cannot use Thunderbird to add or edit events.

**Comment by elhennig** [comment]
OK, I try to explain a bit better, what I meant with singular edits:
If you have a time series and you shift single events to another time/date, usually that works (and definitely worked with older TB version) and the updated single events taken from the series are displayed correctly.
Now I see the old unchanged single events in the calendar and they are only displayed with the updated time/date if I unsubscribe the calendar and re.subscribe to it with the gdata addon. I haven't found any workaround for the CalDav setup.

**Comment by Dolphyn5** [comment]
That's what I thought you meant, but I have not been able to replicate this problem.
Check the "Refresh Calendar" setting in Thunderbird calendar properties, or try "Synchronize Calendars." (In Windows, right-click the calendar name to find these items.)

**Comment by elhennig** [comment]
Unfortunately sync does not help, seems like the cached version has higher priority....

**Comment by Dolphyn5** [comment]
I think CalDAV-related bugs should be reported here: 
https://bugzilla.mozilla.org/buglist.cgi?product=Calendar&component=Provider%3A%20CalDAV&resolution=---&list_id=15611737

**Comment by elhennig** [comment]
> Unfortunately sync does not help, seems like the cached version has higher priority....

I just noticed that if I unsubscribe and re-subscribe a calendar, edited time series are cirrectly displayed but as soon as I perform a manual sync it shows the series and not the individually changed entry (deleted single entries are not shown, though).

**Comment by elhennig** [comment]
I just tested this on a second linux machine: TB 78.8.0 fixes this problem for me

**Comment by tperk100** [comment]
Same Problem. Not working at all.

**Comment by fthx** [comment]
https://github.com/kewisch/gdata-provider/issues/140#issuecomment-793544569

**Comment by kewisch** [comment]
There is a new version out for Thunderbird 91.
