### ISSUE TITLE
Cannot close Google calendar event item after opening it in Thunderbird 68.1 ESR with Lightning/Calendar/Provider for Google Calendar (gdata.provider) 68.1

### ISSUE THREAD

**Issue by richardleger** [kewisch/gdata-provider#16]
[Bugzilla Bug 1581304](https://bugzilla.mozilla.org/show_bug.cgi?id=1581304)

Steps to reproduce:

- Install Thunderbird 68.1 ESR (British version) from https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/68.1.0/win32/en-GB/Thunderbird%20Setup%2068.1.0.exe
- Create new Thunderbird user profile with no email setup
- Go to TB Menu > Add-ons > Extensions
- Add Provider for Google Calendar add-on from file downloaded from  https://archive.mozilla.org/pub/thunderbird/releases/68.1.0/en-US/gdata-provider.en-US.xpi
- Restart Thunderbird
- Add one Google Network Calendar with ~4000items
- Wait for initial loading to complete (~8mn)
- Restart Thunderbird
- Open one or more event items from the Google calendar (via double click on item to see/edit details)

Actual results:

- When clicking on the cross icon to close the event item window, nothing happens, the windows does not close.

The following errors appear in DevTools > Console:

```
defaultReminders is undefined gdata-lightning-item-iframe.js:144
    <anonymous> chrome://gdata-provider/content/gdata-lightning-item-iframe.js:144
    x resource://gdata-provider/modules/gdataUtils.jsm:1346
    saveDialog chrome://lightning/content/lightning-item-iframe.js:1610
    saveItem chrome://lightning/content/lightning-item-iframe.js:3049
    isItemChanged chrome://lightning/content/lightning-item-iframe.js:3996
    onCommandCancel chrome://lightning/content/lightning-item-iframe.js:477
    onCancel chrome://lightning/content/lightning-item-iframe.js:539
    receiveMessage chrome://lightning/content/lightning-item-iframe.js:213
TypeError: defaultReminders is undefined
gdata-lightning-item-iframe.js:144:13
    <anonymous> chrome://gdata-provider/content/gdata-lightning-item-iframe.js:144
    x resource://gdata-provider/modules/gdataUtils.jsm:1346
    saveDialog chrome://lightning/content/lightning-item-iframe.js:1610
    saveItem chrome://lightning/content/lightning-item-iframe.js:3049
    isItemChanged chrome://lightning/content/lightning-item-iframe.js:3996
    onCommandCancel chrome://lightning/content/lightning-item-iframe.js:477
    onCancel chrome://lightning/content/lightning-item-iframe.js:539
    receiveMessage chrome://lightning/content/lightning-item-iframe.js:213
```

Expected results:

- When attempting to close the event items window, it should close immediately... which is the usual behaviour...

**Comment by richardleger** [comment]
Hard to tell if issue is Gdata-Provider related or Lightning/Calendar related... but it seems to not occur with CalDAv network calendar so may be related to Gdata-Provider or its interaction with Lightning or vice-versa...

**Comment by kewisch** [comment]
So it seems it can't find the defaultReminders on the calendar, not sure how this is happening. Can you set a breakpoint at gdata-lightning-item-iframe.js line 144 and see what `unwrappedCal` looks like? It should be an instance of the calGoogleCalendar, but it seems to be something else.

**Comment by richardleger** [comment]
Via TB 68.1.1 (with gdata 68.0) > DevTools > Debugger, I cannot find the file gdata-lightning-item-iframe.js so I am not in measure to set the breakpoint as indicated... 

Could the file missing be the root cause of the issue?

Looking for "unwrappedCal" in files returns no results either...

![image](https://user-images.githubusercontent.com/6603379/65973968-1283c980-e464-11e9-935c-89e3dc7f7bfe.png)

![image](https://user-images.githubusercontent.com/6603379/65974068-39da9680-e464-11e9-984e-5a5ecc126be4.png)

![image](https://user-images.githubusercontent.com/6603379/65974776-71960e00-e465-11e9-98a4-a263526869e5.png)

**Comment by richardleger** [comment]
Any update?

**Comment by kewisch** [comment]
Ah, you'll need to use the frame picker to navigte to the right window first. The icon next to the three dots.

**Comment by TDErdmann** [comment]
I have the same problem as richardleger.
TB 68.2.2 (64bit), Provider for Goggle calendar 68.2.1

I don't untgerstand the above instructions.

**Comment by richardleger** [comment]
> Ah, you'll need to use the frame picker to navigte to the right window first. The icon next to the three dots.

Kewish,

I tried to follow your suggestion, and with each of the window available (as per below picture), none of them allow me access to the gdata-lightning-item-iframe.js file. It simply seems to be missing from Debugger somehow...

![image](https://user-images.githubusercontent.com/6603379/69321794-a17aba00-0c3b-11ea-94f3-da3c48a479b3.png)

Though according to source code repository https://dxr.mozilla.org/comm-central/search?q=unwrappedCal&redirect=false unwrappedCal object would be defined in that file.

I am just not able to access it via DevTools to set a breakpoint as you suggested.

Does the reminder windows needs to be opened for this peace of code to become accessible?
I do have an event opened... but still no luck...

More advice and instructions needed.

Regards,

**Comment by kewisch** [comment]
This is the window picker, those urls are the window urls. Select lightning-item-iframe.xul, then you should see the js file in the file search of the debugger

**Comment by Genji-tech** [comment]
I was able to solve this problem by setting defaults for reminders in the Calendar prefs. My Error Console showed the same "defaultReminders is undefined" message, so I decided to define those defaults and that worked.

So I think that actually persisting the default values used for notifications as part of the install or initialization process should fix this bug, and anyone encountering it in the meantime can do what I did.

**Comment by hfball** [comment]
> I was able to solve this problem by setting defaults for reminders in the Calendar prefs. My Error Console showed the same "defaultReminders is undefined" message, so I decided to define those defaults and that worked.
> 
> So I think that actually persisting the default values used for notifications as part of the install or initialization process should fix this bug, and anyone encountering it in the meantime can do what I did.

Tried it on Windows 10 and it didn't work. Set calendar default to 30 minutes and task default to 15 minutes.

However, having Thunderbird open the tasks and events in a tab instead of a dialog box did work. It allowed me to open directly to the Google task list without the save/close dialog function failing.

**Comment by hfball** [comment]
Also of note, when the task creation is directly launched from a Google account on my system, the dialog box is the default Lightning format and not the Provider task format that only has Google options.

**Comment by kewisch** [comment]
This should be fixed in Thunderbird 91

**Comment by Sebi2020** [comment]
@kewisch It's not. Still happens (Thunderbird 91.4)

**Comment by hydrobyte** [comment]
Problem persists with version 91.5.
