### ISSUE TITLE
Cannot add calendar on fresh install

### ISSUE THREAD

**Issue by Heidistein** [kewisch/gdata-provider#160]
Hi,
I just installed the plugin, and I try adding a calendar.  I select 'google calendar', click next, fill in my (non google) email address, click next. In a window asking me which calendar I only see a spinner. I forgot the window was opened, it was there for hours.
thunderbird-78.7.0-2.fc33.x86_64

**Comment by kele888** [comment]
same here
78.7.1

**Comment by tobixx** [comment]
When the spinner starts I can see:
```
TypeError: right-hand side of 'in' should be an object, got undefined iteratorUtils.jsm:75:1
    fixIterator resource:///modules/iteratorUtils.jsm:75
    setupOAuth resource://gdata-provider/legacy/modules/gdataSession.jsm:226
    calGoogleSession resource://gdata-provider/legacy/modules/gdataSession.jsm:113
    getSessionById resource://gdata-provider/legacy/modules/gdataSession.jsm:91
    gdataCalendarsShow resource://gdata-provider/legacy/modules/ui/gdata-calendar-creation.jsm:250
    trycatch resource://gdata-provider/legacy/modules/ui/gdata-calendar-creation.jsm:112
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-calendar-creation.jsm:373
    _fireEvent chrome://global/content/elements/wizard.js:484
    set currentPage chrome://global/content/elements/wizard.js:197
    advance chrome://global/content/elements/wizard.js:326
    listeners chrome://global/content/elements/wizard.js:536
    openCalendarWizard resource:///modules/calendar/utils/calWindowUtils.jsm:25
    doCommand chrome://calendar/content/calendar-command-controller.js:379
    goDoCommand chrome://global/content/globalOverlay.js:101
    oncommand chrome://messenger/content/messenger.xhtml:1
```

**Comment by rudi1969** [comment]
Exact same behaviour here. I also deleted the addon, restarted TB and reeinstalled TB.
(TB 78.7.1 (64-Bit) on Ubuntu 20.04, , provider 78.0.1)

with fake Email hi@gmai.com

I get Lightning: [calGoogleSessionManager] Creating session hi@gmail.com

then  the exact same error-message as tobixx

When I click on "Weiter" (don't know what the button says in Englisch, something like "go on" or "ok") I get "calender created" (which it isn't of course) and the following in the error console.

InvisibleToDebugger: Error
ThreadSafeDevToolsUtils.js:82:13
    reportException resource://devtools/shared/ThreadSafeDevToolsUtils.js:82
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:109
    _fireEvent chrome://global/content/elements/wizard.js:484
    set currentPage chrome://global/content/elements/wizard.js:197
    advance chrome://global/content/elements/wizard.js:326
    listeners chrome://global/content/elements/wizard.js:536
    openCalendarWizard resource:///modules/calendar/utils/calWindowUtils.jsm:25
    doCommand chrome://calendar/content/calendar-command-controller.js:379
    goDoCommand chrome://global/content/globalOverlay.js:101
    oncommand chrome://messenger/content/messenger.xhtml:1

Regards

**Comment by zazy** [comment]
Same problem here with same error message as @tobixx . Reinstalled thunderbird, reinstalled extension but problem persists. Ubuntu 20.04 LTS, Thunderbird 78.7.1.
Extension is now absolutely unuseful. Any idea on how to solve this? Is this extension still in development?

**Comment by zazy** [comment]
I found a workaround solution for this issue. Follow this steps:
1. Disable Google Data Provider Add-on and if asked remove subscription to each calendar
2. Go to Thunderbird settings > Preferences > Privacy and security > Accept cookies from sites and enable it
3. Close Thunderbird and restart it
4. Install Google Data Provider again
5. Add your calendars
In my case (Ubuntu 20.04, Thunderbird 78.7.1) if I disable cookies calendars disappears again. I left cookies enabled. This is not an issue for me because I don't use TB to open webpages.

Settings entries names may differ becuase I translated it from italian.

Hope this helps.

**Comment by junkchandu** [comment]
I am still using TB 52.9.1 (for legacy reasons), with Lightning 5.4.9.1 and Provider 4.4.2
My Lightning was syncing with my Google calendar till April. Now, after a shift of computers, even though I am using exactly the same profile, it is not syncing. So I unsubscribed all calendars, exited TB, restarted, and added a new calendar pointing to my Google calendar: it went one step further than the folks reporting above: it offered me the choice of all the calendars that are visible in my google account. I choose the ones I want, and click Next, but then nothing happens: it just sits there. Any suggestions?

**Comment by kewisch** [comment]
This should be resolved in Thunderbird 91, and with cookies enabled, please re-open if not the case.
