### ISSUE TITLE
Provider for Google Calendar: no password saving

### ISSUE THREAD

**Issue by checkthis1** [kewisch/gdata-provider#161]
I've just uninstalled Thunderbird, manually removed profile folders and other remnants of data, restarted the PC, downloaded the latest version of Thunderbird (78.7.1), installed Provider for Google Calendar and, as always, wanted to integrate my Google Calendar. When logging in to grant access rights for PfG, the Google login screen appears for each calendar that I want to integrate. Because I have five calendars, I had to log in five times. The same procedure every time I restart Thunderbird. I've never had this mistake before.

**Comment by twaapo** [comment]
This has been annoying me for some while now. What I did was remove all access permissions to my google account related to calendar, and then login with Thunderbird. I was presented with OAuth to allow access to calendar, which I allowed. This time it seemed to remember the setting.

Perhaps old permissions started conflicting with something?

**Comment by hartmark** [comment]
+1 same error here
I need to reauthenticate for all calendars separately and need to do that again on restart.

Quite annoying as I have 13 calendars

**Comment by andbuitra** [comment]
I'm having a similar issue (TB 78.7.1) where it doesn't remember my login and asks for credentials everytime I interact with my single calendar. I have 2FA enabled.

**Comment by advisorgee** [comment]
Brand new installation of ThunderBird and Google Provider. Every time I restart I am asked to re-authorize 3 times; once for calendars, once fort tasks and once for contacts. I also use 2FA

**Comment by treasury-raminter** [comment]
I solved this problem by unistaling Google Calendar. When re-installing system offered to install calendar with current user or offered to inform an email. This time I tried with second option, so I informed email... and this time worked fine. No more asking passwords after closing Thunderbird !!!!!

**Comment by Goatflange** [comment]
I'm having this problem too, not only on starting TB but occasionally again throughout the day.  @treasury-raminter - what do you mean 'uninstalling' google calendar? It seems to just be part of 'the system'. I'm on W10 using Firefox to view it.

**Comment by treasury-raminter** [comment]
I uninstalled extension **Provider for Google Calendar**., and then install again. This solved my problem.

**Comment by treasury-raminter** [comment]
Part of the system is only the **Calendar**

The link between **Calendar** and the calendar I had with Google is the Add On **Provider for Google Calendar**

**Comment by Brutus-Tinyfoot** [comment]
Thanks for clarifying that - I'll give it a go.

**Comment by kewisch** [comment]
One part of this is that Thunderbird will show its own OAuth dialog (mail, contacts, calendar). If you have any other such addon installed it will show its own as well. 

If you are seeing multiple from the Provider, can you let me know what the calendar urls are? Feel free to redact emails, as long as I can see which two are the same.
