### ISSUE TITLE
Rappel rendez-vous récurrent impossible à désactiver

### ISSUE THREAD

**Issue by darksite00** [kewisch/gdata-provider#162]
Bonjour,

On m'a inclus dans une réunion tous les 1er lundi du mois (évènement récurrent).
Bien que la date soit passé, j'ai toujours le rappel qui revient.
![image](https://user-images.githubusercontent.com/78374822/107748333-25c1cd00-6d19-11eb-8f8f-3a774a390452.png)

Un appel est fait au site googleapi, mais ne récupère un erreur 404
![image](https://user-images.githubusercontent.com/78374822/107748450-5dc91000-6d19-11eb-8151-6ff691688fa0.png)

Mais, chaque fois que je désactive ce rappel, j'ai ce popup qui apparaît dans Thunderbird
![image](https://user-images.githubusercontent.com/78374822/107748320-2195af80-6d19-11eb-8708-d6774400d807.png)

Sur celle-ci, si je clic sur "Annuler mes modifications", le popup de rappel s'affiche à nouveau, avec cette appel API.
![image](https://user-images.githubusercontent.com/78374822/107748584-9832ad00-6d19-11eb-9c5f-8002f6807de8.png)

Mais, si j'appuie sur le bouton "appliquer mes modifications", cet appel API est fait
![image](https://user-images.githubusercontent.com/78374822/107748752-d62fd100-6d19-11eb-8e42-9553174395a6.png)

Puis, environ 30mn plus tard, le popup de rappel revient pour toujours cette réunion

Thunderbird > 78.7.0
Addons _Provider For Google Agenda_ > 78.0.1

**Comment by kewisch** [comment]
Unfortunately the workaround now is to disable showing missed reminders. I've fixed this on the main branch though, so closing this issue.
