### ISSUE TITLE
Provider for Google Calendar Addon often does not work for me

### ISSUE THREAD

**Issue by paul-jr** [kewisch/gdata-provider#166]
I have Provider for Google Calendar installed in version 78.8.0 of Mozilla Thunderbird my windows 10 HP laptop, and sometimes when I start tbird, my calendar entries for today, tomorrow and the next 5 days are displayed in the far right hand pane.

But, sometimes not.  No calendar entries at all are displayed.  And, this is more often the case than when the entries are displayed.

On my Google Calendar, there are entries for every single day.  One for the morning, and another for the evening reminders for me to take my medication.  Neither of these are shown when the problem is happening when I brought up tbird.

I am relatively new to tbird, so, if someone could please send me trouble shooting steps for this problem, I'd very much appreciate it.

No errors are shown me when the problem happens.

But, here is the error console fwiw:

10:47:14.614
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
10:47:14.654 Successfully loaded OpenPGP library rnp.dll from C:\Program Files (x86)\Mozilla Thunderbird\rnp.dll RNPLib.jsm:49:13
10:47:14.662
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
10:47:14.666 [l10nregistry] Attempting to synchronously load file
            resource:///chrome/en-US/locale/en-US/calendar/messenger/openpgp/msgReadStatus.ftl while it's being loaded asynchronously. L10nRegistry.jsm:563:19
10:47:14.666
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
10:47:14.692
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
10:47:14.757
TypeError: singletons is null
3 ActorManagerChild.jsm:297:32
10:47:14.956
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
10:47:14.957
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
10:47:15.590
Error while loading 'jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Thunderbird/omni.ja!/chrome/messenger/search-extensions/twitter/manifest.json' (NS_ERROR_FILE_NOT_FOUND) Extension.jsm:570
10:47:15.591 1614278835590	addons.xpi	WARN	Exception running bootstrap method startup on twitter@search.mozilla.org: Error: Error while loading 'jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Thunderbird/omni.ja!/chrome/messenger/search-extensions/twitter/manifest.json' (NS_ERROR_FILE_NOT_FOUND)(resource://gre/modules/Extension.jsm:570:20) JS Stack trace: readJSON/</<@Extension.jsm:570:20
onStopRequest@NetUtil.jsm:128:18
10:47:15.725 Successfully loaded OTR library libotr-5.dll from C:\Program Files (x86)\Mozilla Thunderbird\libotr-5.dll OTRLib.jsm:43:13
10:47:15.779 public keys: 0, secret keys: 0

**Comment by paul-jr** [comment]
If anyone has read this, can you please help me by advising what steps I can use to trouble shoot this problem?

**Comment by kewisch** [comment]
This should be resolved with Thunderbird 91, would appreciate if you could give it another try.
