### ISSUE TITLE
Provider for Google Calendar: cannot deactivate an event when it's over

### ISSUE THREAD

**Issue by fdepub** [kewisch/gdata-provider#167]
### Describe the problem and steps to reproduce it:

When an event is created by other people (like a meeting), I cannot deactivate it when it's over.
I have to go on the gmail calendar to make it disappear.

### What happened?

The pop-up alarm event stay on screen. 

### What did you expect to happen?

I'd like it disappears when I click on "deactivate"

**Comment by DravenJohnson** [comment]
I also noticed the similar:
A recursive event that's been removed (remove all following events from today) will continue show even on Google Calendar it's already hidden.

What happened:
- I had a recursive event 2 years ago, weekly on wee day.
- I modified and removed "following event" about few months ago since some changes.
- I can't see those event now on Google Calendar.
- But I can still see it on Thunderbird with this add-on

**Comment by alvarookticket** [comment]
Same thing here. TB 78.8.1 + GCP 78.0.1. Tried reinstalling, with no luck. Calendar appears with a warning sign in calendars list: 
![imagen](https://user-images.githubusercontent.com/42064095/110600058-ccb45000-8183-11eb-940f-6987d87d32d1.png)

**Comment by lake-effect** [comment]
I have logs from what I believe to be this issue:

```
09:19:03.475 Lightning: [calGoogleCalendar] Modifying item <REDACTED> (master item) gdataCalendar.jsm:467
09:19:03.481 Lightning: [calGoogleRequest] Requesting PATCH https://www.googleapis.com/calendar/v3/calendars/<REDACTED>/events/<REDACTED> gdataRequest.jsm:206
09:19:03.482 Lightning: [calGoogleCalendar] Setting Upload Data (application/json; charset=UTF-8):
{"start":{"dateTime":"2021-03-09T10:00:00","timeZone":"America/Los_Angeles"},"end":{"dateTime":"2021-03-09T10:30:00","timeZone":"America/Los_Angeles"},"summary":"<REDACTED>","location":"<REDACTED>","status":"confirmed","reminders":{"overrides":[],"useDefault":true},"extendedProperties":{"private":{"X-MOZ-LASTACK":"2021-03-16T16:19:03Z","X-GOOGLE-SNOOZE-RECUR":"{\"1615226400000000\":\"20210308T180004Z\"}"}},"recurrence":["RRULE:FREQ=WEEKLY;UNTIL=20210316T065959Z;BYDAY=MO,TU,WE,TH,FR;WKST=SU","EXDATE:20210310T180000Z"]} gdataRequest.jsm:273
09:19:03.482 Lightning: [calGoogleCalendar] Sending request headers: ({}) gdataRequest.jsm:302
09:19:03.849 Lightning: [calGoogleRequest] Clock skew is -2 seconds gdataRequest.jsm:376
09:19:03.849 Lightning: [calGoogleCalendar] Request PATCH https://www.googleapis.com/calendar/v3/calendars/<REDACTED>/events/<REDACTED> responded with HTTP 403 gdataRequest.jsm:383
09:19:03.849 Lightning: [calGoogleCalendar] Login failed for <REDACTED> HTTP Status: 403 Reason: forbidden gdataRequest.jsm:416
09:19:03.851 Lightning: [calGoogleCalendar] Modifying item <REDACTED> failed:2147500037: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "forbidden",
    "message": "Forbidden"
   }
  ],
  "code": 403,
  "message": "Forbidden"
 }
}
gdataCalendar.jsm:567
```

It only happens for one recurring meeting another user set up in the same business domain, and I see the same symptoms as other users in this thread. Every day the meeting recurs another reminder stacks up in the reminders window.

So no other event returns HTTP 403, or has this strange login problem, whether I own it or not.

**Comment by aengelas** [comment]
I'm also experiencing what appears to be the same issue. I wind up accumulating a lot of un-dismissable notifications.

**Comment by kewisch** [comment]
Unfortunately the workaround now is to disable showing missed reminders. I've fixed this on the `main` branch though, so closing this issue.
