### ISSUE TITLE
Dismissed event is deleted and can't get it back 

### ISSUE THREAD

**Issue by DravenJohnson** [kewisch/gdata-provider#168]
### Describe the problem and steps to reproduce it:

N/A

### What happened?
First of all, I just want to confirm this IP from Amazon: 100.25.134.155 is used by this add-on. Based on the log on Google, seems like this IP modified the event.

Installed this add-on last week and I bulk dismissed some notifications from Calendar. 

Yesterday, I noticed that one of my recursive event (invite from another people) disappeared. 

sysadmin helped me indicated that the IP mentioned above did tons of modifications and deletions on my account.

I asked the people who invite me to re-invite me, but the event will be automatically rejected and removed from my calendar.

### What did you expect to happen?

A place to revive the deleted / dismissed event so I can restore them.

**Comment by kewisch** [comment]
I don't think this is related to the add-on. The add-on doesn't interact with any servers except Google itself. So to answer your question, the IP you linked is unrelated to this add-on in any way
