### ISSUE TITLE
Google Calendar 'New Event' window no longer opens with cursor in the Title field

### ISSUE THREAD

**Issue by theishjorth** [kewisch/gdata-provider#169]
### Describe the problem and steps to reproduce it:

Highlight a google calendar in the left sidebar with lists of calendars. Double-click on any day, or select 'new event' in any other way to get the 'new event' dialog box. The problem is that the cursor is not at the "title" field as it used to be, so you cannot start typing the name of the event. 

But when opening a local calendar (non-google calendar), the cursor is in the title field as expected.
If disabling the google provider add-on, and highlighting one of the now disabled google calendars and creating a new event, the cursor is correctly in the title field also (because the dialog box defaults to the local 'Home' calendar and can't use the google calendars).
The issue seems to be exclusively when creating a new event in a google calendar managed by this add-on.

### What happened?
Cursor is not anywhere, you have to click the dialog box to get it back.

### What did you expect to happen?
The cursor should be in the Title field, as it used to be :)

### Anything else we should know?

This seems to have broken about 2 updates ago in a 78.7.x (not sure about the exact version). The newest update 78.8.0 still has this problem (not sure if this is related to the add-on's update?)
I did a reinstall of the newest Thunderbird from scratch, installed the google provider and added a calendar, and the issue is there.

Not sure if this is relevant, but when opening a 'new event' dialog, I get this output in the error console:

aElement is null 2 calendar-ui-utils.js:180
    removeChildren chrome://calendar/content/calendar-ui-utils.js:180
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:147
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    commonUpdateReminder chrome://calendar/content/calendar-dialog-utils.js:514
    updateReminder chrome://lightning/content/lightning-item-iframe.js:1604
    updateCalendar chrome://lightning/content/lightning-item-iframe.js:2763
    updateCalendar self-hosted:844
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:36
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    loadDialog chrome://lightning/content/lightning-item-iframe.js:824
    onLoad chrome://lightning/content/lightning-item-iframe.js:445
    onload chrome://lightning/content/lightning-item-iframe.xhtml:1
Uncaught TypeError: aElement is null
    removeChildren chrome://calendar/content/calendar-ui-utils.js:180
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:147
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    commonUpdateReminder chrome://calendar/content/calendar-dialog-utils.js:514
    updateReminder chrome://lightning/content/lightning-item-iframe.js:1604
    updateCalendar chrome://lightning/content/lightning-item-iframe.js:2763
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:36
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    loadDialog chrome://lightning/content/lightning-item-iframe.js:824
    onLoad chrome://lightning/content/lightning-item-iframe.js:445
    onload chrome://lightning/content/lightning-item-iframe.xhtml:1
calendar-ui-utils.js:180:10
    removeChildren chrome://calendar/content/calendar-ui-utils.js:180
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:147
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    commonUpdateReminder chrome://calendar/content/calendar-dialog-utils.js:514
    updateReminder chrome://lightning/content/lightning-item-iframe.js:1604
    updateCalendar chrome://lightning/content/lightning-item-iframe.js:2763
    updateCalendar self-hosted:844
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:36
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    loadDialog chrome://lightning/content/lightning-item-iframe.js:824
    onLoad chrome://lightning/content/lightning-item-iframe.js:445
    onload chrome://lightning/content/lightning-item-iframe.xhtml:1

**Comment by kewisch** [comment]
This looks like the same message as in #150, I'm marking this duplicate for now.
