### ISSUE TITLE
Email Invitations are not sent since Thunderbird 78.7.1

### ISSUE THREAD

**Issue by DaGeRe** [kewisch/gdata-provider#170]
### Describe the problem and steps to reproduce it:

Until last week, everything was working fine. In the beginning of this week, `apt` regularly installed Thunderbird 78.7.1 on my Ubuntu 20.04 installation, then first the google calendar plugin was not working. After its update yesterday, it is displaying my events again and I can create new events, but sending invitations for a google calendar event does not work anymore.

### What happened?

If I create a new event and add email adresses for invitations, the invitations are not sent. If I open the saved event, the mail adresses are removed from the participants list.

### What did you expect to happen?

I would expect the invitations to be sent and the email adresses to be saved in the participants list. 

For a event in my local calendar, it works.

### Anything else we should know?

During the creation of the event, logs like this appear:

> Lightning: [calGoogleCalendar] A request Error Occurred. Status Code: 400 Bad Request Body: {
>  "error": {
>   "errors": [
>    {
>     "domain": "global",
>     "reason": "badRequest",
>     "message": "Bad Request"
>    }
>   ],
>   "code": 400,
>   "message": "Bad Request"
>  }
> }
> gdataRequest.jsm:534
> Lightning: [calGoogleCalendar] Failed freebusy request: [Exception... "A request Error Occurred. Status Code: 400 Bad Request Body: {
>  "error": {
>   "errors": [
>    {
>     "domain": "global",
>     "reason": "badRequest",
>     "message": "Bad Request"
>    }
>   ],
>   "code": 400,
>   "message": "Bad Request"
>  }
> }
> "  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://gdata-provider/legacy/modules/gdataRequest.jsm :: fail :: line 232"  data: no]
> 
> Lightning: [calGoogleCalendar] Setting Upload Data (application/json; charset=UTF-8):
> {"timeMin":"2021-03-10","timeMax":"2021-03-15","items":[{"id":"my@guest.de"}]} gdataRequest.jsm:273
> Lightning: [calGoogleCalendar] Request POST https://www.googleapis.com/calendar/v3/freeBusy responded with HTTP 400 gdataRequest.jsm:383
> Lightning: [calGoogleCalendar] A request Error Occurred. Status Code: 400 Bad Request Body: {
>  "error": {
>   "errors": [
>    {
>     "domain": "global",
>     "reason": "badRequest",
>     "message": "Bad Request"
>    }
>   ],
>   "code": 400,
>   "message": "Bad Request"
>  }
> }
> gdataRequest.jsm:534
> Lightning: [calGoogleCalendar] Failed freebusy request: [Exception... "A request Error Occurred. Status Code: 400 Bad Request Body: {
>  "error": {
>   "errors": [
>    {
>     "domain": "global",
>     "reason": "badRequest",
>     "message": "Bad Request"
>    }
>   ],
>   "code": 400,
>   "message": "Bad Request"
>  }
> }
> "  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://gdata-provider/legacy/modules/gdataRequest.jsm :: fail :: line 232"  data: no]

**Comment by boldcompany** [comment]
Seeing the same issue. Nothing additional to report; just wanted to show support for this request.

**Comment by WernerAUT** [comment]
Same issue here and its a big issue for my company :( we can't invite others to events

**Comment by humbertleonardo** [comment]
Did the Developer abandon the project?

**Comment by oururbanfarm** [comment]
Having the same issue

**Comment by kewisch** [comment]
There are a few other issues open on this topic. I have this on my radar for Provider 91.0.2
