### ISSUE TITLE
drag and drop an event needs two attempts

### ISSUE THREAD

**Issue by upatamby** [kewisch/gdata-provider#171]
### Describe the problem and steps to reproduce it:
When I try to drag and drop an existing event from one date to another the event does not move at all. If I try again it does move as expected. This happens with any event but it happens only once after opening Thunderbird.

I would like to provide the debug info as explained below, but those instructions below are a mystery to me.

**Comment by kewisch** [comment]
Would appreciate feedback on how I can improve the instructions. Can you let me know which step was probelmatic and why?

Is this still an issue with Thunderbird 91?

**Comment by upatamby** [comment]
I don't see these instructions to provide debug-info anymore, and after such a long time I cannot remember them. I'm not a developer, just a user. 
The issue still exists in my most recent version of Thunderbird which is version 78.14.0

**Comment by kewisch** [comment]
Here is the text. I do want this to be understandable by non-developers!

>   Please provide any errors or relevant messages from the error console (Tools Menu → Error Console), with debugging enabled:
    * Open your application preferences (Tools or Edit Menu)
    * Select the `Advanced` icon at the top.
    * Click on the `General` tab, below the icons.
    * Select `Advanced Configuration` or `Config Editor`, whichever is available
    * Right Click on an empty space in the list of preferences
    * Select `New` → `Boolean`
    * Enter `calendar.debug.log` as the preference name
    * Pick `true` as the Boolean value.
    * Repeat the same for `calendar.debug.log.verbose`
