### ISSUE TITLE
all calendars connected through Google Provider are showing after restart

### ISSUE THREAD

**Issue by zxcygnus** [kewisch/gdata-provider#172]
### Describe the problem and steps to reproduce it:

I expected, Thunderbird will remember which calendar should be shown and which not.

### What happened?

All calendars are showing after restart if they are connected through Google provider.

### What did you expect to happen?

What was hidden, should stay hidden.

### Anything else we should know?

I had this issue on two very different computers (one W10 Pro 64b Czech, second Gentoo Linux 64b cs_CZ), but it worked fine on third computer with W10 and Thunderbird portable, but same version of Thunderbird 78.8.1. Thunderbird Portable was in EN US localisation. Maybe it can have some connection to this issue?

I tried search in prefs.js through Config Editor, but i did not found item for showing calendar, i could only disable calendar. So i don't know where this setting should be stored and what else i could check.

In all installation was more calendars, some through Google provider and one or more through LDAP (Google or NextCloud).

**Comment by kewisch** [comment]
I believe this was resolved in Thunderbird 91, please reopen if not.
