### ISSUE TITLE
Calendar sync does work one way only

### ISSUE THREAD

**Issue by noffie99** [kewisch/gdata-provider#173]
I use TB 78.8. and updated to 78.9.0 just a few minutes ago. 78.0.1 is the 'Provider for Google Calendar' version.
I want to sync my calendar entries with my Samsung mobile phone (Galaxy A51 SM-A515F/DSN running under Android 11, Kernel 4.14113-20899478. When adding/modifying/deleting a caledar entry on the phone, it syncs with my TB calendar on my Windows-PC. The other way round, no updates are made. No idea, how to work around this.

Error log (no clue what this info means or if it is relevant, I am a retired user and no programmer.......:
Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
Successfully loaded OpenPGP library rnp.dll from C:\Program Files (x86)\Mozilla Thunderbird\rnp.dll RNPLib.jsm:49:13
public keys: 0, secret keys: 0 RNPLib.jsm:247:15
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
DOMException: CSSStyleSheet.cssRules getter: Can't access rules of still-loading stylsheet tabmail.js:914:21
Successfully loaded OTR library libotr-5.dll from C:\Program Files (x86)\Mozilla Thunderbird\libotr-5.dll OTRLib.jsm:43:13
Win error 2 during operation open on file C:\Users\rb\AppData\Roaming\Thunderbird\Profiles\45rqfsu6.default-release\TbSync\accounts68.json (Das System kann die angegebene Datei nicht finden.

) db.js:51
Win error 2 during operation open on file C:\Users\rb\AppData\Roaming\Thunderbird\Profiles\45rqfsu6.default-release\TbSync\folders68.json (Das System kann die angegebene Datei nicht finden.

) db.js:51
TypeError: aTab.browser is undefined
implementation.js:329:13
TypeError: aTab.browser is undefined
implementation.js:405:13
Win error 2 during operation open on file C:\Users\rb\AppData\Roaming\Thunderbird\Profiles\45rqfsu6.default-release\TbSync\changelog68.json (Das System kann die angegebene Datei nicht finden.

) db.js:51
Win error 2 during operation open on file C:\Users\rb\AppData\Roaming\Thunderbird\Profiles\45rqfsu6.default-release\TbSync\accounts.json (Das System kann die angegebene Datei nicht finden.

**Comment by cwoschek** [comment]
I think I have same issue with google tasks which I like to sync.
Using 
TB 78.9.1 (64-Bit)
Windows 10 Pro 20H2 Build 19042.867
After installation of Plugin loading tasks from google account works once. But updates of a task made on smartphone are not synchronized under Windows TB. ALso when trigger synchonize functions the tasks are not updated. 
In my case I closed a tasks but it stay still open in task list in TB. But when I try to close this task than in TB, a dialog appears and informed my about difference between local status of this task on server status of this task with possibility to overwrite server status. But also after this dialog appears and I do not overwrite state, the staus of the task in TB was not updated.

**Comment by yuuurchyk** [comment]
@cwoschek I'm experiencing the same behavior with ubuntu TB. Also, when I create the task with a button, the new task window never closes and stays frozen forever

**Comment by cwoschek** [comment]
Have found solution until bugs here are solved: I exchanged this add-on with "using google calendar" add-on.

**Comment by yuuurchyk** [comment]
Guess there is no such add-on for ubuntu. Tasks is the only bug that stops me from using TB for now.

**Comment by tugkanbatu** [comment]
> @cwoschek I'm experiencing the same behavior with ubuntu TB. Also, when I create the task with a button, the new task window never closes and stays frozen forever

Have you tried changing "Default Reminder" to something else, like "No Reminder"? That solves the problem ("create task" window not closing) for me.

**Comment by yuuurchyk** [comment]
@tugkanbatu that solves the issue, thanks! Another workaround is not to use ```Add Task``` button but to write the task inside the input line next to it in the **tasks** tab.

**Comment by yuuurchyk** [comment]
The issue with not sync is more crucial though.

**Comment by cwoschek** [comment]
> > @cwoschek I'm experiencing the same behavior with ubuntu TB. Also, when I create the task with a button, the new task window never closes and stays frozen forever
> 
> Have you tried changing "Default Reminder" to something else, like "No Reminder"? That solves the problem ("create task" window not closing) for me.

Yes, this works for this one problem

**Comment by cwoschek** [comment]
> > @cwoschek I'm experiencing the same behavior with ubuntu TB. Also, when I create the task with a button, the new task window never closes and stays frozen forever
> 
> Have you tried changing "Default Reminder" to something else, like "No Reminder"? That solves the problem ("create task" window not closing) for me.

I think reminder is essential and necessary, I dont try it

**Comment by cwoschek** [comment]
> @tugkanbatu works for me, thanks! Another workaround is not to use `Add Task` button but to write the task inside the input line next to it in the **tasks** tab.

Yes this works

**Comment by kewisch** [comment]
This should be resolved in Thunderbird 91 with the latest version of the Provider. Please reopen if not the case.

**Comment by cwoschek** [comment]
I have tested the solution, and it does not work as expected.
Environment:
OS: Windows 10 Pro, Windows Feature Experience Pack 120.2212.3530.0
Version: 20H2
Build: 19042.1237
System: 64-Bit-Betriebssystem, x64-basierter Prozessor
Thunderbird: 91.1.1 (64-Bit)
Provider für Google Kalender: 91.0.1
Test:
Using google calendar on Windows PC and Android Smartphone
1. on PC: in thunderbird calendar: create apointment for 22.09.21 15:00-16:00 with a header, the appoint is visible
2. on smartphone: wait a moment, the new appointment is visible
3. on smartphone: open new appointment and change time to 17:00-18:00 and change header
4. on PC: in thunderbird calendar: press sync button, the changed time and header have changed and the one appointment is now visible twice, as 2 appointments

**Comment by cwoschek** [comment]
expected behaviour: 
the one appointment changes the time and header text on pc sychronized with smartphone
