### ISSUE TITLE
Hello, despite addon, my entries in Google Calendar appear in the Thunderbird Calendar, but inversely it does not work.

### ISSUE THREAD

**Issue by Hasenhexer** [kewisch/gdata-provider#174]
Hello, sorry i am new. Can you help me?
Despite addon, my entries in Google Calendar appear in the Thunderbird Calendar, but inversely it does not work.

**Comment by jsibley2** [comment]
I also have this issue. Is there an extra step for items in the Lightning "home" calendar to synch to google calendar? Or a way to have Lightning events from emails go directly to a shared google calendar?

Thanks!

**Comment by angerangel** [comment]
Me too
