### ISSUE TITLE
error msg: Can't create calendar. 'TypeError'

### ISSUE THREAD

**Issue by fladrinar** [kewisch/gdata-provider#176]
On a thunderbird that worked on Friday 3/26, now Monday morning 3/29 it can't connect to my many google calendars.

After turning on the debug log, I see for each calendar:

``Lightning: Can't create calendar for XXX (gdata, googleapi://XXX@gmail.com/?calendar=XXX%40group.calendar.google.com): TypeError: right-hand side of 'in' should be an object, got undefined``

Provider for Google Calendar
Version 78.0.1  (most recent available)

Thunderbird 78.5.0 (64-bit) RHEL 6 (most recent available on this old linux os flavor)

Thanks much for supporting this add on all this time!

**Comment by Barnoid-** [comment]
I have the same problem for all my Google Calendars after updating from an old TB (68) to the most recent version on Gentoo (78.11.0) and version 78.0.1 of the plugin.
`Lightning: Can't create calendar for xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (gdata, googleapi://xxx@gmail.com/?calendar=yyy%40gmail.com):`
`TypeError: right-hand side of 'in' should be an object, got undefined                                 (CalCalendarManager.jsm:280)`

Upon startup, no calendars are shown and the above error occurs for all calendars in CalCalendarManager.jsm:280. Interestingly, I do see the calendars in the left-hand calendar tab _after uninstalling the addon_, however, their contents are not shown. Upon re-installing the plugin, the calendars are not shown anymore in the calendar tab.

Attempting to connect to a Google Calendar via Calendar + -> On the Network -> Google Calendar -> xxx@gmail.com -> Next results in a similar error:
`right-hand side of 'in' should be an object, got undefined                          (iteratorUtils.jsm:75)`
`TypeError: right-hand side of 'in' should be an object, got undefined          (iteratorUtils.jsm:75:1)`

I can provide more information if necessary.

**Comment by fladrinar** [comment]
In the end, my problem turned out to be that cookies were disabled inside thunderbird settings:

  Privacy & Security / Web Content / accept cookies from sites

When I allowed cookies again, problem went away.
The error message should be clearer.

**Comment by kewisch** [comment]
I've also removed use of iteratorUtils since then. Cookies is a good point as well!
