### ISSUE TITLE
Can't create new calendar

### ISSUE THREAD

**Issue by craigs100** [kewisch/gdata-provider#177]
### Describe the problem and steps to reproduce it:
In TB 78.7.1 on Linux Mint 20.1 cinnamon.
Click "Calendar +"
Select "On the Network" - Next
Select "Google Calendar" - Next
Enter email address - Next

### What happened?
White box appears with a spinner which spins forever.

### What did you expect to happen?
Not sure but something to select a calendar

### Anything else we should know?
Restarting TB doesn't make any difference.

Logs entries:-
22:08:05.075
TypeError: window is undefined
    getWindowID resource://devtools/server/actors/targets/browsing-context.js:82
    onWindowCreated resource://devtools/server/actors/targets/browsing-context.js:1672
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:103
    _fireEvent chrome://global/content/elements/wizard.js:484
    set currentPage chrome://global/content/elements/wizard.js:197
    advance chrome://global/content/elements/wizard.js:326
    _maybeStartWizard chrome://global/content/elements/wizard.js:422
    _registerPage chrome://global/content/elements/wizard.js:401
    connectedCallback chrome://global/content/elements/wizard.js:500
    openCalendarWizard resource:///modules/calendar/utils/calWindowUtils.jsm:25
    doCommand chrome://calendar/content/calendar-command-controller.js:379
    goDoCommand chrome://global/content/globalOverlay.js:101
    oncommand chrome://messenger/content/messenger.xhtml:1
ThreadSafeDevToolsUtils.js:82:13
22:08:07.935
TypeError: window is undefined
    getWindowID resource://devtools/server/actors/targets/browsing-context.js:82
    onWindowCreated resource://devtools/server/actors/targets/browsing-context.js:1672
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:103
    _fireEvent chrome://global/content/elements/wizard.js:484
    set currentPage chrome://global/content/elements/wizard.js:197
    advance chrome://global/content/elements/wizard.js:326
    listeners chrome://global/content/elements/wizard.js:536
    openCalendarWizard resource:///modules/calendar/utils/calWindowUtils.jsm:25
    doCommand chrome://calendar/content/calendar-command-controller.js:379
    goDoCommand chrome://global/content/globalOverlay.js:101
    oncommand chrome://messenger/content/messenger.xhtml:1
ThreadSafeDevToolsUtils.js:82:13
22:08:11.232
TypeError: window is undefined
    getWindowID resource://devtools/server/actors/targets/browsing-context.js:82
    onWindowCreated resource://devtools/server/actors/targets/browsing-context.js:1672
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:103
    _fireEvent chrome://global/content/elements/wizard.js:484
    set currentPage chrome://global/content/elements/wizard.js:197
    advance chrome://global/content/elements/wizard.js:326
    listeners chrome://global/content/elements/wizard.js:536
    openCalendarWizard resource:///modules/calendar/utils/calWindowUtils.jsm:25
    doCommand chrome://calendar/content/calendar-command-controller.js:379
    goDoCommand chrome://global/content/globalOverlay.js:101
    oncommand chrome://messenger/content/messenger.xhtml:1
ThreadSafeDevToolsUtils.js:82:13
22:08:21.433
TypeError: window is undefined
    getWindowID resource://devtools/server/actors/targets/browsing-context.js:82
    onWindowCreated resource://devtools/server/actors/targets/browsing-context.js:1672
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:103
    _fireEvent chrome://global/content/elements/wizard.js:484
    set currentPage chrome://global/content/elements/wizard.js:197
    advance chrome://global/content/elements/wizard.js:326
    listeners chrome://global/content/elements/wizard.js:536
    openCalendarWizard resource:///modules/calendar/utils/calWindowUtils.jsm:25
    doCommand chrome://calendar/content/calendar-command-controller.js:379
    goDoCommand chrome://global/content/globalOverlay.js:101
    oncommand chrome://messenger/content/messenger.xhtml:1
ThreadSafeDevToolsUtils.js:82:13
22:08:21.438
right-hand side of 'in' should be an object, got undefined iteratorUtils.jsm:75
22:08:21.438
TypeError: right-hand side of 'in' should be an object, got undefined
iteratorUtils.jsm:75:1

**Comment by Darkstarinternet** [comment]
I am also having this problem on MacOS with Thunderbird 78.9.0.

**Comment by Darkstarinternet** [comment]
See #160 for a workaround that worked for me.

**Comment by kewisch** [comment]
This should be resolved for Thunderbird 91.
