### ISSUE TITLE
can't deactivate check of read-only/write icals

### ISSUE THREAD

**Issue by michas79de** [kewisch/gdata-provider#178]
Hi there,

I've subscribed three Google calendars with my own calendar by adding there ics file adresses. I haven't any rights for them so they're read-only.

### What happened?
Every time starting Thunderbird I'm getting a window asking to convert read-only online ics calendars.

Since I only subscribe to the calendars (like holidays or sports matches), they are as a matter of fact read-only. So every time I uncheck the checkbox below and choose Cancel or uncheck them all and choose convert. However there's no change. I'v ealso tried to unsubscribe an subscribe them again.
One link for example: https://calendar.google.com/calendar/ic ... /basic.ics

### What did you expect to happen?
**This window should only appear once**, if the lower checkbox is unchecked (until a new calendar is recognised).

**How to deactivate this check or accept this as read-only permanently?** The query is annoying!

### Anything else we should know?
It says:
A check by the provider for Google Calendar has revealed that the calendars listed below
have read-only access to Google Calendar. If you want to provide calendars
with write access as well and therefore want to convert them, please select them below.

[ ] Always check
Convert / Cancel
![2021-04-11 17_47_32-gdata migration title;](https://user-images.githubusercontent.com/49291708/114311652-e84aa780-9aef-11eb-8881-4c80b9b234aa.png)

[console-export-2021-4-11_18-12-42.txt](https://github.com/kewisch/gdata-provider/files/6292227/console-export-2021-4-11_18-12-42.txt)

**Comment by FS93** [comment]
Same here, using TB 78.10.2 and Provider 78.0.1 under Windows & Ubuntu

**Comment by michas79de** [comment]
I don't know, why I haven't tried it earlier (Because a read-only calender shall not be read+write?!):
After selecting all these calendars, unchecking 'Always check' and choosing convert, this message box seems gone forever.
However these three calendars seemed not to be read-only any longer, but of course I won't write to them (due to the lack of rights as they're not mine). So I've marked them as read-only in their properties (context menu) again. And the message box keeps to be gone.

@FS93 Maybe this will work for you, too.

**Comment by FS93** [comment]
Didn't work for me. I think I have tried all permutations of checking / unchecking both boxes without success

**Comment by michas79de** [comment]
Sorry to read! Then maybe you want to reopen this issue. (Or do I have to, as I'm the OP?)

**Comment by FS93** [comment]
I would appreciate if you'd reopen it. Thanks!

**Comment by kewisch** [comment]
I think I know why this is happening, confirming so I can investigate for the next release.

**Comment by kewisch** [comment]
Fixed in faf2124e6e4e4f058e8d163efa7ce635df9d0f7a
