### ISSUE TITLE
Can't edit single instance of repeated event anymore

### ISSUE THREAD

**Issue by eogloblin** [kewisch/gdata-provider#179]
When trying to change date and time for 
 the single instance of the repeated event in the Google calendar got message ![2021-04-21_155743](https://user-images.githubusercontent.com/582939/115526588-63634900-a2ba-11eb-891c-a2ae5e99f620.jpg)
Clicking any button produces no result, the event remains unchanged. Previously it works correctly.

From the error console
Lightning: [calGoogleCalendar] Modifying item ****** (20210421T160000) gdataCalendar.jsm:467
Lightning: [calGoogleRequest] Requesting PUT https://www.googleapis.com/calendar/v3/calendars/*******%40…ccp66b9hcdhmap1h64r3ic1o70_R20201028T090000_20210421T090000Z gdataRequest.jsm:206
Lightning: [calGoogleCalendar] Setting Upload Data (application/json; charset=UTF-8):
{"start":{"dateTime":"2021-04-22T16:00:00","timeZone":"Asia/Krasnoyarsk"},"end":{"dateTime":"2021-04-22T18:00:00","timeZone":"Asia/Krasnoyarsk"},"summary":"******","sequence":"1","status":"confirmed","reminders":{"overrides":[{"method":"popup","minutes":30},{"method":"popup","minutes":60}],"useDefault":false},"originalStartTime":{"dateTime":"2021-04-21T16:00:00","timeZone":"Asia/Krasnoyarsk"},"recurringEventId":"6li6aopl6th3gb9p75gj6b9k70o34b9pccp66b9hcdhmap1h64r3ic1o70_R20201028T090000"}
Lightning: [calGoogleCalendar] Request PUT https://www.googleapis.com/calendar/v3/calendars/******%40…ccp66b9hcdhmap1h64r3ic1o70_R20201028T090000_20210421T090000Z responded with HTTP 404
Lightning: [calGoogleCalendar] A conflict occurred for ******

**Comment by kewisch** [comment]
I unfortunately cannot reproduce this. Is this still happening to you? Was this event imported from somewhere else? The double dates in the URL seem like they are the issue, whereas recurringEventId looks right.
