### ISSUE TITLE
Uncaught TypeError: defaultReminders is undefined

### ISSUE THREAD

**Issue by MLopez-Ibanez** [kewisch/gdata-provider#182]
### Describe the problem and steps to reproduce it:

I tried to edit an event from my calendar.

### What happened?

Cannot close/save the event after not changing anything.

### What did you expect to happen?

If I did not change anything, then I should be able to save the event / close the edit window.

### Anything else we should know?

I have not changed anything in the "reminders" configuration. I get this error in the log. I can save if I change the event to have no reminder.

Uncaught TypeError: defaultReminders is undefined
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:161
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    saveDialog chrome://lightning/content/lightning-item-iframe.js:1702
    saveItem chrome://lightning/content/lightning-item-iframe.js:3167
    isItemChanged chrome://lightning/content/lightning-item-iframe.js:4124
    onCommandCancel chrome://lightning/content/lightning-item-iframe.js:524
    onCancel chrome://lightning/content/lightning-item-iframe.js:590
    receiveMessage chrome://lightning/content/lightning-item-iframe.js:243
gdata-lightning-item-iframe.jsm:161:7
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:161
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    saveDialog chrome://lightning/content/lightning-item-iframe.js:1702
    saveItem chrome://lightning/content/lightning-item-iframe.js:3167
    isItemChanged chrome://lightning/content/lightning-item-iframe.js:4124
    onCommandCancel chrome://lightning/content/lightning-item-iframe.js:524
    onCancel chrome://lightning/content/lightning-item-iframe.js:590
    receiveMessage chrome://lightning/content/lightning-item-iframe.js:243

**Comment by Grid-LTS** [comment]
This is a possible duplicate of #110 . PR is created but sadly is not merged  :-(

**Comment by MLopez-Ibanez** [comment]
Indeed, it seems the same issue.
