### ISSUE TITLE
Event repeat end date always set to "forever" 

### ISSUE THREAD

**Issue by george2asenov** [kewisch/gdata-provider#183]
### Describe the problem and steps to reproduce it:
If you add and event which should repeat till a set date. 
like this 
https://screenshots.wpxtools.com/k/thunderbird_kIyFsdJrO0.png
it is always set to forever
### What happened?
repeat is set to forever - not the date you set to end
### What did you expect to happen?
event to be set to end on the date I choose 
### Anything else we should know?

https://screenshots.wpxtools.com/k/thunderbird_zoTtVop1XM.png

**Comment by MichelHanzen** [comment]
I have exactly the same problem since the upgrade to Thunderbird 78 (78.10.2 (64 bits) currently installed on Linux Mint 20.1)

**Comment by MichelHanzen** [comment]
The problem persists after Thunderbird 78.11.0 installation.

**Comment by MichelHanzen** [comment]
The problem persists after Thunderbird 78.13.0 installation.
Is there anybody who can help? Allooooo

**Comment by kewisch** [comment]
I cannot seem to reproduce this. What timezone are you in? Can you enable debugging and let me know what information gets sent to Google when you create the event, and what comes back? I send this:

```json
{
   "end" : {
      "dateTime" : "2021-06-23T12:00:00",
      "timeZone" : "Europe/Berlin"
   },
   "recurrence" : [
      "RRULE:FREQ=WEEKLY;UNTIL=20210630T090000Z"
   ],
   "reminders" : {
      "useDefault" : true
   },
   "start" : {
      "dateTime" : "2021-06-23T11:00:00",
      "timeZone" : "Europe/Berlin"
   },
   "summary" : "test",
   "transparency" : "opaque"
}
```

and get back this

```json
{
 "kind": "calendar#event",
 "etag": "\"2398750239467768\"",
 "id": "bf72350lu4kecfu5du3g2dqd94",
 "status": "confirmed",
 "htmlLink": "https://www.google.com/calendar/event?eid=some_id_here",
 "created": "2021-09-07T10:34:39.000Z",
 "updated": "2021-09-07T10:34:39.102Z",
 "summary": "test",
 "creator": {
  "email": "myemail@example.com",
  "self": true
 },
 "organizer": {
  "email": "myemail@example.com",
  "self": true
 },
 "start": {
  "dateTime": "2021-06-23T11:00:00+02:00",
  "timeZone": "Europe/Berlin"
 },
 "end": {
  "dateTime": "2021-06-23T12:00:00+02:00",
  "timeZone": "Europe/Berlin"
 },
 "recurrence": [
  "RRULE:FREQ=WEEKLY;UNTIL=20210630T090000Z"
 ],
 "iCalUID": "asdas9a8sfh3bjasfdbu3bafsa45@google.com",
 "sequence": 0,
 "reminders": {
  "useDefault": true
 },
 "eventType": "default"
}
```

**Comment by MichelHanzen** [comment]
As I met the same problem, I can maybe provide the info. How do you proceed? I'm running Thunderbird 78.14.0 under Linux Mint 20.2. I tried developer tools without success.

**Comment by kewisch** [comment]
Would be great if you could test in Thunderbird 91. See https://github.com/kewisch/gdata-provider/wiki/FAQ#enabling-debugging on how to enable debugging, which should show you the above messages.

devtools should work as well if you see the request in the network monitor.
