### ISSUE TITLE
Only one event can be created per session.  

### ISSUE THREAD

**Issue by derekmueller** [kewisch/gdata-provider#185]
### Describe the problem and steps to reproduce it:
Only one calendar event add succeeds.  The next one I add throws an error.   I can add another after restart. 

See log file below added 2 events : test calendar1 and test calendar2.   

This has been an issue for a few days, maybe a new version of TB broke this?  Calendar event dialog looks fancier now... 

Provider 78.0.1 (last updated January); TB 78.10.2; OS Ubuntu 20.04

### What happened?
The first event gets added, but following this the calendar doesn't seem to sync - spinning wheel..

### What did you expect to happen?
Should be able to add more than one event

### Anything else we should know?
See below
-->
12:13:25.106
aElement is null 2 calendar-ui-utils.js:180
    removeChildren chrome://calendar/content/calendar-ui-utils.js:180
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:147
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    commonUpdateReminder chrome://calendar/content/calendar-dialog-utils.js:514
    updateReminder chrome://lightning/content/lightning-item-iframe.js:1604
    updateCalendar chrome://lightning/content/lightning-item-iframe.js:2763
    updateCalendar self-hosted:844
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:36
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    loadDialog chrome://lightning/content/lightning-item-iframe.js:824
    loadDialog jar:file:///home/dmueller/.thunderbird/dmail/extensions/owl@beonex.com.xpi!/webapi/calendar/uiOverlay.js:355
    onLoad chrome://lightning/content/lightning-item-iframe.js:445
    onload chrome://lightning/content/lightning-item-iframe.xhtml:1
12:13:25.106
Uncaught TypeError: aElement is null
    removeChildren chrome://calendar/content/calendar-ui-utils.js:180
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:147
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    commonUpdateReminder chrome://calendar/content/calendar-dialog-utils.js:514
    updateReminder chrome://lightning/content/lightning-item-iframe.js:1604
    updateCalendar chrome://lightning/content/lightning-item-iframe.js:2763
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:36
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    loadDialog chrome://lightning/content/lightning-item-iframe.js:824
    owl beonex.com.xpi!/webapi/calendar/uiOverlay.js:355
    onLoad chrome://lightning/content/lightning-item-iframe.js:445
    onload chrome://lightning/content/lightning-item-iframe.xhtml:1
calendar-ui-utils.js:180:10
12:13:50.065 Lightning: [calGoogleCalendar] Adding regular event test calendar1 gdataCalendar.jsm:409
12:13:50.066 Lightning: [calGoogleRequest] Requesting POST https://www.googleapis.com/calendar/v3/calendars/email.address%40gmail.com/events gdataRequest.jsm:206
12:13:50.067 Lightning: [calGoogleCalendar] Setting Upload Data (application/json; charset=UTF-8):
{"start":{"dateTime":"2021-06-02T13:00:00","timeZone":"America/Toronto"},"end":{"dateTime":"2021-06-02T14:00:00","timeZone":"America/Toronto"},"summary":"test calendar1","description":"\n","reminders":{"useDefault":true}} gdataRequest.jsm:273
12:13:50.075
Uncaught 
Exception

columnNumber: 0

data: null

filename: "chrome://lightning/content/lightning-item-iframe.js"

lineNumber: 487

location: XPCWrappedNative_NoHelper { QueryInterface: QueryInterface(), filename: Getter, name: Getter, ... }

message: "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIObserverService.removeObserver]"

name: "NS_ERROR_ILLEGAL_VALUE"

result: 2147942487

stack: "onEventDialogUnload@chrome://lightning/content/lightning-item-iframe.js:487:16\nonunload@chrome://lightning/content/lightning-item-iframe.xhtml:1:1\n"

<prototype>: ExceptionPrototype { toString: toString(), name: Getter, message: Getter, ... }
lightning-item-iframe.js:487
12:13:50.328 Lightning: [calGoogleCalendar] Request POST https://www.googleapis.com/calendar/v3/calendars/email.address%40gmail.com/events responded with HTTP 200 gdataRequest.jsm:383
12:13:50.329 Lightning: [calGoogleCalendar] Parsing entry:
{
 "kind": "calendar#event",
 "etag": "\"3245300860322000\"",
 "id": "dj4ltoa13fjr6xxig0fj2u4jcs",
 "status": "confirmed",
 "htmlLink": "https://www.google.com/calendar/event?eid=ZGo0bHRvYTEzZmpyNmNjaWcwZmoydTRqY8ZgNC5kZXJlay5tdWVsbGVyQG0",
 "created": "2021-06-02T16:13:50.000Z",
 "updated": "2021-06-02T16:13:50.161Z",
 "summary": "test calendar1",
 "description": "\n",
 "creator": {
  "email": "email.address@gmail.com",
  "self": true
 },
 "organizer": {
  "email": "email.address@gmail.com",
  "self": true
 },
 "start": {
  "dateTime": "2021-06-02T13:00:00-04:00",
  "timeZone": "America/Toronto"
 },
 "end": {
  "dateTime": "2021-06-02T14:00:00-04:00",
  "timeZone": "America/Toronto"
 },
 "iCalUID": "dj4ltoa13fjr6xxig0fj2u4jcs@google.com",
 "sequence": 0,
 "reminders": {
  "useDefault": true
 },
 "eventType": "default"
}
gdataLogging.jsm:16
12:13:50.331 Lightning: [calGoogleCalendar] 2021-06-02T13:00:00-04:00 does not match timezone offset for America/Toronto gdataUtils.jsm:265
12:13:50.331 Lightning: [calGoogleCalendar] 2021-06-02T14:00:00-04:00 does not match timezone offset for America/Toronto gdataUtils.jsm:265
12:13:50.333 Lightning: [calGoogleCalendar] Adding test calendar1 succeeded gdataCalendar.jsm:451
12:14:11.264
aElement is null 2 calendar-ui-utils.js:180
    removeChildren chrome://calendar/content/calendar-ui-utils.js:180
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:147
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    commonUpdateReminder chrome://calendar/content/calendar-dialog-utils.js:514
    updateReminder chrome://lightning/content/lightning-item-iframe.js:1604
    updateCalendar chrome://lightning/content/lightning-item-iframe.js:2763
    updateCalendar self-hosted:844
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:36
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    loadDialog chrome://lightning/content/lightning-item-iframe.js:824
    loadDialog jar:file:///home/dmueller/.thunderbird/dmail/extensions/owl@beonex.com.xpi!/webapi/calendar/uiOverlay.js:355
    onLoad chrome://lightning/content/lightning-item-iframe.js:445
    onload chrome://lightning/content/lightning-item-iframe.xhtml:1
12:14:11.264
Uncaught TypeError: aElement is null
    removeChildren chrome://calendar/content/calendar-ui-utils.js:180
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:147
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    commonUpdateReminder chrome://calendar/content/calendar-dialog-utils.js:514
    updateReminder chrome://lightning/content/lightning-item-iframe.js:1604
    updateCalendar chrome://lightning/content/lightning-item-iframe.js:2763
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:36
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    loadDialog chrome://lightning/content/lightning-item-iframe.js:824
    owl beonex.com.xpi!/webapi/calendar/uiOverlay.js:355
    onLoad chrome://lightning/content/lightning-item-iframe.js:445
    onload chrome://lightning/content/lightning-item-iframe.xhtml:1
calendar-ui-utils.js:180:10
12:14:33.720 Lightning: [calGoogleCalendar] Adding regular event test calender2 gdataCalendar.jsm:409
12:14:33.722 Lightning: [calGoogleRequest] Requesting POST https://www.googleapis.com/calendar/v3/calendars/email.address%40gmail.com/events gdataRequest.jsm:206
12:14:33.722 Lightning: [calGoogleCalendar] Setting Upload Data (application/json; charset=UTF-8):
{"start":{"dateTime":"2021-06-02T14:00:00","timeZone":"America/Toronto"},"end":{"dateTime":"2021-06-02T15:00:00","timeZone":"America/Toronto"},"summary":"test calender2","description":"\n","reminders":{"useDefault":true}} gdataRequest.jsm:273
12:14:33.727 Lightning: [calGoogleCalendar] Adding Item test calender2 failed:2147500036: gdataCalendar.jsm:457
12:14:33.729
Uncaught 
Exception

columnNumber: 0

data: null

filename: "chrome://lightning/content/lightning-item-iframe.js"

lineNumber: 487

location: XPCWrappedNative_NoHelper { QueryInterface: QueryInterface(), filename: Getter, name: Getter, ... }

message: "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIObserverService.removeObserver]"

name: "NS_ERROR_ILLEGAL_VALUE"

result: 2147942487

stack: "onEventDialogUnload@chrome://lightning/content/lightning-item-iframe.js:487:16\nonunload@chrome://lightning/content/lightning-item-iframe.xhtml:1:1\n"

<prototype>: ExceptionPrototype { toString: toString(), name: Getter, message: Getter, ... }
lightning-item-iframe.js:487
    onEventDialogUnload chrome://lightning/content/lightning-item-iframe.js:487
    onunload chrome://lightning/content/lightning-item-iframe.xhtml:1

**Comment by derekmueller** [comment]
Just a quick follow-up.  My TB updated to 78.11.0 and this issue seems to have gone away!

**Comment by kewisch** [comment]
Glad this ended up working! Let me know if it reoccurs with Thunderbird 91.
