### ISSUE TITLE
Can't access google tasks

### ISSUE THREAD

**Issue by millwood** [kewisch/gdata-provider#189]
If I start a new profile and try to attach to my google calendar, I do not get a task entry.  This is true on release and beta.  My existing release profile has a "default list" calendar for tasks.  This is not created for a new profile.  The calendar list I get to choose from does not include tasks.

**Comment by kewisch** [comment]
I've updated this add-on to work with Thunderbird 91, you should be able to access tasks again.

**Comment by drm135** [comment]
Thanks! Works perfectly now.
