### ISSUE TITLE
Deprecate this plug-in in favour of CalDAV for general use cases

### ISSUE THREAD

**Issue by colans** [kewisch/gdata-provider#190]
Because [CalDAV is more stable nowadays](https://github.com/kewisch/gdata-provider/wiki/FAQ#why-should-i-use-the-provider-and-not-access-via-caldav) and this module not actively maintained, we should deprecate it for general use in favour of Thunderbird's built-in CalDAV support.

Folks that need it for specific use cases can still use it, however.

Problems that this solves are issues like #63.

So this is basically a documentation task.

**Comment by timur-tabi** [comment]
I think it would be great if the first paragraph of the README provided clear instructions on how to set up Google CalDAV.  I had no idea until I saw Rolf185's comment on #63 today how to actually do that.

**Comment by ahukkanen** [comment]
> That's exactly what's needed. Any idea how folks can help move that along?

@colans I don't think there's much that can be done here other than wait for someone to review it. You could try contacting some of the people who have permissions to review content in the knowledge base:
https://support.mozilla.org/en-US/groups/reviewers
https://support.mozilla.org/fi/groups/knowledge-base-reviewers

These users seem to be part of those groups that have contributed to that particular documentation page:
https://support.mozilla.org/en-US/user/michro
https://support.mozilla.org/en-US/user/wsmwk
https://support.mozilla.org/en-US/user/firefox877

They are all volunteers, so I wouldn't expect any response in a timely manner. Just patience needed with this one.

I did one other contribution to the Mozilla knowledge base at the end of February and my change seemed to be approved now (I don't know the exact date when it was approved). So, maybe by the end of the year we should expect to see some action, maybe? Or sooner if someone steps in.

**Comment by kewisch** [comment]
Even if we favor use of caldav instead of the API, there are still a few things this extension provides in addition, including the tasks api and support for some features in UI that are not available using pure caldav. I'm still working on this, even if not regularly. See the webextension branch for more details.

Once I've gotten to a good spot with the webextension branch I'll check out the pull requests in more detail to see how thing can be integrated.
