### ISSUE TITLE
Impossible to save a new task because default reminder undefined

### ISSUE THREAD

**Issue by chmarty** [kewisch/gdata-provider#193]
### Describe the problem and steps to reproduce it:
It is impossible to create/save a new task unless you manually define a reminder setting each time.
Provider for Google Calendar ignores default reminder setting for tasks.

The problem occurs independent of the Option setting: Default reminder of tasks setting ON or OFF.

### Anything else we should know?
Thunderbird 78.12.0 (64-bit)
Provider for Google Calendar 78.0.1

Error Log: 
defaultReminders is undefined gdata-lightning-item-iframe.jsm:161
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:161
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    saveDialog chrome://lightning/content/lightning-item-iframe.js:1702
    saveItem chrome://lightning/content/lightning-item-iframe.js:3167
    isItemChanged chrome://lightning/content/lightning-item-iframe.js:4124
    onCommandCancel chrome://lightning/content/lightning-item-iframe.js:524
    onCancel chrome://lightning/content/lightning-item-iframe.js:590
    receiveMessage chrome://lightning/content/lightning-item-iframe.js:243

**Comment by chmarty** [comment]
I just found a possible solution:
https://github.com/kewisch/gdata-provider/issues/150

**Comment by kewisch** [comment]
I believe this should be resolved with Thunderbird 91 with f6e3babf9de0911a9b7aa3a58f3493cc79694c60
