### ISSUE TITLE
Provider for Google Calendar doesn't seem to find anything

### ISSUE THREAD

**Issue by jay-sf** [kewisch/gdata-provider#195]
Dear @kewisch ,

first of all thanks for providing this great tool which basically worked fine so far! However, I have encountered a problem and it would be great if you could help me solve it.

I'm using Ubuntu 20.04.2 LTS with the 5.11.0-27-generic kernel. I freshly installed it on my desktop and updated everything. I also installed Provider for Google Calendar Version 78.0.1 in Thunderbird 78.11.0 (64-bit) yesterday. With my gmail address I tried to search for Google calendars (Format), but nothing happened and it just runs forever with no error messages. I also tried a TB 91 binary but the problem persists.

Weirdly enough on my laptop the setup is absolutely the same and it works like charm. I haven't install it freshly there, though.

I have no clue what could be wrong, and it would be great if you had any idea what might cause the problem and how to fix it.

Cheers

**Comment by thejazzid** [comment]
Same here. MacOS, TB 78.13.0, Calendar 78.0.1. just keep spinning when I try to add gmail calendar

**Comment by jay-sf** [comment]
Just opened `thunderbird` in terminal, and this output appears while adding calendar fails:
`JavaScript error: resource:///modules/iteratorUtils.jsm, line 75: TypeError: right-hand side of 'in' should be an object, got undefined`
@kewisch  Would this perhaps help you to provide a fix now? Thanks

**Comment by kewisch** [comment]
Hi @jay-sf , this should be fixed in Thunderbird 91 with the new version of the Provider. I'm no longer using iteratorUtils there. Can you give it a shot? Apologies for closing already, I'm trying to trim down the number of issues with the new version out. Please do re-open or comment if you are still experiencing issues.

**Comment by jay-sf** [comment]
It was a bit tedious to install Thunderbird91 on a Ubuntu 20.04LTS system, but I managed it. Actually I did not need to download the provider at all, adding Google calendars using WebDAV worked quite well. Thanks!
