### ISSUE TITLE
Can't accept invitation for repeated event

### ISSUE THREAD

**Issue by chartre** [kewisch/gdata-provider#199]
### Describe the problem and steps to reproduce it:

Receive an invitation email and try to "accept all".
![imagen](https://user-images.githubusercontent.com/2323237/130772083-014b7619-7bad-4b71-be54-62835222397f.png)

### What happened?

Message "Error processing the message. Status: 80004005" appears.

![imagen](https://user-images.githubusercontent.com/2323237/130770549-3276c1fd-4139-475d-90ba-5543d6e8b3d1.png)
![imagen](https://user-images.githubusercontent.com/2323237/130770520-4ceffd2f-57d5-45d4-bddd-85350fa794ce.png)

And the event is not inserted in the calendar.

### What did you expect to happen?

I expected to Thunderbird to add this event to the google calendar.

### Anything else we should know?

- TB 91.0.1
- Google calendar with corporate email account. Calendar is not shared publicly and accessed by its "secret address" (iCal format).
- Working well for either repeating or single other invititations.
- Forbidden error shown in logs:
![imagen](https://user-images.githubusercontent.com/2323237/130772378-7db4f66d-3e97-4c05-b879-714a5fd413f5.png)

**Comment by kewisch** [comment]
The calendar here is a CalDAV calendar, it is not using the Provider for Google Calendar. I'm not quite ready for Thunderbird 91, but there should be an updated version in a few days. You'll need to re-create the calendar using the Provider for Google Calendar.
