### ISSUE TITLE
"Migrate read-only calendars" Popup then Empty Calendar

### ISSUE THREAD

**Issue by dylanmorroll** [kewisch/gdata-provider#20]
Hi there, I'm not sure what's happening but when I enable the Provider for Google Calendar plugin and restart Thunderbird to activate it, upon restarting a popup displays titled "Migrate read-only calendars". No matter what I click on this popup (OK, cancel or the 'X' button), when I navigate to my calendar tab it is now completely blank. I checked the error logs and have these errors:

```
Overlays.jsm: Could not resolve 2 references 
(2) […]
​
0: <menupopup id="options-privacy-menupopup">
​
1: <hbox id="status-privacy" class="statusbarpanel">
​
length: 2
​
<prototype>: Array []
Overlays.jsm:195
statusPrivacy is null gdata-event-dialog.js:40
    <anonymous> chrome://gdata-provider/content/gdata-event-dialog.js:40
    loadScript resource:///modules/Overlays.jsm:561
    load resource:///modules/Overlays.jsm:226
    load resource:///modules/Overlays.jsm:48
    observe chrome://messenger/content/parent/ext-legacy.js:229
Overlays.jsm: Could not resolve 1 references 
Array [ menupopup#appmenu_taskPopup ]
Overlays.jsm:195
Use of Mutation Events is deprecated. Use MutationObserver instead. calendar-views.js:97:9
Attempt to set a forbidden header was denied: Content-Length cardbookWebDAV.js:387:17
getViewDeck(...) is null calendar-views-utils.js:301
    currentView chrome://calendar/content/calendar-views-utils.js:301
    setDateRange chrome://calendar/content/calendar-views-utils.js:600
    setDateRange chrome://calendar/content/calendar-month-base-view.js:296
    showDate chrome://calendar/content/calendar-month-base-view.js:253
    goToDay chrome://calendar/content/calendar-views.js:275
    switchToView chrome://calendar/content/calendar-views-utils.js:280
    ltnSwitch2Calendar chrome://lightning/content/messenger-overlay-sidebar.js:629
    openTab chrome://lightning/content/messenger-overlay-sidebar.js:70
    openTab chrome://messenger/content/tabmail.xml:624
    oncommand chrome://messenger/content/messenger.xul:1
uncaught exception: 2147746065 autosync.jsm:251:30
```

I'm not sure what to do next! Any help would be appreciated :)

**Comment by ExTechOp** [comment]
I've seen the same issue on Thunderbird 68.2.0 (64-bit) on Fedora Linux, any suggestions on what debugging is needed?

**Comment by gtk-aschmidt** [comment]
![migrate-read-only-calendars](https://user-images.githubusercontent.com/3429447/68973803-0e0d3900-07a4-11ea-90dd-433f0293103c.png)

I also get the blank dialog upon every restart.

In Lightning proper, I can populate the calendar by pressing "Synchronize Calendars," but it is blank otherwise.

**Comment by addessom** [comment]
Hi folks,

By setting up parameter 'calendar.google.migrate' to 'false' it stopped from showing that popup.

I hope this helps.

**Comment by HagiRT** [comment]
Hi,
unfortunately I do not know where to set this parameter.
Could you explain ?
thx

**Comment by SebastianAltmeyer** [comment]
Hi, 

The parameter 'calendar.google.migrate' can be set in the very same way as the debug-options, as explained here: 

https://github.com/kewisch/gdata-provider/wiki/FAQ#enabling-debugging

**Comment by kewisch** [comment]
This should no longer be the case in the latest version
