### ISSUE TITLE
feature: Save invitations to non-primary calendar

### ISSUE THREAD

**Issue by MLopez-Ibanez** [kewisch/gdata-provider#21]
Right now, I can save a copy of an invitation to my main calendar, then copy+paste into non-primary calendar. If I can do that, why can't gdata-provider do this for me? I know notifications will not work, but a warning dialog would be enough.

**Comment by kewisch** [comment]
This is rather a feature to be provided by Lightning, saving an event without the notifications. Can you check bugzilla instead?
