### ISSUE TITLE
Failed to acquire a new OAuth token: invalid_grant, "Malformed auth code."

### ISSUE THREAD

**Issue by sphakka** [kewisch/gdata-provider#23]
Since a while adding a new calendar (Thunderbird-60 and SeaMonkey2.49, GData-provider-4.4.2, Gentoo and Arch) is quite a nightmare. It works randomly one time out of X -- even after removing all google calendars and oauth tokens. The procedure goes through without UI errors and ends up with an **empty**  list of available calendars; the error console shows:
```
[calGoogleSessionManager] Creating session ...@gmail.com
[calGoogleSession] Token expired 1571828596 seconds ago, resetting
[calGoogleCalendar] Logging in session marcoep@gmail.com
[calGoogleCalendar] No access token for marcoep@gmail.com, refreshing token
[calGoogleSession] Adding item https://www.googleapis.com/tasks/v1/users/@me/lists to queue
[calGoogleSession] Adding item https://www.googleapis.com/calendar/v3/users/me/calendarList to queue
[calGoogleCalendar] Failed to acquire a new OAuth token for ...@gmail.com data: {
  "error": "invalid_grant",
  "error_description": "Malformed auth code."
}
```
After many attempts I managed to (re-)configure all my calendars (spent 2-3 hours!). There's something fishy... please have a look.

**Comment by sphakka** [comment]
Also, the exception should trigger a UI pop-up message.

**Comment by dlob** [comment]
I encountered the same error.
After logging the network packets, I discovered that the authorization code contains escaped chars (e.g. %2F). Looking at the `parseURLData` method in OAuth2.jsm, there is no decoding of such sequences. Testing the original request with all chars decoded properly returns a valid access token.
