### ISSUE TITLE
Email with calendar entry becomes hidden when entry is accepted

### ISSUE THREAD

**Issue by redstang33** [kewisch/gdata-provider#231]
### Describe the problem and steps to reproduce it:

When receiving a regular e-mail with a calendar entry in the attachment you have the ability to accept the calendar entry. Once that is accepted the e-mail body itself is hidden and you only see the calendar details. Steps to reproduce:

- Receive email with body text and calendar invite in the attachment.
- Accept the invite

### What happened?

The email body text is no longer visible once the calendar entry in the attachment is accepted.

### What did you expect to happen?

The email body text should still be visible.

### Anything else we should know?

Output from the Console when selecting the message:
Lightning: iTIP method: REQUEST calItipUtils.jsm:193
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. contentAreaClick.js:82:6
Lightning: iTIP on REQUEST: found 1 items. calItipUtils.jsm:1706
Lightning: iTIP operations: 0 calItipUtils.jsm:2019

**Comment by kewisch** [comment]
This is an issue in Thunderbird rather than the Provider. Since it has been a longstanding issue I wouldn't be surprised if it has already been filed. Please check out bugzilla.mozilla.org.
