### ISSUE TITLE
Feature request: Add option to disable alerts when a calendar is hidden please

### ISSUE THREAD

**Issue by consultingroupitaly** [kewisch/gdata-provider#235]
Hi,
is it possible to do not show alerts when a calendar is hidden?

Best regards.

**Comment by kewisch** [comment]
This would be something in Thunderbird, not the provider. You can "disable" calendars, in this case they don't do alarms. Check out the properties dialog for calendars in the calendar ist.

**Comment by consultingroupitaly** [comment]
Thanks.
