### ISSUE TITLE
Event colors reset

### ISSUE THREAD

**Issue by DaveH52** [kewisch/gdata-provider#236]
### Describe the problem and steps to reproduce it: 

Events I've already created with various colors all had their colors reset. Create a task on my cell phone, color it red, and when I look at it in Thunderbird it's set to blue. Go back into my phone and it's been reset to blue also.

(Please include as many details as possible.)

### What happened? 

Color isn't just being ignored, it's being reset to some default.

### What did you expect to happen? 

I expected the event color to remain as I set it.

### Anything else we should know? 

I use the colors to indicate priorities to make events easier to find.

**Comment by kewisch** [comment]
This should be working on the `main` branch as is, I've added something to the legacy version that will at least roundtrip event colors. Once 91.0.2 is released you may need to re-subscribe to the calendar to make it work for old events, but new ones should be good.
