### ISSUE TITLE
Provider for Google Calendar breaks default reminder behavior in TB 78

### ISSUE THREAD

**Issue by DaveLaQ** [kewisch/gdata-provider#238]
### Describe the problem and steps to reproduce it:

Reminder drop-down display in Edit Item dialog when creating a New Event displays the wrong thing when opening the dialog.

Steps to reproduce: Create a new event in the TB calendar. Look at the current setting in the drop-down display for "Reminder." It shows "Default Reminder," which it should not.

### What happened?

Reminder defaults to "Default Reminder" setting.

### What did you expect to happen?

New event should have defaulted to "No reminder" since in TB Options/Calendar I have "Default reminder setting for events" set to "Off."

### Anything else we should know?

Same result when the default reminder option is set to "On" and a default reminder time is set in TB Options/Calendar: New Event Edit Item dialogue shows the same "Default Reminder" setting upon opening the dialog—when it should show the default reminder *value* (e.g. "2 days").

Note that this behavior is only when Provider for Google Calendar is enabled. When it is disabled or not installed, TB acts properly in these regards.

**Comment by kewisch** [comment]
If the default reminder for events is off, then even when selecting default reminder in Thunderbird, it will keep them off. The difference here, when you later change your default reminder, it will be changed for all events that have the "default" setting. If I were to explicitly set "no reminder", it would stay on no reminder even if you change the default.

**Comment by DaveLaQ** [comment]
Thanks for your swift reply.

Yes, I believe that is the way it is intended to work. If you turn on the 
default reminder in Options, it should not affect any existing events.

For what it's worth, I prefer this native behavior of Thunderbird, so I 
have disabled Provider. It's a bummer, because it's really great for 
quickly setting up a bunch of Google calendars in TB. Nicely done. 🙂

Thanks,

Dave
