### ISSUE TITLE
Invite attendees does not work in TB 91.1.2 (64 bit) and Provider for Google Calendar

### ISSUE THREAD

**Issue by Colingross** [kewisch/gdata-provider#246]
I have scheduled a meeting with zoom and the meeting is in my Google calendar
I double click on the item to open the details panel then click "Edit" to open the "Edit Event" panel and click "Invite  Attendees" which opens the "Invite Attendees" panel.
I add some attendees and click :OK". The added attendees now appear in the "Edit Event" panel.
I click "Save and close" but then when I reopen the "Edit Event" panel the attendees have now disappeared and no invites have been sent.

The following appears to be the error console messages of interest:
11:28:19.251 Calendar: [calGoogleCalendar] Freebusy query for mailto:colingrossau@gmail.com failed (2147746065): null gdataSession.jsm:480
11:29:29.206 Calendar: [calGoogleRequest] Requesting POST https://www.googleapis.com/calendar/v3/freeBusy gdataRequest.jsm:205
11:29:29.207 Calendar: [calGoogleCalendar] Setting Upload Data (application/json; charset=UTF-8):
{"timeMin":"2021-09-28","timeMax":"2021-10-03","items":[{"id":"stevemara@aapt.net.au"}]} gdataRequest.jsm:272
11:29:29.734 Calendar: [calGoogleRequest] Clock skew is 1 seconds gdataRequest.jsm:375
11:29:29.734 Calendar: [calGoogleCalendar] Request POST https://www.googleapis.com/calendar/v3/freeBusy responded with HTTP 400 gdataRequest.jsm:382
11:29:29.734 Calendar: [calGoogleCalendar] A request Error Occurred. Status Code: 400 Bad Request Body: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "badRequest",
    "message": "Bad Request"
   }
  ],
  "code": 400,
  "message": "Bad Request"
 }
}
gdataRequest.jsm:533
11:29:29.734 Calendar: [calGoogleCalendar] Failed freebusy request: [Exception... "A request Error Occurred. Status Code: 400 Bad Request Body: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "badRequest",
    "message": "Bad Request"
   }
  ],
  "code": 400,
  "message": "Bad Request"
 }
}
"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://gdata-provider/legacy/modules/gdataRequest.jsm :: fail :: line 231"  data: no] gdataSession.jsm:562
11:29:29.735 Calendar: [calGoogleCalendar] Freebusy query for mailto:stevemara@aapt.net.au failed (2147746065): null gdataSession.jsm:480
11:29:33.769 Calendar: [calGoogleRequest] Requesting POST https://www.googleapis.com/calendar/v3/freeBusy gdataRequest.jsm:205
11:29:33.769 Calendar: [calGoogleCalendar] Setting Upload Data (application/json; charset=UTF-8):
{"timeMin":"2021-09-28","timeMax":"2021-10-03","items":[{"id":"katelynegross@gmail.com"}]} gdataRequest.jsm:272
11:29:34.378 Calendar: [calGoogleRequest] Clock skew is 1 seconds gdataRequest.jsm:375
11:29:34.378 Calendar: [calGoogleCalendar] Request POST https://www.googleapis.com/calendar/v3/freeBusy responded with HTTP 400 gdataRequest.jsm:382
11:29:34.378 Calendar: [calGoogleCalendar] A request Error Occurred. Status Code: 400 Bad Request Body: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "badRequest",
    "message": "Bad Request"
   }
  ],
  "code": 400,
  "message": "Bad Request"
 }
}
gdataRequest.jsm:533
11:29:34.379 Calendar: [calGoogleCalendar] Failed freebusy request: [Exception... "A request Error Occurred. Status Code: 400 Bad Request Body: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "badRequest",
    "message": "Bad Request"
   }
  ],
  "code": 400,
  "message": "Bad Request"
 }
}
"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://gdata-provider/legacy/modules/gdataRequest.jsm :: fail :: line 231"  data: no] gdataSession.jsm:562
11:29:34.379 Calendar: [calGoogleCalendar] Freebusy query for mailto:katelynegross@gmail.com failed (2147746065): null gdataSession.jsm:480
11:31:03.568 Calendar: [calGoogleCalendar] Modifying item Colin Gross' Zoom Meeting (master item) gdataCalendar.jsm:468
11:31:03.569 Calendar: [calGoogleRequest] Requesting PUT https://www.googleapis.com/calendar/v3/calendars/colingrossau%40gmail.com/events/3r1vai39n4dtfm9fhsua6a7rko gdataRequest.jsm:205
11:31:03.569 Calendar: [calGoogleCalendar] Setting Upload Data (application/json; charset=UTF-8):
{"start":{"dateTime":"2021-09-29T15:00:00","timeZone":"Australia/Sydney"},"end":{"dateTime":"2021-09-29T15:45:00","timeZone":"Australia/Sydney"},"summary":"Colin Gross' Zoom Meeting","description":"Colin Gross is inviting you to a scheduled Zoom meeting.<br><br>Join Zoom Meeting<br><a class=\"moz-txt-link-freetext\" href=\"https://us04web.zoom.us/j/77316245406?pwd=cG9MUzNXWGxWVTZrUVJzMlNFb2dBUT09\">https://us04web.zoom.us/j/77316245406?pwd=cG9MUzNXWGxWVTZrUVJzMlNFb2dBUT09</a><br><br>Meeting ID: 773 1624 5406<br>Passcode: eT7zZe<br><br>","location":"https://us04web.zoom.us/j/77316245406?pwd=cG9MUzNXWGxWVTZrUVJzMlNFb2dBUT09","sequence":3,"status":"confirmed","reminders":{"overrides":[],"useDefault":true}} gdataRequest.jsm:272
11:31:03.570 Calendar: [calGoogleCalendar] Sending request headers: ({}) gdataRequest.jsm:301
11:31:04.182 Calendar: [calGoogleRequest] Clock skew is 2 seconds gdataRequest.jsm:375
11:31:04.182 Calendar: [calGoogleCalendar] Request PUT https://www.googleapis.com/calendar/v3/calendars/colingrossau%40gmail.com/events/3r1vai39n4dtfm9fhsua6a7rko responded with HTTP 200 gdataRequest.jsm:382
11:31:04.184 Calendar: [calGoogleCalendar] Parsing entry:
{
 "kind": "calendar#event",
 "etag": "\"3265571708518000\"",
 "id": "3r1vai39n4dtfm9fhsua6a7rko",
 "status": "confirmed",
 "htmlLink": "https://www.google.com/calendar/event?eid=M3IxdmFpMzluNGR0Zm05ZmhzdWE2YTdya28gY29saW5ncm9zc2F1QG0",
 "created": "2021-09-26T03:47:56.000Z",
 "updated": "2021-09-27T23:37:34.259Z",
 "summary": "Colin Gross' Zoom Meeting",
 "description": "Colin Gross is inviting you to a scheduled Zoom meeting.<br><br>Join Zoom Meeting<br><a class=\"moz-txt-link-freetext\" href=\"https://us04web.zoom.us/j/77316245406?pwd=cG9MUzNXWGxWVTZrUVJzMlNFb2dBUT09\">https://us04web.zoom.us/j/77316245406?pwd=cG9MUzNXWGxWVTZrUVJzMlNFb2dBUT09</a><br><br>Meeting ID: 773 1624 5406<br>Passcode: eT7zZe<br><br>",
 "location": "https://us04web.zoom.us/j/77316245406?pwd=cG9MUzNXWGxWVTZrUVJzMlNFb2dBUT09",
 "creator": {
  "email": "colingrossau@gmail.com",
  "self": true
 },
 "organizer": {
  "email": "colingrossau@gmail.com",
  "self": true
 },
 "start": {
  "dateTime": "2021-09-29T15:00:00+10:00",
  "timeZone": "Australia/Sydney"
 },
 "end": {
  "dateTime": "2021-09-29T15:45:00+10:00",
  "timeZone": "Australia/Sydney"
 },
 "iCalUID": "3r1vai39n4dtfm9fhsua6a7rko@google.com",
 "sequence": 3,
 "reminders": {
  "useDefault": true
 },
 "eventType": "default"
}
gdataLogging.jsm:16
11:31:04.187 Calendar: [calGoogleCalendar] Modifying Colin Gross' Zoom Meeting succeeded gdataCalendar.jsm:561

**Comment by p4ssc3** [comment]
Hi, same probleme here, Google invites doesn't work anymore...
Thanks

**Comment by kewisch** [comment]
This is with the pre-release file I posted in a few other issues? Do you have all the attendee options enabled in the preferences?

**Comment by p4ssc3** [comment]
> Can you try with https://github.com/kewisch/gdata-provider/files/7192893/gdata-provider-91.0.2pre3.xpi.zip instead? Make sure you have all the attendee options enabled in the add-on preferences.

I tried this but install failed : "not compatible"

**Comment by kewisch** [comment]
> One thing to note that could influence things, I receive invites on other email adresses than my gmail account

Yes, this could be an issue. Unfortunately, the calendar apis in Thunderbird just support one email address per calendar, and that is automatically configured to the main email address of the account when you subscribe to the main calendar. For secondary calendars, scheduling is disabled because Google doesn't work well with this.

**Comment by gromain** [comment]
Unless there is something that can be done on the extension side regarding scheduling on secondary calendars, I agree this can be closed (at least for my use case).
