### ISSUE TITLE
Cannot dismiss or snooze calendar reminders

### ISSUE THREAD

**Issue by dwenzlick** [kewisch/gdata-provider#258]
### Describe the problem and steps to reproduce it:

(Please include as many details as possible.)

I just installed this extension in thunderbird yesterday and everything is working great except I cannot dismiss or snooze meeting reminders. Clicking on the buttons does nothing.

Seeing this with latest version plugin and version 91.2.0 of Thunderbird

### What happened?

* Clicking on snooze or dismiss does absolutely nothing for a single event.
* Clicking snooze all or dismiss all does absolutely nothing for all events.

### What did you expect to happen?

* Events to get dismissed or snoozed appropriately.

**Comment by kewisch** [comment]
Thanks for reporting! Please see #3
