### ISSUE TITLE
 [Lightning, Provider: GData]: use stored oauth when the password manager is disabled

### ISSUE THREAD

**Issue by adrianf0** [kewisch/gdata-provider#27]
Reopening of issue from: https://bugzilla.mozilla.org/show_bug.cgi?id=1476330

Setup:
 * Ubuntu 18.04 LTS
 * Thunderbird 68.2.1 

It seems, that in case the password manager is disabled (i.e. by the KeeBird plugin), Lightning/GData will always pop up Oauth2 login window instead of using the OAuth token stored during the previous session. 

The method with the stored OAuth2 and running KeeBird works properly with Google e-mail accounts served directly by Thunderbird. However, for Google calendars, Lightning/GData behaves differently than Thunderbird causing problems. 

More details regarding the issue can be found under:
* https://github.com/kee-org/keebird/issues/14

**Comment by adrianf0** [comment]
I suspect it may by a different issue, related to authentication this time.
I removed all google calendars and tried to add it from scratch. I get to OAuth2 window where I type the proper credentials. The window disappears, but there are no google calendars which I could add and in the debugger I can find:
```
uncaught exception: 2147746065 autosync.jsm:251:30
Assert failed: undefined
 calUtils.jsm:139
    ASSERT resource://calendar/modules/calUtils.jsm:139
    passwordManagerGet resource://calendar/modules/utils/calAuthUtils.jsm:452
    get resource://gdata-provider/modules/gdataSession.jsm:167
    connect resource://gdata-provider/modules/OAuth2.jsm:72
    onPromptAuthAvailable resource://gdata-provider/modules/gdataSession.jsm:295
    onPromptStartAsync resource://gdata-provider/modules/gdataSession.jsm:292
    _promiseAuthPrompt jar:file:///usr/lib/thunderbird/omni.ja!/components/msgAsyncPrompter.js:26
    _promiseAuthPrompt jar:file:///usr/lib/thunderbird/omni.ja!/components/msgAsyncPrompter.js:24
    run jar:file:///usr/lib/thunderbird/omni.ja!/components/msgAsyncPrompter.js:49
    InterpretGeneratorResume self-hosted:1284
    AsyncFunctionNext self-hosted:839
Assert failed: undefined
 calUtils.jsm:139
    ASSERT resource://calendar/modules/calUtils.jsm:139
    passwordManagerRemove resource://calendar/modules/utils/calAuthUtils.jsm:483
    set resource://gdata-provider/modules/gdataSession.jsm:184
    onAccessTokenFailed resource://gdata-provider/modules/OAuth2.jsm:237
    onAccessTokenFailed self-hosted:1007
    onload resource://gre/modules/Http.jsm:77
[Exception... "null"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gdata-provider/modules/gdataSession.jsm :: login/authFailed< :: line 284"  data: no] gdataSession.jsm:284:33
    authFailed resource://gdata-provider/modules/gdataSession.jsm:284
    <anonimowa> self-hosted:1001
    onPromptAuthAvailable resource://gdata-provider/modules/gdataSession.jsm:301
    onAccessTokenFailed resource://gdata-provider/modules/OAuth2.jsm:240
    onAccessTokenFailed self-hosted:1007
    onload resource://gre/modules/Http.jsm:77
```
The provider is also not added to the Google linked applications (I checked in the google settings).

I have tried the same with the completely new Thunderbird account and got the same problem.

**Comment by adrianf0** [comment]
The suggestion from the other thread ([link](https://github.com/kee-org/keebird/issues/14#issuecomment-549205097)) solves the problem of the missing calendars.
However, I confirm that the problem of the login prompt with every thunderbird start has not been resolved.

**Comment by martinperreault** [comment]
I also experience the problem of the recurring login prompt every time I launch Thunderbird (68.4.1).

**Comment by kewisch** [comment]
Unfortunately I will not be able to support this. The newest version on the `main` branch will move towards using only WebExtensions APIs. If there is a fix that could be applied to https://github.com/kewisch/gdata-provider/blob/main/src/experiments/gdata/ext-gdata.js that would help with this I'm happy to take a patch.
