### ISSUE TITLE
"Secure connection failed" error when authenticating to Google.

### ISSUE THREAD

**Issue by EKatowitz** [kewisch/gdata-provider#272]
### Discussed in https://github.com/kewisch/gdata-provider/discussions/266

<div type='discussions-op-text'>

<sup>Originally posted by **JonathanRRogers** October 12, 2021</sup>
I'm using Provider for Google Calendar 91.0.1 on Thunderbird 91.2.0 on Ubuntu 20.04.3 LTS. A few days ago, it began failing to fully authenticate to my Google Calendar. Most steps succeed, but after I check boxes under "Select what Provider for Google Calendar can access" and click "Continue," I get a "Secure connection failed" page in the "Sign in to your account" window. There is an "Or you can add an exception..." link, but clicking it has no effect.</div>

**Comment by kewisch** [comment]
Provider 91.0.2 is in review, please give it a test when it is out and let me know if it works.

**Comment by kewisch** [comment]
Resolving this, based on discussion in #266 it looks like this works in the release candidate. Thanks for testing!
