### ISSUE TITLE
repeating google tasks not synchronizing properly 

### ISSUE THREAD

**Issue by Al-Edev** [kewisch/gdata-provider#273]
### Describe the problem and steps to reproduce it:

When a repeating google task created on the android google task app is marked complete on the app, the task remains active on the thunderbird task list instead of synchronizing as completed.  

(Please include as many details as possible.)

### What happened?

For example, if you create a daily repeating task on the android google task app and mark the task complete each day on the android google task app, instead of the task being synched as completed, the task will show up cumulatively each day.

### What did you expect to happen?

When you mark a repeating task as completed on the android google task app as completed for one of the repeating periods, it should be synched as completed until the next time the task is due.

**Comment by kewisch** [comment]
See #10, the repeating property is not exposed via the API. I'm not sure how it works on Android, I suspect Google is doing something sekrit in their own internal API. Unfortunately I cannot take action on this until Google adds API, therefore closing.
