### ISSUE TITLE
Calendar reminders for events won't dismiss and won't snooze

### ISSUE THREAD

**Issue by mtpmd** [kewisch/gdata-provider#274]
This happens in all 91.x versions of thunderbird/lightning and all versions of Google provider including the about-to-be released 91.0.2.  Click dismiss or snooze on an event reminder and nothing perceptible happens at all.   Unsubscribing from all the calendars and uninstalling and re-installing Google provider and re-subscribing, which per the web has sometimes fixed such problems in past, has no effect.

The error console  (redacted for privacy) on these attempts says:

> Calendar: [calGoogleCalendar] Modifying item [Item Name] failed:2147500037: {
>  "error": {
>   "errors": [
>    {
>     "domain": "calendar",
>     "reason": "forbiddenForNonOrganizer",
>     "message": "Shared properties can only be changed by the organizer of the event."
>    }
>   ],
>   "code": 403,
>   "message": "Shared properties can only be changed by the organizer of the event."
>  }
> }

and those are preceded also by log entries that read
<Calendar: [calGoogleCalendar] Setting Upload Data (application/json; charset=UTF-8):  [bunch of settings]
>Calendar: [calGoogleCalendar] Sending request headers: ({})
> Calendar: [calGoogleCalendar] Request PUT https://www.googleapis.com/calendar/v3/calendars/[GoogleUserName]%4…60o30c1g6oo30h1m8crj4hi68co3ch9k6p0j6d1g6t0jchi468okcc9o8p30 responded with HTTP 403 gdataRequest.jsm:389
> Calendar: [calGoogleCalendar] Login failed for [GoogleEMailAddr] HTTP Status: 403 Reason: forbiddenForNonOrganizer

The gmail API says
> 403: Forbidden for non-organizer [comes from]
> The event update request is attempting to set one of the shared event properties in a copy that isn't the organizer's. Shared properties (for example, guestsCanInviteOthers, guestsCanModify, or guestsCanSeeOtherGuests) can only be set by the organizer.
> [.... and .... ]
> Suggested actions:
> If you're using Events: insert, Events: import, or Events: update, and your request doesn't include any shared properties, this is equivalent to trying to set them to their default values. Consider using Events: patch instead.
> If your request has shared properties, make sure that you're only trying to change these properties if you're updating the organizer's copy.

I'm not the organizer for most of these events, just trying to modify my own reminders, so sounds like only the first suggestion applies, and the issue might be not using "Events: patch" vs. update?  

I don't have the background , knowledge or time to track down or try to test fix where this is actually happening in the code to try to help out, sorry.

**Comment by kewisch** [comment]
This is fixed on the `main` branch, but unfortunately I won't be able to backport this to the legacy branch. The old version pushes the whole event, the main branch will patch only changed properties.
