### ISSUE TITLE
Gcal not syncing with Tbird on Mac

### ISSUE THREAD

**Issue by punkfrogab** [kewisch/gdata-provider#275]
### Describe the problem and steps to reproduce it:
Thunderbird 78.14.0(64)
Provider for Google Calendar 78.0.2
OSX 11.6
I've reported this earlier, but there have been updates and the behaviour is different.
Event is created, but sometimes attendee doesn't get email notification, and attendee disappears from event; sometimes the event isn't replicated in G calendar.

Create an event in Tbird, and invite an attendee. Repeated from another email account.

### What did you expect to happen?
a) Event is created in Tbird
b) Event in Tbird shows attendee
c) Attendee receives email invitation
d) Event is synchronised i Gcalendar

### What actually happened?
Actual result: differs depending on which email account in Tbird I use for the event, despite both being Gmail addresses.

**First email account**
a) Event is created in Tbird: Yes
b) Event in Tbird shows attendee: Yes
c) Attendee receives email invitation: Yes
d) Event is synchronised i Gcalendar: No

**Second email account**
a) Event is created in Tbird: Yes
b) Event in Tbird shows attendee: No
c) Attendee receives email invitation: No
d) Event is synchronised i Gcalendar: Yes

<!--
  Please provide any errors or relevant messages from the error console (Tools Menu → Error Console), with debugging enabled
[Tbird-error-console.pdf](https://github.com/kewisch/gdata-provider/files/7360405/Tbird-error-console.pdf)
:

**Comment by punkfrogab** [comment]
I'm not a developer myself any more, so I can only test once they updates are available in production on mac - but then I know to test thoroughly. I think the strange thing now is that there are different outcomes using two (Gmail) email accounts.

**Comment by kewisch** [comment]
Thunderbird 91 should be the latest release version, the Provider for Google Calendar release candidate I linked is in review and should be out in a few days. When you've been able to test on the latest version please let me know :)

**Comment by punkfrogab** [comment]
Tbird 91.2.0(64), Provider 91.0.2. No improvement - behaviour same as reported in #275.
First email account
a) Event is created in Tbird: Yes
b) Event in Tbird shows attendee: Yes
c) Attendee receives email invitation: Yes
d) Event is synchronised i Gcalendar: No

Second email account
a) Event is created in Tbird: Yes
b) Event in Tbird shows attendee: No
c) Attendee receives email invitation: No
d) Event is synchronised i Gcalendar: Yes

**Comment by punkfrogab** [comment]
TB 91.3.0(64); Provider 91.0.2; OSX 12.0.1. Result same as above. Do you want me to run the test again and send log files, or do the existing log files suffice?

**Comment by punkfrogab** [comment]
TB 91.4.0(64); Provider 91.0.2; OSX 12.0.1. Same result. On the Provider pages you can set three Preferences which seem important for the function to work, but the settings don't get saved.

**Comment by kewisch** [comment]
Fixing that in #312. Stay tuned for a new release!

**Comment by kewisch** [comment]
Closing this for now, when the new release is out and this is not fixed please open a new issue.
