### ISSUE TITLE
No calendars appear after granting access to Google

### ISSUE THREAD

**Issue by dradtke** [kewisch/gdata-provider#28]
I've tried this with several different accounts, and I'm never able to get the list of calendars to populate, even though I've successfully logged in via the popup window and granted access to my account. One possible solution I've seen is to disable all other Google calendars, but I don't have any other ones set up, so that's not an option.

I enabled debug logging, and here's what I see in the error console:

```
Lightning: [calGoogleSession] Authentication failure: undefined gdataSession.jsm:282

[Exception... "null"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gdata-provider/modules/gdataSession.jsm :: login/authFailed< :: line 284"  data: no] gdataSession.jsm:284:33
    authFailed resource://gdata-provider/modules/gdataSession.jsm:284
    <anonymous> self-hosted:1007
    onPromptAuthAvailable resource://gdata-provider/modules/gdataSession.jsm:301
    onAccessTokenFailed resource://gdata-provider/modules/OAuth2.jsm:240
    onAccessTokenFailed self-hosted:1013
    onload resource://gre/modules/Http.jsm:77
```

The `NS_ERROR_FAILURE` is interesting to me because this is on Linux, specifically openSUSE Tumbleweed.

**Thunderbird / Lightning Version:** 68.1.2 (64-bit)
**Google Calendar Provider Version:** 68.0

**Comment by Greebodash** [comment]
I had the same problem, its apparently a compatibility issue between the new lightning version and Provider.

I followed this thread: https://groups.google.com/forum/#!topic/provider-for-google-calendar/7ySGzSgdMkE

And it worked for me TL;DR: Set TB 68.2 config setting "general.useragent.compatMode.firefox" to true and it should start working

**Comment by knighttoo** [comment]
Similar issues with yubikey but I was able to work around via the above config setting(Thanks Greebodash).

[Exception... "null"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gdata-provider/modules/gdataSession.jsm :: login/authFailed< :: line 284"  data: no] gdataSession.jsm:284:33
    authFailed resource://gdata-provider/modules/gdataSession.jsm:284
    <anonymous> self-hosted:1001
    onPromptAuthAvailable resource://gdata-provider/modules/gdataSession.jsm:301
    onAccessTokenFailed resource://gdata-provider/modules/OAuth2.jsm:240
    onAccessTokenFailed self-hosted:1007
    onload resource://gre/modules/Http.jsm:77
    openCalendarWizard resource://calendar/modules/utils/calWindowUtils.jsm:26
    doCommand chrome://calendar/content/calendar-common-sets.js:375
    goDoCommand chrome://global/content/globalOverlay.js:101
    oncommand chrome://messenger/content/messenger.xul:1

**Comment by dradtke** [comment]
Yep, I can confirm that that fixed the issue.

**Comment by Rinaldo-60** [comment]
Thanks, this fixed my issue as well.

**Comment by sgrossberndt** [comment]
Thanks, confirms the issue for me too on Ubuntu 19

**Comment by marzn** [comment]
Can confirm, that setting `general.useragent.compatMode.firefox = true` fixes the plugin on Win 10 / Thunderbird 68.2.1 / Lightning 68.2.0

**Comment by marzn** [comment]
I think it is the same issue like mentioned in #26

**Comment by christophetd** [comment]
> And it worked for me TL;DR: Set TB 68.2 config setting "general.useragent.compatMode.firefox" to true and it should start working

Thank you! Fixed the issue for me as well.

**Comment by kewisch** [comment]
This has been fixed in #23, the new version is pending review. The pref will work as well for the time being.

**Comment by ktomk** [comment]
Thanks for the report, it helped me solve the following issue:

Updating to Thunderbird 68.2 on Ubuntu with Chromium as Default Browser.

The Popup did open https://accounts.google.com/signin/v1/lookup which causes a 405 after entereng the password.

I then changed the Config Setting general.useragent.compatMode.firefox from false to true and restarted Thunderbird to trigger the login popup again.

With the new setting the login popup had a different visual identity and I could come over the first submission step only leading in the end to open in the Chromium browser the following URL:

https://accounts.google.com/signin/v2/challenge/password/empty

However this time the popup allowed to retry.

I did so. When a blank (sort of blank) page was shown I then put in my Yubikey and pressed it.

The Popup dialog website then continued.

I then could successfully continue with the login, setting up the app details

**Comment by newachu** [comment]
Thanks @Greebodash, setting `general.useragent.compatMode.firefox = true` fixed the issue and google calendars now appear and can be subscribed and synchronized normally. Didn't have to unsubscribe and re-add them.

Ubuntu 16.04 32bit
Thunderbird 60.9.0
Lightning 6.2.5
Provider for Google Calendar 4.4.2
