### ISSUE TITLE
Calendar access authorization cannot be completed for shared Google calendars.

### ISSUE THREAD

**Issue by cpuwzd** [kewisch/gdata-provider#281]
### Describe the problem and steps to reproduce it:
A recent Thunderbird update included an update for Google Provider.
I have at least three calendars: one in my name, one in my wife's name and a shared calendar on Google in which
we can both schedule events that involve both of us. This has been working perfectly for years.

Now when I start Thunderbird or perform certain calendar-related actions within Thunderbird, I am asked to authorize
access to my calendars for Google Provider. This happens sequentially for each calendar. The first day, I entered my
user name and password, but I didn't have my wife's password, so I had to abort the process. The second day, I entered
my wife's user name and password. Then it came up with a random looking account that appeared to be my shared
account. The long, random-looking account name ended with "@" and some Google domain. I don't know if I've associated
a password with this account, but I'm sure I've never logged into it manually. The calendar properties identify the account
as being accessed via the Google API.

### What happened?

I tried to use the forgot password option, but I didn't have a first and last name to enter in the form. Ultimately,
I aborted the registration.

### What did you expect to happen?

In a perfect world, nothing. However, given the constraints of privacy and security, I can understand why you might not
be able to pass the needed information from one software version to the next. I'm guessing that you are missing a use
case for shared accounts. You would need something similar to the procedure for offering to share a calendar with
write permission with a human user.

### Anything else we should know?

I'm a retired software developer. I volunteer on the WixTools project here on github.

**Comment by cpuwzd** [comment]
My wife and I both have access to our own calendars and each other's calendars. The problem is the shared calendar
that is created without an email-associated login. Even if this calendar weren't shared with my wife, I think that the issue
is still the same: It is the creation of an extra calendar that is visible both in Thunderbird and in Google Calendar. The mechanism exists to create such calendars, but we have now lost the ability to link the two environments.

Overall, I consider this a regression. There must be other users who have shared more than one calendar without creating
bogus email accounts to uniquely identify them.

**Comment by kewisch** [comment]
Sorry if I described this wrong. I am not suggesting you create a new google account or email. When you have unsubscribed from all calendars in Thunderbird as noted above and then re-subscribe to your own calendars, you should also see your wife's calendar in the list.

Maybe I am misunderstanding the situation though?
