### ISSUE TITLE
Event not displaying its status properly

### ISSUE THREAD

**Issue by jimmychu0807** [kewisch/gdata-provider#282]
First of all, thank you for working on this plugin. I made a small coffee contribution via paypal. This plugin is another reason why I am sticking on using Thunderbird.

### What happened?

I have a few event invites not confirmed yet, and a few I have declined. Before the Thunderbird upgrade in mid Oct, unconfirmed events have dotted border line, and declined events have a lighter color. 

After the recent Thunderbird upgrade to v91.2.0 (and also Provider for GCal, now 91.0.2), all events are shown as confirmed, even for declined and unconfirmed ones.

A minor feature request, is it possible to add a setting to hide declined events, not just making a lighter color?

---
Updated 20 mins later:

Hmm.... I just play around with the setting more. I might have imported my GCal previously using iCal link, instead of the provider. But is gdata-provider able to retrieve event status (unconfirmed invite, confirmed, declined) and display properly?

**Comment by jimmychu0807** [comment]
Actually I should clarify I am not talking about the event status confirmed or not. Those inviting events are confirmed to happen, but it is **my reply** toward those events. They could either be pending (I haven't replied), accepted (those I say yes to), and declined (those I say no to). But currently events shown is not distinguishing these three statuses. So all declined events are shown the same in the calendar.

**Comment by kewisch** [comment]
Likewise the attendee info should be in the debugging information. If you could grab that I'd appreciate.

**Comment by jimmychu0807** [comment]
This is the log for a cal event when having the two debugging flag on, with PII data redacted.

I am the one that declined the meeting.

```
[calGoogleCalendar] Logging calIEvent:
  id:3bgoi4s9lfpapqbn3d7hajqrgt_R20211028T133000@google.com
  created:2021/09/14 08:58:58 UTC isDate=0 nativeTime=1631609938000000
  updated:2021/10/27 22:00:31 UTC isDate=0 nativeTime=1635372031000000
  title:Event Update
  description:This is the EVENT DESCRIPTION
  transparency:null
  status:CONFIRMED
  startTime:2021/10/28 15:30:00 Europe/Berlin isDate=0 nativeTime=1635427800000000
  endTime:2021/10/28 16:00:00 Europe/Berlin isDate=0 nativeTime=1635429600000000
  location:null
  privacy:null
  sequence:1
  alarmLastAck:null
  snoozeTime:null
  isOccurrence: false
  Organizer: 
    ID: mailto:someone@email.addr
      Name: undefined
      Rsvp: null
      Is Organizer: yes
      Role: null
      Status: NEEDS-ACTION
  Attendees: 

    ID: mailto:someone1@email.addr
      Name: undefined
      Rsvp: null
      Is Organizer: no
      Role: REQ-PARTICIPANT
      Status: DECLINED

    ID: mailto:someone2@email.addr
      Name: First-name Last-name
      Rsvp: null
      Is Organizer: no
      Role: REQ-PARTICIPANT
      Status: NEEDS-ACTION

    ID: mailto:someone3@email.addr
      Name: First-name Last-name
      Rsvp: null
      Is Organizer: no
      Role: REQ-PARTICIPANT
      Status: ACCEPTED

  recurrence: yes: 
    RRULE:FREQ=WEEKLY;INTERVAL=2;BYDAY=TH
  Exceptions:

  alarms: yes: 
    
    Action: DISPLAY
    Offset: -PT10M
    alarmDate: null
    related: 1
    repeat: 0
    repeatOffset: null
    repeatDate: null
    description: null
    summary: null
    properties: yes:
      X-DEFAULT-ALARM:TRUE
```

**Comment by kewisch** [comment]
Re-reading I may have misunderstood your request. Do I understand correctly that you'd like to be able to hide declined events, and that they are shown regardless of status in the view?

What I am unsure about, for example declined events, are they shown exactly the same as accepted events (a bug?) or is there a visual difference while you'd prefer not to show the at all (feature).

Please see also https://bugzilla.mozilla.org/show_bug.cgi?id=1705056 which might resolve this, if I understood your request correctly I'm not sure it makes sense to add this in the provider and we should prefer fixing mentioned bug.

**Comment by jimmychu0807** [comment]
> Do I understand correctly that you'd like to be able to hide declined events, and that they are shown regardless of status in the view?

Yes.

> What I am unsure about, for example declined events, are they shown exactly the same as accepted events (a bug?) or is there a visual difference while you'd prefer not to show the at all (feature).

There is a visual difference, but I want to hide and forget about the event at all.

**Comment by kewisch** [comment]
Got it, thank you! In that case I'd defer to https://bugzilla.mozilla.org/show_bug.cgi?id=1705056 instead of special-casing this in the Provider. Thank you for taking the time to report this issue!
