### ISSUE TITLE
Event reminders (Notifications) by email can not be added to the calendar

### ISSUE THREAD

**Issue by lucky1luc** [kewisch/gdata-provider#285]
### Describe the problem and steps to reproduce it:

Thunderbird 91.2.1, gdata-provider 91.0.2. My Notifications for events are not longer emailing me, and the reminder/notification option has disappeared from the add notifcation dialog in Thunderbird. I can still add an email notification on the google calendar directly.

### What happened?
No email notification

### What did you expect to happen?
I wanted to add an email notification

### Anything else we should know?

![image](https://user-images.githubusercontent.com/33922423/138595395-7461a584-a518-4fea-9ace-0e805165fd55.png)

**Comment by lucky1luc** [comment]
TB 91.3.2 (64bit), Gprovider (91.0.2) same problem

**Comment by kewisch** [comment]
I've tried to reproduce this, but (un)fortunately it is working for me without issues. Do you get any error console messages?

**Comment by lucky1luc** [comment]
Do you mean that you do get the option in the drop down box to send e-mail? (Just like google does on it's calendar, add notification page?

**Comment by lucky1luc** [comment]
It used to work on the "old" thunderbird, but do not ask for the version number, as I do not remember.

**Comment by lucky1luc** [comment]
I do not see anything obvious in the error console: 

17:36:12.685 Calendar: [calStorageCalendar] Message: Error setting metadata for id calendar-properties!
Connection Ready: true
Last DB Error Number: 6
Last DB Error Message: database table is locked
Database File: D:\Thunderbird\Profiles\xeckzpz1.default\calendar-data\cache.sqlite
Last DB Statement: [object StatementJSHelper]
Last Statement param [0]: undefined
Last Statement param [1]: undefined
Last Statement param [2]: undefined
Last Statement param [cal_id]: undefined
Last Statement param [item_id]: undefined
Last Statement param [value]: undefined
Last Statement param [length]: 3
Exception: [Exception... "Component returned failure code: 0x8052000e (NS_ERROR_FILE_IS_LOCKED) [mozIStorageStatement.executeStep]"  nsresult: "0x8052000e (NS_ERROR_FILE_IS_LOCKED)"  location: "JS frame :: resource:///modules/CalStorageCalendar.jsm :: setMetaData :: line 2618"  data: no]
1: [resource:///modules/CalStorageCalendar.jsm:2725] logError
2: [resource:///modules/CalStorageCalendar.jsm:2626] setMetaData
3: [resource:///modules/CalDavCalendar.jsm:230] saveCalendarProperties
4: [resource:///modules/caldav/CalDavRequestHandlers.jsm:554] endDocument
5: [resource:///modules/caldav/CalDavRequestHandlers.jsm:61] handleResponse
CalStorageCalendar.jsm:2725
17:36:13.926 Calendar: [calCachedCalendar] replay action failed: <unknown>, uri=googleapi://myemail@gmail.com/?calendar=german__nl%40holiday.calendar.google.com, result=[object Object], operation=[object Object] 2 calCachedCalendar.js:346
21:28:52.091
Some cookies are misusing the recommended “SameSite“ attribute 2
21:36:15.134 Calendar: [calCachedCalendar] replay action failed: <unknown>, uri=googleapi://myemail@gmail.com/?calendar=german__nl%40holiday.calendar.google.com, result=[object Object], operation=[object Object] calCachedCalendar.js:346
21:38:54.942
XHRPOSThttps://api.login.yahoo.com/oauth2/get_token
[HTTP/1.1 200 OK 439ms]

21:39:37.923 window.controllers/Controllers is deprecated. Do not use it for UA detection. blank
21:39:45.766 Element.releaseCapture() is deprecated. Use Element.releasePointerCapture() instead. For more help https://developer.mozilla.org/docs/Web/API/Element/releasePointerCapture 2 menupopup.js:163:13
21:40:13.427 window.controllers/Controllers is deprecated. Do not use it for UA detection. blank
21:40:29.610 Element.releaseCapture() is deprecated. Use Element.releasePointerCapture() instead. For more help https://developer.mozilla.org/docs/Web/API/Element/releasePointerCapture 2 menupopup.js:163:13

​

**Comment by kewisch** [comment]
The NS_ERROR_FILE_IS_LOCKED error sounds familiar, though this is likely an issue with Thunderbird. Can you try:

1) quit Thunderbird
2) Go to `D:\Thunderbird\Profiles\xeckzpz1.default\calendar-data\` in windows explorer
3) Move cache.sqlite out of the way (you can probably delete it, but if you want to be on the safe side then keep a copy)
4) Start Thunderbird

Potentially you'll need to unsubscribe and re-subscribe to the Google Calendar as well.

**Comment by lucky1luc** [comment]
It seems to work now! Thank you very much! That is such a relieve!
