### ISSUE TITLE
Sign-in rate limit (Error 403: rate_limit_exceeded)

### ISSUE THREAD

**Issue by Kalobi** [kewisch/gdata-provider#288]
After the recent Thunderbird update to version 91.2.1, I was asked to sign in again. After signing in, I was told that the app has reached its sign-in rate limit and the developer has to increase it. The full message is as follows:

    Authorization Error
    Error 403: rate_limit_exceeded
    
    This app has reached its sign-in rate limit for now.
    
    Google limits how quickly an app can get new users. You can try signing in again later or ask the developer (provider-for-google-calendar@googlegroups.com) to increase this app's sign-in rate limit.
    
    If you are the developer for this app, you can request a sign-in rate limit increase.

These are the (censored) displayed request details:
    login_hint: <my email address>
    hl: en-GB
    response_type: code
    redirect_uri: urn:ietf:wg:oauth:2.0:oob:auto
    client_id: <maybe an identifying string?>.apps.googleusercontent.com
    access_type: offline
    scope: https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/tasks

**Comment by kewisch** [comment]
Google got back and increased the limit. We should be good here. Thank you all for hanging in. If you are enjoying the Provider I'd appreciate your support, check out the contribute button at https://addons.thunderbird.net/addon/provider-for-google-calendar/

**Comment by MD299** [comment]
Hi, today I start thunderbird 91.5.0, and I have the same issue (Sign-in rate limit (Error 403: rate_limit_exceeded)).
Thx for help...
MD

**Comment by elhennig** [comment]
> Hi, today I start thunderbird 91.5.0, and I have the same issue (Sign-in rate limit (Error 403: rate_limit_exceeded)). 

Same here with TB 96.0.2

**Comment by TBuyankovaWisercat** [comment]
Same here

**Comment by anatoliDeryshev** [comment]
same here, started TB and got this error....

**Comment by MarkWest2017** [comment]
Sadly issue seems to be back :( - Error 403: rate_limit_exceeded - running 91.5.0 on Windows 11
I did come across this seemingly related article - maybe it will help with a more permanent solution - https://stackoverflow.com/questions/48868737/rate-limit-exceeded-google-calendar
Kind Regards
Mark

**Comment by geertvandeweyer** [comment]
same here, running TB 91.5.0 on Ubuntu 20.04 , addon version 91.0.3.

**Comment by infospa** [comment]
Ok anche a me windows 10 thunderbird 91.5.0 (32 bit)

**Comment by depauw75** [comment]
It is back again....

**Comment by diplonics** [comment]
Seems back now....difference for me was I got a security alert email from google saying a windows machine was trying to access my account and once I authorised that security alert Thunderbird logged me in fine.

**Comment by EmEiBee** [comment]
... nope ...
It's note solved on my side. I can try it in an endless loop but ever get the same error again and again ...

**Comment by mfrosch** [comment]
Mhh, still have this issue on 91.5.0 (64-Bit).

**Comment by poul-erik** [comment]
Thunderbird 91.5.0 (32 bit - Windows 11)

I have 3 personal google calendars, they work OK, and 1 group calendar owned by another google account. The latter is not working, gives me the 403 error

**Comment by EmEiBee** [comment]
> Mhh, still have this issue on 91.5.0 (64-Bit).

... I'm talking about the PlugIn version and not about the TB version ...

After Update the **Plugin** to 91.0.4 all my systems works well with own,  group and shared calendars

**Comment by brb61** [comment]
Windows 10 Thunderbird 91.5.0 (64-bit).  Similar results to diplonics.  Start Thunderbird and get the Google login box.  Log in and respond to a verification prompt from Google on my phone.  Then get 403 error.  I then respond to the Google security alert e-mail, log into my Google account, verify myself again, and Calendar works.

**Comment by n33tfr33k** [comment]
> Start Thunderbird and get the Google login box. Log in and respond to a verification prompt from Google on my phone. Then get 403 error. I then respond to the Google security alert e-mail, log into my Google account, verify myself again, and Calendar works.

This process worked for me as well, Linux, TB version 91.5.0, Plugin version 91.0.4

**Comment by rhaimann** [comment]
Having the same issue. Started 1/23/2022.

**Comment by HgWing** [comment]
Having the same issue. Started 1/23/2022. Logging into Google and accepting security alert did not fix it.

**Comment by MartinX3** [comment]
Please stop commenting, if you have the same issue. Just subscribe to this issue ticket and wait for a solution.
You all are disturbing everyone who subscribed to this issue ticket.

**Comment by lenhodder** [comment]
I was able to resolve this (if it stays resolved...).  Do this at your own risk, and I welcome expert feedback if any of this doesn't make sense.

Steps, as best as I can recall now:
1. Log into your Google account via web browser, go to calendars and select the one that's causing problems.  Click the 3 vertical dots to the right and select Settings
![image](https://user-images.githubusercontent.com/40070071/150873843-15086aec-0531-426e-8a11-744472daf674.png)
2. Click Calendar Settings
3. Scroll down to the "Integrate Calendar" section, then down to "Secret address in iCal format".
![image](https://user-images.githubusercontent.com/40070071/150874290-142d4f4c-350d-4c8d-ad59-54e4ba816480.png)
4. Click the copy link to get the connection string.
5. In Thunderbird, File->New->Calendar
6. Select "on the network", next
7. Enter your email address and paste the clipboard into Location. Click Find Calendars.  Enter your Google password, etc.
8. Select the calendar from the list that comes up, then OK (or something like that... sorry - it's not in front of me anymore!)

I have now re-subscribed to the original calendar.  Next, I unsubscribed from the old one that was giving errors (in TB, right click the calendar, and unsubscribe).  I tested that events sync in both directions.

With this, do we even need the "Provider for Google Calendar" add-in?  I see a reviewer's comment for that add-in that says it's not needed any more?

Good luck!

**Comment by MartinX3** [comment]
@lenhodder That's the way how it works without the addon.
But this addon let's you use your main calendar and the shared ones, regardless of private or public and without the need to copy their links.

**Comment by daveymg-nz** [comment]
Updating the addon to 91.0.4 solved the login problem for me.

**Comment by jfabini** [comment]
Same issue is here again. The reason is imho that Ubuntu and Mint have finally rolled out the Thunderbird update 78.x to 91.x as part of the automated updates. The add-ons of millions of users worldwide all attempt to re-authenticate with Google and cause the impression of a DDoS. Perhaps someone should drop the guys at Google a note to weaken the restrictions for some days...

**Comment by arvendal** [comment]
I updated the addon to 91.0.4 (dated today) and it still works after restarting TB and rebooting pc. I also updated TB to 91.5.1.

**Comment by poul-erik** [comment]
Updated to TB 91.5.1.

Now all my calendars work OK

**Comment by Giosmile** [comment]
All ok, now! G. Inviato da Posta per Windows Da: poul-erikInviato: martedì 25 gennaio 2022 11:12A: kewisch/gdata-providerCc: Giosmile; CommentOggetto: Re: [kewisch/gdata-provider] Sign-in rate limit (Error 403: rate_limit_exceeded) (Issue #288) Updated to TB 91.5.1.Now all my calendars work OK—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by dralexk** [comment]
After updating TB to 91.5.1 the problem disappeared

**Comment by polak7gt** [comment]
> After updating TB to 91.5.1 the problem disappeared

It still doesn't work for me.

**Comment by Defcon0** [comment]
Same here, not working with tb 91.5.1 and plugin 91.0.4:

`403: rate_limit_exceeded`

**Comment by SteveLamberts** [comment]
Just updated to 91.5.1 and still have the same problem.

**Comment by MartinX3** [comment]
@kewisch please lock this issue as well

**Comment by jbr-it** [comment]
I have the same problem, thunderbird and plugin is up to date.

**Comment by wb2dyb** [comment]
Same problem.

**Comment by micklafisch** [comment]
same for me, All components are up2date but code 403 is showing.

**Comment by jfabini** [comment]
For me it worked on one PC, on the other it didn't so far. Some user comments posted to the add-on's homepage (https://addons.thunderbird.net/en-US/thunderbird/addon/provider-for-google-calendar/) identify the reason and possible solutions/workarounds - including a link to the author's statement on twitter: https://twitter.com/pkewisch/status/1485690970624643074?cxt=HHwWhMCy4Z6Enp4pAAAA

**Comment by svhadd** [comment]
Same for me. Sorry but I tend to look for another alternative. Things happen all the time that shouldn't happen in a productive environment, so that the complete functionality is no longer available. It then makes no difference for me as the end user whether the problem is with Google or with the plugin - it just doesn't work and I need time to work around it.

**Comment by menloperk** [comment]
What the heck is going on with this??? I have used thunderbird for many many years and now I get this strange 403 error "This app has reached its sign-in rate limit for now." Never had any issues but this is really very annoying!!!

**Comment by portablejim** [comment]
Seems that at least the main functionality can be found without the add on, for those wanting a work around. See https://support.mozilla.org/en-US/questions/1355356

**Comment by b-domenick** [comment]
I have two computers both running Fedora 35. The older machine is running the latest version on Fedora 35 which is tb 91.5.0 and provider 91.0.4 This combination works fine on that machine. On the newer machine running the same version of software it will never work since yesterday. I tried downgrading as well as manual non-repo upgrading to tb 91.5.1 with provider 91.0.4. It wouldn't work with either of these combinations.

**Comment by polak7gt** [comment]
It is working!

**Comment by MrSALSA** [comment]
Confirmed, for me it is also wirking again!

**Comment by b-domenick** [comment]
> I have two computers both running Fedora 35. The older machine is running the latest version on Fedora 35 which is tb 91.5.0 and provider 91.0.4 This combination works fine on that machine. On the newer machine running the same version of software it will never work since yesterday. I tried downgrading as well as manual non-repo upgrading to tb 91.5.1 with provider 91.0.4. It wouldn't work with either of these combinations.

Now like magic today it's working again and not a post from anyone why it failed to work for two day. In the end, I am running the same lower version of thunderbird that didn't work yesterday and the same provider version. It would be good to understand why so it doesn't happen again.

**Comment by daveymg-nz** [comment]
> . It would be good to understand why so it doesn't happen again.

It looks like an update was pushed out that caused the addon to have to sign back in to the Google calendar. Having many thousand installations of the addon all trying to do this around the same time caused google to reject the logins from the addon due to its login rate limit, hence the error everyone was receiving. I suspect the rate of logins has now dropped to a level where google is happy again.

**Comment by pi4630** [comment]
> > Start Thunderbird and get the Google login box. Log in and respond to a verification prompt from Google on my phone. Then get 403 error. I then respond to the Google security alert e-mail, log into my Google account, verify myself again, and Calendar works.
> 
> This process worked for me as well, Linux, TB version 91.5.0, Plugin version 91.0.4

This procedure didn't work for me. I've tried it several times. Most probably the success is because your attempt went under the access rate limit.

**Comment by b-domenick** [comment]
> > . It would be good to understand why so it doesn't happen again.
> 
> It looks like an update was pushed out that caused the addon to have to sign back in to the Google calendar. Having many thousand installations of the addon all trying to do this around the same time caused google to reject the logins from the addon due to its login rate limit, hence the error everyone was receiving. I suspect the rate of logins has now dropped to a level where google is happy again.

Thanks daveymg-nz , I was reinstalling and trying different combinations for quite some time yesterday. Happy to know the problem is understood.

**Comment by pi4630** [comment]
> I was able to resolve this (if it stays resolved...). Do this at your own risk, and I welcome expert feedback if any of this doesn't make sense.
> 
> Steps, as best as I can recall now:
> 
> 1. Log into your Google account via web browser, go to calendars and select the one that's causing problems.  Click the 3 vertical dots to the right and select Settings
>    ![image](https://user-images.githubusercontent.com/40070071/150873843-15086aec-0531-426e-8a11-744472daf674.png)
> 2. Click Calendar Settings
> 3. Scroll down to the "Integrate Calendar" section, then down to "Secret address in iCal format".
>    ![image](https://user-images.githubusercontent.com/40070071/150874290-142d4f4c-350d-4c8d-ad59-54e4ba816480.png)
> 4. Click the copy link to get the connection string.
> 5. In Thunderbird, File->New->Calendar
> 6. Select "on the network", next
> 7. Enter your email address and paste the clipboard into Location. Click Find Calendars.  Enter your Google password, etc.
> 8. Select the calendar from the list that comes up, then OK (or something like that... sorry - it's not in front of me anymore!)
> 
> I have now re-subscribed to the original calendar. Next, I unsubscribed from the old one that was giving errors (in TB, right click the calendar, and unsubscribe). I tested that events sync in both directions.
> 
> With this, do we even need the "Provider for Google Calendar" add-in? I see a reviewer's comment for that add-in that says it's not needed any more?
> 
> Good luck!

This worked for me. Thanks!
