### ISSUE TITLE
Addon not working in latest version

### ISSUE THREAD

**Issue by styler2go** [kewisch/gdata-provider#29]
The addon is not workign anymore since the latest update.

I constantly get a google login mask. Uninstalling and reinstalling made it even worse: I cannot select any calendar anymore.
![image](https://user-images.githubusercontent.com/2152144/68152841-ba4d5500-ff44-11e9-9273-55746824d1a3.png)

The selection mask stays blank:

![image](https://user-images.githubusercontent.com/2152144/68152875-cafdcb00-ff44-11e9-8293-4a15d442f417.png)

**Comment by kewisch** [comment]
This has been fixed in #23, the new version is pending review.

**Comment by styler2go** [comment]
It's not working in the latest update

**Comment by kewisch** [comment]
Can you confirm you are using the Provider version 68.2.1? Are you getting similar error console messages?

**Comment by styler2go** [comment]
Yes, i can confirm it's the 68.2.1 on Thunderbird 68.2.2

![image](https://user-images.githubusercontent.com/2152144/68416853-8f0d7480-0195-11ea-9624-1f2320977f8b.png)

**Comment by styler2go** [comment]
After disabling the firefox compat option again, it's working. Sorry for the confusion, i enabled the option because it was a recommendation in another issue.
