### ISSUE TITLE
Shared google agenda doesn't appear in available agendas since 91 version

### ISSUE THREAD

**Issue by naeldue** [kewisch/gdata-provider#293]
Hello.
As in the title, Shared google agendas doesn't appear in available agendas since 91 versions.
When I enter my google user name I have access to my owned calendars, but not those shared with me by other google users.
The feature was available in previous versions.
Can you please solve and let me know ?
Best regards.
Naël

**Comment by g-denis64** [comment]
Hi, I have exactly the same issue. On my collegue computer, she had just install the new 91 version of TB  last week and the sharing schedules are now disable.
It's working for her correctly on the website.
Thanks for all.
Best regards

G.DENIS

**Comment by kewisch** [comment]
@naeldue ah I see. If the calendars you see in the other calendars section are for example subscribed ICS calendars, they won't show in the API calls. If you want to verify, you could:

1) Go to https://developers.google.com/calendar/api/v3/reference/calendarList/list
2) In the right sidebar (may need to widen your window), click the "Execute" button (no other details necessary)
3) Authenticate
4) At the bottom right in the box with "200 OK", go through the entries. 

If your calendars don't show up there, the Provider won't be able to see them. If they do, we'll need to find out why they aren't showing in the Provider.

@splisp This looks more like a different issue. Can you file a new issue? If you are running Thunderbird 78, please upgrade to version 91.

**Comment by g-denis64** [comment]
Hi, 
Thank you for your answer. I try to read the entries in "200 OK". Calendars are available.
So, I try to create a new calendar, using the Google Account for login. 
All calendars are sync now.
In fact, a new login is maybe necessary to import once again all informations from the Google API. The update maybe"cut" existing links.

**Comment by naeldue** [comment]
Hello @kewisch 
I verified the list provided by google api, and the calendar shows up.  

Here is an extract of the result
 {
   "kind": "calendar#calendarListEntry",
   "etag": "\"1635271639334000\"",
   "id": "[email of the person who shared]",
   "summary": "Pro sido nael",
   "timeZone": "Europe/Paris",
   "summaryOverride": "Perso Sidonie et Naël",
   "colorId": "21",
   "backgroundColor": "#cca6ac",
   "foregroundColor": "#000000",
   "selected": true,
   "accessRole": "writer",
   "defaultReminders": [],
   "conferenceProperties": {
    "allowedConferenceSolutionTypes": [
     "hangoutsMeet"
    ]
   }

Best regards.
Naël

**Comment by naeldue** [comment]
Ok. It works fine now. Thanks for your help.
Br.
Naël
