### ISSUE TITLE
Cannot dismiss reminders

### ISSUE THREAD

**Issue by Sir-Lax** [kewisch/gdata-provider#297]
### Discussed in https://github.com/kewisch/gdata-provider/discussions/284

<div type='discussions-op-text'>

<sup>Originally posted by **Chris-Thom** October 22, 2021</sup>
I'm having an issue in that I cannot dismiss reminders. Also and maybe related to this is there is an exclamation point next to the calendar name and it says 'momentarily not available'. I have unsubscribed, restarted and resubscribed but I still get that message and cannot cancel reminders still.

What else do I need to do?
I'm using TB 91.2.1 (64-bit) & Provider 91.0.2</div>

**Comment by dik23** [comment]
I am also seeing this with events created by others

TB 78.14.0 (64-bit), provider 78.0.2, U20.04

**Comment by svenheiberg** [comment]
Same here: 91.2.1 (64-bit), provider 91.0.2

Just added my corporate Google account, it imported all the events and then I get the long list of past events with option to dismiss them. If I click the dismiss, then nothing happens, and the error looks like:

gdataCalendar.jsm:567

```
Calendar: [calGoogleCalendar] Organized meeting  failed:2147500037: {
 "error": {
  "errors": [
   {
    "domain": "calendar",
    "reason": "forbiddenForNonOrganizer",
    "message": "Shared properties can only be changed by the organizer of the event."
   }
  ],
  "code": 403,
  "message": "Shared properties can only be changed by the organizer of the event."
 }
}
```

I'm only attempting to dismiss a reminder, not to modify an event.

**Comment by svenheiberg** [comment]
Ok, after some digging around I found that this is already known issue: https://github.com/kewisch/gdata-provider/issues/274 closed with a comment "This is fixed on the main branch, but unfortunately I won't be able to backport this to the legacy branch. The old version pushes the whole event, the main branch will patch only changed properties."

The workaround was going into Thunderbird Preferences -> Calendar -> Uncheck Show missed reminders for writable calendars.

Are there any plans to release a non-legacy add-on version?

**Comment by kewisch** [comment]
Yes, there are plans. See #224. It is still a bit of work though :)

Thanks for digging this out!
