### ISSUE TITLE
Cannot enable Google Calendar after 2-Step Verification turned on

### ISSUE THREAD

**Issue by dncmrc** [kewisch/gdata-provider#308]
### Describe the problem and steps to reproduce it:

I turned on Google Calendar 2-Step Verification.

### What happened?

The add-on requires but does not accept anymore my password to enable my Google Calendar. Like the password was invalid or wrong.

### What did you expect to happen?

Nothing. My Google Calendar should have been working as before. It had been working for years with no glitches.

### Anything else we should know?

This is pretty annoying.

**Comment by kewisch** [comment]
I've tested this with company-provided SSO where it seem to work. Can you check your cookie settings in Thunderbird?

**Comment by dncmrc** [comment]
They are like this:
Remember websites: yes
Accept cookies: yes
Accept 3rd party cookies: yes
Keep until: they expire
Do not track: unchecked

**Comment by kewisch** [comment]
Do you get any error console messages worth noting? Is this with regular Google 2FA, or a company domain?

**Comment by dncmrc** [comment]
It is usual Google 2FA, no company domain, no VPN, etc.
I haven't been looking at the error console (I didn't even know there is one). Sorry, I'm not a GITHUB developer, just a regular user with IT and SW developer skills, of course.
I gave up. I disabled a few days ago Google 2-step verification and, as expected, the issue went away. Before of that I was able to reproduce the same issue on any PC I used Thunderbird with. The issue is still there.

**Comment by kewisch** [comment]
I've tested again on a normal Google account with 2FA enabled and could not reproduce. Can you try removing all entries in the password manager around gdata, unsubscribing from all calendars, re-subscribing to all calendars? You can also try clearing cookies in Thunderbird, maybe this helps additionally.
