### ISSUE TITLE
Overwrite warning in Thunderbird regarding an event that does not exist on either side anymore

### ISSUE THREAD

**Issue by k-risc** [kewisch/gdata-provider#31]
When Thunderbird/gdata-provider synchronize with the Google calendar, I receive a warning about an event that supposedly recently has been changed "on the server" as well.

The change on the Thunderbird/Lightning calendar side is a "delete", so the warning says that by deleting this entry, any change on the server would be lost.

If I open the Google calendar in a browser, I do not see that event there any more. My suspicion is that I deleted it on my smartphone, and then later, because Thunderbird hadn't yet synchronized and the event was still visible there, as well in Thunderbird.

The curious thing about this: The event is over a month old and was deleted (on either side, I think) back then. But the warnings only started appearing today.

If I chose "Delete anyway", then the warning disappears for the moment, but pops up the next time the calendar is synchronized. If I choose "Discard changes and reload", the warning disappears and immediately appears again. Clicking  "Discard changes and reload" repeatedly doesn't change this, the warning simply pops up immediately again.

As I cannot see the event in either calendar (TB/Lightning or Googe/Browser, or Android/Smartphone), I wouldn't know any way of getting rid of the warning.

I had an older version of the add-on, which I then updated to the latest version (4.4.2), with the problem persisting. TB version is 60.9.1.

Any idea how to get rid of this? Anbody else made a similar experience?

**Comment by suskozaver** [comment]
Settings, Calendar, Reminders, untick Show missed reminders for writable calendars. 

I had the same issue.

**Comment by suskozaver** [comment]
Adding source where I originally found this: https://superuser.com/questions/1207195/cannot-dismiss-certain-reminders-in-lightning-thunderbird

It's old, but it helped me.

**Comment by skywalker89** [comment]
HI, have this annoying issue too... but in TB68 the "setting" seems to not exist anymore ..  "
Unfortunately this solution does not work in the latest Thunderbird version because the setting does not exist anymore. – Carsten Schmitz Nov 6 at 11:58"  (https://superuser.com/questions/1207195/cannot-dismiss-certain-reminders-in-lightning-thunderbird) .... what version do you use?

Thx
Dan

**Comment by suskozaver** [comment]
TB 68.2.2, the setting is there: https://1drv.ms/u/s!AnoBuO2krSk44QLEpDQs4Odlj86y?e=KfZwKc

**Comment by jonathan-g** [comment]
I have a related problem: The event, from yesterday, exists on the Google calendar in the cloud, but every time I open Thunderbird, I get an unending series of dialogs telling me it's changed and do I want to save my version or discard it and reload from the server.  Whichever option I select, the same dialog, asking me about the same event pops up again, over and over and it never stops. 

This makes Thunderbird unusable with the Google Calendar Provider enabled.

I have unticked the "`Show missed reminders for writable calendars`" in the Thunderbird calendar options, but this **does not** stop the behavior.

I'm using Thunderbird 68.4.1

**Comment by kewisch** [comment]
The first part of this I think I will keep as a "feature". Of course it suggests itself to not show the conflict dialog if you are doing a delete and it is already deleted, but in theory, this should only occur within the 30 minutes sync time.

Technically, I get a 412 error in both the modify and delete case, so I'm not able to immediately see if the event was deleted server side. 

For the second part, with the reminders, this should be fixed on the `main` branch where I don't send the whole event during a change, but only what changed. This way you don't run into a conflict if all you did was dismiss a reminder on an invitation.
