### ISSUE TITLE
All attendees and invited users deleted when event changed in Thunderbird Calendar

### ISSUE THREAD

**Issue by MartinX3** [kewisch/gdata-provider#312]
91.2.0 here
I create a google calendar event with attendees.
I open it in thunderbird and I can see and edit everyone.
But if I save it in thunderbird, all attendees are removed.

(Created a new issue ticket, since https://github.com/kewisch/gdata-provider/issues/156 doesn't get reopened)

**Comment by rb1t** [comment]
See my comment at the bottom of #156 as well, re-pasting:

> Same experience for me. I did notice the following error in the console after hitting 'Send and close' on the event (after adding Attendees), not sure if related? #149

**Comment by balonik** [comment]
Same issue with extension version `91.0.2`

**Comment by kewisch** [comment]
Can you go into the add-on's preferences and let me know which checkboxes are checked? Checking all three should get you all the attendee options, but please test before you keep it on to avoid invitations being sent to people you didn't intend.

**Comment by MartinX3** [comment]
I activated now every checkbox.
They are deactivated by default and nothing hinted me to them.

**Comment by MartinX3** [comment]
@kewisch I see now that I can't activate the options.
Everytime I go back into the settings they are not checked anymore.

**Comment by kewisch** [comment]
Surprised this wasn't caught earlier, there was an issue on how settings are saved. I'll spin a new release with the settings fixed, this should also allow you to enable invitations.

**Comment by MartinX3** [comment]
@kewisch The option "Force use of plain text in event descriptions" still doesn't work.
