### ISSUE TITLE
Cannot dismiss reminders

### ISSUE THREAD

**Issue by peter-robert-idnow** [kewisch/gdata-provider#315]
in addition to the below discussion / description:
TB Lightning opens and loads / sychronizes with Google Calendar fine.
Reminders open and pop up
Try to close all / or selectively
Some reminders cannot be dismissed.
-> as soon this is attempted / done, the Calendar in Lighting calendar list gets an alert / exclamation mark next to it
Any synchronization through the provider continues to function, but the alert / ! mark stays.
The reminders (new ones appear) cannot be closed to the "cannot dismiss reminders"

Provider 91.0.2 last updated 26 Oct 2011 -> issue occurs since around this date.
TB version 91.3.0 32 bit
Win 10

### Discussed in https://github.com/kewisch/gdata-provider/discussions/284

<div type='discussions-op-text'>

<sup>Originally posted by **Chris-Thom** October 22, 2021</sup>
I'm having an issue in that I cannot dismiss reminders. Also and maybe related to this is there is an exclamation point next to the calendar name and it says 'momentarily not available'. I have unsubscribed, restarted and resubscribed but I still get that message and cannot cancel reminders still.

What else do I need to do?
I'm using TB 91.2.1 (64-bit) & Provider 91.0.2</div>

**Comment by wuntusk** [comment]
Same here. It's made the calendar unuseable unless I go into google calendar and delete any events I've been invited to by others after they occur.

**Comment by ericzolf** [comment]
Could it be the same issue as https://bugzilla.mozilla.org/show_bug.cgi?id=1736842 ?

**Comment by mthmulders** [comment]
I believe I am facing the same issue. Dismissing a reminder for an event that I was invited for (but that was not created by me) shows the following in the Thunderbird Error Console:

```
POST https://www.googleapis.com/calendar/v3/calendars/<my-google-id>/events/<a-very-long-string-of-letters-and-numbers
```

I captured the request body as well but it's full of personal info so I won't post that here; send a DM if you want to know about it.

The response to that call is:
```json
{
 "error": {
  "errors": [
   {
    "domain": "calendar",
    "reason": "forbiddenForNonOrganizer",
    "message": "Shared properties can only be changed by the organizer of the event."
   }
  ],
  "code": 403,
  "message": "Shared properties can only be changed by the organizer of the event."
 }
}
```

**Comment by mechanicjay** [comment]
I'm seeing the same thing, this is new with the update to TB 91.

**Comment by kewisch** [comment]
This is fixed on the main branch, but unfortunately I won't be able to backport this to the legacy branch. The old version pushes the whole event, the main branch will patch only changed properties. See #224 for progress on the rewrite.

**Comment by kewisch** [comment]
The workaround is, iirc, to disable the "show missed" option in Thunderbird.

**Comment by peci1** [comment]
@kewisch For those of us not familiar with your development process. What does `legacy` and `main` translate to regarding released/planned TB versions? Can we expect the fix to appear in 91.x anytime soon, or is it for a long run?

**Comment by kewisch** [comment]
Given I haven't had a chance to work on this lately, I don't suspect I will be able to complete the transition in the 91.x time frame.

**Comment by peci1** [comment]
Hmm, so I have to keep around a TB78 copy just to dismiss reminders? Thanks Ubuntu for its slow pace at getting TB updates =)

**Comment by matthbakeredb** [comment]
> The workaround is, iirc, to disable the "show missed" option in Thunderbird.

This worked for me, thanks!

**Comment by kewisch** [comment]
> Hmm, so I have to keep around a TB78 copy just to dismiss reminders? Thanks Ubuntu for its slow pace at getting TB updates =)

If it worked in 78 then it was a coincidence, this was always an issue. The original issue is #3 and respective bug linked there. Hope the workaround works for you as well!

**Comment by pryorda** [comment]
Is there a fix coming in the soonish future?

**Comment by pryorda** [comment]
> I switched to TbSync with "Provider for CalDAV & CardDAV" and have had no problems at all with authentication or synchronization both ways.  It does require adding a line to the Config Editor in order to recognize the Google calendar, but after several weeks now, it has worked flawlessly. On 2/23/2022 7:21 PM, Daniel Pryor wrote: Is there a fix coming in the soonish future? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[#315 (comment)](https://github.com/kewisch/gdata-provider/issues/315#issuecomment-1049398464)", "url": "[#315 (comment)](https://github.com/kewisch/gdata-provider/issues/315#issuecomment-1049398464)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

Ill take a look at it

**Comment by mhalano** [comment]
@kewisch the latest release fot Thunderbird 102 is considered legacy branch?

**Comment by cgr71ii** [comment]
This issue hasn't been solved in the last thunderbird release... it will be solved, @kewisch ?
