### ISSUE TITLE
Add an option to force use of plain text for descriptions

### ISSUE THREAD

**Issue by glda19** [kewisch/gdata-provider#316]
![Screenshot_20211115-172212](https://user-images.githubusercontent.com/45542607/141821489-fa478c3f-a7d3-42f3-9067-9700b03ca034.png)
![Screenshot_20211115-172212](https://user-images.githubusercontent.com/45542607/141821512-4619078b-2c43-4c72-afb3-cc80f368f61f.png)
![Screenshot_20211115-171216](https://user-images.githubusercontent.com/45542607/141821515-5dac19b8-0415-4c39-99ce-060dc214933d.png)
### Describe the problem and steps to reproduce it:
When i make a new event in the calendar of thunderbird and fill in the discription
On firefox last verdersion and the app onecalendar on android 11 i the the description as follow
<body>
<div>xvdgshn<br>
fghdfh<br>

</body>
(Please include as many details as possible.)

**Comment by kewisch** [comment]
Yeah, the current mechanism is super fragile. There was a change in Thunderbird to a HTML description, and in addition Google's description field is html-but-sometimes-plain-text. I can see if I can tweak the logic a bit, but unfortunately it would be very difficult to fully work around Thunderbird.

Can you check what it looks like in the deskop version of the google calendar website?

**Comment by glda19** [comment]
When I use the google calender website it works fine.
From which program do I check it in the desktop version

⁣Mvg Glenn Daelman

Op 20 nov. 2021 21:09, om 21:09, Philipp Kewisch ***@***.***> schreef:

**Comment by glda19** [comment]
I want for a program I made also a connection to google galendar.
How can l do that? Wat do I need to setup the connection?

⁣Mvg Glenn Daelman ​

Op 20 nov. 2021 21:09, om 21:09, Philipp Kewisch ***@***.***> schreef:

**Comment by kewisch** [comment]
I've also tried to reproduce this and it is working fine for me. With desktop version I mean checking what the event looks like when you go to calendar.google.com on a computer instead of a mobile device, so it doesn't load the mobile view.

**Comment by glda19** [comment]
Id dont uderstand you. In google it looks fine. But in onecalendar there is see the html tags. One desktop version and android

⁣Mvg Glenn Daelman ​

Op 2 jan. 2022 21:42, om 21:42, Philipp Kewisch ***@***.***> schreef:

**Comment by kewisch** [comment]
Ok, I see. So this is mostly an issue that onecalendar needs to fix. They need to work around the quirks of Google Calendar where the description field can both be html and plain text. 

I might add an option to force use of plain text, but note enabling that might cause some issues with invitations received.

**Comment by glda19** [comment]
Thnx
Can you helpme a bit. Amy looking for a wile how I can make a connection  to a google by vb.net ore c#. I have looked in de documentation but I'd don't now how to do it?

⁣Mvg Glenn Daelman ​

Op 2 jan. 2022 23:15, om 23:15, Philipp Kewisch ***@***.***> schreef:

**Comment by kewisch** [comment]
Unfortunately I don't have experience with the Google APIs for other platforms. You can always directly use REST calls. This is off topic for the issue though, would appreciate if we could keep this issue for providing the plain text descriptions.
