### ISSUE TITLE
Please provide a way to completely disable sending email on behalf of the user unless explicitly requested

### ISSUE THREAD

**Issue by akorn** [kewisch/gdata-provider#32]
Steps to reproduce:

I wanted to copy events from one remote calendar into another. Following advice I found on the web, I exported it into an ICS file, then imported that ICS file and selected a Google calendar as the destination.

I also deleted some events from the Google calendar using the context menu's "delete event" entry.

Actual results:

The import partially succeeded, and Thunderbird spammed all attendees of all imported events with new invites.

When I deleted some events from one of the two calendars, Thunderbird cancelled the events on my behalf, again spamming the other attendees and sowing confusion.

It was royally embarrassing.

Expected results:

When importing the calendar, my intention was not to create new events and send new invites, just to rearrange my records of existing events. When I selected "delete event" from the context menu, my intention was not to cancel the event, just to remove my own record of it from one of the places where that record existed.

Thunderbird should not send any email on behalf of the user without the user explicitly requesting it; if you think that it should send such emails by default, at least there should be a way to disable this "loose cannon" behaviour.

While searching for solutions to this issue on the web I came across several reports from people who wanted to do something similar: use their calendars to keep track of their appointments, but not automatically notify anyone of changes they made to their calendar.

Looking through the preferences and the config editor (and indeed the web), I found no obvious way of disabling this behaviour.

I'm now afraid to use Thunderbird for calendaring because I have no way of knowing which UI actions will cause it to send unwanted email to other event participants.

I don't know how much of this is up to the gdata-provider extension and how much to Thunderbird itself; I filed a similar bug against Thunderbird: https://bugzilla.mozilla.org/show_bug.cgi?id=1597327.

**Comment by Belaial** [comment]
I recently experienced the same issue. Moved a Event between the integrated Thunderbird calendar to my Google calendar only to find myself spamming invites to all attendees.

I did not export / import as ICS tho, I just edited a few events manually but the results are the same.

**Comment by kewisch** [comment]
There are options to do this, I will be surfacing them better in Provider 91.0.2
