### ISSUE TITLE
On event creation, invited attendees are removed from the specified attendees list (because of gdata-provider internal failures and/or googleapis request failures) 

### ISSUE THREAD

**Issue by dsauvage** [kewisch/gdata-provider#320]
- Using Ubuntu 18.04 LTS, Thunderbird 78.14.0 (64-bit), Provider for Google Calendar [78.0.2]
- Calendar is not read-only

**Reproducer**
1. Using Thunderbird calendar, click on a calendar slot in order to create a calendar event
2. Select "Invite attendees" and add a valid email
3. Select "Save and close"
4. On your Thunderbird calendar, open the event
5. Notice that the list of invited attendees is empty

**Preliminary investigation**
1. Open the Thunderbird Error Console using the menu "Tools > Developer Tools > Error Console"
2. Using Thunderbird calendar, click on a calendar slot in order to create a calendar event
3. Select "Invite attendess"
    The following output is displayed in the Error Console:
```
Lightning: [calGoogleRequest] Requesting POST https://www.googleapis.com/calendar/v3/freeBusy gdataRequest.jsm:206
Lightning: [calGoogleCalendar] Setting Upload Data (application/json; charset=UTF-8):
{"timeMin":"2021-11-18","timeMax":"2021-11-23","items":[{"id":"your@email.com"}]} gdataRequest.jsm:273
Lightning: [calGoogleRequest] Clock skew is 1 seconds gdataRequest.jsm:376
Lightning: [calGoogleCalendar] Request POST https://www.googleapis.com/calendar/v3/freeBusy responded with HTTP 400 gdataRequest.jsm:383
Lightning: [calGoogleCalendar] A request Error Occurred. Status Code: 400 Bad Request Body: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "badRequest",
    "message": "Bad Request"
   }
  ],
  "code": 400,
  "message": "Bad Request"
 }
}
gdataRequest.jsm:534
Lightning: [calGoogleCalendar] Failed freebusy request: [Exception... "A request Error Occurred. Status Code: 400 Bad Request Body: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "badRequest",
    "message": "Bad Request"
   }
  ],
  "code": 400,
  "message": "Bad Request"
 }
}
"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://gdata-provider/legacy/modules/gdataRequest.jsm :: fail :: line 232"  data: no] gdataSession.jsm:562
Lightning: [calGoogleCalendar] Freebusy query for mailto:your@email.com failed (2147746065): null gdataSession.jsm:480
NS_ERROR_NOT_AVAILABLE: 
```
4. Add the invited attendee email and hit enter 
    The following output is displayed in the Error Console:
```
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIAutoCompleteInput.popup] LoginManagerChild.jsm:174
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIAutoCompleteInput.popup] LoginManagerChild.jsm:174
Lightning: [calGoogleRequest] Requesting POST https://www.googleapis.com/calendar/v3/freeBusy gdataRequest.jsm:206
Lightning: [calGoogleCalendar] Setting Upload Data (application/json; charset=UTF-8):
{"timeMin":"2021-11-18","timeMax":"2021-11-23","items":[{"id":"invited-attendee@gmail.com"}]} gdataRequest.jsm:273
Lightning: [calGoogleCalendar] Request POST https://www.googleapis.com/calendar/v3/freeBusy responded with HTTP 400 gdataRequest.jsm:383
Lightning: [calGoogleCalendar] A request Error Occurred. Status Code: 400 Bad Request Body: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "badRequest",
    "message": "Bad Request"
   }
  ],
  "code": 400,
  "message": "Bad Request"
 }
}
gdataRequest.jsm:534
Lightning: [calGoogleCalendar] Failed freebusy request: [Exception... "A request Error Occurred. Status Code: 400 Bad Request Body: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "badRequest",
    "message": "Bad Request"
   }
  ],
  "code": 400,
  "message": "Bad Request"
 }
}
"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://gdata-provider/legacy/modules/gdataRequest.jsm :: fail :: line 232"  data: no] gdataSession.jsm:562
Lightning: [calGoogleCalendar] Freebusy query for mailto:invited-attendee@gmail.com failed (2147746065): null gdataSession.jsm:480
```
5. Click on the Invite attendee dialog "ok" button
6. Click on "Save and Close"
    The following output is displayed in the Error Console:
```
Lightning: [calGoogleCalendar] Adding regular event ert gdataCalendar.jsm:409
Lightning: [calGoogleRequest] Requesting POST https://www.googleapis.com/calendar/v3/calendars/your@email/events gdataRequest.jsm:206
Lightning: [calGoogleCalendar] Setting Upload Data (application/json; charset=UTF-8):
{"start":{"dateTime":"2021-11-18T17:00:00","timeZone":"Indian/Mauritius"},"end":{"dateTime":"2021-11-18T18:00:00","timeZone":"Indian/Mauritius"},"summary":"ert","reminders":{"overrides":[],"useDefault":true}} gdataRequest.jsm:273
Uncaught 
Exception
​columnNumber: 0
​data: null
​filename: "chrome://lightning/content/lightning-item-iframe.js"
​lineNumber: 487
​location: XPCWrappedNative_NoHelper { QueryInterface: QueryInterface(), filename: Getter, name: Getter, … }
​message: "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIObserverService.removeObserver]"
​name: "NS_ERROR_ILLEGAL_VALUE"
​result: sdfsdf
​stack: "onEventDialogUnload@chrome://lightning/content/lightning-item-iframe.js:487:16\nonunload@chrome://lightning/content/lightning-item-iframe.xhtml:1:1\n"
​<prototype>: ExceptionPrototype { toString: toString(), name: Getter, message: Getter, … }
lightning-item-iframe.js:487
Lightning: [calGoogleCalendar] Request POST https://www.googleapis.com/calendar/v3/calendars/your@email/events responded with HTTP 200 gdataRequest.jsm:383
Lightning: [calGoogleCalendar] Parsing entry:
{
 "kind": "calendar#event",
 "etag": "\"sdfsdf\"",
 "id": "sdfsdf",
 "status": "confirmed",
 "htmlLink": "https://www.google.com/calendar/event?eid=qsdqsdqsdqsdqsd",
 "created": "2021-11-18T12:39:57.000Z",
 "updated": "2021-11-18T12:39:57.618Z",
 "summary": "ert",
 "creator": {
  "email": "your@email",
  "self": true
 },
 "organizer": {
  "email": "your@email",
  "self": true
 },
 "start": {
  "dateTime": "2021-11-18T17:00:00+04:00",
  "timeZone": "Indian/Mauritius"
 },
 "end": {
  "dateTime": "2021-11-18T18:00:00+04:00",
  "timeZone": "Indian/Mauritius"
 },
 "iCalUID": "qsdqsdqs@google.com",
 "sequence": 0,
 "reminders": {
  "useDefault": true
 },
 "eventType": "default"
}
gdataLogging.jsm:16
Lightning: [calGoogleCalendar] Adding ert succeeded gdataCalendar.jsm:451
```
Thanks for this great plugin, do not hesitate if further tests/logs are needed
Cheers

**Comment by kewisch** [comment]
The error messages are a red herring I believe. Can you open the add-on's preferences and fiddle with the three checkboxes? Everything on should make attendees work, though no guarantees that it won't send invitations in cases where it shouldn't.

**Comment by dsauvage** [comment]
Apologize I do not understand where are located the three check-boxes to fiddle with.

1. in Tools > Adds-ons > Extensions > Provider for  Google Calendar  > Details
There only checkboxes are only **Allow automatic updates**    x Default - On - Off
2. Reading the [FAQ](https://github.com/kewisch/gdata-provider/wiki/FAQ#why-cant-i-configure-any-options-in-the-extension-manager), are you referring to the Config Editor Boolean parameters **calendar.google.useHTTPMethodOverride**, **calendar.google.sendEventNotifications** and **calendar.google.enableAttendees** ?
Currently none exists in the Config Editor.
3. When I add the **calendar.google.enableAttendees** Boolean parameter and set it to true, it is present in the registry, but when I restart Thunderbird it is no more present

Thanks

**Comment by samueltardieu** [comment]
@dsauvage Tools > Adds-ons > Extensions > Provider for Google Calendar > Settings (or Preferences, the tab right to Details)

**Comment by samueltardieu** [comment]
Adding those two lines in `pref.js`

```js
user_pref("calendar.google.enableAttendees", true);
user_pref("calendar.google.sendEventNotifications", true);
```

checked those two checkboxes and seem to have solved the problem for me. But that should not be necessary.

**Comment by dsauvage** [comment]
> @dsauvage Tools > Adds-ons > Extensions > Provider for Google Calendar > Settings (or Preferences, the tab right to Details)

Hi Samuel,
Great to here from you !

In Thunderbird 78.14.0 (64-bit) Provider for Google Calendar [78.0.2], there is no such "Settings" or "Preferences" tab

Cheers

**Comment by dsauvage** [comment]
> Adding those two lines in `prefs.js`
> 
> ```js
> user_pref("calendar.google.enableAttendees", true);
> user_pref("calendar.google.sendEventNotifications", true);
> ```
> 
> checked those two checkboxes and seem to have solved the problem for me. But that should not be necessary.

This work-around does not work in my case. 

@samueltardieu It is recommended that you add your custom settings in `user.js`, otherwise they will be removed next-time you close Thunderbird.

Cheers

**Comment by tarikgraba** [comment]
@dsauvage It seems that those options appeared only  in version 91.0.2 (https://github.com/kewisch/gdata-provider/releases/tag/v91.0.2)

**Comment by kewisch** [comment]
Please see #312, there was an issue with the options in the preferences. Will release a new version with this fixed soon.
