### ISSUE TITLE
Settings are not saved and checkboxes stay unchecked

### ISSUE THREAD

**Issue by samueltardieu** [kewisch/gdata-provider#323]
### Describe the problem and steps to reproduce it:

Using Thunderbird 91.3.2 on ArchLinux and version 91.0.2 of this extension. Checkboxes in the addon preferences don't stay checked, and the options don't appear in the configuration editor.

### What happened?

None of the three checkbox stay checked once you leave the settings screen. I can't find the corresponding options such as `calendar.google.sendEventNotifications` in the configuration editor either.

### What did you expect to happen?

I would expect my preferences to be taken into account, and I would expect them to appear in the configuration editor.

### Anything else we should know?

Setting those preferences in `prefs.js` makes them stay checked and appear in the configuration editor.

**Comment by ARAR5000** [comment]
Hello, same issue.  It is not possible to keep the checkbox active.
Original issue: 
There is no way to setup the meeting with google calendar:
- impossible to remove notification of meeting which are accepted through google calendar
- impossible to accept or refuse a meeting through thunderbird

**Comment by kewisch** [comment]
Thank you, fixed this in #312
