### ISSUE TITLE
Provide xpi for thunderbird 60

### ISSUE THREAD

**Issue by simonschaufi** [kewisch/gdata-provider#35]
I have ubuntu 18 and the latest official release is thunderbird 60. I found there is no compatible working addon version available for tb 60. I guess the latest version contains a lot of bug fixes (the only compatible version (4.4.2) of this addon doesn't work because of constant google login attempts)

**Comment by PCMedic67** [comment]
Same problem here.  I start TB 60.9.1 and it prompts for UN & PW then allow.  I have to do this every time an it isn't loading all calendar entries.  Seemingly from some date on.  Is a fix coming for this? Everybody says get off of v59 but there are major pieces like this that don't work in v60 or v68.

**Comment by simonschaufi** [comment]
I updated to 68.4 and since the latest version works fine with TB 68.4, I don't need it any more.
