### ISSUE TITLE
"No writeable calendars are configured for invitations, please check the calendar properties"

### ISSUE THREAD

**Issue by MattWeatherford** [kewisch/gdata-provider#351]
### Describe the problem and steps to reproduce it:
Received an email invitation to a meeting - but gdata-provider says "No writeable calendars are configured for invitations, please check the  calendar properties"

note that my email address "mbw@uw dot edu" was not included in the recipient list, could that be the problem? The organizer invited a mailing list called "csde_staff@uw dot edu" of which I am a member. 

My google calendar for mbw@uw.edu is indeed writeable
I don't quite get how this plugin processes invitations to figure out which calendar meeting invites should land in   - would be interested to hear more. I didn't see any "Use this calendar by default" setting anywhere. I didn't see any "invitation" related preference anywhere.

I also didn't understand the preferences in the 2nd screen shot & what they mean / are for

(Please include as many details as possible.)

### What happened?
Received an email invitation to a meeting - but gdata-provider says "No writeable calendars are configured for invitations, please check the  calendar properties"

### What did you expect to happen?
I expected it to be added to my mbw@uw.edu google calendar

### Anything else we should know?

I do see calendar events - they seem to be syncing

I turned on "calendar.debug.log.verbose" and "calendar.debug.log" but didn't see anything in there
I restarted the application after setting the preference.

screenshot attached

-->
![Screen Shot 2022-01-05 at 7 47 38 PM](https://user-images.githubusercontent.com/12401873/148326223-6b36cc4b-d717-42c6-a5c1-225903e50d02.png)
![Screen Shot 2022-01-05 at 8 04 22 PM](https://user-images.githubusercontent.com/12401873/148326796-dae6a1ca-6909-45d1-a11a-d9eac284ea1b.png)

**Comment by mat-hew1** [comment]
I have the same problem and the settings for "Provider for Google Calendar" are not saved. Especially the "Enable email scheduling" checkbox.
And my email address was part of the recipient list!

**Comment by melish** [comment]
@MattWeatherford @mat-hew1 Have you seen [this comment](https://github.com/kewisch/gdata-provider/issues/63#issuecomment-939404271)?

**Comment by kewisch** [comment]
Enabling the settings should be fixed with version 91.0.4, can you give that one a try?

**Comment by Mister-A** [comment]
I confirm re-enabling the email scheduling setting in 91.4.0 has resolved this for me. Thanks @kewisch.

**Comment by kewisch** [comment]
Thank you for confirming @Mister-A ! I'm going to close this, @MattWeatherford i this is still an issue feel free to create a new one.

**Comment by ChauhanT** [comment]
Hi, 

I encountered the same error (I am using the plugin "Provider for Google Calendar")  and am looking for a solution. I have multiple calendars defined with the same google a/c, and I can't seem to find the option to choose one of them as the writeable calendar for adding events from an email (like a Teams invitation). Has anyone got some useful advice/suggestions/links? 

I have googled this quite a bit, and have most likely read all the links from the first few google and duckduckgo pages (the ones shown to me).

If this is the not the proper forum for this sort of thing, please let me know and I will remove the comment!

Cheers
