### ISSUE TITLE
Can't dismiss reminder for event with a different organizer

### ISSUE THREAD

**Issue by blu28** [kewisch/gdata-provider#352]
### Describe the problem and steps to reproduce it:

I bought a ticket through the service Eventbrite (http://eventbrite.com). It sent me my digital tickets via email. The email included a series of links that looked like this:

Wednesday, January 5, 2022 from 7:00 PM to 8:00 PM (EST)
Add to    Google     ·      Outlook     ·     iCal   ·     Yahoo

The link marked Google was this:
https://clicks.eventbrite.com/f/a/ejip9TSI4pG03SBd3yFXxg~~/AAQxAQA~/RgRjlRGAP0SvaHR0cHM6Ly93d3cuZXZlbnRicml0ZS5jb20vY2FsZW5kYXIuaWNzP3V0bV9jYW1wYWlnbj1vcmRlcl9jb25maXJtJnV0bV9tZWRpdW09ZW1haWwmcmVmPWVlbWFpbG9yZGNvbmYmZWlkPTIyNDg2NTM5NzQ1NyZ1dG1fc291cmNlPWV2ZW50YnJpdGUmdXRtX3Rlcm09Z29vZ2xlY2FsJmNhbGVuZGFyPWdvb2dsZVcDc3BjQgphswDes2GY9j5FUhNicmlhbkB1dHRlcmJhY2sub3JnWAQAAAAA

Clicking the link added the event to my Google Calendar.

### What happened?

The event came and I attended. When I came back, I found my reminder dialog for the event was up. I clicked "Dismiss All" but nothing happened. I closed the window and continued, but shortly the reminder came up again. I was unable to get either the "Dismiss" or "Dismiss All" buttons to do anything. 

### What did you expect to happen?

Pressing "Dismiss All" should make the reminder go away and not come back.

### Anything else we should know?

I looked at the error console and found this error:

Calendar: [calGoogleCalendar] Modifying item Wood Shop Orientation & Safety failed:2147500037: {
 "error": {
  "errors": [
   {
    "domain": "calendar",
    "reason": "forbiddenForNonOrganizer",
    "message": "Shared properties can only be changed by the organizer of the event."
   }
  ],
  "code": 403,
  "message": "Shared properties can only be changed by the organizer of the event."
 }
}

So, what has happened is that the link I pressed did not create a new event in my calendar, but rather shared an existing event to my calendar as an attendee. This seems like the right thing since the organizer might add or change details. But since it is not my event the extension cannot write to it to indicate that the reminder has been dismissed. I wanted the information in the event, so I copied the details, deleted it and then re-added myself, creating a copy owned by me.

**Comment by kewisch** [comment]
This should be fixed on `main`, but unfortunately I won't be able to release soon. See #3
