### ISSUE TITLE
Oauth access token not saved

### ISSUE THREAD

**Issue by jinnko** [kewisch/gdata-provider#353]
### Describe the problem and steps to reproduce it:

Similar to reports in https://github.com/kewisch/gdata-provider/issues/161 I am always presented with the Oauth2 login on startup.

I have done the following to try to resolve this:

1. Checked the preferences relating to cookies are all set to allow all cookies.
2. As suggeted in some comments on https://github.com/kewisch/gdata-provider/issues/161, uninstalled the addon, shutdown TB, start TB (and see no Oauth2 prompt), then re-install addon and complete the Oauth2 flow.  Finally shutdown TB and start it up again and I'm prompted with the Oauth2 flow again.
3. Confirmed that `Don’t ask again on this device` is checked during the Oauth2 flow.

### What did you expect to happen?

I expect the auth to be remembered such that the Oauth2 flow isn't necessary on every startup.

### Anything else we should know?

- Thunderbird 91.4.1 (64-bit) on linux
- Provider for Google Calendar 91.0.2

After enabling debugging, Noticed the following (among other things) in the error console (`**` on lines mine for emphasis)

```
Calendar: [calGoogleSessionManager] Creating session redacted gdataSession.jsm:88
Calendar: [calGoogleSessionManager] Reusing session redacted 2 gdataSession.jsm:86
Calendar: Couldn't find /freeassociation.sourceforge.net/Europe/London 4 CalTimezoneService.jsm:206
Unknown Collection "thunderbird/query-stripping" RemoteSettingsClient.jsm:160
    UnknownCollectionError resource://services-settings/RemoteSettingsClient.jsm:160
    sync resource://services-settings/RemoteSettingsClient.jsm:501
    InterpretGeneratorResume self-hosted:1482
    AsyncFunctionNext self-hosted:692
Calendar: Couldn't find /freeassociation.sourceforge.net/Europe/London 2 CalTimezoneService.jsm:206
ReferenceError: module is not defined punycode.js:440:1
    <anonymous> moz-extension://e419583f-592d-464e-b86d-c14ac62f5138/punycode/punycode.js:440
...
No chrome package registered for chrome://sendtocategory/content/category_tools.js 2
...
Calendar: Couldn't find /freeassociation.sourceforge.net/Europe/London 3 CalTimezoneService.jsm:206
...
Calendar: Couldn't find /freeassociation.sourceforge.net/Europe/London 2 CalTimezoneService.jsm:206
Calendar: [calCachedCalendar] Doing changelog based sync for calendar googleapi://redacted/?calendar=redacted%40import.calendar.google.com calCachedCalendar.js:340
**Calendar: [calGoogleSession] Token expired 1641484927 seconds ago, resetting gdataSession.jsm:388**
**Calendar: [calGoogleCalendar] Logging in session redacted gdataSession.jsm:266**
**Calendar: [calGoogleCalendar] No access token for redacted, refreshing token gdataSession.jsm:347**
Calendar: [calGoogleSession] Adding item https://www.googleapis.com/calendar/v3/users/me/calendarList…redacted%40import.calendar.google.com to queue gdataSession.jsm:407
Calendar: [calGoogleSession] Adding item https://www.googleapis.com/calendar/v3/calendars/redacted%40import.calendar.google.com/events to queue gdataSession.jsm:407
```

**Comment by jinnko** [comment]
I'm now unable to authenticate at all, with the following 403 API Rate Limit Exceeded message since 2 days.

> Authorisation Error
>
> Error 403: rate_limit_exceeded
>
> This app has reached its sign-in rate limit for now.
>
> Google limits how quickly an app can get new users. You can try signing in again later or ask the developer (provider-for-google-calendar@googlegroups.com) to increase this app's sign-in rate limit.
>
> If you are the developer for this app, you can request a sign-in rate limit increase.

**Comment by kewisch** [comment]
The 403 error is covered in #373. Let's wait until this cools down and then check if the original issue still occurs.

**Comment by AJJLagerweij** [comment]
I have the same issue, now that the 403 error issue cooled down, I get prompted for my calendar account login every startup of thunderbird.

**Comment by zhum** [comment]
I have to do F2A auth every time I start thunderbird. I set "remember me on this device" on, but it doesn't help...

**Comment by kewisch** [comment]
@jinnko is this still an issue for you? 

@zhum have you tried re-subscribing to the calendars? Would appreciate any logging you have that might help identify the cause.

**Comment by jinnko** [comment]
@kewisch - I actually fell back to the native support in TB and that has been good enough.  Sorry I can't be more help.

**Comment by kewisch** [comment]
Ah no worries, that is fine. Glad you have something working, thanks for taking the time to report!
