### ISSUE TITLE
Synch

### ISSUE THREAD

**Issue by philips791** [kewisch/gdata-provider#355]
### Discussed in https://github.com/kewisch/gdata-provider/discussions/350

<div type='discussions-op-text'>

<sup>Originally posted by **philips791** January  5, 2022</sup>
I am having issues with synchronizing using your add-on between my Google calendar and my Thunderbird calendar.  I am running v91.4.1 of Thunderbird (TB) & v91.0.2 of your add-on Provider for Google Calendar v91.0.2.  I thought that it was working fine a couple of days ago when I first implemented the add-on but that was primarily adding events from the Google calendar to the TB calendar.   But now none of the new events I enter into the TB calendar appear on my Google calendar.  Did a recent update of TB cause your add-on to fail?  Since this a bidirectional interface, events entered into the TB calendar should therefore be uploaded into the Google calendar?  I appreciate your assistance.  Thank you.</div>

UPDATE:
FYI the issue with uploading events form the Thunderbird calendar to the Google calendar.  Events entered into the Google calendar download to the Thunderbird calendar.

**Comment by kewisch** [comment]
I'm only aware of breaking changes in Thunderbird 96. Can you enable debugging as noted in the wiki and provide more information?

**Comment by philips791** [comment]
I attempted to follow  the instructions for turning on debug but I believe the instructions are out of date.  However I was able to turn on both of the preferences and have attached the debug log as a result of restarting Thunderbird and then clicking on the Synchronize action.  Even though the Google calendar was not synchronized the TB Calendar is still showing the status message of "Synchronizing calendar...".  Thank you
[console-export-2022-1-9_17-51-56.txt](https://github.com/kewisch/gdata-provider/files/7836233/console-export-2022-1-9_17-51-56.txt)
.

**Comment by philips791** [comment]
It appears that only new events are being synchronized with the Google calendar.  Recurring events that were entered a few weeks ago are not being uploaded to the Google calendar.  Even those recurring events that are modified for only that single date are not updated.

**Comment by kewisch** [comment]
Do you also have `calendar.debug.log.verbose` set? It seems the console messages are missing a few things. I've not been able to reproduce this unfortunately.

If you say what fails is adding these events, then maybe you could send logs on what happens while trying to add an event.
