### ISSUE TITLE
Can't modify shared event

### ISSUE THREAD

**Issue by tclavier** [kewisch/gdata-provider#366]
### Describe the problem and steps to reproduce it:

Invited as participant in an event, at each synchronization TB show me a reminder popup. When I clic to Dismiss, calendar switch in error state with that in console : 

```
Calendar: [calGoogleCalendar] Modifying item Thomas and blabla  failed:2147500037: {
 "error": {
  "errors": [
   {
    "domain": "calendar",
    "reason": "forbiddenForNonOrganizer",
    "message": "Shared properties can only be changed by the organizer of the event."
   }
  ],
  "code": 403,
  "message": "Shared properties can only be changed by the organizer of the event."
 }
}
```
At next synchronization, I will have a new popup I will clic to Dismiss All and that loop.

### What did you expect to happen?

I want no popup ;-) I don't know what is the good solution : 
* do not remind events when i'm not organizer ? 
* do not remind events they are passed ?
* do not remind events after a 403

**Comment by kewisch** [comment]
Unfortunately right now the only option is to disable "Show Missed". I've fixed this on the development version, but it will still be a while until I can release it. See #224 and #3 for details
