### ISSUE TITLE
Can't select email for all google calendars

### ISSUE THREAD

**Issue by Belaial** [kewisch/gdata-provider#37]
Hi,

I recently created a bug report for the calendar in Thunderbird, however my ticket was apparently for the wrong developer and I got appoint here instead.

Please see the detailed report I made here, https://bugzilla.mozilla.org/show_bug.cgi?id=1600292

In short what I wanna report is that I can only select a Email: for the main calendar of my Google account, however I would like to select it on another calendar on same account (not the default one that is created as default), is this possible to implement?

In case I need to detail all stuff here let me know, otherwise please see the the link above where I already did my best to explain the issue.

**Comment by kewisch** [comment]
Due to the way invitations work on Google Calendar, only the primary calendar can be the target for invitations. I don't remember the specifics, but I believe it had to do with sending notification emails. They wouldn't send on secondary calendars.

**Comment by Belaial** [comment]
Ok, then I know, thanks for the update.
Hopefully in the future Google will change how this works then.
