### ISSUE TITLE
Silently fails to save event to Calendar without error or message (data is lost)

### ISSUE THREAD

**Issue by MLopez-Ibanez** [kewisch/gdata-provider#370]
### Describe the problem and steps to reproduce it:

I saved an event to a Google Calendar in Thunderbird.
(Please include as many details as possible.)

### What happened?

The event is not added to the Calendar and no error is given. Unless you go and check the calendar, you will not notice that the event is not there.

JavaScript error: chrome://calendar/content/calendar-ui-utils.js, line 180: TypeError: aElement is null
console.log: Lightning: [calGoogleCalendar] Adding regular event Tesis
console.log: Lightning: [calGoogleRequest] Requesting POST https://www.googleapis.com/calendar/v3/calendars/XXXXX%40group.calendar.google.com/events
console.log: Lightning: [calGoogleCalendar] Setting Upload Data (application/json; charset=UTF-8):
{"start":{"dateTime":"2022-02-11T11:00:00","timeZone":"Europe/Madrid"},"end":{"dateTime":"2022-02-11T12:00:00","timeZone":"Europe/Madrid"},"summary":"Tesis","description":"","reminders":{"overrides":[],"useDefault":false}}
JavaScript error: chrome://lightning/content/lightning-item-iframe.js, line 487: NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIObserverService.removeObserver]
console.error: Lightning: 
  [calGoogleCalendar] Adding Item Tesis failed:2147500036: 

### What did you expect to happen?
The event is added or I get an error. The error is silent and I don't get to save the event in a different calendar or try again or save the text (the description is lost!).

### Anything else we should know?

aElement is null 2 calendar-ui-utils.js:180
    removeChildren chrome://calendar/content/calendar-ui-utils.js:180
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:147
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    commonUpdateReminder chrome://calendar/content/calendar-dialog-utils.js:514
    updateReminder chrome://lightning/content/lightning-item-iframe.js:1604
    updateCalendar chrome://lightning/content/lightning-item-iframe.js:2763
    updateCalendar self-hosted:844
    gdataInitUI resource://gdata-provider/legacy/modules/ui/gdata-lightning-item-iframe.jsm:36
    x resource://gdata-provider/legacy/modules/gdataUtils.jsm:1383
    loadDialog chrome://lightning/content/lightning-item-iframe.js:824
    onLoad chrome://lightning/content/lightning-item-iframe.js:445
    onload chrome://lightning/content/lightning-item-iframe.xhtml:1

Lightning: [calGoogleCalendar] Adding Item Tesis failed:2147500036: gdataCalendar.jsm:457

**Comment by MLopez-Ibanez** [comment]
Restarting Thunderbird fixes it... for a little while then it happens again:

78.14.0 (64-bit)
Provider for Google Calendar	78.0.2

Having at least an error will give me the chance of restarting TB and trying again.

**Comment by kewisch** [comment]
Unfortunately I can no longer support Thunderbird 78. Please upgrade to Thunderbird 91 and the respective provider to continue.
