### ISSUE TITLE
Attendees are not added to gmail calendar

### ISSUE THREAD

**Issue by dsoldguy** [kewisch/gdata-provider#371]
I am using  the latest provider for gmail from Thunderbird. I can successfully add attendees to the event. The event is created in the gmail calendar. However the attendees are not added to the calendar. 

In addition, when I check the options in the provider itself, there doesn't appear to be any way to save the options from the provider screen.

Thanks

**Comment by kewisch** [comment]
This is fixed in 91.0.3 and 91.0.4, you should be able save the options afterwards and then add attendees to the calendar. Thanks for reporting!
