### ISSUE TITLE
OAuth secrets lost

### ISSUE THREAD

**Issue by FabianRahm** [kewisch/gdata-provider#372]
### Describe the problem and steps to reproduce it:

Thunderbird regularly asks to log in into Google Account after Thunderbird/Plugin update.

### What happened?

I got prompted to log in multiple times over the last couple of days and Google rejected the login after allowing access to the calendar with a 403 error - too many signups for the same application within a short time frame.

### What did you expect to happen?

That credentials are not lost and Thunderbird keeps the secret stored of how to access my Google calendar.

### Anything else we should know?

Thunderbird 91.5.0 on Ubuntu Linux. Provider for Google Calendar version 91.0.3.

**Comment by bmmeijers** [comment]
Same here, #373 seems to be exact same problem (but then on Windows)

**Comment by kewisch** [comment]
Thank you for reporting. Please see my coment in #373 for details.
