### ISSUE TITLE
After addon update "error 403: rate_limit_exceeded" is thrown

### ISSUE THREAD

**Issue by endlessterror** [kewisch/gdata-provider#373]
### Describe the problem and steps to reproduce it:
Windows 10 64bit, Thunderbird 91.5.0 (64-bit). Addon version is 91.0.3

Today when starting up tbird I was prompted to enter my Google credentials.

After doing so I was presented with the 2FA authentication. Passed successfully and then I was prompted if it would be ok for calendar to access this and that. Accepting that I get a 403 error: rate_limit-exceeded

### What happened?

Received the error mentioned above

### What did you expect to happen?

Google calendar would authenticate ok and events from my Google calendar would start appearing

### Anything else we should know?
With debugging enabled:

![εικόνα](https://user-images.githubusercontent.com/8733010/150736491-c22321fd-aa79-4e88-8dba-392f44d4e7b7.png)

![εικόνα](https://user-images.githubusercontent.com/8733010/150736813-80dfe3b5-7f34-4c76-b5d8-9901c28542eb.png)

**Comment by performantp** [comment]
Same here

**Comment by andreas301-sketch** [comment]
Same here. I had to sign in to Google again today and was presented with "error 403: rate_limit_exceeded" after 2FA

**Comment by FredH42** [comment]
Hi, same for me. The popup mentions that the developer can ask to raise the connexion rate limit...
Any help appreciated. Thx

**Comment by anatoliDeryshev** [comment]
Previous issue - https://github.com/kewisch/gdata-provider/issues/288
Possible details - https://stackoverflow.com/questions/48868737/rate-limit-exceeded-google-calendar

**Comment by georgmo** [comment]
same. Thank you.

**Comment by IanBlakeley** [comment]
I'd try to authenticate again later if I knew how to trigger it. Just had the same failure so I am thinking no sync until updated signin?

**Comment by alfredo49** [comment]
Same issue

**Comment by peterVoisin** [comment]
The same

**Comment by Botislav** [comment]
Same here

**Comment by HeikoPaulheim** [comment]
Same here

**Comment by pajew** [comment]
This addon is not necessary any more.
[https://support.mozilla.org/pl/questions/1355356](url)

**Comment by depauw75** [comment]
same problem here!

**Comment by IceKarimMore** [comment]
Very sorry for my Twiter error report
I have the same problem.
Google error message for me is below
Erreur d'autorisation
Erreur 403 : rate_limit_exceeded

Cette appli a atteint son taux de connexion maximal.

Google limite la fréquence à laquelle une appli peut accepter de nouveaux utilisateurs. Vous pouvez réessayer plus tard ou demander au développeur (provider-for-google-calendar@googlegroups.com) d'augmenter le taux de connexion maximal de l'appli.

Si vous êtes le développeur, vous pouvez demander à augmenter ce taux.
En savoir plus
Le contenu de cette section a été fourni par le développeur de l'appli. Google ne l'a pas examiné ni validé.
Si vous êtes le développeur de l'appli, assurez-vous que les détails de cette requête respectent les règles de Google.

    login_hint: tabbarakarim@gmail.com
    hl: fr
    response_type: code
    redirect_uri: urn:ietf:wg:oauth:2.0:oob:auto
    client_id: 647770275422-f30mivm6f2nli7qu4mpt20a3lc83t1vv.apps.googleusercontent.com
    access_type: offline
    scope: https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/tasks

    AideConfidentialitéConditions d'utilisation

If I can provide more information please let me know

**Comment by IceKarimMore** [comment]
Thanks, I've just seen  pajew's comment.
Works fine

**Comment by srsbiz** [comment]
> This addon is not necessary any more. [https://support.mozilla.org/pl/questions/1355356](https://support.mozilla.org/pl/questions/1355356)

Just checked it again, and it still does not support private calendars shared with my account (public ones are available to subscribe), and this plugin does.

**Comment by anatoliDeryshev** [comment]
Started to work again, was able to login.

**Comment by danardf** [comment]
No way to use for now. 
I'm watting the fix.

**Comment by morbac** [comment]
same problem here

**Comment by kewisch** [comment]
Hey folks, apologies this is happening again. Unfortunately when releasing 91.0.3 I used the wrong API key, so folks need to log in again, which is causing Google to hit the rate limits. I've requested an increase last time, though it seems I am reaching that limit as well. 

There are two things I can do:
* Re-release as 91.0.4 with the same api key as 91.0.2. This should save users who have not upgraded yet, but will cause users who have to re-login once more. 
    * &rarr; I've done this, I think the trade-offs are reasonable, and it will save about 60% of users.
* Create a local mechanism for staged rollout. Unfortunately, neither AMO nor ATN provide a way to only upgrade a percentage of users. What I can do is cache the API key locally, and if it changes during an upgrade I first try with the new key, if that doesn't work due to rate_limit_exceeded I continue with the cached key and try again for a certain period of time. This will be a bit of work, but would ultimately save people from this happening again.


In the short term, this issue should "fix itself" after a few days. It may even be quicker this time since I have higher rate limits. Hang in there ❤️

**Comment by JPRuehmann** [comment]
After Updating to 91.0.4 Login does not work anymore.

**Comment by kewisch** [comment]
Can you clarify "does not work"? Does it also show the 403 error, or something completely different?

**Comment by JPRuehmann** [comment]
It shows the 403 Error.
91.0.3 worked.

**Comment by Giosmile** [comment]
I also upgraded to version 91.0.4 but the 403 Error problem persists the same as before with 91.0.3.
What do we do?

**Comment by Giosmile** [comment]
> It shows the 403 Error. 91.0.3 worked.

But have you installed the previous version and now it works for you? Error cleared?

**Comment by kewisch** [comment]
No need to downgrade to 91.0.3. If you switch between these versions, you will need to re-authenticate, and will hit the 403 error either way. Unfortunately the best advice I can give at the moment is to wait and see, trying again later in the day or tomorrow. Eventually enough folks will have logged in so that the load balances, and everyone will be able to use it again.

**Comment by JPRuehmann** [comment]
How can I do that? It got updated automaticaly.

**Comment by crimle** [comment]
Same issue for me...

**Comment by n33tfr33k** [comment]
>Start Thunderbird and get the Google login box. Log in and respond to a verification prompt from Google on my phone. Then get 403 error. I then respond to the Google security alert e-mail, log into my Google account, verify myself again, and Calendar works.

This process worked for me, Linux, TB 64-bit version 91.5.0, Plugin version 91.0.4

**Comment by sasha-** [comment]
Just stopping by to say thank you for addressing this quickly.  Now we just wait for google to reset counters.

**Comment by syl1010** [comment]
Same problem here for 2 days "Error 403: rate_limit_exceeded"

Running version 91.5.0

**Comment by ncroiset** [comment]
Since release 91.0.4 same problem in mys side also.

**Comment by HgWing** [comment]
Same problem. No way to get it working :(

**Comment by MartinX3** [comment]
Please stop commenting, if you have the same issue. Just subscribe to this issue ticket and wait for a solution.
You all are disturbing everyone who subscribed to this issue ticket.

**Comment by kewisch** [comment]
Locking comments for the moment. This is indeed the main issue where folks may be waiting for a resolution. If you need help with something not covered in my comments above please file a new issue or reach out to me via email. I'm getting a lot of requests right now, so I may not be able to get back to everyone, but I'm trying!

**Comment by kewisch** [comment]
Hey folks, we should be good now, sign-in rates are back to normal!
<img width="516" alt="graph showing sign-in rates back far under the limit" src="https://user-images.githubusercontent.com/607198/151629406-159d28b0-3e82-4049-b879-6b94299c5dc4.png">

Thank you everyone for your support, the generous donations, and your understanding. I acknowledge this was frustrating to many of you and may have taken some of the productivity out of your day. I have a few ideas on how to mitigate this in case it happens in the future that I'll be looking in to before I do any further releases.

**Comment by hnsch** [comment]
Thanks for responding so fast!Mine started to function again on Thursday 27th Jan 2022.Kind regards,Hennie SchoemanPr Ing / Pr EngSent by Mobile Phone
-------- Original message --------From: Philipp Kewisch ***@***.***> Date: 2022/01/29  00:24  (GMT+02:00) To: kewisch/gdata-provider ***@***.***> Cc: hnsch ***@***.***>, Manual ***@***.***> Subject: Re: [kewisch/gdata-provider] After addon update "error 403:
  rate_limit_exceeded" is thrown (Issue #373) 
Hey folks, we should be good now, sign-in rates are back to normal!

Thank you everyone for your support, the generous donations, and your understanding. I acknowledge this was frustrating to many of you and may have taken some of the productivity out of your day. I have a few ideas on how to mitigate this in case it happens in the future that I'll be looking in to before I do any further releases.
