### ISSUE TITLE
After addon update  today , version 91.0.4 "error 403: rate_limit_exceeded" 

### ISSUE THREAD

**Issue by Noddy1970** [kewisch/gdata-provider#377]
After update addon today (01-24-2022) , version 91.0.4 I've got this error message each time I want to access to calendar under Thunderbird. See the screen capture below. 
![Sans titre](https://user-images.githubusercontent.com/74466838/150842274-f1bbcf89-240a-4562-adb5-af9e9b342b28.png)

**Comment by wosym** [comment]
Same issue here. I think the core problem has existed at least since yesterday.

**Comment by Lusseyran** [comment]
The same for me

**Comment by kewisch** [comment]
Please see #373
