### ISSUE TITLE
All calendars switched to visible when logging in again

### ISSUE THREAD

**Issue by LinAGKar** [kewisch/gdata-provider#383]
Recently, the extension had required logging in again, as noted by multiple other issues. Annoyingly, when this happens, all subscribed calendars are switched to visible, and you have to switch each to hidden again.

**Comment by kewisch** [comment]
I believe this was fixed in Thunderbird 102. I have a release of the Provider coming out soon, once the Provider hits version 102.0.0 and Thunderbird 102 beta is available, can you give this another try?
