### ISSUE TITLE
Locking comments for the moment. This is indeed the main issue where folks may be waiting for a resolution. If you need help with something not covered in my comments above please file a new issue or reach out to me via email. I'm getting a lot of requests right now, so I may not be able to get back to everyone, but I'm trying!

### ISSUE THREAD

**Issue by fstjohn** [kewisch/gdata-provider#384]
Locking comments for the moment. This is indeed the main issue where folks may be waiting for a resolution. If you need help with something not covered in my comments above please file a new issue or reach out to me via email. I'm getting a lot of requests right now, so I may not be able to get back to everyone, but I'm trying!

_Originally posted by @kewisch in https://github.com/kewisch/gdata-provider/issues/373#issuecomment-1020461696_

**Comment by kewisch** [comment]
Hey John. Not quite sure I understand this issue. Is there anything I can help with not covered?

**Comment by adamz01h** [comment]
@kewisch So now that its broken again and you continue to get people having issues maybe you should open this up and unencrypt the part of the code that handles the keys and you put in sample data, these issues will stop.

**Comment by adamz01h** [comment]
@kewisch also not cool to lock that thread. your creating unnecessary friction.

**Comment by kewisch** [comment]
Even without unencrypting the session data it should be possible to figure out how to use your own keys. I'm sure there are provisions in Google's TOS that would prevent me from making the keys configurable in the UI, but I admit I have not checked.

Regarding locking the thread, I feel there is value in having one issue that people can use to learn about updates. They don't need many emails saying "I have this issue as well", as some folks have pointed out. Locking threads does create some friction, but it also alleviates other friction. Given I've provided alternative ways to reach out I think it has been an acceptable trade-off.

As mentioned in the other issue, I'm looking into a few ideas to mitigate the sign-in rates in case this situation appears again. I hope this doesn't repeat just as much as you do :) Thank you for sharing your concerns!
