### ISSUE TITLE
Processing message failed. Status: 80004004 when accepting invitation

### ISSUE THREAD

**Issue by MLopez-Ibanez** [kewisch/gdata-provider#387]
### Describe the problem and steps to reproduce it:

Trying to accept a meeting invitation into a Google Calendar setup via the add-on.
(Please include as many details as possible.)

### What happened?

A popup asks for the calendar, choose Google's main calendar.

Another popup asks for "You are not on the guest list yet. Respond as:" I choose the email address that was invited to the event.

A popup saying that an error has occurred: Processing message failed. Status: 80004004.

### What did you expect to happen?

No error. Event is added to the calendar.

### Anything else we should know?

Calendar: Unknown iTIP method: nomethod calItipUtils.jsm:301
Calendar: [calGoogleCalendar] Adding Item AI SIG Meeting #13 failed:2147500036: gdataCalendar.jsm:457
Assert failed: error on iTIP processing
 calUtils.jsm:121
    ASSERT resource:///modules/calendar/calUtils.jsm:121
    onOperationComplete resource:///modules/calendar/utils/calItipUtils.jsm:1209
    onOperationComplete resource:///components/calCachedCalendar.js:782
    notifyPureOperationComplete resource:///modules/calendar/utils/calProviderUtils.jsm:560
    adoptItem resource://gdata-provider/legacy/modules/gdataCalendar.jsm:460

TB 91.5.0
Provider for Google Calendar	91.0.4

**Comment by kewisch** [comment]
Assuming this is related to #358, marking duplicate
