### ISSUE TITLE
Provider v68.2.1 does not work with TB 72.0b2 (64-bit)

### ISSUE THREAD

**Issue by DavidFlory** [kewisch/gdata-provider#39]
There are two problems.

First: Reminders cannot be dismissed.  I get into an endless loop and have to kill TB.  If I disable Provider the problem stops. The endless loop alternates between the screen to dismiss or sleep the reminder and the screen saying the action has already been taken, resubmit or ignore.

Second:  Subscribed Google calendars (with full R/W authority) will not update on TB Calendar Display.  If you try to create a new event it is created on Google but not replicated on Calendar.

This has been reported in a review (not by me) on the Thunderbird Provider page.  Not a good review.  

When I sync on my Google calendar I have 2 errors in the development error console:

        Lightning: [Exception ... "Cannot convert primitive JavaScript value into an array arg 0 [calIItemBase.setCategories]" nsresult: "0x80570022 (NS_ERROR_XPC_CANT_CONVERT_PRIMITIVE_TO_ARRAY)" location: "JS frame :: resource: // gdata-provider / modules / gdataUt .jsm :: JSONToEvent :: line 835 "data: no] 

and

        Lightning: [calCachedCalendar] replay action failed: null, uri = googleapi: // xxx...@gmail.com /?calendar=XXXXXX%40gmail.com, result = Cannot convert primitive JavaScript value into an array arg 0 [calIItemBase.setCategories], operation = [xpconnect wrapped calIOperation]

**Comment by suskozaver** [comment]
First: can you get around this if you disable Show missed reminders for writable calendars in Options/Calendar? It worked for me

Second: how long did you wait? what's your default sync time? Did you click Sync in TB?

> There are two problems.
> 
> First: Reminders cannot be dismissed. I get into an endless loop and have to kill TB. If I disable Provider the problem stops. The endless loop alternates between the screen to dismiss or sleep the reminder and the screen saying the action has already been taken, resubmit or ignore.
> 
> Second: Subscribed Google calendars (with full R/W authority) will not update on TB Calendar Display. If you try to create a new event it is created on Google but not replicated on Calendar.
> 
> This has been reported in a review (not by me) on the Thunderbird Provider page. Not a good review.
> 
> When I sync on my Google calendar I have 2 errors in the development error console:
> 
> ```
>     Lightning: [Exception ... "Cannot convert primitive JavaScript value into an array arg 0 [calIItemBase.setCategories]" nsresult: "0x80570022 (NS_ERROR_XPC_CANT_CONVERT_PRIMITIVE_TO_ARRAY)" location: "JS frame :: resource: // gdata-provider / modules / gdataUt .jsm :: JSONToEvent :: line 835 "data: no] 
> ```
> 
> and
> 
> ```
>     Lightning: [calCachedCalendar] replay action failed: null, uri = googleapi: // xxx...@gmail.com /?calendar=XXXXXX%40gmail.com, result = Cannot convert primitive JavaScript value into an array arg 0 [calIItemBase.setCategories], operation = [xpconnect wrapped calIOperation] 
> ```

**Comment by DavidFlory** [comment]
Yes, disabling Show Missed Reminders provides a work about for the endless loop.   On the syncing problem-- I have clicked on Synchronize and waited up to an hour.  The progress bar at the bottom says Synchronizing 0 of 25 events or Synchronizing Default Calendar List.  It will not update TB from Google Calendar.

**Comment by BlackDex** [comment]
I have the same issue.
Using TB 72.0b3 in this case.
I also tried to reinstall the addon, but that resulted in not being able to add new google calendars at all.
I can enter my e-mail address, but i can not press the "next" button.

**Comment by alambike** [comment]
Same issue here using TB 72.0b3, as stated by BackDex in https://github.com/kewisch/gdata-provider/issues/39#issuecomment-571943479 is not possible to add new google calendars.
The option exists in "Create new calendar" dialog but can't continue after write my email address:
![image](https://user-images.githubusercontent.com/1025564/72158924-9d595600-33bb-11ea-9e4f-2e2557c691cd.png)

**Comment by gmbolger** [comment]
Same, am unable to dismiss items that are in tentative... driving me mad

**Comment by creechy** [comment]
Just tried with Thunderbird 78, also doesn't appear to work with it either. Didn't have much time to investigate and had to back down to TB 68.

**Comment by kewisch** [comment]
#77
