### ISSUE TITLE
Impossible to register an event into google agenda from Thunderbird

### ISSUE THREAD

**Issue by Sylvain7345** [kewisch/gdata-provider#40]
Thunderbird 68.3.1
Windows 10 familly
Extensions : Lightning and Provider for Google agenda
When I want to register an event from Thunderbird into my google agenda, I have an error message.
Later on, it's no more possible to select the google agenda to register an other event.
From google agenda, I can register events and I can see them into thunderbird.
You can see it below.
![error message](https://user-images.githubusercontent.com/59049460/71164652-ccaef400-224f-11ea-98a1-df4b1380de7d.png)
To remove the warning, I have to reboot Thunderbird.
I already reinstall the extensions.
Thanks for your help

**Comment by kewisch** [comment]
Please re-test on Thunderbird 91 if this is still an issue and re-open if necessary.
