### ISSUE TITLE
Google Tasks - Can't remove repeatable task

### ISSUE THREAD

**Issue by MartinX3** [kewisch/gdata-provider#408]
### Describe the problem and steps to reproduce it:

I created a repeating task in the google website.
I try to remove it in thunderbird.

### What happened?
It comes back and is not deleted from the server.

### What did you expect to happen?
It being removed from the server.

### Anything else we should know?

N/A

**Comment by kewisch** [comment]
Can you provide logging for this? Google does not expose via API that tasks are repeating, so they should look like normal tasks to Thunderbird. I've tried this locally and was not able to reproduce.

**Comment by MartinX3** [comment]
I switched to th faster and bugfree email client `evolution` from the gnome project.
It has buildin task support.
