### ISSUE TITLE
No longer works with TB 68.3.1 (32 bit)

### ISSUE THREAD

**Issue by sensato50** [kewisch/gdata-provider#42]
Calendars list appears in grey, and no events appear for any of the calendars.

**Comment by saiful76** [comment]
Yes, it stopped working after the update to 68.3.1 in Windows 10 Pro with this message:
"Provider for Google Calendar is incompatible with Thunderbird 68.3.1" and it is in disabled state.

**Comment by saiful76** [comment]
I can confirm that this issue is now fixed on my machine after today's update.

**Comment by macgeekpro** [comment]
I concur. Running TB v68.3.1 and Provider v68.2.1

**Comment by DavidFlory** [comment]
Any info on the problem with TB 72.0b2 (64bit)?  Updates in Google Calendar are not seen in TB.

**Comment by sensato50** [comment]
> Calendars list appears in grey, and no events appear for any of the calendars.

After a system reboot Provider v68.2.1 is displaying data, but the event detail window refuses to close, either through Save and Close button or Esc key or X window button, and with both New Event and existing events.

**Comment by houstonwb** [comment]
This worked for me, although the system reboot had to come after reinstalling Provider.

**Comment by kewisch** [comment]
I'm closing this issue for lack of additional details. Resubscribing to calendars usually helps as a workaround. Thanks for reporting!
