### ISSUE TITLE
Cannot add invitation to corresponding calendar

### ISSUE THREAD

**Issue by kirk86** [kewisch/gdata-provider#422]
### Describe the problem and steps to reproduce it:

I have multiple emails accounts in thunderbird 91.8 on OSX Big Sur, e.g. lets say those email accounts are `A,B,C,D`.
Each of them has a corresponding google calendar which has been added using the provider for google addon.
An email is received on `account B` with an invitation.
<img width="820" alt="image" src="https://user-images.githubusercontent.com/2902390/162203992-702e5662-e992-464a-9982-10df48629f7d.png">

Click on accept and and it shows a message asking on which calendar to import these items into?

A popup shows calendars corresponding to accounts `A,C,D` but not `B` the calendar to which the received email invitation corresponds to.
<img width="311" alt="image" src="https://user-images.githubusercontent.com/2902390/162209800-1ed8d66d-ad7e-4902-90ba-7d63a7fd4bc4.png">

On a different email received on first April 2022 with a repeating invitation
<img width="820" alt="image" src="https://user-images.githubusercontent.com/2902390/162205905-56e3f4b3-bdc0-4758-b287-1524989df6da.png">

Pressing `Accept all` does absolutely nothing. No popup to choose calendar and no invitation added to calendar. 

### What happened?
Nothing happens

### What did you expect to happen?
Event invitations should be added to each corresponding calendar

### Anything else we should know?

This is the error when pressing `Accept all`

```
Uncaught (in promise) Error: Incorrect argument types for convCalendar.onMessageNotification.
    makeError resource://gre/modules/Schemas.jsm:540
    throwError resource://gre/modules/Schemas.jsm:2625
    checkParameters resource://gre/modules/Schemas.jsm:2682
    stub resource://gre/modules/Schemas.jsm:2792
    init moz-extension://0804d7c0-f4ef-344a-9a2b-fd2492a74c50/content/background.bundle.js:1094
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:626
    fire resource://gre/modules/ExtensionChild.jsm:806
    recvRunListener resource://gre/modules/ExtensionChild.jsm:810
    _recv resource://gre/modules/ConduitsChild.jsm:78
    receiveMessage resource://gre/modules/ConduitsChild.jsm:184
[background.bundle.js:1094:39](moz-extension://0804d7c0-f4ef-344a-9a2b-fd2492a74c50/content/background.bundle.js)
```

**Comment by kewisch** [comment]
The error message you reference seems to be from a different add-on, maybe Thunderbird Conversations? Does disabling that add-on change anything about this?
