### ISSUE TITLE
Unable to sign into google account: "The browser you're using doesn't support Javascript or has Javascript turned off."

### ISSUE THREAD

**Issue by Infinoid** [kewisch/gdata-provider#425]
Is it possible to perform OAuth authentication without javascript?

I normally have `javascript.enabled = false` in thunderbird for security reasons.  Once in a while, when I update thunderbird, I have to turn it back on to allow this plugin to authenticate.
This happened today after updating Thunderbird from 78.14.0 to 91.7.0 as part of an OS update.  (I am using the Debian Linux packages for thunderbird.)

Without javascript enabled, after typing in my email address and clicking next, I got this error:

![image](https://user-images.githubusercontent.com/50254/162968958-dd56b560-dd68-4ac9-806d-af1acf73fb55.png)

I was able to retry with javascript enabled, and it worked.

But it raises the question: is there an alternative to using their web/js authentication in an embedded browser?

**Comment by Infinoid** [comment]
> is there an alternative to using their web/js authentication in an embedded browser?

Failing that, is it possible to enable javascript for just this login window, rather than doing so globally?

**Comment by kewisch** [comment]
Thanks for checking on this. As far as I can see, I can't allow scripts if `javascript.enabled = false` unless I set a domain policy, so it would be specific to some domains and not to that popup window. Unfortunately I don't think I can support a configuration like this, as it would be difficult to justify.
