### ISSUE TITLE
[FAQ] "Turn cookies on or off"

### ISSUE THREAD

**Issue by bill-mcgonigle** [kewisch/gdata-provider#43]
TB 68.3.0
gdata-provider:  68.2.1

For whatever reason, Google decided I needed to re-authenticate today (I upgraded TB last week, possibly quit it over the holidays).

After authenticating with my username and password, instead of 2FA I would get a "Turn cookies on or off" screen and a link to Google help pages.

After a bunch of digging around I found that a long, long time ago I apparently set `network.cookie.cookieBehavior` to 2, or "don't let Thunderbird send cookies".    Changing this to 1, or "Only cookies from the originating server are allowed" allowed 2FA to proceed on the next login.  Previously '2' was an acceptable value, for however many long years I've been using your addon (thanks!).

Perhaps something like this for the FAQ:

Q: When I try to authenticate with a Google account set up with 2FA, after i type in my username and password I get  a message in the authentication dialog that says, "Turn cookies on or off".  
A: Check in your Config Editor (Preferences ... Advanced ... General ... Config Editor) for the setting 'Network.cookie.cookieBehavior'.  If ti is set to 2, reset it to the default of 0, or 1 for more privacy.  See: http://kb.mozillazine.org/Network.cookie.cookieBehavior

**Comment by kewisch** [comment]
Confirming this, thanks for reporting. Worse yet, in 91.0.1 I made some updates based on wrong assumptions of how the code works. I have a patch ready that will fix this.
