### ISSUE TITLE
Calendar momentarily not available

### ISSUE THREAD

**Issue by davidselig** [kewisch/gdata-provider#443]
WHen opening TB, 91.6.2
with provider v. 102.0.0

I get the "Calendar momentarily not available" warning
(see screenshot)
After quite a long time the issue partly resolves, but I cannot copy and paste in the calendar... 
And loading the calendar into TB takes ... up to 30'..

The error log is enormous. 
Below is the most recent, repeated several times
Any help appreciated. 

Error: Connection closed, pending request to server1.conn0.longstractor3751, type release failed

Request stack:
request@resource://devtools/shared/protocol/Front.js:289:14
generateRequestMethods/</frontProto[name]@resource://devtools/shared/protocol/Front/FrontClassWithSpec.js:46:19
generateRequestMethods/</frontProto[name]@resource://devtools/shared/protocol/Front/FrontClassWithSpec.js:62:19
enableActorReleaser/</</releaseActorsEnhancer/<@resource://devtools/client/webconsole/enhancers/actor-releaser.js:40:33
releaseActorsEnhancer@resource://devtools/client/webconsole/enhancers/actor-releaser.js:30:40
batchingReducer@resource://devtools/client/webconsole/enhancers/batching.js:21:18
messagesCacheClearingEnhancer@resource://devtools/client/webconsole/enhancers/message-cache-clearing.js:17:15
ensureErrorReportingEnhancer@resource://devtools/client/webconsole/enhancers/css-error-reporting.js:21:15
dispatch@resource://devtools/client/shared/vendor/redux.js:256:22
eventTelemetryMiddleware/</<@resource://devtools/client/webconsole/middleware/event-telemetry.js:25:21
historyPersistenceMiddleware/</<@resource://devtools/client/webconsole/middleware/history-persistence.js:37:21
thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:18:11
ignore/</<@resource://devtools/client/shared/redux/middleware/ignore.js:31:12
createPerformanceMarkerMiddleware/</</<@resource://devtools/client/shared/redux/middleware/performance-marker.js:50:28
setTimeoutIfNeeded/this.throttledDispatchPromise</<@resource://devtools/client/webconsole/webconsole-wrapper.js:301:15

![caldendar issue](https://user-images.githubusercontent.com/106147600/169990543-fcd2347c-929b-47e1-92b5-bbf027dabfbc.jpg)

**Comment by kewisch** [comment]
Can you try https://github.com/kewisch/gdata-provider/wiki#enabling-debugging to get more messages? It may be a temporary problem that goes away on its own, but in case there are error messages in the advanced logs lets take a look

**Comment by knarrff** [comment]
I just had the same problem. I did not see any error messages in the log, yet it was still disabled and stayed that way. What might have been the case in my case was that I might have had two different sessions connecting to the same account. The dialog states "you should only need one", but it does not say "you must only use one session for the same account".

Despite this setup working for quite a while now and only stopping recently, I removed all google calendars for good measure and added them again, this time using the same session. Something in that process must have "fixed" it: it now works again.

So, you can see my report as
- possible workaround for the original reporter
- possible cause for this issue when you have multiple sessions for the same google account

**Comment by kewisch** [comment]
Using two sessions is fine, just means you have to log in twice when OAuth expires :) The re-subscribe usually fixes intermittent issues for a while, given no further response from OP I'm going to close this one. Feel free to open a new issue if it persists.
