### ISSUE TITLE
Sync with google is gone in latest version

### ISSUE THREAD

**Issue by ZirconfleX** [kewisch/gdata-provider#45]
Hi,

It worked perfectly and after an update it didn't.
Uninstalled everything from Thunderbird and then reinstalled the latest version of thunderbird and plugins (Lightning and Provider for Google Calendar).

OS used: Linux Mint 19.3 - 64-bit
Thunderbird (downloaded from the Thunderbird website is) now version: 68.3.1 (64-bit).
Lightning version:  68.3.1.1
Provide for Google calendar: 68.2.1

Setup/subscribed in Thunderbird to my Google calendar (it is visible and I can hit Synchronize).

This is what happens:
- When creating an event in Thunderbird/Lightning and hitting synchronize, nothing happens.
  - Lightning displays the event but there is no event in Google calendar.
- When creating a calendar entry in Google calendar and then synchronizing, the created appointment appears in Thunderbird.
- When creating a reminder in Google calendar it does not appear in Thunderbird although the option is turned on in the thunderbird Calendar options for the added Google calender.
  - Strange is that old reminders set in Google appear in Lightning.
  - When deleting them in Google they disappear in Lightning.
  - New reminders are not passed from Google to Thunderbird.

Conclusion: It worked perfectly and now it kind of works.

Thanks for looking into this.

**Comment by harshupadhya** [comment]
Hi 

Facing similar issue - 

When creating an event in Thunderbird/Lightning and hitting synchronize, nothing happens.
Lightning displays the event but there is no event in Google calendar.
When creating a calendar entry in Google calendar and then synchronizing, the created appointment appears in Thunderbird.

**Comment by fwillier** [comment]
Hi,

I have a similar problem, but only with multiple google accounts.
first account seems to work correctly (calendar synchro ok, adding modifying and suppressing event ok)
second account with other calendars does not work anymore after upgrade of thunderbird and lightning and module google provider.
I deleted it and recreated it, but during process, the calendar available shown are the ones from my first google account. If I go back in the process, the first account is selected. I select the 2nd one again and go forward in the process of adding calendars. Same thing happens, the list of calendars shown are the ones from my first account. So managing another google account with calendars is not possible

Please help, I had to suppress second account (which is a shared accounts with multiple calendars for internal use).

**Comment by XizzyO** [comment]
Hi,

I upgraded Thunderbird and now there is no sync at all between Google and Thunderbird. The Thunderbird addons page reports that the Google Calendar addon is not compatible with Thunderbird 68.3.1. (I use windows)

I miss you Google Calendar addon :/

**Comment by houstonwb** [comment]
Broke with Tbird update to 68.3.1 (32 bit), Win 10.  Previous versions working on other computers.

**Comment by kalumet** [comment]
I updated to Thinderbird 68.3.1 (68.3.1 (32-Bit)) and the add-on stoped working for incompatibility-issues.

Very sad and I hope it will be fixed? Many thanks for your effort!

**Comment by richwales** [comment]
I encountered this same issue yesterday (Tue. 15 Jan. 2020), on my Ubuntu desktop.

I found a workaround on another discussion forum.  After going into TB's configuration editor and setting **general.useragent.compatMode.firefox** to **true**, I can access my calendar once again.

People who are having trouble getting the Provider add-on to work for them might want to try this configuration setting and see if it fixes the problem for them.  The fact that this seems to work might also point the way to a solution to the original problem.

Possibly (or possibly not) coincidentally, the **calendar.google.com** web site no longer works in Google Chrome on my desktop -- though it does work in Firefox on the same machine.

Ubuntu 19.10; Thunderbird 60.9.1 (64-bit); Provider add-on 4.4.2.

**Comment by ZirconfleX** [comment]
Hi,

Thanks for this!
Your solution works for me too.

I can add event in TB and sync them with google.
Reminders entered in Googls still don't appear in TB (worked before 
flawless).

Regards,

Marc

**Comment by richwales** [comment]
I entered an appointment yesterday via a web site that generated a Google Calendar popup.  It did not show up in my Thunderbird/Lightning Google calendar until I clicked the "Synchronize" option along the top (above the calendar, below TB's tab list).

**Comment by ZirconfleX** [comment]
Indeed, that is what you need to do in TB to get things in Google. When
using Google there is no sync (on GSM). When entering there it's unsure if
things appear in TB. Reminders do not.

Marc

Send from GSM.

**Comment by ZirconfleX** [comment]
> Hi,
> 
> It worked perfectly and after an update it didn't.
> Uninstalled everything from Thunderbird and then reinstalled the latest version of thunderbird and plugins (Lightning and Provider for Google Calendar).
> 
> OS used: Linux Mint 19.3 - 64-bit
> Thunderbird (downloaded from the Thunderbird website is) now version: 68.3.1 (64-bit).
> Lightning version: 68.3.1.1
> Provide for Google calendar: 68.2.1
> 
> Setup/subscribed in Thunderbird to my Google calendar (it is visible and I can hit Synchronize).
> 
> This is what happens:
> 
>     * When creating an event in Thunderbird/Lightning and hitting synchronize, nothing happens.
>       
>       * Lightning displays the event but there is no event in Google calendar.
> 
>     * When creating a calendar entry in Google calendar and then synchronizing, the created appointment appears in Thunderbird.
> 
>     * When creating a reminder in Google calendar it does not appear in Thunderbird although the option is turned on in the thunderbird Calendar options for the added Google calender.
>       
>       * Strange is that old reminders set in Google appear in Lightning.
>       * When deleting them in Google they disappear in Lightning.
>       * New reminders are not passed from Google to Thunderbird.
> 
> 
> Conclusion: It worked perfectly and now it kind of works.
> 
> Thanks for looking into this.

**Comment by ZirconfleX** [comment]
Hi,

Install Thunderbird version 68.4.2 and calendar works again perfect.
appointments are synced and google remainders are shown.

Thanks!
