### ISSUE TITLE
When I Accept an invitation to a meeting that arrives in Thunderbird Inbox email, my synced Google Calendar calendar wrongly does not appear on the Select Calendar dialog's list

### ISSUE THREAD

**Issue by davidberman** [kewisch/gdata-provider#457]
When I Accept an invitation to a meeting that arrives in Thunderbird Inbox email, my synced Google Calendar calendar wrongly does not appear on the Select Calendar dialog's list.

I installed the Provider for Google add-on for the first time ever today, in my Thunderbird for Windows v91.
I successfully followed the instructions to get an existing Google Calendar that was in my Google account to appear in the Thunderbird list of calendars.

I then went to an email in my Thunderbird inbox that just arrived that is inviting me to a meeting. 
I pressed Thunderbird's Accept button, which results in Thunderbird offering me a "Select Calendar" dialog box. 
The dialog box only shows my two existing Thunderbird calendars.

I expected it to now also show the Google Calendar in that list, so that I can can select it.

There are no other errors or error messages.

Help!

Thanks,
David

**Comment by zwergziege** [comment]
I had not, but ticking the `Enable email scheduling` box did not make any difference even after restarting thunderbird.

**Comment by davidberman** [comment]
@kewisch Thanks for your reply. In the Provider for Google Calendar addon settings tab, I have all 4 checkboxes checked. I don't see an setting called "Scheduling Options" and I'm not sure which of the addons you are referring to. Could you please be more specific? Thanks!

**Comment by kewisch** [comment]
I mean the first three options. If you have all four ticked then you are good. You may need to re-subscribe to all calendars once you have ticked the boxes. As I assume this solves the issue I'm closing this ticket, feel free to create a new one if issues persist.

**Comment by zwergziege** [comment]
The suggested fix did not resolve the issue for me. I have tired resubscribing but not creating a new session / reinstalling the plugin.
