### ISSUE TITLE
Clear an existing "session" ?

### ISSUE THREAD

**Issue by commonpike** [kewisch/gdata-provider#46]
I have tested gdata-provider with a google account. It worked, but I now need to connect it to a different google account. I need to use the same email address as used when testing, because invitations need to go to that other google account.

However, when creating a new calendar it says
"please pick an existing session or enter your email address to create new session"

if I enter the email address used when testing, this is (apparently) an open session and it shows me my testing calendars. deleting calendars, rebooting etc dont seem to help.

How can I remove the accounts related to my 'session', or the email address used in that session ?

**Comment by Kipperlenny** [comment]
same here, searched all the settings, but cannot find a "remove session" Button. This is very important for security reasons as well!

**Comment by Stefan-vm-1** [comment]
Same here.. very annoying!

**Comment by kewisch** [comment]
You should be able to remove this by going to the password preferences in Thunderbird and removing all gdata related entries. A restart may be required as well.

**Comment by Kipperlenny** [comment]
You were right! It worked by reming the saved oauth and password under thunderbird settings (and restart).
