### ISSUE TITLE
After Upgrading to Thunderbird version102 Gdata-Provider do no synchronization from google servers to thunderbird.

### ISSUE THREAD

**Issue by Rainer06** [kewisch/gdata-provider#464]
### Describe the problem and steps to reproduce it:
Upgrading Thunderbird from Version 91.3 ? to Version102.0 (64bit) make Provider for Google calender a one-way sync tool

### What happened?
If i modify my google calenders within thunderbird, this is immediatly synchronized to google servers and i see the modification immediatly on my smartphone calender app or in a web browser. 

If i however modify my google calenders with my smartphone or with a web browser, this is never synchronized from google servers to thunderbird (neither after 30 min nor after 60 min nor manually by clicking the "Synchronize" item ("Synchronisieren" in german) in den calender/task-menu nor by clicking the context-menu item "Synchronize calender" ("Kalender synchronisieren" in german). 

There are only two ways to get a synchronizsation from google servers zu thunderbird:
- Either deactivate the addon "Provider for Google calender" and reactivate it in the extra/add-ons window. 
- Or Close Thunderbird and reopen it.
In both cases my google calenders are synchronized to thunderbird almost immediately.

### What did you expect to happen?
I still expected (automatic) synchronization of my google calenders in both directions - from thunderbird to google servers and vice versa.

### Anything else we should know?
Clicking "Synchronize" _seems_ to do synchronization - e. g. the task-window is wiped out and refilled, but unfortunately with "old data" discarding any changes which were made meanwhile on my google calenders with smartphone or web browser.

But synchronization is functioning well at restart of either the add-on Provider for Google calender or the thunderbird app itself.

I use a HP Probook with 16 GB RAM, Windows 10 / 64 Bit Version 21H2.
Did anyone else encounter this problem after upgrading to thunderbird version102?
Can anyone help me to get this problem fixed?

Many thanks
Rainer

==============================
Additional info:
Meanwhile i use a Medion Notebook with 16 GB RAM, Windows 11 / 64-Bit Version 22H2.
I have Thunderbird Version 102.13.0 and Provider for Google Calender Version 115.0.1.
I experience still the same problems as before. 
Shutdown and restart thunderbird helps for at least one-time syncing my google calenders. But rurther on neigther autosync nor manual sync does show any result.
I am completely at a loss.
Greetings Rainer
==============================

**Comment by GraemeG60** [comment]
A possible work around.

I had the same problem after Thunderbird upgraded to 102. Calendar events would synchronise from my phone or from Thunderbird 91.11.0 on another PC to Google but TB 102 would not pick up the changes even when I manually synched. It was necessary to either restart TB or to disable the Provider for Google Calendars add-on and re-enable before it would synch correctly. I put up with this for a while hoping an update would fix it but after 2 or 3 TB updates I am now on TB102.1.0 and the problem remained.

However! I have just completely removed the Provider extension, deleted the calendar from TB, restarted TB and then added it all back in. So far, on just a couple of tests, I think the problem has gone away.

My problem machine is running Windows 10 Pro 21H1 and TB 102.1.0 64-bit with Provider 102.0.0

**Comment by GraemeG60** [comment]
I spoke too soon. After working with TB for a day the synch problem still exists

**Comment by wsmwk** [comment]
@Rainer06, Are you still seeing this problem when using a newer version of Thunderbird and a newer version of provider?

**Comment by biosas** [comment]
Mac OS 10.15.7 on MacBook Pro ,  Latest Thunderbird 102.1.2, Provider 102.0.1 and 102.0.0

Same result: enable plugin, Thunderbird uses 100% of CPU and just spins on and on.

Left it running for about six hours. Only one google calendar updated.

restarted with 

Applications/Thunderbird.app/Contents/MacOS>./thunderbird --safe-mode

(disabled Gdata-provider) and thunderbird back to normal without calendar working.

Was a great plugin for me for many years. 

Sad.

**Comment by Christoph75** [comment]
Same problem like @Rainer06. 
Does anybody have a solution for this problem? 

I use latest TB and latest Provider on a ThinkPad with Win11. 
Thanks.

**Comment by hellsbelz** [comment]
> A possible work around.
> 
> I had the same problem after Thunderbird upgraded to 102. Calendar events would synchronise from my phone or from Thunderbird 91.11.0 on another PC to Google but TB 102 would not pick up the changes even when I manually synched. It was necessary to either restart TB or to disable the Provider for Google Calendars add-on and re-enable before it would synch correctly. I put up with this for a while hoping an update would fix it but after 2 or 3 TB updates I am now on TB102.1.0 and the problem remained.
> 
> However! I have just completely removed the Provider extension, deleted the calendar from TB, restarted TB and then added it all back in. So far, on just a couple of tests, I think the problem has gone away.
> 
> My problem machine is running Windows 10 Pro 21H1 and TB 102.1.0 64-bit with Provider 102.0.0
I
I have the same issue. After working for about 1 day after the last restart of TB it refuses to sync.

**Comment by Soundmanbe** [comment]
Google Agenda access add-on still freezing all. (Thunderbird 102.3.0 (64 bits) linux). All ok when add-on disabled .... except my access to agendas.
Tried to remove all Agendas and reinstall it >> doesn't solve anything.

**Comment by nneul** [comment]
I'm having the same problem with the sync "silently stopping". Disabling/re-enabling clears the symptom each time. 

Is there any way to get more logging or information to help you diagnose this?

**Comment by nneul** [comment]
Absent that, can you consider implementing a "Force Full Sync" button/menu item on the calendar that would cause it to restart entire calendar equivalent to disabled/enabling plugin? That would at least allow the issue to be mitigated easily in one click.

**Comment by biosas** [comment]
With great joy I get to report that Gdata-Provider version 102.0.1 is working perfectly on Mac OS 10.15.7, thunderbird 102.3.3 !

Multiple gmail accounts, weird corporate calendars that I have to subscribe to, all of it !

Thank you , thank you thank you!

Happy camper again!

**Comment by nneul** [comment]
I don't know if it has anything to do with the failure or not (will be trying to delete the event in question) - but I see this in my error console log - might be worth looking at others who are seeing the 'stops syncing' problem and see if they see similar error/failure.

![image](https://user-images.githubusercontent.com/828492/208445327-f1921e85-3ea0-4527-b148-976f57e0aff6.png)

**Comment by nneul** [comment]
Interesting about that particular error/request - nothing immediately appears wrong about the json.

```{
   "description" : "Using Google Meet going forward",
   "end" : {
      "dateTime" : "2022-11-18T15:30:00",
      "timeZone" : "America/Los_Angeles"
   },
   "extendedProperties" : {
      "private" : {
         "X-MOZ-LASTACK" : "2022-12-15T22:21:21Z"
      }
   },
   "recurrence" : [
      "RDATE:20221118T190000Z",
      "EXDATE:20221123T190000Z",
      "EXDATE:20221216T190000Z",
      "EXDATE:20221219T190000Z",
      "EXDATE:20221221T190000Z",
      "EXDATE:20221223T190000Z",
      "EXDATE:20221226T190000Z",
      "EXDATE:20221228T190000Z"
   ],
   "reminders" : {
      "overrides" : [
         {
            "method" : "popup",
            "minutes" : 10
         }
      ],
      "useDefault" : false
   },
   "sequence" : 6,
   "start" : {
      "dateTime" : "2022-11-18T11:00:00",
      "timeZone" : "America/Los_Angeles"
   },
   "status" : "confirmed",
   "summary" : "Get Together"
}
```

which is getting this response from Google APIs:

```{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "Invalid start time."
   }
  ],
  "code": 400,
  "message": "Invalid start time."
 }
}
```

**Comment by carlosabalde** [comment]
I've trying to understand the issue and I found a tiny modification of the add-on that -so far- has fixed the issue for me. Details in https://github.com/kewisch/gdata-provider/discussions/497#discussioncomment-5188907 just in case somebody here wants to help testing it.

**Comment by kewisch** [comment]
This issue has collected quite a few comments from different reporters and I'm not really sure how to take appropriate action. I'm having trouble reproducing this, and I haven't yet seen logs that have given me the right hint.  The invalid start time issue seems unrelated to the sync, but could still be a problem.

With a heavy heart I'm going to close this issue. I'd appreciate if people still experiencing this issue could:

1) Upgrade to Thunderbird 115 and the latest provider.
2) Enable debugging as in the README
3) When filing a new issue, provide debug logging as noted in the readme between the last time the sync worked and the first time it didn't.

@nneul If you are still getting the invalid start time issue, can you file a new issue on this? Please provide details on how you created that event and what your OS timezone is, and what the timezone in Thunderbird is set to. I think what is missing is the '-07:00' at the end to indicate timezone, though I am not sure why it does not appear.
