### ISSUE TITLE
Hight CPU load after last extension update

### ISSUE THREAD

**Issue by bamyasi** [kewisch/gdata-provider#469]
### Describe the problem and steps to reproduce it:

Using Thunderbird 91.11.0 on Kubuntu 22.04 LTS. After the extension was upgraded today I am experiencing high CPU load for the Thunderbird process (>100%) and overall sluggish TB GUI.

### Anything else we should know?

It seems the problem arises from the extension trying to sync my subscribed calendars and failing to do so (Google blocks access?), then restarting from scratch, failing again, etc. This creates constant high CPU load and causes the GUI to slow down to a crawl. Also, for some reason I cannot unsubscribe from ALL of subscribed calendars, the last one is imp[ossible to remove/unsubscribe, TB won't let you to do this.

Tons of the same error messages repeated:
Calendar: [calGoogleCalendar] 2065-01-12T17:30:00-05:00 does not match timezone offset for America/New_York [gdataUtils.jsm:275](resource://gdata-provider/legacy/modules/gdataUtils.jsm)

Thanks,
Ivan

**Comment by Fist0urs** [comment]
I got the same problem and it is actually impossible to access the right menu to enable logs

**Comment by kewisch** [comment]
Haven't heard back from the issue author, closing this out for now.
