### ISSUE TITLE
Gdata-Provider stops working after Tunderbird & Lighning updated to 68.4.1

### ISSUE THREAD

**Issue by rmc-va** [kewisch/gdata-provider#47]
Provider for Google Calendar - 68.2.1
Thunderbird & Lightning - 68.4.1
Windows 10 Home 1909 (18363.592)

Almost all of the commands dealing with the calendar in Thunderbird are grayed out.  My Google and other calendars no longer show up as an entry in the list of calendars.   Individual calendar entries appear on calendar tab with existing info but are read only.  I can not even open an individual calendar entry or create a new one.

I used to be able to recover from this situation by closing the calendar in Thunderbird and then closing Thunderbird.  Create new event or edit an existing event by logging into Google Calendar directly.  Logoff Google Calendar and then logon to Thunderbird and either open the Today Pane or the Calendar tab.   

Any help would be appreciated.

**Comment by gdsotirov** [comment]
You problem seems familiar to me (see #33), but it's rather with Lightning than with gdata-provider. I still do not have a definitive solution, but there are some workarounds.

**Comment by rmc-va** [comment]
Thanks for the pointing out the other thread.   Tried the workarounds but they did correct the problem.

**Comment by gdsotirov** [comment]
@rmc-va Did or did not?

**Comment by rmc-va** [comment]
Sorry - Sometimes I just can't type!   They did not correct the problem.

You were right about it being a Thunderbird/Lightning created problem.

When I opened Thunderbird today, it and Lightning had updated itself to 68.4.2 which includes a fix for:

Calendar: Various parts of the calendar UI stopped working when a second Thunderbird window opened

This fix appears to resolve the ghosting of my calendars on Thunderbird. I will add a post here if that changes.

**Comment by rmc-va** [comment]
Sorry for the delay in updating this thread.  Here's a link to a similar thread with a solution that worked repeatedly for me:
https://support.mozilla.org/en-US/questions/1278196?utm_campaign=questions-reply&utm_medium=email&utm_source=notification#answer-1313937

**Comment by rmc-va** [comment]
I am also posting the proposed solution here - just in case you don't want to search thru the whole thread:
"john.thompson Mar 6, 2020, 4:54:00 PM

Folks, we're making progress here.

Thanks dbstraffin for the info, and glad this worked for you. For me, initially it didn't, but it now has. AND I KNOW WHY, AND I CAN REPRODUCE THE BUG!!

Sorry to be so extatic but when you've been wrestling with a seemingly mindless problem for months and you finally solve it, that feels good as we all know.

After resetting toolbars and controls, and with the calendar working as it should, I naturally reset my toolbars and controls, and in particular three things, to the way I like them. These settings are:

   In calendar, multi-week view
   In calendar, list of entries at top of screen to show "Events in current view"
   In mail Today pane, categories "Tomorrow" and "Upcoming" are expanded. 

To cut a long story short, it turns out that the "Events in current view" option for the list at the top of calendar, was causing the problem for me.

I can reproduce at will. All you have to do is select another option, such as "next 7 days". No messing about with "save mode" etc. Then re-start TB in normal mode and then problem disappears.

I will post this info to the bug report

Thanks again to dbstraffin whose suggestion about resetting toolbars and controls pointed me in the right direction."

**Comment by gdsotirov** [comment]
Really, how could one expect that "Events in current view" option is causing these problems... but the workaround to change to "Events in the next 7 days" works for me too :-) I really hope however the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1596919) is found and fixed, because "Events in current view" is the most useful option for me.

**Comment by atscomms** [comment]
DangBob! What a weird lookin' bug! I didn't believe it either, but it worked, at least for now.
It may be the first solid lead for the coders to look at since being reported.
Thank you, and keep us posted.
