### ISSUE TITLE
Calendar Freezing Thunderbird... on Windows 10 Pro only (not Windows 10 Home)

### ISSUE THREAD

**Issue by Tchibeck** [kewisch/gdata-provider#473]
Hello world,

I have 3 PC under Windows 10
One under Windows 10 Pro with 64 GB RAM, 2 others, under Windows 10 Home with 16 GB RAM

- My Wife computer, on wich she wants the minimum stricly necessary. On her computer, Thunderbird latest release 102.1.1 works perfectly well with Calendar (Gdata Plug-in)

- My Main computer wich run Windows 10 Pro

- My Spare computer wich run Windows 10 Home, ,and is the most possible copy of my main computer. Exactly same softwares are installed (and on wich data were synch via Dropbox)

(haven't tried under Linux PCs, beeing bored to spend too much time in front of PCs, trying to unfreeze softwares).

My first remark is, off topic, not only Thunderbird is slow to start when Google Data Provider plug-in is active.

Also some other softwares, (stupid i am), as i was used to work directly from a drive in wich all my data were... synchronized with Dropbox.

So, my Directory containing the local files of Thunderbiord is on Dropbox.

I have exported all my local e-mails of them in EML format, out of Dropbox. (10 years of mails.... wich were heavy to deal, asa long as to many files synched on Dropbox make them reindex slower)

And archived out of synch a lot of other data with no link with Thunderbird.

So, now what is my reporting  :

1° Even before extracting 70% of my Dropbox data from synch, both of the PCs working on Windows 10 Home had no problem at all with Gdata Provider (i share my calendar with my wife's computer)

No freezing at all, nore on my spare PC (Windows 10 Home)

Now, i have emptied most of the synch data from Dropbox, uninstalled Thnderbird and all traces of it, reinstall a clean Thunderbird on may main computer runninig Windows 10 Pro.... Thunderbird started to freeze again as soone as i installed Gdata Provider plug-in. Freezing approximatly 25 sesond before working nice.

None of the two other computers freeze : the strat Thunderbird immediatly and run Gdata Provider perfectly.

On My W10 Pro PC, i did resynch each Calendar one by one.

But nothing changed : Thunderbird freeze almost 30 seconds before runnig.

It doesn't freeze in safe mode nore if if deactivate temporarily Gdata Provider plug-in.

So my question is : Do other people experiences this problem on Windows 10 PRO, and could it be possible taht this problem with Gdata Provider occured becaus the OS is W10 PRO ?

Should i ask Microsoft to downgrade my license to W10 Home, knowing that i bought this PC without the choice : it was pre-installed with W10 PRO, wich i have no use ?

Sorry for my poor english, and thanks having read me.

**Comment by tt-aqt** [comment]
I'm  also seeing freezing due to the latest Provider version on Windows 10 Education 10.0.19044 and Thunderbird 102.2.2.

**Comment by pkarpin** [comment]
freezing for hours, high CPU and Memory usage, until it resolves and starts working --- started about 2 weeks ago with the upgrade. Uninstalled and Installed the add-on, but did not resolve the issue. Thunderbird works fine with add-on turned off.
- Windows 10 Pro, Version 21H1, OS build 19043.2006, Windows Feature Experience Pack 120.2212.4180.0
- Thunderbird 102.2.2 (32-bit)

**Comment by fmp-martins** [comment]
Same issue here on Kubuntu/Ubuntu:

- Kubuntu 20.04 Linux kubuntu 5.4.0-131-generic, 64 bits
- Thunderbird 102.2.2 (64-bit)

Tried to set up the debug log but was not able to following the given instructions.

**Comment by kewisch** [comment]
The usual issue is that the initial sync will hang Thunderbird. I can't reasonably influence that in the add-on, this needs substantial changes in Thunderbird. In the best case, if you let it sit for a while that initial sync will complete, and then subsequent updates will be quick and not hang.

Is this what you all are seeing?

**Comment by Tchibeck** [comment]
Sorry to think i was right : when updated to Thunderbird 103.x.x 64 bits, the issue desappeared.
So it was actully a problem bitween Thunderbird and Gcalendar wich had been announced to be solved with thé coming release of Thunderbird 103.x.x
For my part the issue doesn't exist anymore.
Thanks having been trying to help.
