### ISSUE TITLE
Can't create event with default reminder

### ISSUE THREAD

**Issue by benbaylis** [kewisch/gdata-provider#48]
Provider 68.2.1 in thunderbird 68.4.1 is refusing to create events with default reminder. I saw this in the error console (ctrl+shift+J):
defaultReminders is undefined 7 gdata-lightning-item-iframe.js:144

If set a non-default reminder I can create an event. 

Looking at thunderbird/lightning calendar options I see the default reminder is set to 15 minutes.

**Comment by kewisch** [comment]
This was fixed in 91.0.1
