### ISSUE TITLE
Invitations not sent while creating an event

### ISSUE THREAD

**Issue by Fist0urs** [kewisch/gdata-provider#482]
### Describe the problem and steps to reproduce it:

While creating an event with invitations, invitations are not sent and are not recorded in the event entry on the organizer's calendar (both in this add-on and gmail.com calendar).

Step to reproduce:

1. Create invitation
2.  Add attendes
3. Send

### Anything else we should know?

Thunderbird version: 91.12.0 (x64)
Add-on version: 102.0.0

Debug log:

```
Calendar: [calGoogleCalendar] Freebusy query for mailto:xxx.yyy@ccc.com succeeded, returning 5 intervals gdataSession.jsm:466
Calendar: [calGoogleCalendar] Adding regular event bla gdataCalendar.jsm:491
Calendar: [calGoogleRequest] Requesting POST https://www.googleapis.com/calendar/v3/calendars/me%40gmail.com/events
[...]
POST https://www.googleapis.com/calendar/v3/calendars/me@gmail.com/events
[HTTP/2 200 OK 331ms]
```

No trace of "xxx.yyy@ccc.com" invitation in the POST request:

```json
Calendar: [calGoogleCalendar] Parsing entry:
{
 "kind": "calendar#event",
 "etag": "\"***\"",
 "id": "***",
 "status": "confirmed",
 "htmlLink": "https://www.google.com/calendar/event?eid=***",
 "created": "2022-08-19T10:24:26.000Z",
 "updated": "2022-08-19T10:24:26.176Z",
 "summary": "bla",
 "creator": {
  "email": "me@gmail.com",
  "self": true
 },
 "organizer": {
  "email": "me@gmail.com",
  "self": true
 },
 "start": {
  "dateTime": "2022-08-19T14:30:00+02:00",
  "timeZone": "Europe/Paris"
 },
 "end": {
  "dateTime": "2022-08-19T15:30:00+02:00",
  "timeZone": "Europe/Paris"
 },
 "iCalUID": "***@google.com",
 "sequence": 0,
 "reminders": {
  "useDefault": true
 },
 "eventType": "default"
}
```

I guess it comes from here:

https://github.com/kewisch/gdata-provider/blob/effc4fc8988b896f3f5b0f4b1e956094fd3b1a25/src/background/calendar.js#L214-L222

**Comment by stkogr** [comment]
I have the same issue!

**Comment by mhalano** [comment]
I have an issue that, I think, is related: when I accept an invitation for a meeting it adds to Thunderbird's calendar but not in Google Calendar

**Comment by kewisch** [comment]
Version 102.0.0 comes from the `legacy` branch, where that code is still functional. Can you make sure you have the relevant scheduling/invitations options enabled in the add-on preferences?

**Comment by Fist0urs** [comment]
> Version 102.0.0 comes from the `legacy` branch, where that code is still functional. Can you make sure you have the relevant scheduling/invitations options enabled in the add-on preferences?

I have the relevant scheduling/invitations options enabled in the add-on preferences

**Comment by punknroll** [comment]
Same problem here.

**Comment by kewisch** [comment]
I've tried to reproduce this, but the attendees show up for me. Can you make sure to re-subscribe to your calendars after enabling the scheduling options in the add-on prefs? Also, please try again on Thunderbird 115
