### ISSUE TITLE
gdata-provider not syncing certain modifications of Google Tasks when changes made in Google Tasks web & Android apps

### ISSUE THREAD

**Issue by David-I-SW** [kewisch/gdata-provider#49]
Using Slackware64 Linux 14.2 with Tbird 68.4.1 (64-bit).
The following changes to tasks, when made using Google's own Google Task apps, do not sync back to TB via gdata-provider (68.2.1):
Changes in dates
Changes in task status
Task deletions.
Otherwise this extension seems to work pretty perfectly.

**Comment by David-I-SW** [comment]
There seems to be a workaround. In summary:
All entries in Thunderbird tasks sync perfectly with Google tasks.
All entries made in Google tasks sync with Thunderbird **apart** from:

- Changes in dates
- Changes in task status
- Task deletions.

However, if you unsubscribe from the 'calendar' which is linked to the task list in Thunderbird and then re-subscribe, gdata-provider picks up everything correctly.
A bit troublesome, but workable for now.

**Comment by Tarneil** [comment]
Exactly same problem here.
Win 10 (64), TB 68.5.0 (32), Provider for Google Calendar 68.2.1.

**Comment by mallniya** [comment]
Same.
Ubuntu 19.10, TB 68.4.1 (64-bit), Provider for Google Calendar 68.2.1.

**Comment by MasterGameOne** [comment]
Exactly same problem.
Win 10 (64), TB 68.6.0 (32), Provider for Google Calendar 68.2.1.

**Comment by AndiG-DE** [comment]
Same for me. TB68.7.0, Provider for Google Calendar 68.2.1. The workaround of David-I-SW works, but it's not very comfortable. Any chance, that this will be fixed?

**Comment by alexivkin** [comment]
Unfortunately that workaround only works for the past events. New events created outside of TB or events modified outside of TB after the workaround are still failing. Added more details in the report when updates are done on google.com here - #72

**Comment by kewisch** [comment]
Please re-test on Thunderbird 91 if this is still an issue and re-open if necessary.

**Comment by David-I-SW** [comment]
Hi Philipp - thanks for all your hard work on this; much appreciated 😀

Kind regards,

David.

David B. Ingham
Support software freedom - visit:
https://www.fsf.org/ <http://www.fsf.org/>
https://www.opensource.org/ <http://www.opensource.org/>

**Comment by kewisch** [comment]
Appreciate it David! Should be close with full functionality in 91, was great to go through all the open issues.
