### ISSUE TITLE
Provider button all of a sudden disappeared

### ISSUE THREAD

**Issue by dellow3** [kewisch/gdata-provider#494]
All of a sudden, the Provider button disappeared in TB 102.2.2.  I have not updated TB, and it's not set to update automatically.  But it stopped working.  I rely on your excellent extension and hope that you can help me fix this.  It was working find yesterday.  But there is no button anymore.  I uninstalled and reinstalled the extension with no luck.

**Comment by MoralCode** [comment]
have you tried following the debugging steps in the README to get error logs or other detailed information to help narrow down the issue?

**Comment by kewisch** [comment]
Can you try the latest version? I've made some recent fixes that might have affected this.
