### ISSUE TITLE
cannot accept invitation to any google calendar

### ISSUE THREAD

**Issue by MLopez-Ibanez** [kewisch/gdata-provider#50]
When trying to accept this invitation, no Google Calendar is shown as an option:

[bug.txt](https://github.com/kewisch/gdata-provider/files/4108774/bug.txt)

Name 	Thunderbird
Version 	68.4.1
gdata-provider 68.2.1

**Comment by markusb68** [comment]
Same here Versio 4.42. and TB Version 60.9.1

**Comment by kewisch** [comment]
This should be resolved with Thunderbird 91

**Comment by kewisch** [comment]
Apologies, was too quick on this. I have an upcoming patch for Provider 91.0.2, please wait until that is released and try again.
