### ISSUE TITLE
Warning to stop using unsupported OAuth flows

### ISSUE THREAD

**Issue by scarf** [kewisch/gdata-provider#508]
Hi I just installed the add-on and received the below warning after logging into my Google account.  Just wanted to let you know so you can take it into account in the next release.  Also tried to notify provider-for-google-calendar@googlegroups.com but received bounce-back error that it "does not allow posting through email" so you might want to address that as well.

> 
> To help protect your account, Google will soon block apps that don’t comply with Google’s security policies.
> You can let the [app developer](mailto:provider-for-google-calendar@googlegroups.com) know that this app should stop using unsupported OAuth flows. [Learn more](https://support.google.com/accounts/answer/12379384).
> If you're the app developer, see the [migration guide](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration).

**Comment by zak1388** [comment]
I think my issue is related, it seems google no longer supports the oauth flow of the extension

> Unknown localization message errors.
> �invalid_request���
> you can't sign in to this app because it doesn't comply with google's oauth 2.0 policy for keeping apps secure.
> 
> you can let the app developer know that this app doesn't comply with one or more google validation rules.
>   �3https://support.google.com/accounts/answer/12379384 ��*&
> 
> login_hint��zakar> Unknown localization message errors.
> �invalid_request���
> you can't sign in to this app because it doesn't comply with google's oauth 2.0 policy for keeping apps secure.
> 
> you can let the app developer know that this app doesn't comply with one or more google validation rules.
>   �3https://support.google.com/accounts/answer/12379384 ��*&
> 
> login_hint��MY_EMAIL@gmail.com*�
> �hl��en-gb*�
> 
> response_type��code*.
> �redirect_uri��urn:ietf:wg:oauth:2.0:oob:auto*u
> 	client_id�.apps.googleusercontent.com*�
> �access_type��offline*w
> �scope�nhttps://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/tasks2�������the out-of-band (oob) flow has been blocked in order to keep users secure. follow the out-of-band (oob) flow migration guide linked in the developer docs below to migrate your app to an alternative method.�ohttps://developers.google.com/identity/protocols/oauth2/resources/oob-migration [ExtensionCommon.jsm:2070](resource://gre/modules/ExtensionCommon.jsm)�
> �hl��en-gb*�
> 
> response_type��code*.
> �redirect_uri��urn:ietf:wg:oauth:2.0:oob:auto*u
> 	client_id�.apps.googleusercontent.com*�
> �access_type��offline*w
> �scope�nhttps://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/tasks2�������the out-of-band (oob) flow has been blocked in order to keep users secure. follow the out-of-band (oob) flow migration guide linked in the developer docs below to migrate your app to an alternative method.�ohttps://developers.google.com/identity/protocols/oauth2/resources/oob-migration [ExtensionCommon.jsm:2070](resource://gre/modules/ExtensionCommon.jsm)

This is all straight from the error console and there's no indication to really tell you otherwise somethings gone wrong other than your calendars not showing up.
Process is the same as described above, I pressed add new calendar, selected the google calendar provider, entered my email, signed in, but then the window thats meant to show your calendars is empty, and this appears in the error console

**Comment by scarf** [comment]
Yes, I had that issue too with seeing an empty list of calendars after signing in.  I simply tried again and started over a second time and, after logging in, it worked fine, showing my list of calendars and importing them.  Just tried creating a new event in TB and it successfully pushed it to my Google calendar, so things are still connected and working here.  Maybe try going thru the process again?  and if you see the blank listing just re-try a second time, let us know if that helps...

**Comment by zak1388** [comment]
no dice, it seems, error console seems to still have the same issue

**Comment by kgday** [comment]
I have the same issue as zak1388 with same errors in error console.

**Comment by fldugue** [comment]
I have the same issue, too (except localization). Log from the error console is attached.
[2022-10-25 FD - Google Calendar Provider, error console.txt](https://github.com/kewisch/gdata-provider/files/9863408/2022-10-25.FD.-.Google.Calendar.Provider.error.console.txt)

**Comment by mluypaert** [comment]
As this issue now breaks the addition of any new google calendars to thunderbird, or reauthentication of existing ones, please prioritize a fix for this.

**Comment by kewisch** [comment]
This should be fixed in 102.0.3, please open a new issue in case not :)
