### ISSUE TITLE
Problems with TB 73.0b1 and provider 68.2.1

### ISSUE THREAD

**Issue by nurbles** [kewisch/gdata-provider#51]
I don't know exactly when my calendar stopped synchronizing with google, but today I tried to find a way to fix it and it only got worse.  I found many comments that re-installing the provider fixed the issue so I told TB to remove it, restarted TB, downloaded the latest version from [Thunderbird Add-ons - Provider for Google Calendar](https://addons.thunderbird.net/en-US/thunderbird/addon/provider-for-google-calendar/), installed the new .xpi file and restarted TB again.

At that point, TB was unable to even **CHECK MAIL**!  (It appeared hung for a long time and then said the connection timed out.)  A mysterious tall, narrow (about twice as tall as wide) window appeared on top of TB, but it didn't even have a title, just a close button in the top right corner.  I rebooted my computer and tried again with the same results.  I told TB to disable the provider add-on, restarted TB and it immediately checked and downloaded my mail.

I am willing to try almost any diagnostic procedures requested, if it will help.  Also, I am running Windows 10 Home (64 bit) version 1903 build 18362.592, Thunderbird 73.0b1 (32 bit) and provider_for_google_calendar-68.2.1-tb.xpi.  The only other add-on I have installed is Lightning, also version 73.0b1.

**Comment by kewisch** [comment]
#77 should fix this with Thunderbird 78, let me know if that isn't the case.
