### ISSUE TITLE
Main Calendar not showing up despite being subscribed

### ISSUE THREAD

**Issue by bradnak** [kewisch/gdata-provider#513]
### Describe the problem and steps to reproduce it:

1. Subscribe to the user's initial calendar on their Google account (mine is labelled "My Calendar" but I have seen others labelled with their email)
2. Let the calendar synchronise (the status bar indicates that events are being retrieved)
3. Observe that events from this calendar do not appear.

### What happened?
The calendar events do not appear in Thunderbird. Events from other calendars on the Google Account appear correctly, even when subscribed through the same login connection.
### What did you expect to happen?
The events should appear on the calendar.
### Anything else we should know?
I have tried unsubscribing and re-subscribing. This has been a long-standing issue for me, which has caused me to not notice events unless I go to Google Calendar in my browser. 

Last 3 log events (verbose on as requested):
```
Calendar: [calGoogleCalendar] Logging calIEvent:
	id:7vv2prhd8vp192htdkuj7ui6mn@google.com
	created:2021-06-17T04:53:49Z
	updated:2021-07-19T21:35:57Z
	title:Pfizer Vaccination Dose 1
	description:null
	transparency:null
	status:CONFIRMED
	startTime:2021-07-07T09:45:00
	endTime:2021-07-07T10:45:00
	location:5/8 Memorial Dr, Shellharbour City Centre NSW 2529, Australia
	privacy:null
	sequence:0
	alarmLastAck:null
	snoozeTime:null
	isOccurrence: false
	Organizer: 
		ID: mailto:bradnak@bigpond.com
			Name: undefined
			Rsvp: null
			Is Organizer: yes
			Role: null
			Status: NEEDS-ACTION
	Attendees: 
	recurrence: no
	alarms: yes: 
		
		Action: DISPLAY
		Offset: -PT5M
		alarmDate: null
		related: 1
		repeat: 0
		repeatOffset: null
		repeatDate: null
		description: null
		summary: null
		properties: yes:
			X-DEFAULT-ALARM:TRUE
gdataLogging.jsm:16

Calendar: [calGoogleCalendar] Error syncing:
2147500037: (resource://gdata-provider/legacy/modules/gdataUtils.jsm:1195):TypeError: item.recurrenceInfo is null gdataCalendar.jsm:990
uncaught exception: [calCachedCalendar] replay action failed: <unknown>, uri=googleapi://bradnak@bigpond.com/?calendar=bradnak%40bigpond.com, result=item.recurrenceInfo is null, operation=[xpconnect wrapped calIOperation]

```

**Comment by bradnak** [comment]
Looking at my logs, as requested for this issue, is it just that event that's broken? It's an old one, I could delete it?

**Comment by xjonx1** [comment]
There was an issue with the add-on and is now fixed by the developer. Details here: https://github.com/kewisch/gdata-provider/discussions/519#discussioncomment-4147395

**Comment by bradnak** [comment]
I can confirm that the update has fixed my issue. Thank you.
