### ISSUE TITLE
Can't modify calendar events because of usage exceeded without signup

### ISSUE THREAD

**Issue by e4lam** [kewisch/gdata-provider#52]
I can't seem to modify my google calendar events. I enabled logging and got this error

![image](https://user-images.githubusercontent.com/1538077/73572391-aa0f1e00-443e-11ea-9fe9-c754a5b24a51.png)

right before I get this error:

```
Lightning: [calGoogleCalendar] Modifying item Important Event failed:2147500037: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "forbidden",
    "message": "Forbidden"
   }
  ],
  "code": 403,
  "message": "Forbidden"
 }
}
```

I've tried disabling and re-enabling the provider extension to no avail. What's weird here, is that I never seem to get prompted anymore to enter my google password. How do I get Thunderbird/Google Provider to prompt me for my google password so that I can sign in again?

Using these versions:
- Thunderbird 68.4.2 (32-bit) on Windows
- Lightning 68.4.2
- Provider for Google Calendar 68.2.1

**Comment by e4lam** [comment]
PS. I just checked my https://myaccount.google.com/permissions page and it says:
>>>- Mozilla Thunderbird EMail - Has access to GMail
Provider for Google Calendar - Has access to Google Calendar

**Comment by kewisch** [comment]
Can you try unsubscribing, removing all related password manager entries, and re-subscribing to the calendar? Please re-open if this is still an issue.
