### ISSUE TITLE
No calenders showing up

### ISSUE THREAD

**Issue by idkhowtocode642** [kewisch/gdata-provider#520]
when i create a new calendar, select google calendar, press next and then enter my email and press find calendars.
The window labelled sign into your account ******@gmail.com pops up for a millisecond (the provider for google calendar would like to... etc) then is replaced by a window labelled create new calendar reading please select the calendars and task lists you would like to subscribe to with no options available. i have not had this issue in any prior issues of thunderbird (love your work?)

**Comment by idkhowtocode642** [comment]
![Screenshot from 2022-10-26 19-24-04](https://user-images.githubusercontent.com/59237849/197989119-f83deeb1-7d32-4772-b9e7-c3d8399ebf2e.png)
![Screenshot from 2022-10-26 19-23-50](https://user-images.githubusercontent.com/59237849/197989124-5227553c-acb4-4294-aa21-a77e1613d990.png)

**Comment by mmeah-riverstar** [comment]
Same issue

**Comment by leoliuf** [comment]
Same here

**Comment by cunningsound** [comment]
Same Problem

**Comment by MikeyMikeyTanTan** [comment]
This is this problem / issue:

https://github.com/kewisch/gdata-provider/discussions/519

https://github.com/kewisch/gdata-provider/issues/521

with a hint it might get addressed soon:
https://twitter.com/pkewisch/status/1587580142922104832

**Comment by kewisch** [comment]
This should be fixed in 102.0.3, please open a new issue in case not :)

**Comment by idkhowtocode642** [comment]
Thanks :D love your work btw
