### ISSUE TITLE
Thunderbird 102.4: Provider login dialog disappears immediately, no login possible

### ISSUE THREAD

**Issue by CarloGraziani** [kewisch/gdata-provider#521]
### Discussed in https://github.com/kewisch/gdata-provider/discussions/519

<div type='discussions-op-text'>

<sup>Originally posted by **CarloGraziani** October 25, 2022</sup>
Hi.
I just installed Thunderbird 102.4 from a tarball on Ubuntu 20.04. When I installed the Provider for Google Calendar, all seemed to go well right up to the point when I attempted to connect to my calendar. Then a window -- which I think is almost certainly the Google login window -- blinks in and out, leaving behind a "Create New Calendar" window with a blank list of calendars and tasks to choose from.

I'm not sure how to troubleshoot this. Is there a debug log that I can turn on?</div>

**Comment by schnittchen** [comment]
Same issue here, on Linux (Pop!OS, effectively Ubuntu 22.04).

The addon is getting 1-star reviews because of this https://addons.thunderbird.net/en-US/thunderbird/addon/provider-for-google-calendar/

**Comment by CarloGraziani** [comment]
> Same problem here on WIndows 11 with Thunderbird 102.4
> 
> edit: the debug log tells me the issue seems to be with a new OAuth flow: https://support.google.com/accounts/answer/12379384

That's interesting. How did you turn on a debug log? I'd like to try to reproduce that.

**Comment by BaffoBill** [comment]
Same problem here on Windows 10 with Thunderbird 102.4.1

How can i turn on a debug log?

**Comment by jnsbck** [comment]
Also got the same problem.
Thunderbird v102.2.2, Ubuntu 20.04

This is the console log:
![image](https://user-images.githubusercontent.com/65561470/198987630-3173e980-b785-4420-8dc4-fcaab264035b.png)

**Comment by thehrushi** [comment]
Having the same issue, with the same console log as @jnsbck

**Comment by MisterDeeDee** [comment]
Same problem here. If you need more info just reply me.

**Comment by flammobammo** [comment]
Same here, Windows 11, TB 102.4.1 x64. 

Literally just left Outlook to TB because Outlook's IMAP support is crap, but, also really looking forward to being able to edit a google calendar. Absolutely gobsmacked that Outlook have not worked out how to do this. Or chose not to support.

**Comment by Gerard64** [comment]
[https://twitter.com/pkewisch/status/1587580142922104832](![afbeelding](https://user-images.githubusercontent.com/7952595/199361521-849b1ea0-0c9c-407a-baea-be4b9ebd8202.png))

**Comment by Gerard64** [comment]
"Hey everyone, I am aware that the Provider for Google Calendar is not working due to an OAuth mechanism being removed, but I just cannot fix it right now as my team is organizing [http://summit.ubuntu.com](https://t.co/uHA2q6BQDR). I will get to this as soon as I can!"

https://twitter.com/pkewisch/status/1587580142922104832

**Comment by TokenRing** [comment]
Good grief. Did Google give developers like Phillipp any notification or heads up that they were changing/breaking existing OAuth methods or did they just do it, heedless of what plugins and extensions it would break? That's So Google.

In any case, those of us who have been using Phillipp's extension for years know he's an excellent developer and will fix it when he can. His time is valulable and of course he has other things going on. To heck with the one-star hatin' plebs on the mozilla extension pages.

**Comment by CarloGraziani** [comment]
> Good grief. Did Google give developers like Phillipp any notification or heads up that they were changing/breaking existing OAuth methods or did they just do it, heedless of what plugins and extensions it would break? That's So Google.
> 
> In any case, those of us who have been using Phillipp's extension for years know he's an excellent developer and will fix it when he can. His time is valulable and of course he has other things going on. To heck with the one-star hatin' plebs on the mozilla extension pages.

No, they did not. And I fear that the fix may not be a simple revert of a patch, as Phillipp is suggesting on his Twitter feed. If you look at the contortions required by users to get themselves successfully authenticated by Google in order to use the [Google-4-TbSync](https://github.com/zanonmark/Google-4-TbSyncurl) extension, documented [here](https://github.com/zanonmark/Google-4-TbSync/wiki/How-to-generate-your-own-Google-Cloud-Console-project-credentials), you may start to wonder whether Google has decided to drive away open-source developers altogether.

The procedure requires _users_ (not developers) of the extension to go to their Google Cloud Console (what?), and then go through a series of easily screwed-up procedures that essentially make them create their own "cloud project" as if they were _bona fide_ cloud developers, navigating opaque jargon-filled screens that must make sense to folks who read AWS and Azure docs, but might as well be counting-rhyme doggerel in Sanskrit formatted as man pages as far as an average Thunderbird extension user is concerned.

According to the extension's author, Google's justification for this idiocy is that ["Developer credentials may not be embedded in open source projects."](https://developers.google.com/terms#b_confidential_matters)  I do not have enough knowledge of authentication protocols to comment on whether there exist alternative methodologies that would allow an open source developer to produce a mechanism that does not force users to go through this crazy, obviously error-prone and discouraging and utterly stupid process (create a cloud project to read a calendar? really?).  If this really is the only way forward, then perhaps it might be a good idea for some large open source players (such as \<cough\> Canonical \<cough\>, Phillipp) to make some Views on the subject known to Google.

**Comment by TokenRing** [comment]
Thanks for your input Carlo - yes, of course I immediately had the idea as soon as I saw the issue that Google, of course, wants everyone in calendar.google.com - they don't want, or like, people using 3rd party applications to access their systems. Making things as convoluted and difficult as possible for both developers using their APIs, and end-users who want to use 3rd party extensions, is almost certainly the goal of the post "don't be evil" Google.

**Comment by ChristopheForever** [comment]
Having the same issue.

**Comment by olivierterlez** [comment]
![image](https://user-images.githubusercontent.com/117501887/200104124-2160d90f-dd8a-4b4b-b78d-36f4f8ab9b8a.png)
Same for me. Just one second of the message and desappears. Windows 11 22H2 Thunderbird 102.4.1

**Comment by CarloGraziani** [comment]
> > Good grief. Did Google give developers like Phillipp any notification or heads up that they were changing/breaking existing OAuth methods or did they just do it, heedless of what plugins and extensions it would break? That's So Google.
> > In any case, those of us who have been using Phillipp's extension for years know he's an excellent developer and will fix it when he can. His time is valulable and of course he has other things going on. To heck with the one-star hatin' plebs on the mozilla extension pages.
> 
> No, they did not. And I fear that the fix may not be a simple revert of a patch, as Phillipp is suggesting on his Twitter feed. If you look at the contortions required by users to get themselves successfully authenticated by Google in order to use the [Google-4-TbSync](https://github.com/zanonmark/Google-4-TbSyncurl) extension, documented [here](https://github.com/zanonmark/Google-4-TbSync/wiki/How-to-generate-your-own-Google-Cloud-Console-project-credentials), you may start to wonder whether Google has decided to drive away open-source developers altogether.
> 
> The procedure requires _users_ (not developers) of the extension to go to their Google Cloud Console (what?), and then go through a series of easily screwed-up procedures that essentially make them create their own "cloud project" as if they were _bona fide_ cloud developers, navigating opaque jargon-filled screens that must make sense to folks who read AWS and Azure docs, but might as well be counting-rhyme doggerel in Sanskrit formatted as man pages as far as an average Thunderbird extension user is concerned.
> 
> According to the extension's author, Google's justification for this idiocy is that ["Developer credentials may not be embedded in open source projects."](https://developers.google.com/terms#b_confidential_matters) I do not have enough knowledge of authentication protocols to comment on whether there exist alternative methodologies that would allow an open source developer to produce a mechanism that does not force users to go through this crazy, obviously error-prone and discouraging and utterly stupid process (create a cloud project to read a calendar? really?). If this really is the only way forward, then perhaps it might be a good idea for some large open source players (such as <cough> Canonical <cough>, Phillipp) to make some Views on the subject known to Google.

I have one suggestion, predicated on the correctness of my diagnosis above (which is not a given), and hedged with the the acknowledgment that I have no actual specific expertise of authentication engineering:

Perhaps a version of the provider extension could be distributed open-source, without credentials, satisfying Google's TOS agreement. Upon installation in a user's Thunderbird client, however, the extension would connect to the developer's website and download  whatever binary authentication data is required to successfully connect to Google, presumably (I think) without violating either the open-source license of the extension or Google's TOS agreement.

**Comment by Gerard64** [comment]
Version 102.0.3 fixed the problem for me.
Thank you!

**Comment by LarrxX** [comment]
Same for me, thank you so much

**Comment by olivierterlez** [comment]
Update of Thunderbird 102.4.1 to 102.4.2 and it's ok for me now !

**Comment by BaffoBill** [comment]
PlugIn Version 102.0.3 fixed the problem.
Thank you!

**Comment by CarloGraziani** [comment]
I also confirm that the issue is fixed for me.  Thank you, Phillipp.  I'll close it now.
