### ISSUE TITLE
I want to access a person's Google calendar that I already have access to on my Google Calendar, but.....

### ISSUE THREAD

**Issue by onebrowtech** [kewisch/gdata-provider#522]
I recently had to replace my laptop's hard drive, but hadn't backed up my Thunderbird profile. 
Having reinstalled Thunderbird, and then access to my Google mail accounts, I noticed that one of the calendars that I have access to on one of those accounts, isn't showing up in Thunderbird on my laptop anymore. 
[But it _is_ showing up on my other (Android) devices.]
I have also reinstalled Provider, and tried using the "new calendar wizard" (as suggested by Phillip in the FAQs) and signed in with my own Google credentials - but the missing calendar doesn't show up - i.e. there is no "list" to choose it from.

Any help or advice would be much appreciated.
Many thanks.

**Comment by xjonx1** [comment]
There was an issue with the add-on and is now fixed by the developer. Details here: https://github.com/kewisch/gdata-provider/discussions/519#discussioncomment-4147395

**Comment by kewisch** [comment]
This could indeed be due to the OAuth issues. If this is still the case, does the other person's calendar show up in your Google Calendar on their website?
