### ISSUE TITLE
Not possible to use Provider in newest version of Thunderbird 68.4 - 68.5

### ISSUE THREAD

**Issue by lucamosca1** [kewisch/gdata-provider#53]
Hi there!
While latest version of provider still works correcty even if thunderbird get updated to the latest version, an installation and setup from scratch simply not working.
Issue found on:
Windows 10 - 64bits - Reinstalled and updated 2 weeks ago (jan 2020)
Ubuntu 19.10 - Thunderbird pre-installed from repo
Ubuntu 19.10 - Thunderbird installed from mozilla's repo ppa:mozillateam/ppa

The issue is the same:
- Install thunderbird and later install provider
- set up new calendars on network - gmail
- pass Google autentication that ends fine
- when I have to choose which calendar I want to sync, an empty window appear and I cannot select.

Available if you need some debug but I need to know how to do it :)

**Comment by jhs29er** [comment]
I'm having the same issue.  Look forward to updates.

**Comment by janbletz** [comment]
Same here.

**Comment by janbletz** [comment]
My problem only occurs with Thunderbird Portable, not on the regular Thunderbird (both 32 bits).

**Comment by lucamosca1** [comment]
Likelihood may increase in next two months when a lot of reinstallation will occur due to new ubuntu version.

**Comment by navennn** [comment]
Similar issue for me. Mint 19.
Works just fine in my older installation. Both have TB 68.4.1
I can see the authentication windows, but it keeps asking me like 5 to 10 times to authenticate each time I start thunderbird.

**Comment by SamuelDSelf** [comment]
Yup, Ubuntu 19.10, TB 68.4.1 64bit, fresh install, no write access to the calendars.

**Comment by TonyK132** [comment]
Does not sync with GMail with TB 68.5.0 32-bit in Win10-64.  Used to work on older TB (don't know version).

**Comment by lucamosca1** [comment]
Ubuntu 20.04 will be released in 10 days, means some TB reisntallation. Just FYI

**Comment by navennn** [comment]
In one of the comments I found that using tbsync addon + Provider for CalDAV & CardDAV will get your google calendar to work in TB. Works for me with v68.8.0.
Quick set up guide - screenshots there https://addons.thunderbird.net/en-US/thunderbird/addon/dav-4-tbsync/
Basically it replaces the whole thing and works great.

**Comment by kewisch** [comment]
This should be resolved in Thunderbird 91.
