### ISSUE TITLE
Provider Calendars GUI problem

### ISSUE THREAD

**Issue by atscomms** [kewisch/gdata-provider#54]
Installed versions are:
Lightning 68.4.2
Provider 68.2.1

I can see existing events from all Google calendars. They are without their assigned colors and cannot be edited or added to. The Calendar list is blank, there are seven.
![Calendar Problem](https://user-images.githubusercontent.com/60936473/74260328-5797f200-4cc7-11ea-9695-53907ac7648b.jpg)

I've tried disabling and removing and reinstalling both add-ons multiple times. I have disabled Lightning Calendar Tabs and Rise of the Tools

I tried the procedure in "Lightning disappears after a Thunderbird update (release and beta versions)", without improvement. I also tried deleting the files      
extensions.sqlite
extensions.sqlite-journal (if found)- not found
extensions.ini- not found
extensions.json 

Thank you

**Comment by gdsotirov** [comment]
Please, look at #33

**Comment by atscomms** [comment]
Thanks. It looks like this is an ongoing issue.
    FYI, I've tried many if not all of the proposed recommendations
      and none have fixed the problem. I'll keep an eye on the forums.
    Thanks
    
    
      
      
      Marty
      
      
    
    On 2/11/2020 1:04 PM, Georgi D. Sotirov
      wrote:
    
    
      
      Please, look at #33
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kewisch/gdata-provider/issues/54?email_source=notifications\u0026email_token=AOQ5CGKZBVAOAJO2ONN4ERTRCLSDDA5CNFSM4KTFFDYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELNOPJQ#issuecomment-584771494",
"url": "https://github.com/kewisch/gdata-provider/issues/54?email_source=notifications\u0026email_token=AOQ5CGKZBVAOAJO2ONN4ERTRCLSDDA5CNFSM4KTFFDYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELNOPJQ#issuecomment-584771494",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by gdsotirov** [comment]
@atscomms Yes, it bugs me for several months already, but it's more with Lightning than with gdata-provider I think. Have you tried switching `extensions.installedDistroAddon.{...}` setting and reinstalling Lightning? It's the workaround for me after each restart of Thunderbird.

**Comment by atscomms** [comment]
Hi,
    I hope everyone is safe & healthy.
    Has there been any progress on this bug?
    
    Not only does this problem persist, the config parameter does not
      always appear. Sometimes after reseting it and restarting the
      program, the calendar is still abnormal and the parameter is
      missing.
    Thank you
    
    
      
      
      Marty Atias
      ATS Communications
        301-754-2871
      
    
    On 2/12/2020 1:49 AM, Georgi D. Sotirov
      wrote:
    
    
      
      @atscomms
        Yes, it bugs me for several months already, but it's more with
        Lightning than with gdata-provider I think. Have you tried
        switching extensions.installedDistroAddon.{...}
        setting and reinstalling Lightning? It's the workaround for me
        after each restart of Thunderbird.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kewisch/gdata-provider/issues/54?email_source=notifications\u0026email_token=AOQ5CGNYWIOIM7MM5Z3O4BTRCOLWXA5CNFSM4KTFFDYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELPUEWA#issuecomment-585056856",
"url": "https://github.com/kewisch/gdata-provider/issues/54?email_source=notifications\u0026email_token=AOQ5CGNYWIOIM7MM5Z3O4BTRCOLWXA5CNFSM4KTFFDYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELPUEWA#issuecomment-585056856",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by atscomms** [comment]
Still having this issue, now on V 68.7.0 (32bit)
 Resetting "extensions.installedDistroAddon.{...}" in advanced config, then removing the Lighting add-on sometimes works but many times does not.

This is extremely frustrating and wastes lots of time! Is anyone working on this? 
Thank you

**Comment by brunis** [comment]
Hi,

No, noone has been working on this for a long time.

**Comment by gdsotirov** [comment]
@atscomms @brunis Checkout the workaround suggested in #47 ;-)

**Comment by kewisch** [comment]
This should be resolved in Thunderbird 91
