### ISSUE TITLE
Still experiencing 'Can't dismiss past events' issue in version 102.0.3

### ISSUE THREAD

**Issue by freshflyingfish** [kewisch/gdata-provider#542]
### Describe the problem and steps to reproduce it:

I am having trouble dismissing calendar notifications. It is never straight forward, but most frustrating is that I am getting notifications for past events. If the event was created by someone else (ie an invitation that I have accepted), I cannot dismiss it at all. 

(Please include as many details as possible.)

### What happened?

The notification windo popped up. 
I pressed Dismiss All button. 
Some events were dismissed, but events created by other people remain. 

### What did you expect to happen?

All events too be dismissed. 
No notification at all for past events unless they have been postponed. 

### Anything else we should know?

This is the same error that was supposed to be fixed in version 91 (I think), but it still occurs in version 102.0.3. 

I am currently running Thunderbird 102.5.0 (64bit) on Windows 10 Home version 21H1, but I experience the same problem on my Ubuntu Studio 22 install. 

This fault is so frustrating that I have uninstalled Provider in the past, finding it easier to copy and paste invitation details into the calendar on a browser. 

I hoped it would be resolved by now.

**Comment by kewisch** [comment]
Totally agree this is frustrating. There is a setting to not show missed alarms in Thunderbird which is the best bet right now. For everything else see #3. I've fixed this in an upcoming version of the Provider, but it might be a while until it is ready for release as it is almost a rewrite.
