### ISSUE TITLE
Thunderbird 91.13.1: Provider login dialog disappears immediately, no login possible

### ISSUE THREAD

**Issue by krettek** [kewisch/gdata-provider#548]
Hi, 

I got the same problem with the plug-in as already solved for the thunderbird 102 Version.
Unfortunately I can not update to this version, so maybe it's possible to update the plugin also for the 91 Version?

Thanks!

**Comment by shibmaster** [comment]
Same issue for me on TB 91.7.0. Cannot update since it is maintained by the company.
No issues on 102.7.1 on my other device.

**Comment by BillyTom** [comment]
I recently update from Thunderbird 78.12.0 and Provider for Google Calendar 78.0.2 to Thunderbird 91.13.1 and Provider for Google Calendar 102.0.0 to escape the following bug:  #255

But the update brought me no peace. I now have this bug instead.

**Comment by kewisch** [comment]
Unfortunately I can no longer support Thunderbird 91. Hope you have a chance to upgrade soon. 115 comes out on Monday :)
