### ISSUE TITLE
Calendar not synchronizing

### ISSUE THREAD

**Issue by naeldue** [kewisch/gdata-provider#549]
Hello.
I use this extension since few years now. Thanks for it.
Since about a month, I can notice that events created out of thunderbird are not synchronizing in it.
This works well when I create an event inside. Yet from another thunderbird (on another location) that synchronized with google, or from google directly, it doesn't appear.
When I opt out of the agenda, and then opt in, all events are well synchronised. 
Is there st I can do to make it work?
br.
Naël

**Comment by mackintg** [comment]
This is probably another symptom of [this thoroughly discussed problem](https://github.com/kewisch/gdata-provider/discussions/497).

**Comment by naeldue** [comment]
Hello. I can say that it doesn't solve the problem. Calendars resync when the module is unactivated/reactivated, yet, it lost its synchronisation after.

**Comment by kewisch** [comment]
Can you provide logs as noted in the bug template?
