### ISSUE TITLE
Multiple email addresses support

### ISSUE THREAD

**Issue by ymollard** [kewisch/gdata-provider#55]
This [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1138636#c14) demonstrates that ICS invites sent to `me@example.org` cannot be transferred to any Lightning calendar if their mail address is not `me@example.org`.
If no mail address matches the recipient, Lightning states that `No writable calendars are configured for invitations, please check the calendar properties.`.
I would suggest a feature in which mail aliases can be setup for each calendar.

**Comment by kewisch** [comment]
This needs to be fixed in Thunderbird first, unfortunately I cannot associate with more than one address.
