### ISSUE TITLE
Addon requires unrestricted permissions

### ISSUE THREAD

**Issue by rustymonkey** [kewisch/gdata-provider#551]
When attempting to install  Provider for Google Calendar 102.0.3 to Thunderbird 102.5.1, Thunderbird indicates that the addon will "Have full, unrestricted access to Thunderbird, and your computer".

Is it possible to create a version of the addon that requests a more limited set of permissions?

Thanks!

**Comment by euven** [comment]
Plus one for this! This makes the plugin seem fishy..

**Comment by kewisch** [comment]
I can understand that, though unfortunately there is no calendar API in Thunderbird yet that would make this possible. I'm working on that in #224 and do hope to eventually make this a pure MailExtension. This text appears as soon as I use the legacy extensions API which allows me to create a provider at all, so there is no inbetween.

**Comment by euven** [comment]
Thanks for explaining @kewisch, and for this plugin!
