### ISSUE TITLE
Recurrent Event doesn't show

### ISSUE THREAD

**Issue by profago** [kewisch/gdata-provider#56]
Hello,
don't know if this is a bug or a missing or bad thunderbird or google setting.

Windows 10 - 1909 - 64bit,
Thunderbird 68.5
Lightning calendar 68.5
Provider for Google Calendar 68.2.1

Google calendar is add to Thunderbird (as described in the FAQ list).
Normal events are fully working and the sync is smooth but otherwise

Normal events are fully working and the sync is smooth but otherwise recurring events created in Lightning or Google are shown until the next refresh.

After the refresh normal events are showed but none of the recurring ones are shown.

If i change something in google calendar (online version) for one refresh the events are correctly shown after this refresh they aren't shown in Thunderbird but fortunatelly they still exist in google calendar (online version).

I have tried to uninstall both Lightning and Provider for Google Calendar, cleaning thunderbird cache and than reinstall but the problem still exists.

Many Thanks in advance

**Comment by mat4444** [comment]
Hello, I experience the same issue as well with recurrent tasks created from Google Task.
The first occurrence and the past occurrences of a Google Task appear in Lightning. However, the future occurrences are NOT shown until the day they are supposed to be completed.

**Comment by mat4444** [comment]
Hi!
 any update on this ? thank you

**Comment by kewisch** [comment]
Please re-test on Thunderbird 91 if this is still an issue and re-open if necessary.
