### ISSUE TITLE
No writable calendars are configured for invitations, please check the calendar properties

### ISSUE THREAD

**Issue by nzhuk98** [kewisch/gdata-provider#563]
### Describe the problem and steps to reproduce it:

Connect to Google Workspace account calendar through the addon.
Receive an event invitation at Google Workspace email for the same account.

 ### What happened?

A message is shown "No writable calendars are configured for invitations, please check the calendar properties"

### What did you expect to happen?

I should be able to accept/reject the invite.

### Anything else we should know?

TB 102.6.0
Provider for Google Calendar 102.0.3
Debian 11
Under the calendar properties "Read Only" is unchecked, Location is correct.
The calendar synchronizes and shows events.

I searched through old issues where a solution was to change a config editor setting that no longer exists and saw that this was fixed in 91. This doesn't work in 102 for me.

**Comment by BDJ441** [comment]
I have the same issue on TB 102.6.0 (64-bit), Debian 10.

**Comment by BDJ441** [comment]
Initially I created the boolean "calendar.google.enableEmailInvitations" (true),  as found in some older Google searches, with no success. I then updated the properties for the Google calendar by specifying the associated email address and was able to accept the invitation.  That is when the weirdness started. 
- the reply to the invitee came to them as an invitation email
- though visible in Thunderbird calendar, the accepted invitation was _not_ reflected in the Google Calendar (desktop or app).
- when the invitee changed the date of the invitation, an update was not received by Thunderbird (AFAIK).
This needs further debugging. Willing to work with an interested party.

**Comment by cantfindagood1** [comment]
I'm also having the same issue with TB 102.8.0 on MacOS 11.7.4 and add-on version 102.0.3. My Google calendar and tasks are visible in TB, but when I receive an email calendar invite, it shows the message "No writable calendars are configured for invitations, please check the calendar properties." The Read-only checkbox in the calendar properties is not checked.

**Comment by frischgis** [comment]
Same issue here (TB 102.11.0 64-bit on Windows).
Additional info: On the Google calendar property page, I was able to configure an email address when I activated the calendar. However, after restarting Thunderbird, the calendar property page does not show this information any more.
I also tried commenting out "await messenger.gdata.purgeLegacyPrefs();" in background.js as suggested [here](https://www.thunderbird-mail.de/forum/thread/85904-kein-kalender-mit-schreibrechten-f%C3%BCr-einladungen-eingerichtet-trotz-google-kalen/?postID=478072#post478072), but to no avail.

**Comment by kewisch** [comment]
The settings you mention are available in the add-on preferences, can you make sure the checkboxes related to attendees and scheduling are checked? Afterwards, please unsubscribe and re-subscribe to your calendars.

**Comment by frischgis** [comment]
> The settings you mention are available in the add-on preferences, can you make sure the checkboxes related to attendees and scheduling are checked? Afterwards, please unsubscribe and re-subscribe to your calendars.

As I said, the checkboxes were there when I first subscribed to the calendar, and I checked them as desired. However, after restarting Thunderbird, they completely disappeared, and the settings were lost (the calendar does not accept invitations).

**Comment by kewisch** [comment]
You should only be able to schedule in the primary calendar, i.e. the one with your name on it. The email should be set automatically, hence the controls are missing. I'd suggest rather enabling the option in Google Calendar to show invitations in the calendar, than to accept invitation emails into the calendar.

We have quite a few reporters here with potentially different issues, this makes it a bit hard to track. I'm going to need some debug logging as described in the readme, and more details on which calendar, what the invitation looks like, etc.

**Comment by frischgis** [comment]
Then in my case this is probably the issue, since I was using a sub-calendar (one that I created as a new calendar in the Google calendar app). When working with a primary Google calendar it works. I hope that sub-calendars will be supported in the future. Thanks for your help Philipp!

**Comment by victor-sudakov** [comment]
I have the same problem on Thunderbird 115.3.1 (64-bit) (Ubuntu). I'm trying to add event invitations from elsewhere (ical files are not from Google) and cannot add them with the "No writable calendar..." message.

**Comment by kewisch** [comment]
Hi folks. Quite a few reporters in this issue, I'm going to close this out. If you are having this issue please make sure you are scheduling in your primary calendar. If there are other issues please open individual issues and make sure to provide debug logs.
