### ISSUE TITLE
Import from .ics fails when target calendar is a Google calendar

### ISSUE THREAD

**Issue by emefay** [kewisch/gdata-provider#57]
On Windows 10, and on two seperate PCs, tried with...
TB 68.4.2 with provider ver 68.2.1 and
TB 60.9.1 with provider ver 4.4.2
with same results.

Can import the ics file with no problems into a local TB calendar, but when I try to import it into a Google-linked calendar it randomly imports 7 or 8  events, typically failing to import (say) 750 events.

Similarly, if I cut or copy a number of events from a TB-local calendar and paste them into a Google-linked calendar, it only manages to copy a couple of the items (randomly) but losing the rest. Going the opposite way round, i.e cutting from Google-linked calendar & pasting into TB-local calendar seems ok.

**Comment by mm-mikemeister** [comment]
same problem, TB 78.4.0 gdate provider 78.0.1
My Workaround at the moment: added a local calender "Import", import the ics files there, open the item and choose the google calender and save. 
Will there be a solution for direct import?
Many thanks

**Comment by kewisch** [comment]
Hard to say without details on which events are failing, what information is sent to the server for those events, etc. I can imagine it may have to do with rate limiting, in that case it would be #187. I'm closing this issue to clean up a bit, if you have more specific error details please let me know.
