### ISSUE TITLE
Event without reminders set is saved with reminders

### ISSUE THREAD

**Issue by piterq** [kewisch/gdata-provider#573]
### Describe the problem and steps to reproduce it:
I've added Google calendar to Thunderbird. I'm creating a new event and "Remind" field is set to "without reminder". After saving this event I see in the calendar view that this event has 2 reminders (email + popup).

### What happened?
Event was saved with 2 reminders set.

### What did you expect to happen?
Event should be saved with no reminders set.

### Anything else we should know?
The same happens when I'm copying events which has no reminder set using copy-paste method (CTRL+C, CTRL+V). Copied events have 2 reminders set (although source events has no reminders).

Event saved with "Remind" set to "without reminders":
![image](https://user-images.githubusercontent.com/59413148/214927143-d2325f90-2909-4815-8dde-c96c12ae6143.png)

**Comment by kewisch** [comment]
Do you have a default alarm set? Can you share the debug logs when adding the event?
