### ISSUE TITLE
Provider not working with Thunderbird versions 109+

### ISSUE THREAD

**Issue by teendocmbc** [kewisch/gdata-provider#574]
Provider for Google Calendar is not compatible with Thunderbird versions 109 and above.  I am now on Thunderbird 110 and I have not been able to use this add on for over a month now since my Thunderbird upgraded to the 109 release.  Is this going to be fixed so that the add-on will be compatible again?  I miss being able to sync and use my Google Calendar!

**Comment by c765f614** [comment]
Same issue over here since a while, running the beta`s on usual basis with no problems for this gdata-provider, but the last time it won`t work. Don`t get it why there seems everytime a chance somewhere with result a not working addon again.

Love this addon, but need to trust that the sync is done so not missing anything...

**Comment by Jpex83** [comment]
Ditto the other comments, I had to remove the module otherwise it crashed thunderbird no command of the program worked, it was necessary to kill the thunderbird process and restart in safe mode, but where did the developer go? Philipp Kewisch where are you?

**Comment by kabirbg** [comment]
Bumping up this issue, I think it might get to be a bigger deal as we approach the public release of 115 (July)... I installed 113 beta the other day, and all my calendars have stopped working (I've had to resort to the Open Google Calendar extension). I trust that it'll get updated soon, but it is an annoyance and it would be really helpful if I could find something like a release timeline somewhere, or a schedule for how this extension normally gets updated... can't find anything right now which makes it more frustrating. Happy to help contribute too if that'll get it out faster.

**Comment by kewisch** [comment]
I currently don't have the extra time to follow each beta release unfortunately. The add-on still mostly uses the legacy extensions API, as there is not yet a calendar API for Manifest v2/3.

Regarding the Manifest v2/3 API and turning this add-on into a pure MailExtension,  I have some experimental work on the `main` branch for this. There are a bunch of things left to do in #224, but also I would love for the calendar API to be part of Thunderbird to make distribution easier.

Going back to beta releases, this work is being released from the `legacy` branch. You are welcome to send pull requests to that branch between releases to fix any intermediate issues in betas. My github notifications are unmanageable though, so you might have to reach out to me using different methods.

Regarding 115, this again is on the `legacy` branch, and I have a release candidate I'll post on an issue here shortly for testing and push to addons.thunderbird.net tomorrow. Just in time, fingers crossed it works for everyone :)
