### ISSUE TITLE
Wrong time set for copy/paste events and for ICS files

### ISSUE THREAD

**Issue by David-Maisonave** [kewisch/gdata-provider#577]
### Describe the problem and steps to reproduce it:
Thunderbird 102.6.1 (64-bit) Windows
Plugin version 102.0.3 (Nov 13,2022)

When adding event using an ICS file, the event gets set to the wrong time (9:15AM instead of 2:15PM). To reproduce use the following file:
[EventToAddToCalendar.zip](https://github.com/kewisch/gdata-provider/files/10669141/EventToAddToCalendar.zip)
If the same ICS file is imported to the default non-google calendar, the correct time is added.
When I copy the same event which has the correct time from by non-google calendar, and paste it to the google calendar account, it again gets set to the wrong time (9:15AM instead of 2:15PM).

### What did you expect to happen?
The correct time and date added to the google calendar when it gets added via ICS file, or via copy and paste from non-google calendar to a google calendar.

### Anything else we should know?
I could not find the Advanced icon or menu item, so I could not turn on debug mode.

From Error Console:
Calendar: [calGoogleCalendar] 2023-02-07T14:35:00-05:00 does not match timezone offset for America/New_York 
**gdataUtils.jsm:276** resource://gdata-provider/legacy/modules/gdataUtils.jsm

I deleted everything in the Error Console, and performed the ICS file import, and I got the following:
```
16:19:57.975 Failed to read 'imipHtml.attendeePartStat2.REQ-PARTICIPANT' from chrome://lightning/locale/lightning.properties. Error: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIStringBundle.formatStringFromName]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/calendar/utils/calL10NUtils.jsm :: _getString :: line 35"  data: no] [calL10NUtils.jsm:40](resource:///modules/calendar/utils/calL10NUtils.jsm)
16:20:09.101 Calendar: [calGoogleCalendar] 2023-02-07T09:15:00-05:00 does not match timezone offset for America/New_York [gdataUtils.jsm:276](resource://gdata-provider/legacy/modules/gdataUtils.jsm)
16:20:09.101 Calendar: [calGoogleCalendar] 2023-02-07T09:35:00-05:00 does not match timezone offset for America/New_York [gdataUtils.jsm:276](resource://gdata-provider/legacy/modules/gdataUtils.jsm)
16:20:28.300 This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
4 [calItemBase.js:431:30](resource:///components/calItemBase.js)
```

I tried running Thunderbird in troubleshoot mode and the ICS import failed with the below logging errors:
```
Failed to read 'imipHtml.attendeePartStat2.REQ-PARTICIPANT' from chrome://lightning/locale/lightning.properties. Error: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIStringBundle.formatStringFromName]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/calendar/utils/calL10NUtils.jsm :: _getString :: line 35"  data: no] 2 [calL10NUtils.jsm:40](resource:///modules/calendar/utils/calL10NUtils.jsm)
16:30:57.765
[Exception... "JavaScript component does not have a method named: "addItem"'JavaScript component does not have a method named: "addItem"' when calling method: [calICalendar::addItem]"  nsresult: "0x80570030 (NS_ERROR_XPC_JSOBJECT_HAS_NO_FUNCTION_NAMED)"  location: "JS frame :: chrome://calendar/content/import-export.js :: putItemsIntoCal :: line 179"  data: no]
```

In below screenshot, the top event on Tuesday is where the event was incorrectly added, and the below events is where it was supposed to go, and where it gets correctly added when I import the ICS file to a non-google calendar.

<img width="278" alt="ScreenShot" src="https://user-images.githubusercontent.com/47364845/217093414-bd340527-5c0d-4893-a190-3a0f5c1d68d2.png">

**Comment by kewisch** [comment]
The tricky part is that this file uses floating time, which IIRC Google Calendar doesn't support well, so I try to convert it to the local timezone. Looks like something is going wrong in doing that.

**Comment by kewisch** [comment]
It would be immensely helpful if you could provide logs with debugging on, can you check the instructions in the README?
