### ISSUE TITLE
Dialog kann nicht geschlossen werden.

### ISSUE THREAD

**Issue by ulli5** [kewisch/gdata-provider#58]
Hallo Herr Kewisch,
ich verwende TB 68.5, Lightning 68.5 und den Provider für Google Kalender 68.2.1.
Einer meiner Termine generiert immer wieder einen Dialog, der nicht geschlossen werden kann.
"Dieser Eintrag wurde auf dem Server geändert ......"
![2020-02-20 07_33_48-Window](https://user-images.githubusercontent.com/9401837/75034370-60e64300-54ad-11ea-8ffe-ace9042d3965.png)

Obwohl ich den Termin in Thunderbird und auch im Google Kalender  gelöscht habe, kommt der Dialog immer wieder. Er läßt sich nur wegschalten, wenn die Netzwerkverbindung unterbrochen wird.
Da es sich das bei Ihnen wahrscheinlich nicht reproduzieren läßt, bin ich bereit, nach Anweisung zu debuggen, um die Ursache aufzuspüren.

**Comment by Michael-Hb** [comment]
Ich hatte dasselbe Problem und konnte es lösen wie folgt:

0) Sicherheitshalber -falls etwas schiefgeht - die mit Google synchronisierten Aufgabenlisten und Kalender als ics-Dateien sichern (das geht mit "Termine und Aufgaben/ Exportieren …")
1) In Thunderbird unter "Extras / Add-ons / Erweiterungen" den "Provider für Google-Kalender" deaktivieren. Dabei erscheint ein Bestätigungsfenster, in dem man die betroffene Aufgabenliste [bei Google] "abbestellen" kann. Hier die betroffene Aufgabenliste anklicken zum "abbestellen".
2) Danach den "Provider für Google-Kalender" wieder aktivieren.
3) Und zum Schluss die vorher "abbestellte" Aufgabenliste  wieder aus Google (rück-)importieren. Die Prozedur dazu ist beschrieben z.B. auf https://www.heise.de/tipps-tricks/Google-Kalender-mit-Thunderbird-synchronisieren-unter-Windows-3831918.html
4) In meinem Fall war in Thunderbird nach abbestellen der Google-Aufgabenliste auch der Google-Kalender gelöscht (vielleicht hatte ich den aus Versehen auch "abbestellt"). Diesen Kalender konnte ich aber problemlos zusammen mit der Aufgabenliste wieder aus Google (rück)importieren.

**Comment by kewisch** [comment]
I've likely fixed this on the `main` branch, though unfortunately I cannot easily make it backwards compatible. Closing accordingly.
