### ISSUE TITLE
Cannot dismiss reminder for deleted event

### ISSUE THREAD

**Issue by eivindt** [kewisch/gdata-provider#581]
### Describe the problem and steps to reproduce it:

Create event on calendar (I've only had this problem when others invite _me_ to an event), have this show up in Thunderbird calendar and create a reminder, then have the organizer delete the event.

This notification cannot be dismissed.

Thunderbird 102.7.1 (64 bit) on Linux, gdata-provider v102.0.3

### What happened?

The call to `this.session.asyncItemRequest` fails with `e.result == calGoogleRequest.CONFLIC_DELETED`, then `checkResolveConflict` is called to fix the situation.  This opens the overwrite prompt, but neither choice fixes the situation.

I've tried digging deeper into the "Update from server" choice, but the call to `aCalendar.superCalendar.refresh()` is not enough to resolve the situation.  I _think_ this is because the calendar refresh will only refresh changes to events on the remote calendar, but since the event has been deleted, there is no change to refresh, and the cached calendar is never told to remove the event.

I would have liked to do a full refresh of the cached calendar in this situation, but haven't figured out how to.

**Comment by moobsen** [comment]
I can confirm this, I have the same problem.

**Comment by StefanPofahl** [comment]
My solution, I have disabled the "gdata-provider". I will wait for a while to see if the situation improves. My OS is Ubuntu 22.04.

**Comment by kewisch** [comment]
Deleted events should be synced as well so that the provider knows they are deleted. The conflict dialog should work accordingly and either just refresh the calendar (which triggers the delete to remove the event), or overwrite the changes (which will create a new event with the details of the deleted event).

Can you share more elaborate logs for the exchange in this case? I haven't been able to reproduce this.

**Comment by eivindt** [comment]
Unfortunately, triggering this situation is harder than described above, there seems to be some internal state involved as well, since a simple restart of Thunderbird fixes the stuck notifications.  I just upgraded to the latest version, and reapplied PR #580 (otherwise I cannot dismiss the notifications at all). 

I'll have to wait until the situation happens again, and I'll provide more info.

**Comment by theuser18** [comment]
I am having problems as well. Clicking dismiss and dismiss all on my Google Calendar reminder pop up does nothing.

Thunderbird 115.4.2 (64-bit) flatpak
Provider for Google Calendar 115.0.2

**Comment by kewisch** [comment]
Hey folks, thanks for reporting this. I'm going to go ahead and close this issue for now as I wasn't able to reproduce. If this is occurring for you, please open a new issue and make sure to include debug logs.
