### ISSUE TITLE
Event invitation time shown correctly in Thunderbird, but inserted one hour later

### ISSUE THREAD

**Issue by GitFuchs** [kewisch/gdata-provider#585]
For some event invitations, the time is initially shown correctly in Thunderbird, but added as an event scheduled one hour later in Google calendar.
The event invitation, when opened a second time, shows the original time striked through with the wrong (e.g. one hour later) time 

I am using Ubuntu 22.04LTS with Thunderbird (102.7.1 (64-bit)) with Provider for Google Calendar (102.0.3).
The time zone is Western Europe, ((UTC+01:00) Amsterdam\, Berlin\, Bern\, Rom\, Stockholm\, Wien)

Interestingly, this only happens for some invitations. It seems invitations generated from other Linux systems work fine.

Importing directly into a lightning calendar works fine. Also importing via the webpage into the google calendar works fine.

I have attached two invitations. One works correctly, one creates the issue. For privacy reasons, I have removed some data, but that should not matter.
![KalenderChanged](https://user-images.githubusercontent.com/5013364/220632490-795a3e35-d2a0-4e6d-b85b-36889f34581f.png)
[Invitation_correct.ics.txt](https://github.com/kewisch/gdata-provider/files/10804238/Invitation_correct.ics.txt)
[Invitation_shiftedBy1Hour.ics.txt](https://github.com/kewisch/gdata-provider/files/10804239/Invitation_shiftedBy1Hour.ics.txt)

**Comment by kewisch** [comment]
Do you think you could provide the full .eml file (details redacted) for where it is shifted by an hour?
