### ISSUE TITLE
Thunderbird crashes when add-on is installed

### ISSUE THREAD

**Issue by pkarpin** [kewisch/gdata-provider#586]
I was not able to dismiss reminders, which started about 2 weeks ago. Shutting down and restarting thunderbird each day would resolve the issue but some reminders came in multiples and others stayed persistent and could not be dismissed.

Yesterday, I changed one reminder to future date and in few minutes error tab came up to "submit and refresh" or "dismiss"
No matter which button was pressed it just kept coming up again and again. I closed Thunderbird, hoping issue would resolve on re-start but started getting "Mozilla Crash Reporter" every time I tried to restart Thunderbird.

Opened Thunderbird in Safe-Mode, removed add-on, reinstalled add-on but when turning off safe-mode or restarting thunderbird, get the same crash report tab, thunderbird itself does not open.

Same thing happens when add-on is installed in safe mode, when turning off safe mode, looks like Thunderbird is trying to restart but gets to same crash report tab "Mozilla Crash Reporter"

![Screenshot_20230301_110127](https://user-images.githubusercontent.com/98428246/222328167-781c82c6-89bf-48db-8159-cb6851d37178.png)
![Screenshot_20230301_110349](https://user-images.githubusercontent.com/98428246/222328291-578b6300-f135-4316-9cce-66acc4d47616.png)

**Comment by pkarpin** [comment]
Same thing happens when add-on is installed in safe mode, when turning off safe mode, looks like Thunderbird is trying to restart but gets to same crash report tab "Mozilla Crash Reporter"

**Comment by pkarpin** [comment]
Have an update:
1. removed add-on is safe mode
2. unsubscribed from all Google Calendars 
3. added add-on 
4. re-subscribed to Google Calendars

Seems to be back to normal operation.

**Comment by kewisch** [comment]
Glad it worked out! Crashes are likely Thunderbird issues, as this extension is Javascript only. Next time it happens maybe we can find out the crash id for more info.
