### ISSUE TITLE
[TB 75.0b1 (64-bit)] - Calendar Wizard: window is undefined

### ISSUE THREAD

**Issue by jrods** [kewisch/gdata-provider#59]
I'm using this version of Thunderbird for the first time with gdata-provider, installed from the add-ons within Thunderbird.

In the screenshot below shows the error log, I'm guessing in previous versions of TB the wizard was in a dialog window but now it looks like it's a dropdown in TB. So the Google Calendar option doesn't appear.

gdata-provider: 68.2.1 (installed via addons.thunderbird.net)
Thunderbird: 75.0b1 (64-bit)
OS: Mac OS X 10.15

<img width="1280" alt="Screen Shot 2020-03-19 at 10 26 25 AM" src="https://user-images.githubusercontent.com/5874122/77046970-960e8400-69cc-11ea-800e-561fc35fbcc3.png">

**Comment by zzrough** [comment]
Ha, I've had the provider installed and tried uninstall/reinstall is with TB >= 72 and now that's the problem I'm hitting since a couple of month. This has been mentioned in a former issue, but providing the stack is a plus.

**Comment by kewisch** [comment]
This should be fixed with Thunderbird 91
