### ISSUE TITLE
Sync Problem Thunderbird

### ISSUE THREAD

**Issue by jfabini** [kewisch/gdata-provider#593]
### Discussed in https://github.com/kewisch/gdata-provider/discussions/592

<div type='discussions-op-text'>

<sup>Originally posted by **jfabini** April 21, 2023</sup>
I've a sync issue between the Google Calendar and Thunderbird 102.10.0 and GProvider 102.0.3  on Linux Mint 21.1 Cinnamon. A calendar item that originally was created in TB has been synced to Google and modified later on several time (using Google's Web UI and several other Calendar clients).
However, the latest changes on the server for this specific item are not reflected in TB. I've tried to force synchronization, to stop and restart TB, rebooted the system: the particular TB calendar entry continues to display old values. 
Even more strange: 
1. If I hover with the mouse cursor over the TB calendar entry, the yellow overview window shows the correct entry, including the additions that are missing when opening/attempting to edit the item in TB! Seems like TB/GCal cache some values and do not update them. 
2. A second TB client running on another computer (Mint 20.3) shows identical behavior: it doesn't sync this specific entry
3. Other clients (iOS for instance) display the correct entry.  
4. I was not able to reproduce this issue for other entries (created a calendar entry in TB, synced it to Google, edited it... all changes are moved forth and back as it should).

I guess I could fix the issue by copying the content from the Goggle Web UI, pasting it into the calendar item on TB that is open for edit and forcing the sync back to Google. But for now I'll leave it as-is - perhaps there are some debugging options to identify the underlying reason why GCal/TB doesn't sync. Seems to be a bug that's worth fixing (after all it can lead to loss of information).</div>

**Comment by Alvarord** [comment]
I have a similar issue but it has autoresolved, not sure how. I use it for a shared calendar and I didn´t see the modifications made by others.

**Comment by kewisch** [comment]
Can you provide more information on the entry that is failing? Do you get any error console messages with debugging enabled?

**Comment by jfabini** [comment]
No suspicious debug message whatsoever as long as the bug persisted. I enabled calendar.debug.log and .verbose, appended a "-test" to the event text in Google Calendar (WebUI) to the faulty calendar entry and forced sync in TB - nothing happened. Still, the same behavior: hovering over the calendar entry with the mouse in TB showed the correct (Google server stored) event content as pop-up (note: the trailing "-test" was not visible in the cal entry, as there was too much text to fit into the pop-up) but when opening the calendar entry for editing in TB it contained only part of the content (so there was additional event text missing, besides the -test)
Unfortunately I've somehow managed to enable  re-sync. It was one of:
1. By mistake I edited the event in TB Calendar and when closing the dialog got the notification/question "Entry has changed on server Reload/Overwrite". I simply closed the dialog but this action may have triggered an update.
2. I added a "-test" text to the head of the event's text (in Google Calendar WebUI) - and this one (including all of the text) is now shown correctly, changes are synced forth and back.

These actions should be visible in the debug console log.

One more potential issue/hint: I've activated (since available) the "force use of plain text in event descriptions". The entry stored by Google contained some tags like <br>,&amp; etc.  

The calendar entry contained some privacy-sensitive data so I refrained from screenshots. All successful syncs are visible in the debug console. So apologies, seems like I've killed my unique event to demonstrate the bug...

**Comment by atscomms** [comment]
I have a very similar issue that's been occurring for a year or more.
Events created in TB and then updated in Google (ie: start time) are not updated back to TB, even after Syncing or Reloading.
Hovering over the TB event does NOT show the updated start time. 
If I edit the event in TB with no changes and try to save, I get the dialog that the server data has changed. I Discard my changes and Reload, but I still see the original start time.

**Comment by kewisch** [comment]
Too bad it no longer reproduces, but then again, I'm glad it is working again! If you encounter the issue again I'd love to hear.

**Comment by atscomms** [comment]
It is reproducible, nothing I did above helped.
However I applied a patch that was posted elsewhere and that did work.

**Comment by kewisch** [comment]
Ah sorry I misunderstood. So I guess this is that patch to ignore the idle time? I'm still trying to figure out why that is an issue and in no issue I've found the right logs to determine the core issue. The reports are that if you idle it skips (which is fine), and then when you are back it just does nothing, not even show up the initial message that you are idle. So it must be bailing out later without action, but I'm not sure where.

Can you confirm what the patch was and maybe help debug in #498 ?
