### ISSUE TITLE
Support for Video conferencing link and details

### ISSUE THREAD

**Issue by Oxalin** [kewisch/gdata-provider#60]
Under Google Calendar, when creating an event > More options, there is a field next to a camera icon where it is possible to add a link for video conferencing (Hangouts for Google accounts, Hangouts Meet for G Suite users). When selected, this adds a link (minimally) and some additionnal details for Hangouts Meet like a Phone number and a PIN.

While the process of adding those details from Thunderbird may be more difficult (or impossible, I don't know), they should be made visible under Thunderbird's calendar if they are already available (event created from Calendar).

**Comment by Oxalin** [comment]
According to Calendar API (https://developers.google.com/calendar/v3/reference/events), there are:
- hangoutLink (Read-only)
- conferenceData: The conference-related information, such as details of a Hangouts Meet conference. (writable)

**Comment by ChrisPurves** [comment]
I would love to see this functionality added.  Presently, if a google calendar entry has a Google Meet (or hangouts) meeting associated with it, there's no way to know from within Lightning.  I have to open the entry in Lightning, click on the Related Link to the Google Calendar entry and then I can see the meeting URL.

**Comment by samikrc** [comment]
Love to have this. Also, by default, a video conference link is always added. Would love to enable/disable this based on the need.

**Comment by Oxalin** [comment]
@samikrc Do you mean you would like an option in the extension to enable or disable the conference link generation by default?

**Comment by samikrc** [comment]
Yes - that is correct. Sometimes, I have to provide Videoconferncing URL through a different system (e.g., Zoom), but it is confusing to the recipient: they see the Google Hangout or Google Meet conference URL, and also the Zoom link in the location/body.

**Comment by alexivkin** [comment]
that link is accessible via CalDav interface - I've referenced it in #73

**Comment by mpapis** [comment]
Hey, what's the progress here? can we at least see the link? Pretty please ❤️

**Comment by unode** [comment]
This seems to now be widely used (Zoom and others).
I find myself going to calendar.google.com every time an invite contains no connection (Location) information.

Beyond the future tag, are there any plans to bring this in the (near) future?

**Comment by kewisch** [comment]
I had originally planned to take care of this when either Thunderbird supports fields for conference data, or when rewriting this to a WebExtension. Since apparently I'm not able to devote time to the WebExtension I might as well hack this in to the legacy version. Patches coming soon.

![image](https://github.com/kewisch/gdata-provider/assets/607198/603590ce-6465-4e65-8add-beb10e06ef14)
<img width="851" alt="image" src="https://github.com/kewisch/gdata-provider/assets/607198/60f9bca1-f008-48f4-8c64-3428df6ee279">

**Comment by kewisch** [comment]
Fixed in e9056136d4c20f5838b74198b7e1d5cce6299fdc . Will release soon.
