### ISSUE TITLE
Issue with "Convert Message to Event" option in Thunderbird's context menu

### ISSUE THREAD

**Issue by skopalv** [kewisch/gdata-provider#601]
Hello,

I would like to report a bug regarding the "Convert Message to Event" option in Thunderbird's context menu. While the "Convert Message to Task" option works correctly, the "Convert Message to Event" option does not function as expected.

Here are the details of the issue:

    Thunderbird version: 102.11.2 (64-bit)
    Operating System: Windows 10 Pro

Description:
When attempting to use the "Convert Message to Event" option in the context menu, nothing happens. The expected behavior is that the selected message should be converted into an event, similar to how the "Convert Message to Task" option works.

This issue is not limited to specific senders or message types; it occurs when trying to convert any message into an event.

I have encountered this problem since I discovered the "Convert Message to Event" option in the context menu. I have regularly restarted Thunderbird and my computer, but the issue persists.

Error Console:  POSThttps://www.googleapis.com/calendar/v3/calendars/https:/events [HTTP/3 404 Not Found 157ms]

Please investigate this matter and provide a solution or workaround if possible. Let me know if any further information or testing is required to assist in resolving this issue.

Thank you for your attention to this matter.

Best regards,
Vladimír Skopal

**Comment by kewisch** [comment]
Can you share the message as an .eml file that you are trying to convert? This could potentially be a Thunderbird bug, but happy to look into it.
