### ISSUE TITLE
Provider for Google Calendar is not being kept up to date. Is it your intention to let die.

### ISSUE THREAD

**Issue by Vakkerrygg** [kewisch/gdata-provider#602]
### Describe the problem and steps to reproduce it:

(Please include as many details as possible.)

**Comment by Vakkerrygg** [comment]
Not compatible with Thunderbird 115
Stopped working
I would expect you to work with Mazilla to maintain compatibility.
Is this going to happen? When?

**Comment by kewisch** [comment]
I'm up to date with the latest release, 115 is not out until Monday. I may certainly be late to the party once in a while, but I'm doing my best.  https://fosstodon.org/@kewisch/110672484200522920 

I have a release candidate I'll post on one of the issues in a short while.
