### ISSUE TITLE
 I have to keep uninstalling/reinstalling (subscribing/unsubscribing) my calendars to get them to sync

### ISSUE THREAD

**Issue by jlbrewster** [kewisch/gdata-provider#604]
### Describe the problem and steps to reproduce it:
I don't know how long it takes, but at least once per day, I will have to remove my two gmail calendars, and re-add them, because they aren't syncing. I have found that re-adding them gets them to sync (once?) but this is inconvenient.
(Please include as many details as possible.)
Mac OSX Mojave, Thunderbird 102.12.10
### What happened?
It keeps happening, at least for the last few months.
### What did you expect to happen?
I expect calendars to sync, at least when I press the "sync" button.

**Comment by kewisch** [comment]
Do you have any error logs with debugging enabled that would be helpful here? Otherwise it will be very hard for me to reproduce.

**Comment by jlbrewster** [comment]
Here is the first log when I startup in terminal:
` /Applications/Thunderbird.app/Contents/MacOS/thunderbird -console
➜  ~ [ImapModuleLoader] Using nsImapService.cpp
[NntpModuleLoader] Using NntpService.jsm
[Pop3ModuleLoader] Using Pop3Service.jsm
[calBackendLoader] Using Thunderbird's ical.js backend
Warning: unrecognized command line flag -console
console.warn: services.settings: Failed to load last_modified.json: TypeError: NetworkError when attempting to fetch resource.
JavaScript error: resource://gdata-provider/legacy/modules/gdataRequest.jsm, line 381: TypeError: getCorrectedDate is undefined
JavaScript error: resource://gdata-provider/legacy/modules/gdataRequest.jsm, line 381: TypeError: getCorrectedDate is undefined
JavaScript error: resource://gdata-provider/legacy/modules/gdataRequest.jsm, line 381: TypeError: getCorrectedDate is undefined
JavaScript error: resource://gdata-provider/legacy/modules/gdataRequest.jsm, line 381: TypeError: getCorrectedDate is undefined
JavaScript error: resource://gdata-provider/legacy/modules/gdataRequest.jsm, line 381: TypeError: getCorrectedDate is undefined
JavaScript error: resource://gdata-provider/legacy/modules/gdataRequest.jsm, line 381: TypeError: getCorrectedDate is undefined
JavaScript error: resource://gdata-provider/legacy/modules/gdataRequest.jsm, line 381: TypeError: getCorrectedDate is undefined
JavaScript error: resource://gdata-provider/legacy/modules/gdataRequest.jsm, line 381: TypeError: getCorrectedDate is undefined
JavaScript error: resource://gdata-provider/legacy/modules/gdataRequest.jsm, line 381: TypeError: getCorrectedDate is undefined
JavaScript error: resource://gdata-provider/legacy/modules/gdataRequest.jsm, line 381: TypeError: getCorrectedDate is undefined
JavaScript error: resource://gdata-provider/legacy/modules/gdataRequest.jsm, line 381: TypeError: getCorrectedDate is undefined
JavaScript error: resource://gdata-provider/legacy/modules/gdataRequest.jsm, line 381: TypeError: getCorrectedDate is undefined
JavaScript error: resource://gdata-provider/legacy/modules/gdataRequest.jsm, line 381: TypeError: getCorrectedDate is undefined
JavaScript error: resource://gdata-provider/legacy/modules/gdataRequest.jsm, line 381: TypeError: getCorrectedDate is undefined
JavaScript error: resource://gdata-provider/legacy/modules/gdataRequest.jsm, line 381: TypeError: getCorrectedDate is undefined
JavaScript error: resource://gdata-provider/legacy/modules/gdataRequest.jsm, line 381: TypeError: getCorrectedDate is undefined
JavaScript error: resource://gdata-provider/legacy/modules/gdataRequest.jsm, line 381: TypeError: getCorrectedDate is undefined
JavaScript error: resource:///modules/CLib.jsm, line 51: Error: couldn't open library libc.dylib: dlopen(libc.dylib, 2): image not found
console.warn: Calendar: [calGoogleCalendar] 2023-07-18T13:00:00-07:00 does not match timezone offset for America/Los_Angeles
console.warn: Calendar: [calGoogleCalendar] 2023-07-18T14:00:00-07:00 does not match timezone offset for America/Los_Angeles
console.warn: Calendar: [calGoogleCalendar] 2023-07-11T13:00:00-07:00 does not match timezone offset for America/Los_Angeles
console.warn: Calendar: [calGoogleCalendar] 2023-07-11T13:30:00-07:00 does not match timezone offset for America/Los_Angeles
console.warn: Calendar: [calGoogleCalendar] 2023-07-14T13:30:00-07:00 does not match timezone offset for America/Los_Angeles
console.warn: Calendar: [calGoogleCalendar] 2023-07-14T14:30:00-07:00 does not match timezone offset for America/Los_Angeles
console.warn: Calendar: [calGoogleCalendar] 2023-07-12T09:00:00-07:00 does not match timezone offset for America/Los_Angeles
console.warn: Calendar: [calGoogleCalendar] 2023-07-12T09:30:00-07:00 does not match timezone offset for America/Los_Angeles`
I see some timezone and date errors which may be related. (I'm on Mac OS X Mojave, suspect that may be it?)

**Comment by jlbrewster** [comment]
(hitting "synchronize' does not produce additional any terminal output).

**Comment by jlbrewster** [comment]
'America/Los Angeles' (PST) should 'GMT-8', right??

**Comment by jlbrewster** [comment]
However, I noticed that currently my google calendars are synching (past 2 days)... I have not had to re-enable/re-subscribe since last week.(FYI).

**Comment by kewisch** [comment]
Glad it is syncing again! I'm not sure why this is happening, the supposedly missing function is defined further up in the same file.
