### ISSUE TITLE
Thunderbird 115 Compatible -- Release Candidate

### ISSUE THREAD

**Issue by kewisch** [kewisch/gdata-provider#613]
Hey Folks,

I have a release candidate for Thunderbird 115. Late to the game so I guess it won't get a lot of testing, but if you could either add a thumbs up if it works for you, or comment if it doesn't, I'd appreciate. I haven't tested if these changes still let it work on Thunderbird 102, I'll do that tomorrow and then push it out for review.

[gdata-provider-115.0.1.xpi.zip](https://github.com/kewisch/gdata-provider/files/11994721/gdata-provider-115.0.1.xpi.zip)

**Comment by peci1** [comment]
Thanks much for the update!

I still wonder how is it possible that Thunderbird with its several paid positions is not taking this addon proffesionally.

I tested on 102 and haven't found anything broken. I only had to re-login to all Google calendar accounts via OAuth.

**Comment by kewisch** [comment]
> Thanks much for the update!
> 
> I still wonder how is it possible that Thunderbird with its several paid positions is not taking this addon proffesionally.

There is a lot to do in Thunderbird :-) Arguably, their focus should be more on open standards, which the Google Calendar REST API is not. I think things are fine as is, and with more effort into a calendaring MailExtensions API (which is generally planned), this extension should get easier to update over time.
> 
> I tested on 102 and haven't found anything broken. I only had to re-login to all Google calendar accounts via OAuth.
FTR there are some stylesheet issues in OAuth on 102 that I just noticed. Taking a closer look tomorrow.

**Comment by kewisch** [comment]
115.0.1 is updated with a few style fixes, see initial comment.

**Comment by kewisch** [comment]
I've submitted 115.0.1 for review. Fingers crossed!
