### ISSUE TITLE
Thunderbird 116+ compatibility

### ISSUE THREAD

**Issue by chiwanpark** [kewisch/gdata-provider#619]
### Describe the problem and steps to reproduce it:

gdata-provider is not compatible with Thunderbird 116+, currently I am using Thunderbird 116.0b1 in Archlinux.

### What happened?

After upgrade Thunderbird to 116.0, the extension is automatically disabled with the following message.

```
Provider for Google Calender is incompatible with Thunderbird 116.0.
```

### What did you expect to happen?
- Working the extension as in Thunderbird 115

### Anything else we should know?

Please let me build this extension with 116+ compatibility, if the solution exists.

**Comment by kewisch** [comment]
I released support for 116 a few days after release, let me know if it isn't working.
