### ISSUE TITLE
Organizer of an event is not included as attendee

### ISSUE THREAD

**Issue by basti35** [kewisch/gdata-provider#62]
The plugin has a different default behaviour if compared to google calendar event creation.

With google calendar, the organizer is included in the list of attendees.

With gdata-provider, the organizer is not included there. Also thunderbird doesn't shows him in the list of participants.

I don't know if it's a bug, but I would expect the same behaviour from google calendar and the plugin.

**Comment by kewisch** [comment]
Took care of this, thank you for catching it! There may still be one difference, it looks like by default if you create an event you don't automatically accept it. This is something for Thunderbird to fix.
