### ISSUE TITLE
Adding a calendar fails when getting the session's task lists from Google returns a 404

### ISSUE THREAD

**Issue by dhruvio** [kewisch/gdata-provider#65]
When I add a new calendar, the addon makes a GET request to `https://www.googleapis.com/tasks/v1/users/@me/lists`. This fails because the response has a status code of 404. It also makes a request to `https://www.googleapis.com/calendar/v3/users/me/calendarList` which responds successfully with a status code of 200.

However, the UI doesn't provide a list of calendars to add. It appears that the entire UI listing operation chooses not to display anything if either of the requests above fail.

IMO, the UI should still display the list of calendars if the `calendarList` request succeeds and the `tasks/*/lists` request fails so the user can still add calendars to Lightning.

Thanks for your work on this add-on! :)

**Comment by dhruvio** [comment]
Also, I was experiencing this issue because I tried to add calendars from a G Suite account. However, in the admin console, the "Tasks" app was turned off for all users, so the API responds with a 404 accordingly.

I was able to workaround this issue by enabling the "Tasks" application. However, it would be nice if the fix described in my previous comment was implemented as it would result in a better user experience.

**Comment by brunis** [comment]
It hasn't been worked on in almost 6 months, so i'm not sure what the status is.
@kewisch are you going to resume work on it? :)

**Comment by dhruvio** [comment]
Bump :) @kewisch

**Comment by rachyandco** [comment]
I have the same issue.

Most users will have a gmail account with tasks enabled. Some will have a google organisation with gmail, and the tasks app can easily be added.

BUT some users (like in my organisation) we already have a email provider and we only use Google essentials for the drive and calendar. In that case, the tasks app is NOT available and cannot be enabled. I had this verified by Google support. 

So the workaround described above is sadly NOT working.

This plugin (awesome by the way) should not fail on the 404 when calling the tasks linked to an account.

**Comment by rachyandco** [comment]
for people in this situation, here is a fix, if you don't want to use Tasks: https://github.com/rachyandco/gdata-provider/releases/tag/v78.0.1.beta

**Comment by kewisch** [comment]
This will be good to go in 91.0.2 \o/

**Comment by kewisch** [comment]
Hey folks, release candidate is out. Would appreciate if you could test this issue and report back here if it doesn't work as expected. Please see https://github.com/kewisch/gdata-provider/discussions/260 for details.
