### ISSUE TITLE
Events with participants

### ISSUE THREAD

**Issue by ncroiset** [kewisch/gdata-provider#658]
### Describe the problem and steps to reproduce it:

I create an event and I invite people by adding participants. I save the event.

### What happened?
When I reopen the event there is no participant in the list. nobody received the invitation.

### What did you expect to happen?
Participants should be saved and invitation sent.

### Anything else we should know?

If I create the event with participants directly in google Agenda is OK and when I check the event on thunderbird, this one contains all participants.

**Comment by kewisch** [comment]
Have you enabled attendes in this add-ons's preferences?

**Comment by ncroiset** [comment]
You means that :
![image](https://github.com/kewisch/gdata-provider/assets/1384260/15aeb812-60e8-4862-a5ad-c90081809757)

**Comment by kewisch** [comment]
Yes, that. Thank you. Can you provide debug logs with debugging enabled as per README?

**Comment by ncroiset** [comment]
OK they were not checked when I did my tests.
