### ISSUE TITLE
Provider for Thunderbird 76.0b1

### ISSUE THREAD

**Issue by mcloaked** [kewisch/gdata-provider#66]
Is there a version of the gdata provider that works with Thunderbird 76.0b1 please? If so where can I download the file? Thank you.  I just updated from Thundebird 71.0b3 to 76.0b1 and there are some issues with the calendar so I wanted to check if there was an updated version since Thunderbird has changed through a significant number of versions since 71.0

**Comment by antcdp** [comment]
Hi, the add-on is part of the TB updates now. 
However, I noted a few versions back that the google link needs to change
I now use this link and edit the email address to suit
https://apidata.googleusercontent.com/caldav/v2/"replace with your email on google"/events

**Comment by kewisch** [comment]
Thats not quite the case, that url is for CalDAV. This add-on is still separate and has a different feature set and backend

**Comment by kewisch** [comment]
I'll look into 76 compat soon.

**Comment by jimrome** [comment]
I installed TB 77 beta. Provider 68.2.1 is installed, but Google Calendar does not work. They are disabled, and their properties say that there is no provider. general.useragent.compatMode.firefox is true. Where do I get the correct provider?

**Comment by antcdp** [comment]
Hi Jim
      
      What platform are you on? Windows, MAC?
      
      I have just installed same and both at the same version and my
      google works.
      
      I have to select caldev for calander type and use this string
      
https://apidata.googleusercontent.com/caldav/v2/"myemail.com"/events
      
       to make it work, replacing the "myemail" with you own address and
      insert the same address for the email address as requested
      
      See attached images
      
      Hope that helps
      
      regards
      Antony
    
    
      
      
      
      
        
          
          
            
              
                
                
                  
                    
                      
                        
                          
                          Antony della Porta MBA
                            GPM-m
                           
                          
                            
                              
                                
                                  
                                    
                                      
                                        
                                          
                                          
                                          Logo Above
                                              "Clickable" for
                                              The YouTube Channel for PM
                                              Real Videos
                                              
                                            The SustainablePM
                                            driving
                                          Sustainable
                                            Strategic
                                              Business Change 
                                            
                                            P: +44 7533 240 675
                                            E: acdp@thesustainablepm.com
                                            W: www.thesustainablepm.com
                                            S: dellaportaconsulting
                                            LinkedIn
                                          
                                                 
                                          
                                            
                                            
                                          
                                           
                                        
                                      
                                    
                                  
                                
                              
                            
                          
                        
                      
                    
                  
                
              
            
          
        
      
    
    On 12/05/2020 19:42, jimrome wrote:
    
    
      
      I installed TB 77 beta. Provider 68.2.1 is installed, but
        Google Calendar does not work. They are disabled, and their
        properties say that there is no provider.
        general.useragent.compatMode.firefox is true. Where do I get the
        correct provider?
      —
        You are receiving this because you commented.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kewisch/gdata-provider/issues/66#issuecomment-627522705",
"url": "https://github.com/kewisch/gdata-provider/issues/66#issuecomment-627522705",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jimrome** [comment]
That worked. But why did I have to change all my calendar addresses? They are nor editable, so I had to make all new calendars.

**Comment by kewisch** [comment]
See #77 . You can continue to use the provider once I've updated to the new format.
