### ISSUE TITLE
HTML not parsed with TB 115.3.1

### ISSUE THREAD

**Issue by JonathanCopus** [kewisch/gdata-provider#660]
Ever since I upgraded to Thunderbird 115.3.1 calendars linked to Google have failed to parse html entered into the 'Description' box.

With TB 102, I could type in the Description box
This is line 1
This is line 2
This is line 3
...and it would stay that way when the event was saved.

Since the upgrade to TB 115, on viewing or editing the Description this appears as
This is line 1<br>This is line 2<br>This is line 3

Not the end of the world, but annoying. Is this a bug, or am I being stupid?

Windows 11 Pro version 22H2 OS Build 22621.2361
TB 115.3.1
Provider 115.0.2

Many thanks

Jonathan

Before saving:
![image](https://github.com/kewisch/gdata-provider/assets/55664953/0e3ab839-0d6f-41a2-a779-c594fcace38d)

After saving:
![image](https://github.com/kewisch/gdata-provider/assets/55664953/f792eaa9-5296-43ae-955b-51c8d9e83981)

**Comment by JonathanCopus** [comment]
Sorry, this blogsite HAS parsed the html, making the first part of my question look nonsensical. Please see the screenshots for a proper explanation.

**Comment by kewisch** [comment]
I've "Fixed" this in 1b494e010928b5a61401b27e7ec866b8e37c4a54, thanks for the report. HTML between Thunderbird and Google Calendar is a mess. Google Calendar has one field for both HTML and plain text descriptions and is even inconsistent in their own GUI. The best we can do is detect HTML in the description and then assume it is HTML.
