### ISSUE TITLE
Line breaks in the event description are replaced with <br> tags when saving events

### ISSUE THREAD

**Issue by k-risc** [kewisch/gdata-provider#661]
### Describe the problem and steps to reproduce it:

(Please include as many details as possible.)

### What happened?
When creating and saving event, line breaks in the event's description text are replaced with <br> tags. For events in other calenders, not using gdata-provider, this does not happen.

### What did you expect to happen?
Line breaks to stay line breaks.
 know?
### Anything else we should know?
![Screenshot 2023-10-03 203311](https://github.com/kewisch/gdata-provider/assets/1674868/1ed7f2a5-6234-4ffe-be9d-684703a4705b)

**Comment by k-risc** [comment]
P.S.: also other parts of the layout of the description are saved as readable HTML code, e.g. ul/li. Maybe an escaping problem.

Thunderbird definitely did changes to the event description field with one of the latest updates. The description had the issue that I needed to press the return key more than twice in order to get two line breaks (which started when they enabled formatted text in the description field).

Since the last update, this line break issue does not occur any more, a single press of the Return key is enough. But no, the issue explained here occurs. It does not occur for calenders which are provided by Thunderbird itself.

**Comment by kewisch** [comment]
"Fixed" this in 1b494e010928b5a61401b27e7ec866b8e37c4a54, thanks for the report. HTML between Thunderbird and Google Calendar is a mess. Google Calendar has one field for both HTML and plain text descriptions and is even inconsistent in their own GUI. The best we can do is detect HTML in the description and then assume it is HTML.

**Comment by k-risc** [comment]
Thanks very much for the fast reply. May I ask: Are there any plans to publish a new official build soon-ish? ;)
