### ISSUE TITLE
It is impossible to set the time for Google tasks, only all-day tasks are available

### ISSUE THREAD

**Issue by Nikela0s** [kewisch/gdata-provider#665]
### Describe the problem and steps to reproduce it:

When creating a new task, you cannot set the time for tasks synced with Google; only tasks for the whole day are available.
Also tasks created for the specific time in the web Google tasks are shown as all-day tasks.

### What happened?

The tasks time is not working correctly

### What did you expect to happen?

It is possible to create task for the specific time that is synced with Google tasks

### Anything else we should know?
no

**Comment by kewisch** [comment]
I believe this is a limitation of the Google Tasks API. See #10
