### ISSUE TITLE
The data in the right column is not updated after suspend from hibernate from yesterday

### ISSUE THREAD

**Issue by XxJooO** [kewisch/gdata-provider#666]
Hello, 

I use TB 115.3.0 under LMDE6 and the latest version of the addon. I always put my computer into hibernate so that I can find everything the way it was finished. Same yesterday. After waking up today, TB correctly retrieves the emails. However, in the right column, the calendar display was not from October 11th. on October 12th updated. This is probably a mistake. After updating TB to 115.3.2 and restarting TB, the display is correct again.

**Comment by kewisch** [comment]
This sounds like more of a Thunderbird issue, please file there.
