### ISSUE TITLE
Can't dismiss calendar events

### ISSUE THREAD

**Issue by go-canes2** [kewisch/gdata-provider#67]
I am unable to dismiss Google Calendar created recurring events.  
![Cant dismiss calendar events screen capture](https://user-images.githubusercontent.com/63683147/79282993-92173a00-7e84-11ea-87f0-5794f44b582b.JPG)

The only way to get rid of the old reminders is to delete the calendar event.

This problem happened in the past, went away but starting recurring in the March time frame. It has been consistent since.

Thunderbird/Lightning 68.7.0
Provider for Google Calendar Add-on 68.2.1

Any help would be appreciated.  I have past software development and debugging skills if there is something you want me to do to debug the problem from within Thunderbird.  
Thanks

**Comment by mwensveen-ebpi** [comment]
I have the same problem.

This is what is written to the error console:

calGoogleCalendar.js:533
Lightning: [calGoogleCalendar] Modifying item Standup failed:2147500037: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "forbidden",
    "message": "Forbidden"
   }
  ],
  "code": 403,
  "message": "Forbidden"
 }
}

**Comment by go-canes2** [comment]
It appears to be working correctly again.  Thank you

**Comment by mwensveen-ebpi** [comment]
@go-canes2 Did you change any settings? I still have the same problems

**Comment by go-canes2** [comment]
Hi Micha,  I didn't change anything that I know of.  There was a MS
Windows update, I don't know if other applications were updated in the
background. I didn't take any direct actions.

I have meetings that were a problem that will pop up tomorrow so I'll
see what happens then.

Tom

**Comment by claudioquaglia** [comment]
I've same problem on Linux platform, unable to dismiss old reminders.

**Comment by mwensveen-ebpi** [comment]
I have now a workaround for the problem by preventing old reminders to be displayed. 
In the config editor: calendar.alarms.showmissed=false

New reminders can be dismissed.

btw: Running on Ubuntu 18.04.4 LTS.

**Comment by claudioquaglia** [comment]
> In the config editor: calendar.alarms.showmissed=false

@mwensveen-ebpi where I can set it?

**Comment by mwensveen-ebpi** [comment]
in the settings:
edit -> preferences -> advanced -> General -> config editor
accept the risk :-)
search for calendar.alarms.showmissed
you can click on it to change from true to false.
If the setting is not there, click on a white space in the config editor and then new -> boolean

**Comment by claudioquaglia** [comment]
thanks... seems to be working. I don't have to smash the computer showing the popup every 30 minutes :)

**Comment by go-canes2** [comment]
Hi,  It's back.  One of my weekly recurring meetings triggered the
problem. It's actually showing meetings that were dismissed over the
last 3 weeks.  All of the meetings showed up at the same time as the
reminder for 'Yesterday at 8:00 PM'

**Comment by dvaerum** [comment]
I am also having this problem, I will try the
```
calendar.alarms.showmissed=false
```
setting

**Comment by Lvceo** [comment]
I tried the "calendar.alarms.showmissed=false" on Ubuntu18.04, TB 68.7.0 & Provider for Google Calendar 68.2.1 and ...
It works!

P.S: Should be fixed IMHO for next release.

**Comment by kewisch** [comment]
Should be fixed with the same patch that will fix #3
