### ISSUE TITLE
Adding a gcal seems to be broken due to reminders (for read-only events?)

### ISSUE THREAD

**Issue by EugenMayer** [kewisch/gdata-provider#673]
### Describe the problem and steps to reproduce it:

- Add a google calender which has events (daily) with reminders
- when asked for a session, enter your email, login properly and finish
- on calender creation in TB, you will see reminders (also for event that are in the past, why so ever)
- If you click 'dismiss all' the dialog wont close or only dismiss some (i had like 85 reminders and ti dismissed until 72 where left). After that the dialog stays open, 72 reminders can no longer be dismissed or snozzed (by using all or by click them one by one)
- in addition, the calender turns 'The calendar xxx is momentarly not available'

When i close TB and start it again , the 72 past reminders are shown again, i can press ESC and the calender will get 'The calendar xxx is momentarly not available'

Enabling debug loggin i see

```
Calendar: [calGoogleCalendar] Modifying item XXXX failed:2147500037: {
 "error": {
  "errors": [
   {
    "domain": "calendar",
    "reason": "forbiddenForNonOrganizer",
    "message": "Shared properties can only be changed by the organizer of the event."
   }
  ],
  "code": 403,
  "message": "Shared properties can only be changed by the organizer of the event."
 }
}
```

This even in particular is not organized by me, so i'am not sure what the operation is trying to do when i press snooze/dismiss in general. Seems to be an attempt to manipulate an event even though i cannot - but for what reaons

### What happened?

Calender is marked ''The calendar xxx is momentarly not available''

### What did you expect to happen?

Dismiss all reminders (or not even see past reminders) and the calender not being marked as ''The calendar xxx is momentarly not available''

### Anything else we should know?

- Thunderbird 115 (manjaro stable)
- linux (manjaro, current patch level)

**Comment by EugenMayer** [comment]
Related to https://github.com/kewisch/gdata-provider/issues/3 i suppose?

**Comment by kewisch** [comment]
This will be the issue I identified in #690, thanks for reporting!

**Comment by EugenMayer** [comment]
Time to fork it then
