### ISSUE TITLE
When using provider Ver. 4.4.2, requests Google login every time

### ISSUE THREAD

**Issue by bankas** [kewisch/gdata-provider#68]
Hi, 
I am using TB TB 60.9.1 (64-bit) With provider for google Calender  4.4.2 On Mac OS. 
every time thunderbird is opened I am requested to sign in again to google, although the checkbox "remember me" is checked.
This Happend only on my iMac and not on my Macbook Pro, although they have the same TB and provider versions.

**Comment by elhennig** [comment]
Same here on Linux with Provider 68.2.1 and TB 68.7, but only for one out of two accounts.

**Comment by navennn** [comment]
https://github.com/kewisch/gdata-provider/issues/36
