### ISSUE TITLE
Feature request: support for starred tasks

### ISSUE THREAD

**Issue by matt-buckley** [kewisch/gdata-provider#683]
Provider for Google Calendar supports most Google Task features, but does not support "Starred" tasks, either as part of a separate list/calendar or via linking to Thunderbird's Priority or Category fields. It'd be great if this feature could be supported in some way.

**Comment by kewisch** [comment]
The "starred" status is unfortunately not exposed via the Google APIs. This is the closest issue I found on that: https://issuetracker.google.com/issues/236524523

If this changes I'm happy to reopen.
