### ISSUE TITLE
Google meet link does not appear

### ISSUE THREAD

**Issue by ariasgian** [kewisch/gdata-provider#694]
### Describe the problem and steps to reproduce it:

If you send me an invitation from Google Meet or I generate it from Google Calendar, the connection link does not appear in the calendar other than if it appears in the email.

**Comment by kewisch** [comment]
Can you provide logs from the provider for when you synchronize with the invitation or it is added to your calendar? Is this when you accept an invitation email manually, or for invitations that are automatically added to your calendar?

**Comment by ariasgian** [comment]
attached log

![2024-02-25_08-52](https://github.com/kewisch/gdata-provider/assets/51102814/605490ee-ca3a-4fb9-9ab8-c7b55ea08344)
