### ISSUE TITLE
Undismissable reminder for rescheduled event

### ISSUE THREAD

**Issue by Thorarin** [kewisch/gdata-provider#700]
### Describe the problem and steps to reproduce it:

1. Plan an appointment with reminders on another device (Android phone in my case)
2. (some time passes)
3. Reschedule the appointment to a later date on that device
4. When the original plan date approaches, a reminder popup will appear in Thunderbird
5. Attempt to dismiss the reminder
6. Reminder cannot be dismissed, because the appointment has changed in the meantime.
    The user is offered the choice to either overwrite the changes (which you don't want because it would presumably revert the rescheduling) or discard the changes.
7. Choose to discard the changes
8. The same reminder (based on outdated information) immediately pops up again, ad infinitum.

### What happened?

I was shown a reminder for an already rescheduled appointment. This happened on many occasions, also when the rescheduling had already happened several days before.

### What did you expect to happen?

1. Not get the incorrect reminder, ideally
2. In case the change was too recent to be synced, at least be able to dismiss the reminder and prevent the reminder loop.

**Comment by kewisch** [comment]
Does discarding the dismissed reminder changes, waiting for the popup to come back, and then overwriting changes, actually revert the scheduling? In theory, between discarding and the popup coming back, the calendar should be synchronized and the etag updated.

**Comment by maxwell-k** [comment]
I think that this might be the same behaviour that we are discussing in <https://github.com/kewisch/gdata-provider/discussions/708>.

I've used a workaround, but I might be able to recreate the issue if that would be helpful?

**Comment by binki** [comment]
Maybe this is #735? I had this exact situation happen to me, but I cannot figure out how to get Lightning to see the updated event.

If I dismiss the event in Lightning and choose to overwrite, it overwrites the event to the old time. The behavior suggests to me that synchronization is only working in one direction (changes are uploaded to Google but Lightning never receives any updates).

**Comment by binki** [comment]
@kewisch 
> Does discarding the dismissed reminder changes, waiting for the popup to come back, and then overwriting changes, actually revert the scheduling? In theory, between discarding and the popup coming back, the calendar should be synchronized and the etag updated.

Yes. If I do this:
1. Click “Dismiss”
2. Click “Discard my changes and reload”
3. Wait for the Reminder dialog to reappear (it takes a second or two). Note that the Calendar view in Lightning never shows the updated time for the event.
4. Click “Dismiss”
5. Click “Submit my changes anyway”
6. The event immediately appears in Google Calendar at the old location.

So it seems to me that synchronization is only working in one direction.

**Comment by kewisch** [comment]
For this issue I'm going to need some debug logs. Please only provide them if you are experiencing exactly the same steps as in the original comment. Otherwise please see #3 in case you are getting the "forbidden" error message. https://github.com/kewisch/gdata-provider/wiki#enabling-debugging
