### ISSUE TITLE
Thunderbird does not preserve the order of the Google calendar in the list of calendars

### ISSUE THREAD

**Issue by tibx** [kewisch/gdata-provider#706]
### Describe the problem and steps to reproduce it:

On the Calendar tab in Thunderbird, I have two calendars: Google (the calendar from the Provider for Google Calendar extension) and Local (for the local Thunderbird standard calendar). The order of the calendars is 1. Google, 2. Local, so when I add a new calendar event, the Google calendar is preselected as I need it.

### What happened?

After some time, however, it repeatedly happens that the order of the calendars changes so that 1. is Local and 2. is Google.

### What did you expect to happen?

Thunderbird should preserve the user's preference and set order of calendars 1. Google, 2. Local

### Anything else we should know?

Thunderbird 115.6.0 32b
Provider for Google Calendar 115.0.2

**Comment by kewisch** [comment]
This is likely more a Thunderbird issue, I don't believe I am messing with the sort order. Can you check with the Thunderbird team?

**Comment by tibx** [comment]
Bugzilla [bug 1877182](https://bugzilla.mozilla.org/show_bug.cgi?id=1877182)
