### ISSUE TITLE
Google Calendars not shown in "Select calendar" dialog when accepting an event invitation

### ISSUE THREAD

**Issue by MoralCode** [kewisch/gdata-provider#715]
### Describe the problem and steps to reproduce it:
1. Have a google account (in this case from an educational institution) and calendar configured in thunderbird
2. receive an invite email (autogenerated by google when youre added as a participant) for an event started by someone else
3. click "accept" in the navbar of the email
![Screenshot_20240118_094932](https://github.com/kewisch/gdata-provider/assets/17362949/8cdc9e55-aa1d-483b-8927-5646f9d14289)

### What happened?
Dialog pops up but no google-linked calendars are displayed in the list

### What did you expect to happen?
Dialog pops up showing all writable calendars

### Anything else we should know?

Debug log doesnt seem to show anything

Thunderbird: 115.6.1 (64-bit)
Gdata Provider: 115.0.2 (updated November 16, 2023)

Am happy to submit a PR if this is suspected to be a relatively newcomer-to-the-codebase type fix!

**Comment by MoralCode** [comment]
Possibly related to #664

**Comment by MoralCode** [comment]
Possibly related to #563

**Comment by MoralCode** [comment]
It looks like the events affected by this have somehow ended up on my calendar anyway, but I think that may be due to some automation on google's side to add invitations to my calendar and maybe not related to this issue

**Comment by kewisch** [comment]
Thanks for reporting! Are you subscribed to the primary calendar, the one with your name on it? This is the only calendar invitations can be accepted into. Do you maybe have multiple email addresses for that account? Do you have an email account/identity for each of those?

**Comment by MoralCode** [comment]
I am subscribed to the primary calendar.

The institution has google apps configured weirdly on a different email domain (i.e. both email@institution.edu and email@g.institution.edu work for receiving email as far as im aware, but you need to use the g. one to sign into google for some reason. the primary account happens to be named using the g. address if that helps anything)

so yeah i guess I do have multiple email addresses/identities for that one gmail inbox (i have both @institution and @g.institution set up as identities that i can send from, but i almost always send using the first one)

Hope that helps!

**Comment by kewisch** [comment]
Unfortunately I don't have a clear idea what the issue might be, but I can give you a few pointers on how to find out if you like. So first of all, the currently released codebase is on the `legacy` branch, and will be until I finally finish the rewrite.

The decision making on which calendars show up is done by the itip/imip code in Thunderbird. This in part uses some of the calendar properties here: https://github.com/kewisch/gdata-provider/blob/1b494e010928b5a61401b27e7ec866b8e37c4a54/src/legacy/modules/gdataCalendar.jsm#L328-L353

I'd suggest starting there by setting a breakpoint and checking which code path `itip.transport` and `imip.identity.disabled` take. You'll need to use the main process debugger, not the add-on debugger. Find it in tools > Developer Tools > Developer Toolbox.

Let me know if this works for you!

**Comment by MoralCode** [comment]
based on the looks of that code and some basic testing in the debugger, it seems like the cause is that `messenger.gdataSyncPrefs.get("settings.enableEmailInvitations", false) ` line, which is using a default value of false. I dont see that setting set by default in the about:config menu and setting it doesnt seem to change anything. I also cant find any related settings in the addon specific preferences.

Is there a way to modify this setting somewhere? or is this something that was possible in a previous verison?

Happy to wait for the rewrite if that helps make things easier

**Comment by kewisch** [comment]
You should be able to change this setting in the add-on preferences, can you take a look?
