### ISSUE TITLE
Missing an important section from events

### ISSUE THREAD

**Issue by alexivkin** [kewisch/gdata-provider#73]
### What happened?
Events created on calendar.google.com have a section with a Google Meet link if one is assigned. That section is visible via CalDAV at the end of the event
```
-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-
Please do not edit this section of the description.

This event has a video call.
Join: https://meet.google.com/[LINKHERE]
+1 [PHONE HERE] PIN: [PINHERE]#
View more phone numbers: https://tel.meet/[LINKHERE]?pin=[PINHERE]hs=7
-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-
```
This section is the only way to access google meet link in TB, as the `location` is never populated automatically using calendar.google.com (only if someone manually copy-pastes the meet link into location)

This section is completely missing from all events created by Gdata-provider, when viewed in TB.

### What did you expect to happen?
This section should be visible on events to be able to use google meet link on the event.

### Steps to reproduce
Create an event on calendar.google.com, click "add video conferencing". View the event via CalDav and compare to GData-provider

**Comment by kewisch** [comment]
#60
