### ISSUE TITLE
Google meet link does not appear

### ISSUE THREAD

**Issue by ariasgian** [kewisch/gdata-provider#731]
### Describe the problem and steps to reproduce it:

If you send me an invitation from Google Meet or I generate it from Google Calendar, the connection link does not appear in the calendar other than if it appears in the email.

Log
![2024-02-25_08-52](https://github.com/kewisch/gdata-provider/assets/51102814/a5b3baa7-5457-4ad0-bff1-9655db027dc9)
Problem
![2024-02-25_12-58](https://github.com/kewisch/gdata-provider/assets/51102814/f67dd3af-f50b-4762-9eca-b462a65e5d99)

![2024-02-25_13-00](https://github.com/kewisch/gdata-provider/assets/51102814/0fdcf2c5-c92e-4da3-8669-5c421b266313)

**Comment by kewisch** [comment]
Fixed this in 115.2.0 which is currently in the review queue. Please file a new issue or re-open if this is still the case after. Thanks for filing!
