### ISSUE TITLE
Google Tasks reminders and recurrences

### ISSUE THREAD

**Issue by xvs03** [kewisch/gdata-provider#732]
Hi, I synchronize my calendar and tasks with Provider for Google Calender.
When creating a new task, the dialog box is reduced by the reminder time and the task repetition. Why is this the case? Google Tasks allows both things in the web dialog and so does the mobile calendar.
The curious thing is that the dialog box is displayed completely for a short time, but is then reduced.

![image](https://github.com/kewisch/gdata-provider/assets/70815257/f70d4276-d987-4ca5-8f09-fcad2be9daa2)

Thank you for your help

Thunderbird V 115.8.0 Windows 10
Provider for Google Calender V 115.0.2

**Comment by kewisch** [comment]
Unfortunately recurrence is not supported in the API, please see #10

**Comment by Nicolii** [comment]
@kewisch I may be wrong and I tried looking for a date of modification on this page, but it looks like the API supports recurring events https://developers.google.com/calendar/api/guides/recurringevents
