### ISSUE TITLE
Stopped working with TB 124.0

### ISSUE THREAD

**Issue by mzur** [kewisch/gdata-provider#733]
### Describe the problem and steps to reproduce it:

The add-on stopped working with TB 124.0 because it is not compatible with that version.

### What happened?

The add-on is disabled.

### What did you expect to happen?

The add-on should work.

### Anything else we should know?

I'm happy to provide more details.

I could also try to work on this issue if someone tells me where to start.

**Comment by mzur** [comment]
I've now built the add-on from source from the `legacy` branch and it works again! Why is it called legacy if it seems to be the newest version? :grin:

**Comment by kewisch** [comment]
Heh yeah, I was very optimistic on that. I wanted to rewrite it as noted in #224 but hit some roadblocks in both time and speed of progress for getting the calendar API into Thunderbird. 

I submitted an update yesterday that should fix all the things and make it work up to 126.
