### ISSUE TITLE
Events not syncing with Google

### ISSUE THREAD

**Issue by Cliker01** [kewisch/gdata-provider#735]
Hi,

I have had this issue for quite some time and have never been able to figure out how to fix it. whenever i receive a calendar invite and I accept it, it rarely syncs to Google Calendar. I sometimes it work, but rarely. I have tried to remove and re-add the calendars but no luck.

Any suggestions?

On another note is there a way to select which calendar to save the invite and can you export as an ics as I currently have to manually export to copy details to google

**Comment by wtstine** [comment]
I have a similar problem. TB, ver 115,9.9.0, simply stops syncing. Nothing I do will cause it to sync short of unsubscribing and then resubscribing to the calendar.

**Comment by kewisch** [comment]
Can you check the main readme on enabling debugging and add some debug logs here?

**Comment by Olen** [comment]
Seeing the same issue.
Wanted to add some debug logs here, but I can't find it.  There is no "Options"  as far as I can see.
But I did find developer tools, and looked at console output.  But that is empty.

I tried to reload the extension, and that refreshed the calendar again, but did not really give much information...

**Comment by kewisch** [comment]
You need to set the preferences, otherwise the error console will be empty. With Options I mean the Thunderbird Preferences.

**Comment by Olen** [comment]
Found it.

Attaching the log, but it does not tell much.  No errors at least.

I noticed that several events in the calendar was missing, or had old timestamps (events that have been moved to a different time).

Just to summarize what the log shows:

**11:09:41** - I tried a "Synchronize" on the google calendar.  

This did not update any of the calendar entries

**11:10:30** - I tried to add a new event to the calendar to verify if that works, and if it would refresh anything.

The event was successfully added, and I could see it on another device.

I then removed the event from another device, and synced it to make sure the entry was properly removed from the Google calendar.

**11:11:25** - I ran a new "Synchronize" in Thunderbird, but the deleted event is still visible, and the other events that I know is changes was not updated.


  
[console-export-2024-4-25_11-11-48.txt](https://github.com/kewisch/gdata-provider/files/15107358/console-export-2024-4-25_11-11-48.txt)

**Comment by Olen** [comment]
A quick way to sync (but it does not fix the problem, as it just sync once) is to go to 
`Tools` -> `Add ons` -> `Provider for Google Calendar`.  Turn the little "Addon enbaled"-switch off.  Just `Cancel` the popup that asks you to unsubscribe the calendar(s).  
You can then turn the switch on again, and it will sync (once).

It is at least easier than to restart Thunderbird or unsubscribe and subscribe again.

**Comment by claireratigan** [comment]
Just chiming in to say I also have been having this problem for a long time, definitely started before January

**Comment by Olen** [comment]
Isn't this the same as #498 ?
