### ISSUE TITLE
Calendar not working after TB 68.8 reinstall

### ISSUE THREAD

**Issue by STEPHEN-GOLDBOROUGH** [kewisch/gdata-provider#74]
### Describe the problem and steps to reproduce it:

Reinstall TB 68.8
Calendar tab not showing

### What happened?

I disabled Lightning, restarted, re-enabled, restarted again  << this *didn't* work
*then* I disabled Provider for GC, restarted, re-enabled, restarted again << this *did* work

### Anything else we should know?

?? Is this a *too* round-about a solution, or is there a quicker way??

**Comment by kewisch** [comment]
Should work in the latest version, let me know if this is still an issue.
