### ISSUE TITLE
Open up Google Calendar conflict

### ISSUE THREAD

**Issue by terashy88** [kewisch/gdata-provider#753]
It seems that having `Provider for Google Calendar` and `Open up Google Calendar` or in conflict with each other. 
While both are active, I can't verify at Google login.

It's only work if `Open up Google Calendar` is disabled.

The error message is:

```
The browser you’re using doesn’t support JavaScript, or has JavaScript turned off.

To keep your Google Account secure, try signing in on a browser that has JavaScript turned on. Learn more
```

**Comment by kewisch** [comment]
I'm not sure what types of changes that add-on is doing, it appears that it is disabling javascript maybe? I don't recall touching that setting. Have you also reported this to the author of the other add-on?
