### ISSUE TITLE
Can't dismiss reminder on past event

### ISSUE THREAD

**Issue by arcenik** [kewisch/gdata-provider#755]
### Describe the problem and steps to reproduce it:

Thunderbird keep display this reminder about an invitation I received (and accepted) but the dismiss (all) buttons have no effect.

![image](https://github.com/kewisch/gdata-provider/assets/1905755/42411346-2eed-4cc0-918c-298c85b012a5)

A quick look at the debug console show the problem

![image](https://github.com/kewisch/gdata-provider/assets/1905755/b08e3122-1735-4f59-a1f2-a4f4c06971d8)

### Anything else we should know?

Extension version: 115.2.0 (2024/05/07)

**Comment by kewisch** [comment]
#690
