### ISSUE TITLE
wiki links support.mozillamessaging.com are oudated 

### ISSUE THREAD

**Issue by wsmwk** [kewisch/gdata-provider#76]
@kewisch at https://github.com/kewisch/gdata-provider/wiki the support.mozillamessaging.com  links are outdated

"Disclaimer ...
You can find a German translation of this page at support.mozillamessaging.com.
Eine Übersetzung dieser Seite ins Deutsche finden Sie auf support.mozillamessaging.com.
(Please include as many details as possible.)"

**Comment by kewisch** [comment]
I removed those links, I believe the translation is out of date anyway. Thanks for the issue!
