### ISSUE TITLE
Event invite alerts cannot be closed

### ISSUE THREAD

**Issue by Sp3EdeR** [kewisch/gdata-provider#760]
### What happened?

* Import a writable Google Calendar to Thunderbird.
* Receive an event invite in e-mail, which contains a reminder alert.
* Accept this invite on the GMail web interface (add to the imported, writable calendar).
* Once the reminder alert is opened by Thunderbird, it cannot be dismissed. The alert window can be closed, however Thunderbird soon pops it up again.

### What did you expect to happen?

The dismiss button should dismiss the alert, and the alert should not come back again.

### Anything else we should know?

Workaround: The event must be deleted. This does erase the information though, so it is not a desired behavour.

Thunderbird used to have a very similar issue with event reminder alerts in read-only calendars. I think the issue may be similar here, not being able to modify an event owned by someone else. The Thunderbird issue was resolved by creating a local database for events where alert states could be stored. Perhaps, if I'm right about the cause, the solution could be reused.

**Comment by kewisch** [comment]
If you get the same error message, this has been around basically forever. See #3 for more info. I have this likely fixed on the main branch, but that one is not ready to be used yet. I'd rather not put extra effort into porting this back to the current release branch, as it would be quite a bit of work. Thank you for reporting, fingers crossed I can release from main soon!
