### ISSUE TITLE
Tasks with no time interval

### ISSUE THREAD

**Issue by edermachado** [kewisch/gdata-provider#769]
### Describe the problem and steps to reproduce it:

The tasks do not allow me to enter the number of hours to complete the tasks. Something that in the local agenda tasks is working normally.
In addition to the time, it is also not possible to inform the start of the task, only the completion date (end).

### What happened?

I am unable to provide a specific start and end time for a task.

### What did you expect to happen?

As with the local calendar, I would like information about the start and end of tasks to be accessible so that they can be informed.

**Comment by kewisch** [comment]
Is this possible in Google Tasks? I'm pretty certain there is only a due date in the tasks and hence the UI for this is removed via the provider.

**Comment by edermachado** [comment]
Hello, you are completely right... but the option to inform the task completion time is missing...

![image](https://github.com/kewisch/gdata-provider/assets/1864475/0b9733c0-bd45-4b15-b3c5-b6c1674bc158)
![image](https://github.com/kewisch/gdata-provider/assets/1864475/3a861f9b-3059-4eff-afe2-bee3e707f78a)

**Comment by kewisch** [comment]
Unfortunately this is not possible via the API, https://developers.google.com/tasks/reference/rest/v1/tasks describes the API I am using and it specifically notes the time will be discarded (I'm assuming you mean the due date with the completion time? Or do you mean the time the task was marked as completed?)
