### ISSUE TITLE
Compatibility for TB 128 is near final release

### ISSUE THREAD

**Issue by tkoeck** [kewisch/gdata-provider#772]
Won't work with new TB 128 ESR version. Tried it with Windows 10 Enterprise 64 Bit.

**Comment by tkoeck** [comment]
Information update: It seems to work if I just adjust the manifest file for the newer upper version.

**Comment by mzur** [comment]
Will be fixed by https://github.com/kewisch/gdata-provider/pull/771.

**Comment by kewisch** [comment]
Here is (moderately untested) preview that includes some local changes: https://mozilla.kewis.ch/xpi/gdata-provider.xpi

I ran into some loader issues which required me to change a few things that could break the world, so I'm going to give it another test before I upload to ATN. 

Note this one I believe will cause you to log in again (and then again when you go back to the release version).

**Comment by tkoeck** [comment]
Nice. I will try it out right away. Thanks.

**Comment by kewisch** [comment]
I'm sufficiently happy with testing for the new version. The new release is at https://github.com/kewisch/gdata-provider/releases/tag/v128.0.0 and has been uploaded to addons.thunderbird.net. Once it passes review, it will be available to all users of Thunderbird 115 to 128.

I'm going to leave this open until it gets approved. Feel free to file new issues if you notice anything in the new version.

**Comment by tkoeck** [comment]
Seems to work. Thanks.
