### ISSUE TITLE
cant add local email address to google calendar for events

### ISSUE THREAD

**Issue by RobinEd** [kewisch/gdata-provider#78]
### Describe the problem and steps to reproduce it:

When right clicking on a google calendar there is no option "email" so I can't save events to the google calendar, only to my Home calendar, which doesn't sync with gmail.

### What happened?

Field was missing

### What did you expect to happen?

Email field there so I could associate non-gmail@email.com with gmail@gmail.com calendar and save events to my google calendar

### Anything else we should know?

I can't find any other way of adding event invites into my google calendar.

**Comment by carlosduelo** [comment]
You have the solution here https://github.com/kewisch/gdata-provider/issues/63

**Comment by colans** [comment]
Here's the process:

1. Preferences -> Config editor
1. Set `calendar.google.enableEmailInvitations` to `true`
1. Restart T-bird.
1. Go into each calendar's setting (right-click), and select your Google e-mail address.

**Comment by twain28** [comment]
Be advised that this **does not work with the most recent version**, due to a change in the syntax for google calendars. See my comment on #63

**Comment by kewisch** [comment]
I'll be making it possible to enable email invitations again in the Provider 91.0.2, please stay tuned.
