### ISSUE TITLE
Event Description not in HTML

### ISSUE THREAD

**Issue by multiprod** [kewisch/gdata-provider#79]
### Describe the problem and steps to reproduce it:

I can send an event with description in HTML to Google Agenda but when event is synchronised with Thunderbird it's displayed with all the html tags

Is there a setting to force description to accept html format?

**Comment by multiprod** [comment]
No idea?

**Comment by kewisch** [comment]
This would require some enhancements in Thunderbird/Lightning to make use of, the calendar event dialog is not meant to show html. The iCalendar standard also assumes the description is plain text, there are efforts to improve this in the standards world. Unfortunately there is nothing I can do here right now, but I'll keep an eye out on changes to Thunderbird.
