### ISSUE TITLE
Will not save login credentials between Thunderbird sessions.

### ISSUE THREAD

**Issue by joekm** [kewisch/gdata-provider#790]
### Describe the problem and steps to reproduce it:

I have my google calendar, my wife's that's shared with me (read only), and my Google Task list.  Every time I restart Thunderbird, I have to manually log back in to my Google account three times to individually activate each one.  This is despite always selecting "Do not ask again on this device".   I really like the tasks integration, but this makes the add on unusable for me.

### What happened?

Constantly being re-asked to log in despite selecting "do not ask again on this device"

### What did you expect to happen?

I expected it to save my login credentials

### Anything else we should know?

Thunderbird version 1.29 installed on EndeavourOS

**Comment by joekm** [comment]
I'm finding other instances now in this forum that were ultimately closed without a fix.

https://github.com/kewisch/gdata-provider/issues/790 

https://github.com/kewisch/gdata-provider/issues/353

**Comment by kewisch** [comment]
Did you get any error console messages worth sharing? Are all accounts using the same session (you can see this in the URL in the calendar properties, the "host" part)?

**Comment by joekm** [comment]
Just one error message, but it doesn't appear related to this:
[ERROR sys_tray::linux] translation issues: [ResolverError(Reference(Function { id: "PLATFORM" }))]

I'm not seeing a "host" part in the calendar URL.  What I see is along the lines of:

googleapi:///?calendar=joekmooney%40gmail.com

Similar format for my task list and my wife's calendar (which I follow read-only).


Meanwhile, the similar URL for the Thunderbird's built in Google calendar connect looks like:

https://apidata.googleusercontent.com/caldav/v2/joekmooney%40gmail.com/events/


Thunderbird just updated to day to 1.30 for me.  Just confirmed that, upon restart, I once, must log into my calendar, my wife's calendar, and my task list.

**Comment by kewisch** [comment]
Yeah the missing host part is concerning, I wonder how that happened. If you can reproduce that in some way I'd be happy to add a fix. Can you unsubscribe from those calendars, then re-subscribe and make sure you enter your primary email when it asks you for the session?

**Comment by joekm** [comment]
I've only got the one gmail to use for my calendar and task list and my wife's gmail is shared with me (that's the other calendar).  So, they only email I have to use is my primary.  Nonetheless, I did just unsubscribe and re-activate your extension and now, I can't seem to do anything.  I've removed it altogether and will later try to re-install and see if I get the option to add calendars again.

**Comment by joekm** [comment]
Ok, after unsubscribing from your calendars as well as the ones I subscribed to within thunderbird itself., then deleting and re-installing your extension, it appears to be working correctly without having to constantly re-login.

**Comment by kewisch** [comment]
Super, glad it works now!
