### ISSUE TITLE
TB with google calendar - this calendar is momentarily not available error

### ISSUE THREAD

**Issue by Narinne** [kewisch/gdata-provider#81]
### Describe the problem and steps to reproduce it:
Using Thunderbird 68.9.0 with Lightning and Provider for Google Calendar, previously have had no issues with using google calendar in TB.
Now:
1) when TB loads I get prompted with reminders for meetings that have passed, and when I press 'dismiss' nothing happens. 
2) when I go to 'accept' a meeting invitation an error code pops up - Processing message failed. Status: 80004005.
3) When I look at my calendar I can see events in it, but nothing updates and a little triangle with an exclamation mark is next to the email address the calendar is linked with. If I hover over it, it reads 'this calendar is momentarily not available'

Google calendar is still showing and updating in one direction (Google to TB) but it appears nothing will work from the TB side back to google calendar.

Steps taken so far:
1) Reinstall Provider for Google Calendar
2) Unsubscribe and resubscribe to calendar

Error messages that may be relevant:
![error](https://user-images.githubusercontent.com/67353082/85492073-bc6b3d80-b613-11ea-8c9e-f1d486cae1e3.PNG)

I would love any help with this, I can't accept any client meetings :(

**Comment by kewisch** [comment]
This should be fixed with Thunderbird 78 and the upcoming provider release. For the mean time, are you using any other add-ons and could try disabling them? It seems the structure for the event dialog has been modified.

**Comment by avg-I** [comment]
I came here to basically just confirm the problem.
TB version is 68.11.0.
The addon version is 68.2.1.
I haven't tried disabling any other addons yet, but I do not have many of them in the first place.

> Amazon.com	1.1	true	amazondotcom@search.mozilla.org
Bing	1.0	true	bing@search.mozilla.org
CompactHeader	3.0.0beta5	true	{58D4392A-842E-11DE-B51A-C7B855D89593}
DuckDuckGo	1.0	true	ddg@search.mozilla.org
Enigmail	2.1.7	true	{847b3a00-7ab1-11d4-8f02-006008948af5}
Google	1.0	true	google@search.mozilla.org
Lightning	68.11.0	true	{e2fda1a4-762b-4020-b5ad-a41df1933103}
Mail Redirect	0.10.9	true	{CC3C233D-6668-41bc-AAEB-F3A1D1D594F5}
Manually sort folders	2.0.2	true	tbsortfolders@xulforum.org
Mark All Read Button	0.8	true	{DA506923-55C4-4fbe-9E4C-D24B80D7DE9F}
Provider for Google Calendar	68.2.1	true	{a62ef8ec-5fdc-40c2-873c-223b8a6925cc}
Twitter	1.0	true	twitter@search.mozilla.org
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org
XNote++	2.3.1	true	xnote@froihofer.net

**Comment by avg-I** [comment]
It seems that in my case it helped to disable "Manually sort folders" and "Mark All Read Button" addons.
Not sure why...

**Comment by lumag** [comment]
I'm also hitting this issue: Debian Testing, Thunderbird 68.11.0 (64-bit), Lightning 68.11.0, Provider for Google Calendar 68.2.1.
I've tried disabling all other extensions (DispMUA and QuoteCollapse), but this did not help.

**Comment by lumag** [comment]
Still present with Thunderbird 78.2.2 and Provider 78.0.1

**Comment by kewisch** [comment]
This should be fixed with the same patch that will fix #3.
