### ISSUE TITLE
English Language (Grammar) Error in Add-ons Manager > Options text

### ISSUE THREAD

**Issue by jethrobelman** [kewisch/gdata-provider#814]
### Describe the problem and steps to reproduce it:

The English is incorrect in Add-ons Manager view of the Provider for Google Calendar.

**Environment:** 

- Lenevo ideapad Gaming3
- OS: Windows 11 Pro22631.4317
- Thunderbird version: 128.3.0esr (64bit)
- Dark mode

**Reproduction:**

1. Open Thunderbird
2. Navigate to: Tools > Add-ons Manager
OR
3. Navigate to: Tools > Settings > Add-ons and Themes
4. Select Settings (Wrench Icon) for the Provider for Google Calendar
5. Select the Options Tab

### What happened?

Grammar error in English, on the Options tab it currently reads: "These settings are will allow you ..."

![Screenshot 1](https://github.com/user-attachments/assets/d70bb325-7010-4a4f-a265-edeaae8c7373)
![Screenshot 2](https://github.com/user-attachments/assets/b88db045-97f4-4d63-9bbc-1dd0ed6827c6)

### What did you expect to happen?

Correct grammar should be: "These settings will allow you ..."

### Anything else we should know?

- OS: Windows 11 Pro22631.4317
- Thunderbird version: 128.3.0esr (64bit)
- Dark mode

**Comment by kewisch** [comment]
Thanks! I've fixed this in 3bb944ee12af95fc3faa9a7f90ec83909f377fe9 and will include it in the next release.
