### ISSUE TITLE
Not compatible 132.0.0

### ISSUE THREAD

**Issue by JPRuehmann** [kewisch/gdata-provider#822]
### Describe the problem and steps to reproduce it:

Since the automatic Update of Thunderbird yesterday Google Callendars wont work anymore and the Extensions say that the Extension is incompatible to Thundeerbird 132.0.0

(Please include as many details as possible.)

### What happened?

No Google callendars shown anymore.

**Comment by JPRuehmann** [comment]
A workaround is to change the strict_max_version in the manifest.json.
That can be found in the extensions Folder in the Profile Folder.
There is an xpi File for the extension in that the Manifest resides.
xpi is in fact an zip File.
It works for me with 133.*

**Comment by kewisch** [comment]
I've updated it to 133.* on addons.thunderbird.net. It is hard to keep up with this especially with monthly releases coming. If you've tested this on a later version let me know, or ping me on Matrix @kewisch:mozilla.org
