### ISSUE TITLE
Regular events: Exceptions do not export properly

### ISSUE THREAD

**Issue by Evil-Knivel** [kewisch/gdata-provider#84]
### Describe the problem and steps to reproduce it:

When I delete or change single instances of a regular event (event series) in Lightning, the change does not export in a format that is displayed properly by other calendar apps. They don't show the changes made.

When I export the calendar as an .ics file, I can see that the exceptions (EXDATE) are added *before* the general rule (RRULE), while all other apps (including the google calendar website) add the exception *after* the rule. So:

Lightning Calendar:
ORGANIZER;CN=Testkalender:mailto:cvpxtr4u73f8k0g13qlno81jk0@group.calendar.google.com
EXDATE:20200720T100000Z
RRULE:FREQ=DAILY

Original Google Calendar:
ORGANIZER;CN=Testkalender:mailto:cvpxtr4u73f8k0g13qlno81jk0@group.calendar.google.com
RRULE:FREQ=DAILY
EXDATE:20200720T100000Z

I don't know enough about .ics files to say if both should be valid or not. But I really would prefer the Lightning calendar to add exceptions in the same way as google, so I don't run into compatibility problems.

Thanks for your time and effort!
Günther

**Comment by kewisch** [comment]
The order of the RRULE and EXDATE does not make a difference as per spec, I am not aware of any calendar systems that rely on the order, including Google. Either way this would be a fix in Lightning, not in the Provider, therefore I am closing this issue. Thanks though for reporting, if you come across actual compatibility issues I'm happy to look into it.
