### ISSUE TITLE
Stopped working in Thunderbird 78

### ISSUE THREAD

**Issue by lugotal** [kewisch/gdata-provider#85]
The extension stopped working properly in Thunderbird 78.

TB recognizes it as compatible and allows the user to enable it, but Google calendars can not be used.
The properties of each calendar say that the required provider is not installed - despite the extension being installed and enabled.

**Comment by xcession** [comment]
This extension need update for the TB78

**Comment by rebel2k** [comment]
Just for the record, that's already discussed here: https://github.com/kewisch/gdata-provider/issues/77 :)

**Comment by antcdp** [comment]
as above, this is being sorted by Philipp under #77 so will close this shortly as a dupe

A workaround is in there as I posted it and it does work - well for me and others so far it does!
