### ISSUE TITLE
2 Google-Konten

### ISSUE THREAD

**Issue by Radime** [kewisch/gdata-provider#86]
Ich habe 2 Google-Konten mit Thunderbird als Adressbuch verbunden. Wenn ich jetzt zum 1. Google-Konto die Kalender abonieren möchte, werden mir nur die Kalender aus dem 2. Google-Konto zur Auswahl angezeigt. Cache und Adressbücher löschen hilft nicht. Was kann ich tun? Welche Informationen / Daten werden zur Analyse benötigt? Ich habe Version 68.2.1 im Einsatz.
Beide Konten nutzen auch einen gemeinsamen Kalender. Das 1. Konto darf lesen und schreiben, das 2. Konto nur lesen. Ich habe jetzt über beide Konten diesen Kalender eingebunden. Die verwendete googleapi ist auch unterschiedlich. Jedoch haben beide Kalender in Thunderbird keine Schreibrechte.
Ich hatte bis heute Linux mint 19.3 im Einsatz und alles war wie es soll. Anstatt eines updates habe ich linux mint 20 vollständig neu aufgesetzt. Jetzt habe ich die Probleme, an den Kalendereinstellungen habe ich nichts geändert.

**Comment by kewisch** [comment]
Ich bin mir nicht gans sicher, wie das Adressbuch hier reinspielt, ist das über ein anderes add-on? Der Provider kann nur Kalender. Die Auswahl welches Konto findet im ersten Schritt statt. Eventuell hilft es alle Kalender abzumelden in Thunderbird, im Passwort Manager alle Einträge zu Google zu entfernen, und dann neu zu abbonieren.

Da es sich um eine Support Anfrage handelt werde ich dieses Issue schließen, wenn noch Fragen sind trotzdem gerne hier posten.
