### ISSUE TITLE
Unable to subscribe company calendar

### ISSUE THREAD

**Issue by joselsegura** [kewisch/gdata-provider#88]
### Describe the problem and steps to reproduce it:

I'm able to use my personal Google account with the provider, but unable to login in my company's SSO that bring me access to a Google Suite

### What happened?

Trying to subscribe to a network calendar of my company, when I introduce my e-mail address, a white window appears, that is closed without any action. The "Locate your calendar" window is shown, but no calendars are listed at all.

### What did you expect to happen?

When I add my company email address, the login page for my company is opened and I'm able to authenticate there. Then, I will chose which calendar to add

### Anything else we should know?

Ask for further info if needed

**Comment by tsmaeder** [comment]
Yeah...this is unfortunately a long-standing issue: https://groups.google.com/g/provider-for-google-calendar/c/lSZMYwsOCFM/m/FYGL3PQVAwAJ

**Comment by tsmaeder** [comment]
I tried finding out what the problem is, unfortunately, my mozilla-fu is pitiful.

**Comment by saprobe** [comment]
It's working for me now, after a 2 step verification which I didnt initially get. Maybe it's a problem with that security step?

**Comment by kewisch** [comment]
Unfortunately this will be hard for me to debug. I've tried this with my own SSO calendar and it works fine. Can you check cookie settings in Thunderbird?

**Comment by tsmaeder** [comment]
Which cookie settings? What should I check?

**Comment by danielmellado** [comment]
It's also happening to me, so far, when I try to add a 'corporate' google calendar, the oauth window pops up and closes, and then I see this on the debug.

```Lightning: [calGoogleSession] Authentication failure: undefined gdataSession.jsm:282
[Exception... "null"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gdata-provider/modules/gdataSession.jsm :: login/authFailed< :: line 284"  data: no] gdataSession.jsm:284:33
    authFailed resource://gdata-provider/modules/gdataSession.jsm:284
    <anonymous> self-hosted:1007
    onPromptAuthAvailable resource://gdata-provider/modules/gdataSession.jsm:301
    onAuthorizationFailed resource://gdata-provider/modules/OAuth2.jsm:210
    onStateChange resource://gdata-provider/modules/OAuth2.jsm:157```

**Comment by danielmellado** [comment]
It's worth mentioning that my corporate gmail account uses its own sso login page.

**Comment by GiriRamaraju** [comment]
Here is the console log with calendar.debug.log and verbose set to true. The actual kerbros and domain have been replaced with user@company.

Lightning: [calGoogleSessionManager] Creating session user@company.com gdataSession.jsm:80
Lightning: [calGoogleSession] Token expired 1598873926 seconds ago, resetting gdataSession.jsm:357
Lightning: [calGoogleCalendar] Logging in session user@company.com gdataSession.jsm:247
Lightning: [calGoogleCalendar] No access token for user@company.com, refreshing token gdataSession.jsm:318
Lightning: [calGoogleSession] Adding item https://www.googleapis.com/tasks/v1/users/@me/lists to queue gdataSession.jsm:374
Lightning: [calGoogleSession] Adding item https://www.googleapis.com/calendar/v3/users/me/calendarList to queue gdataSession.jsm:374
Lightning: [calGoogleCalendar] Failed to acquire a new OAuth token for user@company.com data: undefined gdataSession.jsm:257
Lightning: [calGoogleSession] Authentication failure: undefined gdataSession.jsm:282

[Exception... "null" nsresult: "0x80004005 (NS_ERROR_FAILURE)" location: "JS frame :: resource://gdata-provider/modules/gdataSession.jsm :: login/authFailed< :: line 284" data: no]

**Comment by GiriRamaraju** [comment]
Received some additional info on someone who looked into this issue. @kewisch , does this help towards debugging the issue ?
==========>
Here is how a SAML flow works and how it correlates to the debug capture you got:

1) Your user agent goes to an SP (the page you want to view)
Requests 1-2 in your capture
2) The SP notices you don't have a cookie or session with them and then redirects you to an organizations SSO server.  You come across with a SAMLRequest.  
Request 3 in your capture. 
3) Our SSO server does the following:
a) Do you have a cookie?  Meaning you've already accessed a different SSO site and it tracks sessions like that.
b) No? Do you have a kerberos ticket/negotiate header
if so, autologin
if not fail with a 401 and redirect folks to a pin+token login page
c) person logs in with pin+token
d) SSO server issues cookie
e) SSO server uses RelayState that came across in the SAMLRequest to forward you back to the SP

From your description your UserAgent is failing roughly at 3b.  
<==========

**Comment by cavemanr** [comment]
With the new release of Thunderbird this issue is gone on my computer.

**Comment by tsmaeder** [comment]
@cavemanr which version is that? What OS?

**Comment by cavemanr** [comment]
> @cavemanr which version is that? What OS?

Thunderbird 78.5.0 (64-Bit)
Manjaro (stable) with Kernel 5.4.78-1-MANJARO

**Comment by ddelabru** [comment]
I'm still experiencing this issue with Thunderbird 78.7.0 on NixOS.

**Comment by tsmaeder** [comment]
Me too.

**Comment by joselsegura** [comment]
Same here

**Comment by kewisch** [comment]
Sorry if this was closed preemptively. Would be great if you could retry on Thunderbird 91 if this is still an issue and reopen if necessary.
