### ISSUE TITLE
Not working in 78.1.0 (32-Bit)

### ISSUE THREAD

**Issue by JPRuehmann** [kewisch/gdata-provider#89]
### Describe the problem and steps to reproduce it:

No Events on Google Callendars shown.

### What happened?

No Events shown

### What did you expect to happen?

Events shown such as in all other Versions before.

### Anything else we should know?

Version 68.2.1

**Comment by kewisch** [comment]
Unclear to me which version of Thunderbird you are using now, 78.1.0? I don't have a compatible version for that, but with 78.1.1 you can check out the pre-releases. See #77.

**Comment by JPRuehmann** [comment]
Sorry, I had to read  #77 more than once.
Update to 78.1.1, Download the pre Version and change the Manifest did the Job.
Now it works.

**Comment by kewisch** [comment]
No worries! I'll see why the manifest doesn't work as it should and send out another pre release
