### ISSUE TITLE
Declined invitations are added to calendar anyway. (Bugzilla Bug 1334522)

### ISSUE THREAD

**Issue by kewisch** [kewisch/gdata-provider#9]
# [Bugzilla Bug 1334522](https://bugzilla.mozilla.org/show_bug.cgi?id=1334522)
Date: 2017-01-27T17:31:52+01:00
From: John &lt;<bugzilla@irowat.ca>&gt;
Assigned To:   nobody

Last updated: 2019-09-11T13:21:41+02:00

**Comment by marcdeop** [comment]
I am also affected by this bug.

Is there any work being done on the subject? Can we supply more information that will help this get fixed?

Best regards,

Marc

**Comment by kewisch** [comment]
Would be great to get this tested in Thunderbird 91 with the Provider 91.0.2 which I am going to release soon. Here is a preview:
[gdata-provider-91.0.2pre3.xpi.zip](https://github.com/kewisch/gdata-provider/files/7192893/gdata-provider-91.0.2pre3.xpi.zip)

Here are some steps to get more info:

1) Enable logging as per https://github.com/kewisch/gdata-provider/wiki/FAQ#enabling-debugging
2) Make sure you have all the scheduling and attendee options enabled in the Add-on Options
3) Maybe re-subscribe to the calendar
4) When you decline the invitation, do you get a message `[calGoogleCalendar] Adding invitation event My Event Name` ? Or does it say `...Adding regular event...`
5) In the event data that is sent, does it properly show your email as an attendee and declined?
6) Does is properly set the other person as the organizer and you as an attendee?
