### ISSUE TITLE
Chose Calendar into which the Email Invite Event goes

### ISSUE THREAD

**Issue by JanaJarecki** [kewisch/gdata-provider#90]
### Describe the problem and steps to reproduce it:
When receiving an email invite to a calendar event and accepting it, I can only add the event to my main google calendar. I have multiple calendars that are displayed. I need to add the event to a different calendar. How can I select the calendar?

### What happened?
Upon clicking accept the calendar event invitation on the email, only the main google calendar can be selected.

### What did you expect to happen?
I expected a list of all calendars to be shown.

### Anything else we should know?
Windows 10
Thunderbird: 68.11.0
Provider for Google Kalender: 68.2.1

**Comment by kewisch** [comment]
This is somewhat by design. Only the primary calendar is set up to accept invitations, as Google has some restrictions on this. I can eventually see if this works nowadays, but I had a lot of trouble back when I last tested.
