### ISSUE TITLE
Cannot Synchronize New Calendar 

### ISSUE THREAD

**Issue by Invisible40** [kewisch/gdata-provider#91]
### Describe the problem and steps to reproduce it:

I had three events in a Google Calendar already synchronized to Thunderbird.  On Google Calendar, I made a new calendar, and I moved these three events into the new calendar.  When I hit synchronize on Thunderbird, there were no changes made.  The event is still in the old calendar, and the new calendar is not recognized in the sidebar.

### What happened?

My new calendar and event changes to said new calendar did not synchronize.

### What did you expect to happen?

I expected the new calendar to appear on the sidebar, and the three events to be available in the new calendar.

### Anything else we should know?

I am using 68.11.0 (32-bit).
Windows 10 and the latest Provider update.

**Comment by kewisch** [comment]
Thanks for taking the time to report an issue. Can you check out the [FAQ](https://github.com/kewisch/gdata-provider/wiki/FAQ) and provide debugging information?

Are both "old" and "new" calendars Google Calendars added through the Provider?

**Comment by dziki2604** [comment]
For me, the problem with synchronization occurred after upgrading from 68.x.x to 78.1.1. Then I noticed that calendars cannot be synchronized. According to the plugin's home page ... "Works with Thunderbird 68.0 - 73.0"
Request to add-on developer to update it. It would be a pity to abandon such a valuable accessory.
Thank you.
K.

**Comment by NewKidOnTheBlock** [comment]
The updated add-on works with TB 78.2+

**Comment by dziki2604** [comment]
Confirm, I just updated and everything works. Thank you.

**Comment by kewisch** [comment]
Thanks for the updates!
