### ISSUE TITLE
Empty window with the suggestion to migrate upon start of TB

### ISSUE THREAD

**Issue by ostasevych** [kewisch/gdata-provider#92]
### Describe the problem and steps to reproduce it:
Each time I start Thunderbird I am getting empty window suggesting to migrate read-only calendars. The only thing I may do is to close it.

![image](https://user-images.githubusercontent.com/5199030/90307500-4f6f7800-dedf-11ea-9676-5f20d4434faf.png)

### What did you expect to happen?
The window should contain the list of calendars to be migrated and do not appear next time.

### Anything else we should know?
Thunderbird 68.11.0, 64-bit version, Windows 10

**Comment by kewisch** [comment]
This should be fixed in the upcoming release for Thunderbird 78, it will be available in the next few days.
