### ISSUE TITLE
TB ver: 78.1.1 (64 bit) cannot write to Calendar

### ISSUE THREAD

**Issue by passegua** [kewisch/gdata-provider#94]
### Describe the problem and steps to reproduce it:

Since I updated to the last 78.1.1 (64 bit) version I am no more able to exchange data from/to Google and TB Calendars.
When I try to modify an event in TB Calendar I get: MODIFICATION_FAILED
and the Calendar change by itself to "only read" status.
![cal1](https://user-images.githubusercontent.com/17082209/90954100-bce84f00-e471-11ea-82f9-124c82cc49f0.png)
![cal2](https://user-images.githubusercontent.com/17082209/90954101-bd80e580-e471-11ea-8575-9d4ba22d4008.png)

**Comment by kewisch** [comment]
This looks like it is an iCalendar calendar, not one added through the Provider for Google Calendar. I have support for Thunderbird 78 available [here](https://github.com/kewisch/gdata-provider/releases/tag/v78.0), please install that version once Thunderbird 78.2.0 is available (next few days). You will also need to unsubscribe and re-subscribe to the calendar.
