### ISSUE TITLE
Thunderbird 78.1.1 incompatibility

### ISSUE THREAD

**Issue by SilverGreen93** [kewisch/gdata-provider#96]
Just downloaded the new 78.0 gdata-provider release, but I cannot install in Thunderbird 78.1.1.

"This add-on could not be installed because it is incompatible with Thunderbird 78.1.1"

**Comment by SilverGreen93** [comment]
Update: It can however be installed if I edit the manifest and change 78.2 to 78.0.0, but is this the right thing to do?

**Comment by helmar74** [comment]
> Just downloaded the new 78.0 gdata-provider release, but I cannot install in Thunderbird 78.1.1.
> 
> "This add-on could not be installed because it is incompatible with Thunderbird 78.1.1"

Same issue here...

**Comment by helmar74** [comment]
Similar Issue here. Updated "manually" to TB 78.1.1 (current stable release)
G-Data provider is installed, but all calendars are disabeld, I can't enable same...
Is the Addon compatible to 78.1.1, or do I have to use a "higher" (beta) release of TB?

**Comment by nicorac** [comment]
> Update: It can however be installed if I edit the manifest and change 78.2 to 78.0.0, but is this the right thing to do?

This extension requires 78.1.1, but there's a TB issue on checking 3-parts `min_version` numbers: https://github.com/kewisch/gdata-provider/issues/77#issuecomment-669061886

Everything should be fixed in TB 78.2.0; meanwhile there should be no issue in editing the manifest to `78.1` (see the link above).

**Comment by helmar74** [comment]
The addon is installed on TB 78.1.1 but the calendars are not synced and marked inactive, what could be the issue?

**Comment by wsmwk** [comment]
Thunderbird 78.2.0 candidate can be obtained at https://archive.mozilla.org/pub/thunderbird/candidates/78.2.0-candidates/build1/

Note, it is still undergoing testing - but so far it checks out as good.

**Comment by helmar74** [comment]
> Thunderbird 78.2.0 candidate can be obtained at https://archive.mozilla.org/pub/thunderbird/candidates/78.2.0-candidates/build1/
> 
> Note, it is still undergoing testing - but so far it checks out as good.

This means, that addon isn't correctly running on TB 78.1.1?

**Comment by nicorac** [comment]
> This means, that addon isn't correctly running on TB 78.1.1?

It works, but its manifest must be changed to allow TB 78.1.1 load it without the "incompatibility" error message.

**Comment by NewKidOnTheBlock** [comment]
TB 78.2 is officially out:
https://www.thunderbird.net/en-US/thunderbird/78.2.0/releasenotes/

**Comment by kewisch** [comment]
Closing this now that later versions are out. I found out why this happens and it is a Thunderbird issue. Thanks for the reports!
