### ISSUE TITLE
Google Calendar not syncing on TB 78.1.1

### ISSUE THREAD

**Issue by helmar74** [kewisch/gdata-provider#97]
### Describe the problem and steps to reproduce it:
Update To current stable of TB 78.1.1. Addon is installed afterwards.

(Please include as many details as possible.)

### What happened?
The addon is installed on TB 78.1.1 but the calendars are not synced and marked inactive.

### What did you expect to happen?
Calendars should be active and synced.

**Comment by nicorac** [comment]
TB 78.1.1 needs the latest version of the addon, but you need to edit its manifest.json (due to a bug in TB 78.1.1 that should be fixed in 78.2)
https://github.com/kewisch/gdata-provider/issues/77#issuecomment-669061886

Otherwise wait for TB 78.2.0 (already available as [Candidate](https://archive.mozilla.org/pub/thunderbird/candidates/78.2.0-candidates/))

**Comment by NewKidOnTheBlock** [comment]
TB 78.2 is officially released:
https://www.thunderbird.net/en-US/thunderbird/78.2.0/releasenotes/

**Comment by lucky1luc** [comment]
For me it is not syncing with 78.2 either. Only once when the account is added, and after that no more syncs?

**Comment by NewKidOnTheBlock** [comment]
I never uninstalled the add-on, just waited until it updated because TB had advanced to 78.2
After that, Lightning was missing some calendars, but that could be fixed by forcing a sync and turning the calendars off and on again.

**Comment by lucky1luc** [comment]
I forgot to menytion, I installed the 78.0pre1 version of the gdata provider.

**Comment by lucky1luc** [comment]
I reinstalled the addon 78.0pre1 after upgrading TB to 78.2 and now it seems to work correctly

**Comment by dominiklenne** [comment]
Same with me
TB version 78.2.2 (64-Bit) on W10, Addon-version 78.0.1, freshly installed.
All calendars synced nicely after installation, but after TB restart, all were inactive and could not reactivated via 
- properties - activate this calendar 
with error message: "The provider for this calendar could not be found. ..." 
Hint: I have a parallel installation of Tbsync,which may create a collision.

**Comment by kewisch** [comment]
Closing this specific issue, it should be working with a later version of Thunderbird.
