### ISSUE TITLE
Custom categories in TB category modal are not accepted

### ISSUE THREAD

**Issue by justinseesdragons** [kewisch/gdata-provider#98]
If you adjust the naming or add a new category from preferences then you cant select that category from the tasks view because the modal will never dismiss.  You must unselect the new category for it to go away.  Also this may be a TB window handling issue but the idea of having the modal never go away is really bad design.  The modal should not capture focus to the point that you cannot escape.  Fortunately the one thing that worked was alt+tab to switch focus to an application that had a terminal window open so I could killall -9 thunderbird.

**Comment by kewisch** [comment]
Definitely sounds like a Thunderbird issue. Can you file the issue on bugzilla.mozilla.org?
