### ISSUE TITLE
Support adding conference links

### ISSUE THREAD

**Issue by DavidPyke** [kewisch/gdata-provider#99]
### Describe the problem and steps to reproduce it:

If I accept a meeting that includes a google meet that was added via the calendar.google.com interface "Add google meet button:, that meeting is lost in my calendar if I accept it from the email.

If I accept it via the calendar right click menu, the meeting is maintained.

In either case, that google meet is not shown anywhere in the lightning entry.

(also, it would be nice to be able to add the google meet via lightning)

**Comment by kewisch** [comment]
I have some changes planned that would fix the meet links lost which will fix a bunch of other issues. Evolving this one to support adding conference links.

**Comment by kewisch** [comment]
See #60
